#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# This lane MIRRORS cuML's random forest. Per-file provenance is in this file's own docstring and in NOTICE.
"""The scikit-learn arm of the random-forest benchmark.

Prints `ARM <name> <ms>` lines that `bench/run_bench.py` alternates against
`ensemble/bench/rf_bench.mojo`.

THE DATASET IS GENERATED BY THE SAME splitmix64 AS THE MOJO ARM, so both fit
the same bits. `--checksum` prints a digest of the generated data; the Mojo
arm prints the same digest, and if the two disagree the timings are
comparing different problems and must be thrown away.

WHAT THIS BASELINE IS. cuML's GPU arm cannot run on Apple silicon, and no
library ships a GPU random forest for this box, so scikit-learn on the same
M4 is the strongest thing that actually runs. It is NOT the same algorithm:
scikit-learn searches exact split thresholds where this port (following
cuML) bins each feature into at most 128 quantiles. That difference favours
us on time, which is exactly why accuracy is printed beside every timing.

scikit-learn gets every core (`n_jobs=-1`). A CPU baseline handicapped to
one thread would not be a baseline.
"""

import argparse
import time

import numpy as np
from sklearn.ensemble import RandomForestClassifier

M = np.uint64(0xFFFFFFFFFFFFFFFF)
REPEATS = 5
N_CLASSES = 4
N_TREES = 20
MAX_DEPTH = 12


def mix(x):
    """splitmix64, transcribed from `rf_bench.mojo::_mix`."""
    h = x + np.uint64(0x9E3779B97F4A7C15)
    h = (h ^ (h >> np.uint64(30))) * np.uint64(0xBF58476D1CE4E5B9)
    h = (h ^ (h >> np.uint64(27))) * np.uint64(0x94D049BB133111EB)
    return h ^ (h >> np.uint64(31))


def make(n_rows, n_cols, offset=0):
    r = np.arange(offset, offset + n_rows, dtype=np.uint64)[:, None]
    c = np.arange(n_cols, dtype=np.uint64)[None, :]
    with np.errstate(over="ignore"):
        h = mix(r * np.uint64(1000003) + c)
    m = h % np.uint64(10000)
    x = (m.astype(np.float32) / np.float32(10000.0)).astype(np.float32)
    # Axis-aligned on purpose; see the note in rf_bench.mojo. The first
    # fixture was twelve diagonal bands and BOTH arms scored the 0.25
    # baseline on held-out data, which made the accuracy gate vacuous.
    y = (m[:, :3] >= np.uint64(5000)).sum(axis=1).astype(np.int32)
    return np.ascontiguousarray(x), y, m


def digest(m, y):
    """An EXACT integer digest, so summation order cannot muddy it.

    A float sum would not do: numpy sums pairwise and the Mojo arm sums
    sequentially, so the two would differ in the low bits and the check
    would be reporting its own arithmetic rather than the data."""
    return f"{int(m.astype(np.uint64).sum(dtype=np.uint64))}/{int(y.astype(np.int64).sum())}"


def run_arm(name, n_rows, n_cols, want_checksum, accuracy_only=False):
    x, y, m = make(n_rows, n_cols)
    if want_checksum:
        print("SUM", name, digest(m, y))
        return
    reps = 1 if accuracy_only else REPEATS
    for rep in range(reps):
        clf = RandomForestClassifier(
            n_estimators=N_TREES,
            criterion="gini",
            max_depth=MAX_DEPTH,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features=None,   # all features, matching max_features=1.0
            bootstrap=True,
            random_state=20260821,
            n_jobs=-1,
        )
        t0 = time.perf_counter()
        clf.fit(x, y)
        t1 = time.perf_counter()
        print("ARM", name, (t1 - t0) * 1000.0)
        if rep == reps - 1:
            # HELD OUT -- see the note in rf_bench.mojo. Train accuracy on
            # a bagged ensemble measures memorization, and the arm with
            # bigger trees wins that by construction.
            xte, yte, _ = make(n_rows, n_cols, offset=n_rows)
            print("ACC", name, float((clf.predict(xte) == yte).mean()))


def run_eps_arm(eps_dir, accuracy_only=False):
    """The eps500 arm. Same env-var opt-in as the Mojo side (the shared
    harness passes no arguments), same bytes, same exact integer digest --
    the sum of the file's raw uint32 patterns in FILE order, which UInt64
    wraparound makes identical in numpy and Mojo."""
    name = "rf@eps500-360k"
    n, f, train = 400000, 500, 360000
    xc = np.fromfile(eps_dir + "/eps500_Xcol.f32", dtype=np.float32)
    yf = np.fromfile(eps_dir + "/eps500_y.f32", dtype=np.float32)
    assert xc.size == n * f and yf.size == n
    y01 = (yf > 0).astype(np.int32)
    x_sum = int(xc.view(np.uint32).astype(np.uint64).sum(dtype=np.uint64))
    print("SUM", name, f"{x_sum}/{int(y01.sum())}")
    # Column-major on disk (verified against epsilon_train.tsv row 0):
    # reshape (f, n) then transpose gives rows x features.
    x = np.ascontiguousarray(xc.reshape(f, n).T)
    xtr, ytr = x[:train], y01[:train]
    xte, yte = x[train:], y01[train:]
    reps = 1 if accuracy_only else 3
    for rep in range(reps):
        clf = RandomForestClassifier(
            n_estimators=N_TREES,
            criterion="gini",
            max_depth=MAX_DEPTH,
            min_samples_split=2,
            min_samples_leaf=1,
            max_features=None,   # all features, matching max_features=1.0
            bootstrap=True,
            random_state=20260821,
            n_jobs=-1,
        )
        t0 = time.perf_counter()
        clf.fit(xtr, ytr)
        t1 = time.perf_counter()
        print("ARM", name, (t1 - t0) * 1000.0, flush=True)
        if rep == reps - 1:
            print("ACC", name, float((clf.predict(xte) == yte).mean()))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checksum", action="store_true")
    ap.add_argument("--accuracy", action="store_true",
                    help="one fit per arm, print ACC only -- for reading the "
                         "accuracy that must sit beside any timing")
    args = ap.parse_args()
    import os
    eps_dir = os.environ.get("RF_BENCH_EPS_DIR", "")
    if eps_dir:
        run_eps_arm(eps_dir, args.accuracy)
        return
    run_arm("rf@100000", 100000, 50, args.checksum, args.accuracy)
    run_arm("rf@500000", 500000, 50, args.checksum, args.accuracy)


if __name__ == "__main__":
    main()
