# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
"""CPU training for the Samba stack lanes (lane/cpu-training-samba,
2026-09-15), checked from SOURCE so it runs on a box with nothing built,
plus runtime checks that run only where the host bindings are built and the
package took the CPU-only path.

SambaStack (`python/mojolearn/_samba_impl.py`) holds no numerics: every step
is a call into the training, mamba or transformer binding. The mamba and
transformer host families serve the blocks; the one operation the stack
reached with no host entry was the neural RNG (the initializers and
dropout). The training host binding now registers `neural_rng` over
`core/philox_neural.mojo`'s kernel as `tools/mamba_host_gen.py` writes it
out for the host.

What the source checks hold: the training family declares samba and
samba-untied-dropout-accum and names them for the docs, and the no-CPU-path
sentence no longer names Samba; the training host binding registers
`neural_rng` as the GPU binding does, and the manifest exports it; the
binding's RNG is the generated copy of the device kernel, the generator
reads both Philox sources, and the generated files are current; every
binding entry SambaStack's Python reaches through the three modules is
registered by the three host bindings; the CPU identity gate triggers on the
Philox and Samba sources.

The runtime checks (skipped, and SAID to be skipped, when a binding is
absent or a GPU set loaded): a slice of a stream equals the same elements of
the whole stream for uniform, normal and dropout; the dropout backward
replays the forward's mask; and, where all three families are built, one
Samba training step from the same seed is the same bytes twice.
The bit claim against the GPU columns is the CPU identity gate's.

    cd python && python3 -m mojolearn.tests.test_cpu_training_samba
"""

# Gate-runner scope: host runtime checks require the CPU-only route.
GATE_BACKENDS = ("cpu",)
import re
import subprocess
import sys
from pathlib import Path

import mojolearn
from mojolearn import _backend, host_surface

ROOT = Path(__file__).resolve().parents[3]
SAMBA_LANES = ("samba", "samba-untied-dropout-accum")
PHILOX_GEN = ("mamba/host/gen/philox_neural.mojo", "mamba/host/gen/philox.mojo")


def _read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def _registered(text):
    return set(re.findall(r'def_function\[\w+\]\("(\w+)"\)', text))


def test_manifest_declares_the_samba_lanes():
    fam = host_surface.family("training")
    covered = host_surface.covered_lanes()
    for lane in SAMBA_LANES:
        assert lane in fam["training_lanes"], lane
        assert lane in covered, lane
        assert host_surface.TRAINING_LANE_NAMES[lane] in host_surface.training_sentence()
    assert "Samba" not in host_surface.no_cpu_path_sentence()
    for rel in PHILOX_GEN:
        assert rel in fam["host_modules"] and (ROOT / rel).is_file(), rel


def test_training_host_registers_the_neural_rng():
    gpu = _registered(_read("bindings/_mojolearn_training.mojo"))
    host = _registered(_read(host_surface.binding_source("training")))
    assert "neural_rng" in gpu and "neural_rng" in host
    assert "neural_rng" in host_surface.family("training")["exports"]
    src = _read(host_surface.binding_source("training"))
    assert "from mamba.host.gen.philox_neural import neural_rng_host" in src
    assert not re.search(r"^\s*from\s+core\.philox", src, re.M)


def test_the_host_rng_is_the_generated_device_kernel():
    gen = _read("tools/mamba_host_gen.py")
    for src in ("core/philox_neural.mojo", "core/philox.mojo"):
        assert f'"{src}"' in gen, src
    text = _read("mamba/host/gen/philox_neural.mojo")
    assert "GENERATED by tools/mamba_host_gen.py from core/philox_neural.mojo" in text
    assert "from mamba.host.gen.philox import philox4x32_10" in text
    assert "for gid_ in range(launch_count(" in text
    run = subprocess.run([sys.executable, str(ROOT / "tools" / "mamba_host_gen.py"), "--check"],
                         capture_output=True, text=True)
    assert run.returncode == 0, run.stdout + run.stderr


def test_every_entry_samba_reaches_is_on_the_host():
    """The names SambaStack's Python calls on each binding, read from the
    modules it composes, are all registered by that family's host binding."""
    reaches = {
        "training": ("python/mojolearn/_training_impl.py",),
        "mamba": ("python/mojolearn/_mamba_impl.py",),
        "transformer": ("python/mojolearn/_transformer_impl.py",),
    }
    for fam, files in reaches.items():
        host = _registered(_read(host_surface.binding_source(fam)))
        gpu = _registered(_read(f"bindings/_mojolearn_{fam}.mojo"))
        called = set()
        for rel in files:
            called |= set(re.findall(r"\.(\w+)\(", _read(rel))) & gpu
        missing = sorted(called - host)
        # the multi-GPU availability probes are refused by name on purpose
        # Device-resident sessions are optional GPU APIs. CPU forward uses
        # ordinary block entries, guarded by export checks in the wrappers.
        resident = {
            "mamba": {"mamba1_session_" + name for name in
                      ("create", "open", "step", "export_state", "load_state", "info", "close")}
                | {f"mamba{v}_session_{name}" for v in (2, 3) for name in
                   ("create", "open", "step", "export_state", "load_state", "close")},  # 769936f70, probed by `_has`
            "transformer": {"transformer_session_" + name for name in ("create", "forward", "close")}
                | {"transformer_decode_session_" + name for name in
                   ("create", "open", "step", "forward", "export_state", "load_state", "close")},
        }.get(fam, set())
        missing = [m for m in missing if not m.endswith("_available") and m not in resident]
        assert not missing, f"{fam}: SambaStack's modules call {missing}, absent from the host binding"


def _cpu_only_with(*basenames):
    if _backend._CPU_ONLY is None:
        print("SKIP: a GPU set loaded; the host route is not taken here")
        return False
    built = _backend.host_families_built()
    for basename in basenames:
        if basename not in built:
            print(f"SKIP: {basename} is not built")
            return False
    return True


def test_rng_slices_equal_the_whole_stream_when_built():
    if not _cpu_only_with("_mojolearn_training_host"):
        return
    import numpy as np
    from mojolearn import _training_impl as T
    lib = T._load()
    seed, stream = (7 << 32) | 3, 5
    for kind, a, b in ((T._RNG_UNIFORM, -0.5, 1.0), (T._RNG_NORMAL, 0.0, 1.0)):
        whole = np.asarray(T._rng_call(lib, kind, 37, 0, seed, stream, a, b))
        part = np.asarray(T._rng_call(lib, kind, 11, 13, seed, stream, a, b))
        assert whole.tobytes()[13 * 4:24 * 4] == part.tobytes(), kind
        assert np.isfinite(whole).all()
    x = (np.arange(37, dtype=np.float32) + 1.0)
    fwd = np.asarray(T._rng_call(lib, T._RNG_DROPOUT_FORWARD, 37, 0, seed, stream, 0.5, 2.0, x))
    sub = np.asarray(T._rng_call(lib, T._RNG_DROPOUT_FORWARD, 11, 13, seed, stream, 0.5, 2.0,
                                 np.ascontiguousarray(x[13:24])))
    assert fwd.tobytes()[13 * 4:24 * 4] == sub.tobytes()
    kept = fwd != 0
    assert kept.any() and (~kept).any(), "a p = 0.5 mask kept everything or nothing"
    assert (fwd[kept] == x[kept] * 2.0).all()
    dy = np.full(37, 3.0, dtype=np.float32)
    dx = np.asarray(T._rng_call(lib, T._RNG_DROPOUT_BACKWARD, 37, 0, seed, stream, 0.5, 2.0, dy))
    assert ((dx != 0) == kept).all(), "the backward did not replay the forward's mask"


def test_samba_step_repeats_when_built():
    if not _cpu_only_with("_mojolearn_training_host", "_mojolearn_mamba_host",
                          "_mojolearn_transformer_host"):
        return
    import numpy as np
    ids = (np.arange(2 * 17, dtype=np.int32).reshape(2, 17) * 37) % 256

    def run():
        cfg = mojolearn.SambaConfig(vocab=256, d_model=32, layers=("mamba3", "attention"), n_heads=2,
                                    intermediate=64, tie_embeddings=False, dropout=0.1)
        m = mojolearn.SambaStack(cfg, generator=mojolearn.training.Generator(1), lr=1e-3, max_norm=1.0)
        out = m.train_step(ids[:, :-1], ids[:, 1:])
        p = m.parameters()
        return np.float64(out["loss"]).tobytes() + b"".join(np.asarray(p[k]).tobytes() for k in sorted(p))

    first = run()
    assert first == run(), "the same seeded Samba step was not the same bytes twice"


if __name__ == "__main__":
    names = [n for n in sorted(globals()) if n.startswith("test_")]
    for name in names:
        globals()[name]()
        print("ok", name)
    print(f"{len(names)} passed")
    sys.exit(0)
