"""The differential check: the port against CatBoost's own output.

Separate from `probe_main` because it needs `bench/oracle.txt`, which is
generated by running CatBoost itself. See `mojo_only/oracle_check.mojo` for
why every other check in this repository cannot do what this one does.

    pixi run -e bench python tools/catboost_oracle.py > bench/oracle.json
    pixi run oracle
"""

from mojo_only.oracle_check import (
    check_border_parity,
    check_oracle_is_not_degenerate,
    check_tree_structure,
    print_catboost_structure,
)


def main() raises:
    # Four fixtures. 15 borders is the HALF-BYTE
    # policy; 100 borders is ONE-BYTE and sits inside `maxBins <= 128`,
    # which is the range CatBoost's own dispatch sends to the hist_2
    # family (`hist_one_byte.cu:315-323`). A port of that family passes
    # this suite against CatBoost itself or it does not ship.
    var fixtures = List[String]()
    fixtures.append(String("bench/oracle.txt"))
    fixtures.append(String("bench/oracle100.txt"))
    # border 254: the PASS(8) one-byte range (129-255), which their ladder
    # never sends to hist_2, so no smaller fixture reaches those kernels.
    fixtures.append(String("bench/oracle254.txt"))
    # THE CATEGORICAL FIXTURE. Eight numeric columns at a 100-border grid
    # and three ONE-HOT categorical columns at k = 3, 5 and 8, so the
    # searcher weighs equality candidates against ordered ones in the same
    # tree and the compressed index carries two grid policies at once.
    #
    # ONE-HOT ONLY, and that is a statement about what CatBoost's CPU
    # learner can be asked for rather than a fixture picked to pass: the
    # CTR set this port mirrors is their GPU one, whose frequency column is
    # `FeatureFreq`, and `IsSupportedCtrType(CPU, FeatureFreq)` is FALSE
    # (`private/libs/options/restrictions.h:18-48`). See DEVIATION 113 and
    # the module note in `tools/catboost_cat_oracle.py`.
    fixtures.append(String("bench/oracle_cat.txt"))
    for i in range(len(fixtures)):
        var path = fixtures[i].copy()
        print("CATBOOST DIFFERENTIAL, against " + path + ":")
        check_oracle_is_not_degenerate(path)
        print("  CatBoost's own first three trees:")
        print_catboost_structure(path)
        check_border_parity(path)
        print()
        print(
            "  OUR TREES against THEIRS, same data, same grid, same"
            " parameters:"
        )
        # BOTH SEARCHERS against CatBoost's own dumped decisions. The
        # greedy one is what this repository has always shipped; the
        # pointwise one is the port of the learner CatBoost itself uses for
        # single-target symmetric trees (`PORTING.md` 91 F), and until this
        # ran, every gate on it compared it against a host recomputation or
        # against the other searcher -- never against CatBoost's output.
        check_tree_structure(path, False)
        check_tree_structure(path, True)
        print()
