# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
"""The differential check: the port against CatBoost's own output.

Separate from `probe_main` because it needs `bench/oracle.txt`, which is
generated by running CatBoost itself. See `original/oracle_check.mojo` for
why every other check in this repository cannot do what this one does.

    pixi run -e bench python tools/catboost_oracle.py > bench/oracle.json
    pixi run oracle

The DEPTH and FEATURE-COUNT sweep is a second driver,
`original/oracle_sweep_main.mojo` (`pixi run oracle-sweep`), because it is
fifteen fixtures rather than six and its fixtures vary a different axis.
"""

from original.oracle_check import (
    check_border_parity,
    check_oracle_is_not_degenerate,
    check_tree_structure,
    print_catboost_structure,
    print_policy_reach,
)


def main() raises:
    # SIX FIXTURES, and between them every grid policy and every one-byte
    # accumulator. 15 borders is the HALF-BYTE policy; everything above 15
    # is ONE-BYTE (`SplitByPolicy`, `compressed_index_builder.h:66-70`,
    # against `MaxFolds()` at `grid_policy.h:62-64`), and WITHIN one byte
    # CatBoost runs four different accumulators chosen by fold count:
    #
    #   16..32   5-bit    bench/oracle24.txt
    #   33..64   6-bit    bench/oracle48.txt
    #   65..128  7-bit    bench/oracle100.txt
    #   129..256 8-bit    bench/oracle254.txt
    #
    # from `pointwise_kernels.cpp:57-60` on the host and the bounds at
    # `pointwise_hist2_one_byte_templ.cuh:179-183` on the device. The two
    # middle fixtures were added 2026-08-21: before them the 6-bit
    # accumulator had NO differential against CatBoost at all, and
    # `PORTING.md` 108 is the record of what a kernel reached by exactly one
    # fixture costs. Which accumulator each fixture actually enters is
    # OBSERVED, not assumed -- `pixi run check-onebyte-reach`.
    var fixtures = List[String]()
    fixtures.append(String("bench/oracle.txt"))
    fixtures.append(String("bench/oracle24.txt"))
    fixtures.append(String("bench/oracle48.txt"))
    fixtures.append(String("bench/oracle100.txt"))
    fixtures.append(String("bench/oracle254.txt"))
    # THE CATEGORICAL FIXTURE. Eight numeric columns at a 100-border grid
    # and three ONE-HOT categorical columns at k = 3, 5 and 8, so the
    # searcher weighs equality candidates against ordered ones in the same
    # tree and the compressed index carries two grid policies at once.
    #
    # ONE-HOT ONLY, and that is a statement about what CatBoost's CPU
    # learner can be asked for rather than a fixture picked to pass: the
    # CTR set this port mirrors is their GPU one, whose frequency column is
    # `FeatureFreq`, and `IsSupportedCtrType(CPU, FeatureFreq)` is FALSE
    # (`private/libs/options/restrictions.h:18-48`). See DEVIATION 113 and
    # the module note in `tools/catboost_cat_oracle.py`.
    fixtures.append(String("bench/oracle_cat.txt"))
    for i in range(len(fixtures)):
        var path = fixtures[i].copy()
        print("CATBOOST DIFFERENTIAL, against " + path + ":")
        check_oracle_is_not_degenerate(path)
        print("  CatBoost's own first three trees:")
        print_catboost_structure(path)
        check_border_parity(path)
        # PORTING_RULES 8: the harness prints which path it took, beside the
        # result. A differential that cannot name the accumulator it ran can
        # publish a green tick about a different one.
        print_policy_reach(path)
        print()
        print(
            "  OUR TREES against THEIRS, same data, same grid, same"
            " parameters:"
        )
        # BOTH SEARCHERS against CatBoost's own dumped decisions. The
        # greedy one is what this repository has always shipped; the
        # pointwise one is the port of the learner CatBoost itself uses for
        # single-target symmetric trees (`PORTING.md` 91 F), and until this
        # ran, every gate on it compared it against a host recomputation or
        # against the other searcher -- never against CatBoost's output.
        check_tree_structure(path, False)
        check_tree_structure(path, True)
        print()
