# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
"""Emit tokenizer/data/unicode_categories.tsv: the range tables the GPT-2
pre-tokenizer pattern needs.

THE PATTERN, verbatim from the fixture's `pat_str`:

    '(?:[sdmt]|ll|ve|re)| ?\\p{L}++| ?\\p{N}++| ?[^\\s\\p{L}\\p{N}]++|\\s++$|\\s+(?!\\S)|\\s

Three character classes appear in it and nothing else does:

  L   general category Letter = Lu + Ll + Lt + Lm + Lo. This is what
      `\\p{L}` means in the Rust `regex` / `fancy-regex` syntax tiktoken
      compiles the pattern with -- MARKS (Mn, Mc, Me) are NOT letters, which
      is why a combining acute is its own pre-token in the reference.
  N   general category Number = Nd + Nl + No (`\\p{N}`).
  WS  the Unicode WHITE_SPACE PROPERTY, which is what `\\s` means in that
      syntax. It is NOT Python's `str.isspace()`: isspace() also answers True
      for U+001C..U+001F (category Cc, White_Space=No), so this table is
      written out from PropList.txt rather than taken from Python.

L and N come from `unicodedata.category`, so the Unicode version of the
table is the Unicode version of the Python that ran this script; it is
written into the file header and the check prints it. A codepoint assigned
to a letter category in one Unicode version and unassigned in another is
the one way this table and tiktoken's can disagree; every such codepoint is
outside the fixture.

Run from the repository root, HOST ONLY, no arguments:

    python tokenizer/tools/gen_unicode_categories.py
"""

import sys
import unicodedata

# The White_Space property, PropList.txt (stable since Unicode 4.1).
WHITE_SPACE = [
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
]

OUT = "tokenizer/data/unicode_categories.tsv"


def ranges(prefix):
    out = []
    start = None
    for cp in range(0x110000):
        hit = unicodedata.category(chr(cp)).startswith(prefix)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def main():
    letters = ranges("L")
    numbers = ranges("N")
    lines = [
        "# GENERATED by tokenizer/tools/gen_unicode_categories.py -- do not"
        " hand-edit",
        "# unicodedata %s (python %s)"
        % (unicodedata.unidata_version, sys.version.split()[0]),
        "# class\tfirst_hex\tlast_hex  (inclusive, ascending, disjoint)",
        "# L = \\p{L} (Lu Ll Lt Lm Lo), N = \\p{N} (Nd Nl No),"
        " WS = White_Space property (\\s)",
    ]
    for name, rs in (("L", letters), ("N", numbers), ("WS", WHITE_SPACE)):
        for first, last in rs:
            lines.append("%s\t%04X\t%04X" % (name, first, last))
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(
        "%s: %d L ranges, %d N ranges, %d WS ranges, unicodedata %s"
        % (OUT, len(letters), len(numbers), len(WHITE_SPACE),
           unicodedata.unidata_version)
    )


if __name__ == "__main__":
    main()
