# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""The neighbors lane's GPU drivers (see x_neighbors/gen.py)."""
from std.gpu import block_idx, block_dim, thread_idx
from std.ffi import _Global
from max.gpu.host import DeviceBuffer, DeviceContext
from std.sys.compile import is_defined
from bindings.hostptr import copy_f32
from core.host_parallel import host_parallelize
from core.host_predict_threads import host_predict_chunk, host_predict_task_count
from checks.numerics import GLOBAL_NUMERIC_MODE, NUMERIC_IDENTICAL
from x_neighbors.items import FP, IP, sqdist_item, nan_sqdist_item, l1dist_item, kernel_item, matmul_item, rowsum_item, colsum_item, unary_item, knn_select_item, knn_sq_item, group_mean_item, take_rows_item, take_cols_item, variance_item, ocsvm_smo_item, lof_lrd_item, lof_score_item, kpca_center_item, scale_div_item, svd_flip_item, kpca_alpha_scale_item, nc_std_item, nc_shrink_d_item, nc_shrink_item, nc_decision_item, softmax_item, log_softmax_item, pcs_item, achi2_item, skew_weights_item, skew_transform_item, absdiff_sum_item, row_normalize_item, lp_clamp_item, ls_clamp_item, ls_laplacian_item, knn_graph_item, knn_impute_item, col_degree_item, ls_laplacian_deg_item, row_all_zero_item, pcs_sketch_item, pcs_conv_item, pcs_copy0_item, knn_impute_cell_item, pagerank_step_item, cc_step_item, graph_symmetry_item, louvain_item, svgp_item, svgp_var_item
from x_neighbors.louvain_sparse import louvain_item_sparse
from x_neighbors.block_ops import ocsvm_smo_block, OCSVM_TPB

comptime BLOCK = 128


struct _NeighborsContext(Defaultable, Movable):
    """ONE process-lifetime DeviceContext for every x_neighbors driver. A
    context per call let a driver's DeviceBuffers outlive the context they
    were made on (Mojo destroys the context at its last use, the
    synchronize, before the buffers), and a second GPU call in the same
    process hung (LocalOutlierFactor on an RTX 4090, 2026-09-27); a context
    per call also exhausts Metal's per-process command queues. Storage is
    `std.ffi._Global` (x_cnn/device.mojo's pattern), one slot per numeric
    tier so a FAST and an IDENTICAL .so in one process never share it."""
    var ctx: Optional[DeviceContext]

    def __init__(out self):
        self.ctx = Optional[DeviceContext]()


comptime _CTX_NAME = "MojoXNeighborsContextIdentical" if GLOBAL_NUMERIC_MODE == NUMERIC_IDENTICAL else "MojoXNeighborsContextFast"
comptime X_NEIGHBORS_CONTEXT = _Global[StorageType=_NeighborsContext, name=_CTX_NAME, init_fn=_NeighborsContext.__init__]


def xn_ctx() raises -> DeviceContext:
    """The shared context, created on first use."""
    var slot = X_NEIGHBORS_CONTEXT.get_or_create_ptr()
    if not slot[].ctx:
        slot[].ctx = DeviceContext()
    return slot[].ctx.value().copy()


@always_inline
def _tid() -> Int:
    return Int(block_idx.x) * Int(block_dim.x) + Int(thread_idx.x)


def _grid(count: Int) -> Int:
    return (count + BLOCK - 1) // BLOCK if count > 0 else 1


def _buf(ctx: DeviceContext, addr: Int, count: Int, upload: Bool) raises -> DeviceBuffer[DType.float32]:
    var buf = ctx.enqueue_create_buffer[DType.float32](count if count > 0 else 1)
    if upload and count > 0:
        comptime if is_defined["MOJOLEARN_XN_MAPPED_UP"]():
            # lane neighbors-apple3, OPT-IN: a large input copied into the
            # mapped device buffer over the host cores. A copy.
            if count >= XN_STAGED_MIN:
                ctx.synchronize()
                with buf.map_to_host() as hm:
                    var mdst = rebind[MutPointer[Float32, MutUntrackedOrigin]](hm.unsafe_ptr())
                    var msrc = MutPointer[Float32, MutUntrackedOrigin](unsafe_from_address=addr)
                    var mtasks = host_predict_task_count(count)
                    var mpart = host_predict_chunk(count, mtasks)

                    def _mpart(task: Int) {imm msrc, imm mdst, imm count, imm mpart}:
                        var lo = task * mpart
                        var hi = min(lo + mpart, count)
                        if hi > lo:
                            copy_f32(msrc.unsafe_offset(lo), mdst.unsafe_offset(lo), hi - lo)

                    if mtasks == 1:
                        _mpart(0)
                    else:
                        host_parallelize(_mpart, mtasks)
                return buf^
        ctx.enqueue_copy(dst_buf=buf, src_ptr=FP(unsafe_from_address=addr))
    return buf^


def _buf_i(ctx: DeviceContext, addr: Int, count: Int, upload: Bool) raises -> DeviceBuffer[DType.int32]:
    var buf = ctx.enqueue_create_buffer[DType.int32](count if count > 0 else 1)
    if upload and count > 0:
        ctx.enqueue_copy(dst_buf=buf, src_ptr=IP(unsafe_from_address=addr))
    return buf^


#: lane neighbors-apple2: a large float output comes back through a host
#: staging buffer of XN_OUT_CHUNK floats and is copied into the caller's
#: array over the host cores (the first touch of the caller's fresh pages
#: dominates a plain copy; kernel_methods/estimator.mojo `_download_into`,
#: round one). A copy: no arithmetic. `-D MOJOLEARN_XN_PLAIN_DOWN` keeps the
#: one enqueue_copy.
comptime XN_OUT_CHUNK = 1 << 24
comptime XN_STAGED_MIN = 1 << 22


def _down(ctx: DeviceContext, buf: DeviceBuffer[DType.float32], addr: Int, count: Int) raises:
    if count <= 0:
        return
    comptime if is_defined["MOJOLEARN_XN_PLAIN_DOWN"]():
        ctx.enqueue_copy(dst_ptr=FP(unsafe_from_address=addr), src_buf=buf)
        return
    if count < XN_STAGED_MIN:
        ctx.enqueue_copy(dst_ptr=FP(unsafe_from_address=addr), src_buf=buf)
        return
    comptime if is_defined["MOJOLEARN_XN_MAPPED_DOWN"]():
        # lane neighbors-apple3, OPT-IN: the device buffer mapped into the
        # host (Apple's memory is unified) and copied once, over the host
        # cores, instead of once into the staging buffer and once out of it.
        ctx.synchronize()
        with buf.map_to_host() as hm:
            var msrc = rebind[MutPointer[Float32, MutUntrackedOrigin]](hm.unsafe_ptr())
            var mdst = MutPointer[Float32, MutUntrackedOrigin](unsafe_from_address=addr)
            var mtasks = host_predict_task_count(count)
            var mpart = host_predict_chunk(count, mtasks)

            def _mpart(task: Int) {imm msrc, imm mdst, imm count, imm mpart}:
                var lo = task * mpart
                var hi = min(lo + mpart, count)
                if hi > lo:
                    copy_f32(msrc.unsafe_offset(lo), mdst.unsafe_offset(lo), hi - lo)

            if mtasks == 1:
                _mpart(0)
            else:
                host_parallelize(_mpart, mtasks)
        return
    var c = min(count, XN_OUT_CHUNK)
    var h = ctx.enqueue_create_host_buffer[DType.float32](c)
    var off = 0
    while off < count:
        var m = min(c, count - off)
        var sub = buf.create_sub_buffer[DType.float32](off, m)
        ctx.enqueue_copy(dst_ptr=h.unsafe_ptr(), src_buf=sub)
        ctx.synchronize()
        var src_p = rebind[MutPointer[Float32, MutUntrackedOrigin]](h.unsafe_ptr())
        var dst_p = MutPointer[Float32, MutUntrackedOrigin](unsafe_from_address=addr + off * 4)
        var tasks = host_predict_task_count(m)
        var part = host_predict_chunk(m, tasks)

        def _part(task: Int) {imm src_p, imm dst_p, imm m, imm part}:
            var lo = task * part
            var hi = min(lo + part, m)
            if hi > lo:
                copy_f32(src_p.unsafe_offset(lo), dst_p.unsafe_offset(lo), hi - lo)

        if tasks == 1:
            _part(0)
        else:
            host_parallelize(_part, tasks)
        _ = sub^
        off += m
    _ = h^


def _down_i(ctx: DeviceContext, buf: DeviceBuffer[DType.int32], addr: Int, count: Int) raises:
    if count > 0:
        ctx.enqueue_copy(dst_ptr=IP(unsafe_from_address=addr), src_buf=buf)


@always_inline
def _f(addr: Int) -> FP:
    return FP(unsafe_from_address=addr)


@always_inline
def _i(addr: Int) -> IP:
    return IP(unsafe_from_address=addr)


def sqdist_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var t = _tid()
    if t < n * m:
        sqdist_item(t, x, y, res, n, m, d)


def op_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[sqdist_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^
    _ = ctx^


def nan_sqdist_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var t = _tid()
    if t < n * m:
        nan_sqdist_item(t, x, y, res, n, m, d)


def op_nan_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[nan_sqdist_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^
    _ = ctx^


def l1dist_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var t = _tid()
    if t < n * m:
        l1dist_item(t, x, y, res, n, m, d)


def op_l1dist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[l1dist_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^
    _ = ctx^


def kernel_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64, kind_: Int64, gamma_: Float32, coef0_: Float32, degree_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var kind = Int(kind_)
    var gamma = gamma_
    var coef0 = coef0_
    var degree = Int(degree_)
    var t = _tid()
    if t < n * m:
        kernel_item(t, x, y, res, n, m, d, kind, gamma, coef0, degree)


def op_kernel(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int, kind: Int, gamma: Float32, coef0: Float32, degree: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[kernel_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d), Int64(kind), gamma, coef0, Int64(degree),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^
    _ = ctx^


def matmul_kernel(a: FP, b: FP, res: FP, n_: Int64, k_: Int64, m_: Int64):
    var n = Int(n_)
    var k = Int(k_)
    var m = Int(m_)
    var t = _tid()
    if t < n * m:
        matmul_item(t, a, b, res, n, k, m)


def op_matmul(a: Int, b: Int, res: Int, n: Int, k: Int, m: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * k, True)
    var d_b = _buf(ctx, b, k * m, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[matmul_kernel](
        d_a.unsafe_ptr(), d_b.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(k), Int64(m),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_a^
    _ = d_b^
    _ = d_res^
    _ = ctx^


def rowsum_kernel(a: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < n:
        rowsum_item(t, a, res, n, m)


def op_rowsum(a: Int, res: Int, n: Int, m: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * m, True)
    var d_res = _buf(ctx, res, n, False)
    ctx.enqueue_function[rowsum_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^
    _ = ctx^


def colsum_kernel(a: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < m:
        colsum_item(t, a, res, n, m)


def op_colsum(a: Int, res: Int, n: Int, m: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * m, True)
    var d_res = _buf(ctx, res, m, False)
    ctx.enqueue_function[colsum_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(m), block_dim=(BLOCK if m > 1 else 1),
    )
    _down(ctx, d_res, res, m)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^
    _ = ctx^


def unary_kernel(x: FP, res: FP, count_: Int64, op_: Int64, a_: Float32, b_: Float32):
    var count = Int(count_)
    var op = Int(op_)
    var a = a_
    var b = b_
    var t = _tid()
    if t < count:
        unary_item(t, x, res, count, op, a, b)


def op_unary(x: Int, res: Int, count: Int, op: Int, a: Float32, b: Float32) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, count, True)
    var d_res = _buf(ctx, res, count, False)
    ctx.enqueue_function[unary_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count), Int64(op), a, b,
        grid_dim=_grid(count), block_dim=(BLOCK if count > 1 else 1),
    )
    _down(ctx, d_res, res, count)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
    _ = ctx^


def knn_select_kernel(dmat: FP, dist: FP, idx: IP, n_: Int64, m_: Int64, k_: Int64, exclude_self_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var k = Int(k_)
    var exclude_self = Int(exclude_self_)
    var t = _tid()
    if t < n:
        knn_select_item(t, dmat, dist, idx, n, m, k, exclude_self)


def op_knn_select(dmat: Int, dist: Int, idx: Int, n: Int, m: Int, k: Int, exclude_self: Int) raises:
    var ctx = xn_ctx()
    var d_dmat = _buf(ctx, dmat, n * m, True)
    var d_dist = _buf(ctx, dist, n * k, False)
    var d_idx = _buf_i(ctx, idx, n * k, False)
    ctx.enqueue_function[knn_select_kernel](
        d_dmat.unsafe_ptr(), d_dist.unsafe_ptr(), d_idx.unsafe_ptr(), Int64(n), Int64(m), Int64(k), Int64(exclude_self),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_dist, dist, n * k)
    _down_i(ctx, d_idx, idx, n * k)
    ctx.synchronize()
    _ = d_dmat^
    _ = d_dist^
    _ = d_idx^
    _ = ctx^


def knn_sq_kernel(x: FP, y: FP, dist: FP, idx: IP, n_: Int64, m_: Int64, d_: Int64, k_: Int64, exclude_self_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var k = Int(k_)
    var exclude_self = Int(exclude_self_)
    var t = _tid()
    if t < n:
        knn_sq_item(t, x, y, dist, idx, n, m, d, k, exclude_self)


def op_knn_sq(x: Int, y: Int, dist: Int, idx: Int, n: Int, m: Int, d: Int, k: Int, exclude_self: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_dist = _buf(ctx, dist, n * k, False)
    var d_idx = _buf_i(ctx, idx, n * k, False)
    ctx.enqueue_function[knn_sq_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_dist.unsafe_ptr(), d_idx.unsafe_ptr(), Int64(n), Int64(m), Int64(d), Int64(k), Int64(exclude_self),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_dist, dist, n * k)
    _down_i(ctx, d_idx, idx, n * k)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_dist^
    _ = d_idx^
    _ = ctx^


def group_mean_kernel(x: FP, labels: IP, res: FP, n_: Int64, d_: Int64, g_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var g = Int(g_)
    var t = _tid()
    if t < g * d:
        group_mean_item(t, x, labels, res, n, d, g)


def op_group_mean(x: Int, labels: Int, res: Int, n: Int, d: Int, g: Int) raises:
    comptime if not is_defined["MOJOLEARN_XN_SERIAL_GPU"]():
        for t in range(g * d):
            group_mean_item(t, _f(x), _i(labels), _f(res), n, d, g)
        return
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_labels = _buf_i(ctx, labels, n, True)
    var d_res = _buf(ctx, res, g * d, False)
    ctx.enqueue_function[group_mean_kernel](
        d_x.unsafe_ptr(), d_labels.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(g),
        grid_dim=_grid(g * d), block_dim=(BLOCK if g * d > 1 else 1),
    )
    _down(ctx, d_res, res, g * d)
    ctx.synchronize()
    _ = d_x^
    _ = d_labels^
    _ = d_res^
    _ = ctx^


def take_rows_kernel(src: FP, rows: IP, res: FP, n_out_: Int64, d_: Int64, n_src_: Int64):
    var n_out = Int(n_out_)
    var d = Int(d_)
    var n_src = Int(n_src_)
    var t = _tid()
    if t < n_out * d:
        take_rows_item(t, src, rows, res, n_out, d, n_src)


def op_take_rows(src: Int, rows: Int, res: Int, n_out: Int, d: Int, n_src: Int) raises:
    var ctx = xn_ctx()
    var d_src = _buf(ctx, src, n_src * d, True)
    var d_rows = _buf_i(ctx, rows, n_out, True)
    var d_res = _buf(ctx, res, n_out * d, False)
    ctx.enqueue_function[take_rows_kernel](
        d_src.unsafe_ptr(), d_rows.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n_out), Int64(d), Int64(n_src),
        grid_dim=_grid(n_out * d), block_dim=(BLOCK if n_out * d > 1 else 1),
    )
    _down(ctx, d_res, res, n_out * d)
    ctx.synchronize()
    _ = d_src^
    _ = d_rows^
    _ = d_res^
    _ = ctx^


def take_cols_kernel(src: FP, cols: IP, res: FP, n_: Int64, src_c_: Int64, c_: Int64):
    var n = Int(n_)
    var src_c = Int(src_c_)
    var c = Int(c_)
    var t = _tid()
    if t < n * c:
        take_cols_item(t, src, cols, res, n, src_c, c)


def op_take_cols(src: Int, cols: Int, res: Int, n: Int, src_c: Int, c: Int) raises:
    var ctx = xn_ctx()
    var d_src = _buf(ctx, src, n * src_c, True)
    var d_cols = _buf_i(ctx, cols, c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[take_cols_kernel](
        d_src.unsafe_ptr(), d_cols.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(src_c), Int64(c),
        grid_dim=_grid(n * c), block_dim=(BLOCK if n * c > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_src^
    _ = d_cols^
    _ = d_res^
    _ = ctx^


def variance_kernel(x: FP, res: FP, count_: Int64):
    var count = Int(count_)
    var t = _tid()
    if t < 1:
        variance_item(t, x, res, count)


def op_variance(x: Int, res: Int, count: Int) raises:
    comptime if not is_defined["MOJOLEARN_XN_SERIAL_GPU"]():
        for t in range(1):
            variance_item(t, _f(x), _f(res), count)
        return
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, count, True)
    var d_res = _buf(ctx, res, 1, False)
    ctx.enqueue_function[variance_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count),
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down(ctx, d_res, res, 1)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
    _ = ctx^


def ocsvm_kernel(q: FP, cv: FP, alpha: FP, g: FP, info: FP, iters: IP, n_: Int64, eps_: Float32, max_iter_: Int64):
    var n = Int(n_)
    var eps = eps_
    var max_iter = Int(max_iter_)
    comptime if is_defined["MOJOLEARN_XN_SERIAL_SMO"]():
        var t = _tid()
        if t < 1:
            ocsvm_smo_item(t, q, cv, alpha, g, info, iters, n, eps, max_iter)
    else:
        ocsvm_smo_block(q, cv, alpha, g, info, iters, n, eps, max_iter)


def op_ocsvm(q: Int, cv: Int, alpha: Int, info: Int, iters: Int, n: Int, eps: Float32, max_iter: Int) raises:
    var ctx = xn_ctx()
    var d_q = _buf(ctx, q, n * n, True)
    var d_cv = _buf(ctx, cv, n, True)
    var d_alpha = _buf(ctx, alpha, n, True)
    var d_g = _buf(ctx, 0, n, False)
    var d_info = _buf(ctx, info, 1, False)
    var d_iters = _buf_i(ctx, iters, 1, False)
    comptime tpb = 1 if is_defined["MOJOLEARN_XN_SERIAL_SMO"]() else OCSVM_TPB
    ctx.enqueue_function[ocsvm_kernel](
        d_q.unsafe_ptr(), d_cv.unsafe_ptr(), d_alpha.unsafe_ptr(), d_g.unsafe_ptr(), d_info.unsafe_ptr(), d_iters.unsafe_ptr(), Int64(n), eps, Int64(max_iter),
        grid_dim=1, block_dim=tpb,
    )
    _down(ctx, d_alpha, alpha, n)
    _down(ctx, d_info, info, 1)
    _down_i(ctx, d_iters, iters, 1)
    ctx.synchronize()
    _ = d_q^
    _ = d_cv^
    _ = d_alpha^
    _ = d_g^
    _ = d_info^
    _ = d_iters^
    _ = ctx^


def lof_lrd_kernel(dist: FP, idx: IP, fit_dist: FP, lrd: FP, k_: Int64, n_: Int64, n_fit_: Int64):
    var k = Int(k_)
    var n = Int(n_)
    var n_fit = Int(n_fit_)
    var t = _tid()
    if t < n:
        lof_lrd_item(t, dist, idx, fit_dist, lrd, k, n, n_fit)


def op_lof_lrd(dist: Int, idx: Int, fit_dist: Int, lrd: Int, k: Int, n: Int, n_fit: Int) raises:
    var ctx = xn_ctx()
    var d_dist = _buf(ctx, dist, n * k, True)
    var d_idx = _buf_i(ctx, idx, n * k, True)
    var d_fit_dist = _buf(ctx, fit_dist, n_fit * k, True)
    var d_lrd = _buf(ctx, lrd, n, False)
    ctx.enqueue_function[lof_lrd_kernel](
        d_dist.unsafe_ptr(), d_idx.unsafe_ptr(), d_fit_dist.unsafe_ptr(), d_lrd.unsafe_ptr(), Int64(k), Int64(n), Int64(n_fit),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_lrd, lrd, n)
    ctx.synchronize()
    _ = d_dist^
    _ = d_idx^
    _ = d_fit_dist^
    _ = d_lrd^
    _ = ctx^


def lof_score_kernel(idx: IP, fit_lrd: FP, lrd: FP, score: FP, k_: Int64, n_: Int64, n_fit_: Int64):
    var k = Int(k_)
    var n = Int(n_)
    var n_fit = Int(n_fit_)
    var t = _tid()
    if t < n:
        lof_score_item(t, idx, fit_lrd, lrd, score, k, n, n_fit)


def op_lof_score(idx: Int, fit_lrd: Int, lrd: Int, score: Int, k: Int, n: Int, n_fit: Int) raises:
    var ctx = xn_ctx()
    var d_idx = _buf_i(ctx, idx, n * k, True)
    var d_fit_lrd = _buf(ctx, fit_lrd, n_fit, True)
    var d_lrd = _buf(ctx, lrd, n, True)
    var d_score = _buf(ctx, score, n, False)
    ctx.enqueue_function[lof_score_kernel](
        d_idx.unsafe_ptr(), d_fit_lrd.unsafe_ptr(), d_lrd.unsafe_ptr(), d_score.unsafe_ptr(), Int64(k), Int64(n), Int64(n_fit),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_score, score, n)
    ctx.synchronize()
    _ = d_idx^
    _ = d_fit_lrd^
    _ = d_lrd^
    _ = d_score^
    _ = ctx^


def kpca_center_kernel(k: FP, fit_cols: FP, pred_rows: FP, fit_all: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < n * m:
        kpca_center_item(t, k, fit_cols, pred_rows, fit_all, res, n, m)


def op_kpca_center(k: Int, fit_cols: Int, pred_rows: Int, fit_all: Int, res: Int, n: Int, m: Int) raises:
    var ctx = xn_ctx()
    var d_k = _buf(ctx, k, n * m, True)
    var d_fit_cols = _buf(ctx, fit_cols, m, True)
    var d_pred_rows = _buf(ctx, pred_rows, n, True)
    var d_fit_all = _buf(ctx, fit_all, 1, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[kpca_center_kernel](
        d_k.unsafe_ptr(), d_fit_cols.unsafe_ptr(), d_pred_rows.unsafe_ptr(), d_fit_all.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_k^
    _ = d_fit_cols^
    _ = d_pred_rows^
    _ = d_fit_all^
    _ = d_res^
    _ = ctx^


def scale_div_kernel(x: FP, res: FP, count_: Int64, s_: Float32):
    var count = Int(count_)
    var s = s_
    var t = _tid()
    if t < count:
        scale_div_item(t, x, res, count, s)


def op_scale_div(x: Int, res: Int, count: Int, s: Float32) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, count, True)
    var d_res = _buf(ctx, res, count, False)
    ctx.enqueue_function[scale_div_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count), s,
        grid_dim=_grid(count), block_dim=(BLOCK if count > 1 else 1),
    )
    _down(ctx, d_res, res, count)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
    _ = ctx^


def svd_flip_kernel(v: FP, n_: Int64, c_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var t = _tid()
    if t < c:
        svd_flip_item(t, v, n, c)


def op_svd_flip(v: Int, n: Int, c: Int) raises:
    var ctx = xn_ctx()
    var d_v = _buf(ctx, v, n * c, True)
    ctx.enqueue_function[svd_flip_kernel](
        d_v.unsafe_ptr(), Int64(n), Int64(c),
        grid_dim=_grid(c), block_dim=(BLOCK if c > 1 else 1),
    )
    _down(ctx, d_v, v, n * c)
    ctx.synchronize()
    _ = d_v^
    _ = ctx^


def kpca_alpha_scale_kernel(v: FP, w: FP, res: FP, n_: Int64, c_: Int64, divide_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var divide = Int(divide_)
    var t = _tid()
    if t < n * c:
        kpca_alpha_scale_item(t, v, w, res, n, c, divide)


def op_kpca_alpha_scale(v: Int, w: Int, res: Int, n: Int, c: Int, divide: Int) raises:
    var ctx = xn_ctx()
    var d_v = _buf(ctx, v, n * c, True)
    var d_w = _buf(ctx, w, c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[kpca_alpha_scale_kernel](
        d_v.unsafe_ptr(), d_w.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(c), Int64(divide),
        grid_dim=_grid(n * c), block_dim=(BLOCK if n * c > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_v^
    _ = d_w^
    _ = d_res^
    _ = ctx^


def nc_std_kernel(x: FP, lab: IP, cent: FP, std: FP, n_: Int64, d_: Int64, n_classes_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var t = _tid()
    if t < d:
        nc_std_item(t, x, lab, cent, std, n, d, n_classes)


def op_nc_std(x: Int, lab: Int, cent: Int, std: Int, n: Int, d: Int, n_classes: Int) raises:
    comptime if not is_defined["MOJOLEARN_XN_SERIAL_GPU"]():
        for t in range(d):
            nc_std_item(t, _f(x), _i(lab), _f(cent), _f(std), n, d, n_classes)
        return
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_lab = _buf_i(ctx, lab, n, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_std = _buf(ctx, std, d, False)
    ctx.enqueue_function[nc_std_kernel](
        d_x.unsafe_ptr(), d_lab.unsafe_ptr(), d_cent.unsafe_ptr(), d_std.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes),
        grid_dim=_grid(d), block_dim=(BLOCK if d > 1 else 1),
    )
    _down(ctx, d_std, std, d)
    ctx.synchronize()
    _ = d_x^
    _ = d_lab^
    _ = d_cent^
    _ = d_std^
    _ = ctx^


def nc_shrink_d_kernel(dsc: FP, cent: FP, nk: FP, std: FP, res: FP, devs: FP, n_: Int64, d_: Int64, n_classes_: Int64, do_shrink_: Int64, med_: Float32, shrink_: Float32):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var do_shrink = Int(do_shrink_)
    var med = med_
    var shrink = shrink_
    var t = _tid()
    if t < n_classes * d:
        nc_shrink_d_item(t, dsc, cent, nk, std, res, devs, n, d, n_classes, do_shrink, med, shrink)


def op_nc_shrink_d(dsc: Int, cent: Int, nk: Int, std: Int, res: Int, devs: Int, n: Int, d: Int, n_classes: Int, do_shrink: Int, med: Float32, shrink: Float32) raises:
    var ctx = xn_ctx()
    var d_dsc = _buf(ctx, dsc, d, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_nk = _buf(ctx, nk, n_classes, True)
    var d_std = _buf(ctx, std, d, True)
    var d_res = _buf(ctx, res, n_classes * d, False)
    var d_devs = _buf(ctx, devs, n_classes * d, False)
    ctx.enqueue_function[nc_shrink_d_kernel](
        d_dsc.unsafe_ptr(), d_cent.unsafe_ptr(), d_nk.unsafe_ptr(), d_std.unsafe_ptr(), d_res.unsafe_ptr(), d_devs.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes), Int64(do_shrink), med, shrink,
        grid_dim=_grid(n_classes * d), block_dim=(BLOCK if n_classes * d > 1 else 1),
    )
    _down(ctx, d_res, res, n_classes * d)
    _down(ctx, d_devs, devs, n_classes * d)
    ctx.synchronize()
    _ = d_dsc^
    _ = d_cent^
    _ = d_nk^
    _ = d_std^
    _ = d_res^
    _ = d_devs^
    _ = ctx^


def nc_shrink_kernel(x: FP, cent: FP, nk: FP, std: FP, res: FP, devs: FP, n_: Int64, d_: Int64, n_classes_: Int64, do_shrink_: Int64, med_: Float32, shrink_: Float32):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var do_shrink = Int(do_shrink_)
    var med = med_
    var shrink = shrink_
    var t = _tid()
    if t < n_classes * d:
        nc_shrink_item(t, x, cent, nk, std, res, devs, n, d, n_classes, do_shrink, med, shrink)


def op_nc_shrink(x: Int, cent: Int, nk: Int, std: Int, res: Int, devs: Int, n: Int, d: Int, n_classes: Int, do_shrink: Int, med: Float32, shrink: Float32) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_nk = _buf(ctx, nk, n_classes, True)
    var d_std = _buf(ctx, std, d, True)
    var d_res = _buf(ctx, res, n_classes * d, False)
    var d_devs = _buf(ctx, devs, n_classes * d, False)
    ctx.enqueue_function[nc_shrink_kernel](
        d_x.unsafe_ptr(), d_cent.unsafe_ptr(), d_nk.unsafe_ptr(), d_std.unsafe_ptr(), d_res.unsafe_ptr(), d_devs.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes), Int64(do_shrink), med, shrink,
        grid_dim=_grid(n_classes * d), block_dim=(BLOCK if n_classes * d > 1 else 1),
    )
    _down(ctx, d_res, res, n_classes * d)
    _down(ctx, d_devs, devs, n_classes * d)
    ctx.synchronize()
    _ = d_x^
    _ = d_cent^
    _ = d_nk^
    _ = d_std^
    _ = d_res^
    _ = d_devs^
    _ = ctx^


def nc_decision_kernel(q: FP, cent: FP, std: FP, prior: FP, res: FP, n_: Int64, d_: Int64, n_classes_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var t = _tid()
    if t < n * n_classes:
        nc_decision_item(t, q, cent, std, prior, res, n, d, n_classes)


def op_nc_decision(q: Int, cent: Int, std: Int, prior: Int, res: Int, n: Int, d: Int, n_classes: Int) raises:
    var ctx = xn_ctx()
    var d_q = _buf(ctx, q, n * d, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_std = _buf(ctx, std, d, True)
    var d_prior = _buf(ctx, prior, n_classes, True)
    var d_res = _buf(ctx, res, n * n_classes, False)
    ctx.enqueue_function[nc_decision_kernel](
        d_q.unsafe_ptr(), d_cent.unsafe_ptr(), d_std.unsafe_ptr(), d_prior.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes),
        grid_dim=_grid(n * n_classes), block_dim=(BLOCK if n * n_classes > 1 else 1),
    )
    _down(ctx, d_res, res, n * n_classes)
    ctx.synchronize()
    _ = d_q^
    _ = d_cent^
    _ = d_std^
    _ = d_prior^
    _ = d_res^
    _ = ctx^


def softmax_kernel(x: FP, res: FP, n_: Int64, c_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var t = _tid()
    if t < n:
        softmax_item(t, x, res, n, c)


def op_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[softmax_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(c),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
    _ = ctx^


def log_softmax_kernel(x: FP, res: FP, n_: Int64, c_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var t = _tid()
    if t < n:
        log_softmax_item(t, x, res, n, c)


def op_log_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[log_softmax_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(c),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
    _ = ctx^


def pcs_kernel(x: FP, hidx: IP, hbit: IP, res: FP, scr: FP, n_: Int64, d_in_: Int64, nf_: Int64, nc_: Int64, degree_: Int64, gamma_: Float32, coef0_: Float32):
    var n = Int(n_)
    var d_in = Int(d_in_)
    var nf = Int(nf_)
    var nc = Int(nc_)
    var degree = Int(degree_)
    var gamma = gamma_
    var coef0 = coef0_
    var t = _tid()
    if t < n:
        pcs_item(t, x, hidx, hbit, res, scr, n, d_in, nf, nc, degree, gamma, coef0)


def op_pcs(x: Int, hidx: Int, hbit: Int, res: Int, n: Int, d_in: Int, nf: Int, nc: Int, degree: Int, gamma: Float32, coef0: Float32) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d_in, True)
    var d_hidx = _buf_i(ctx, hidx, degree * nf, True)
    var d_hbit = _buf_i(ctx, hbit, degree * nf, True)
    var d_res = _buf(ctx, res, n * nc, False)
    var d_scr = _buf(ctx, 0, n * 2 * nc, False)
    ctx.enqueue_function[pcs_kernel](
        d_x.unsafe_ptr(), d_hidx.unsafe_ptr(), d_hbit.unsafe_ptr(), d_res.unsafe_ptr(), d_scr.unsafe_ptr(), Int64(n), Int64(d_in), Int64(nf), Int64(nc), Int64(degree), gamma, coef0,
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * nc)
    ctx.synchronize()
    _ = d_x^
    _ = d_hidx^
    _ = d_hbit^
    _ = d_res^
    _ = d_scr^
    _ = ctx^


def achi2_kernel(x: FP, res: FP, n_: Int64, d_: Int64, steps_: Int64, interval_: Float32):
    var n = Int(n_)
    var d = Int(d_)
    var steps = Int(steps_)
    var interval = interval_
    var t = _tid()
    if t < n * d:
        achi2_item(t, x, res, n, d, steps, interval)


def op_achi2(x: Int, res: Int, n: Int, d: Int, steps: Int, interval: Float32) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_res = _buf(ctx, res, n * d * (2 * steps - 1), False)
    ctx.enqueue_function[achi2_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(steps), interval,
        grid_dim=_grid(n * d), block_dim=(BLOCK if n * d > 1 else 1),
    )
    _down(ctx, d_res, res, n * d * (2 * steps - 1))
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
    _ = ctx^


def skew_weights_kernel(z: FP, res: FP, count_: Int64):
    var count = Int(count_)
    var t = _tid()
    if t < count:
        skew_weights_item(t, z, res, count)


def op_skew_weights(z: Int, res: Int, count: Int) raises:
    var ctx = xn_ctx()
    var d_z = _buf(ctx, z, count, True)
    var d_res = _buf(ctx, res, count, False)
    ctx.enqueue_function[skew_weights_kernel](
        d_z.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count),
        grid_dim=_grid(count), block_dim=(BLOCK if count > 1 else 1),
    )
    _down(ctx, d_res, res, count)
    ctx.synchronize()
    _ = d_z^
    _ = d_res^
    _ = ctx^


def skew_transform_kernel(lx: FP, w: FP, off: FP, res: FP, n_: Int64, d_: Int64, nc_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var nc = Int(nc_)
    var t = _tid()
    if t < n * nc:
        skew_transform_item(t, lx, w, off, res, n, d, nc)


def op_skew_transform(lx: Int, w: Int, off: Int, res: Int, n: Int, d: Int, nc: Int) raises:
    var ctx = xn_ctx()
    var d_lx = _buf(ctx, lx, n * d, True)
    var d_w = _buf(ctx, w, d * nc, True)
    var d_off = _buf(ctx, off, nc, True)
    var d_res = _buf(ctx, res, n * nc, False)
    ctx.enqueue_function[skew_transform_kernel](
        d_lx.unsafe_ptr(), d_w.unsafe_ptr(), d_off.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(nc),
        grid_dim=_grid(n * nc), block_dim=(BLOCK if n * nc > 1 else 1),
    )
    _down(ctx, d_res, res, n * nc)
    ctx.synchronize()
    _ = d_lx^
    _ = d_w^
    _ = d_off^
    _ = d_res^
    _ = ctx^


def absdiff_sum_kernel(a: FP, b: FP, res: FP, count_: Int64):
    var count = Int(count_)
    var t = _tid()
    if t < 1:
        absdiff_sum_item(t, a, b, res, count)


def op_absdiff_sum(a: Int, b: Int, res: Int, count: Int) raises:
    comptime if not is_defined["MOJOLEARN_XN_SERIAL_GPU"]():
        for t in range(1):
            absdiff_sum_item(t, _f(a), _f(b), _f(res), count)
        return
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, count, True)
    var d_b = _buf(ctx, b, count, True)
    var d_res = _buf(ctx, res, 1, False)
    ctx.enqueue_function[absdiff_sum_kernel](
        d_a.unsafe_ptr(), d_b.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count),
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down(ctx, d_res, res, 1)
    ctx.synchronize()
    _ = d_a^
    _ = d_b^
    _ = d_res^
    _ = ctx^


def row_normalize_kernel(a: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < n:
        row_normalize_item(t, a, res, n, m)


def op_row_normalize(a: Int, res: Int, n: Int, m: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * m, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[row_normalize_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^
    _ = ctx^


def lp_clamp_kernel(ld: FP, ystatic: FP, unlabeled: IP, res: FP, n_: Int64, c_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var t = _tid()
    if t < n:
        lp_clamp_item(t, ld, ystatic, unlabeled, res, n, c)


def op_lp_clamp(ld: Int, ystatic: Int, unlabeled: Int, res: Int, n: Int, c: Int) raises:
    var ctx = xn_ctx()
    var d_ld = _buf(ctx, ld, n * c, True)
    var d_ystatic = _buf(ctx, ystatic, n * c, True)
    var d_unlabeled = _buf_i(ctx, unlabeled, n, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[lp_clamp_kernel](
        d_ld.unsafe_ptr(), d_ystatic.unsafe_ptr(), d_unlabeled.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(c),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_ld^
    _ = d_ystatic^
    _ = d_unlabeled^
    _ = d_res^
    _ = ctx^


def ls_clamp_kernel(ld: FP, ystatic: FP, res: FP, count_: Int64, alpha_: Float32):
    var count = Int(count_)
    var alpha = alpha_
    var t = _tid()
    if t < count:
        ls_clamp_item(t, ld, ystatic, res, count, alpha)


def op_ls_clamp(ld: Int, ystatic: Int, res: Int, count: Int, alpha: Float32) raises:
    var ctx = xn_ctx()
    var d_ld = _buf(ctx, ld, count, True)
    var d_ystatic = _buf(ctx, ystatic, count, True)
    var d_res = _buf(ctx, res, count, False)
    ctx.enqueue_function[ls_clamp_kernel](
        d_ld.unsafe_ptr(), d_ystatic.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count), alpha,
        grid_dim=_grid(count), block_dim=(BLOCK if count > 1 else 1),
    )
    _down(ctx, d_res, res, count)
    ctx.synchronize()
    _ = d_ld^
    _ = d_ystatic^
    _ = d_res^
    _ = ctx^


def ls_laplacian_kernel(a: FP, res: FP, n_: Int64):
    var n = Int(n_)
    var t = _tid()
    if t < n * n:
        ls_laplacian_item(t, a, res, n)


def op_ls_laplacian(a: Int, res: Int, n: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * n, True)
    var d_res = _buf(ctx, res, n * n, False)
    ctx.enqueue_function[ls_laplacian_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n),
        grid_dim=_grid(n * n), block_dim=(BLOCK if n * n > 1 else 1),
    )
    _down(ctx, d_res, res, n * n)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^
    _ = ctx^


def knn_graph_kernel(idx: IP, res: FP, n_: Int64, m_: Int64, k_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var k = Int(k_)
    var t = _tid()
    if t < n:
        knn_graph_item(t, idx, res, n, m, k)


def op_knn_graph(idx: Int, res: Int, n: Int, m: Int, k: Int) raises:
    var ctx = xn_ctx()
    var d_idx = _buf_i(ctx, idx, n * k, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[knn_graph_kernel](
        d_idx.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(k),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_idx^
    _ = d_res^
    _ = ctx^


def knn_impute_kernel(x: FP, fx: FP, best_d: FP, best_i: IP, res: FP, n_: Int64, m_: Int64, d_: Int64, k_: Int64, weights_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var k = Int(k_)
    var weights = Int(weights_)
    var t = _tid()
    if t < n * d:
        knn_impute_item(t, x, fx, best_d, best_i, res, n, m, d, k, weights)


def op_knn_impute(x: Int, fx: Int, res: Int, n: Int, m: Int, d: Int, k: Int, weights: Int) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d, True)
    var d_fx = _buf(ctx, fx, m * d, True)
    var d_best_d = _buf(ctx, 0, n * d * k, False)
    var d_best_i = _buf_i(ctx, 0, n * d * k, False)
    var d_res = _buf(ctx, res, n * d, False)
    ctx.enqueue_function[knn_impute_kernel](
        d_x.unsafe_ptr(), d_fx.unsafe_ptr(), d_best_d.unsafe_ptr(), d_best_i.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d), Int64(k), Int64(weights),
        grid_dim=_grid(n * d), block_dim=(BLOCK if n * d > 1 else 1),
    )
    _down(ctx, d_res, res, n * d)
    ctx.synchronize()
    _ = d_x^
    _ = d_fx^
    _ = d_best_d^
    _ = d_best_i^
    _ = d_res^
    _ = ctx^


def col_degree_kernel(a: FP, res: FP, n_: Int64):
    var n = Int(n_)
    var t = _tid()
    if t < n:
        col_degree_item(t, a, res, n)


def op_col_degree(a: Int, res: Int, n: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * n, True)
    var d_res = _buf(ctx, res, n, False)
    ctx.enqueue_function[col_degree_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^
    _ = ctx^


def ls_laplacian_deg_kernel(a: FP, deg: FP, res: FP, n_: Int64):
    var n = Int(n_)
    var t = _tid()
    if t < n * n:
        ls_laplacian_deg_item(t, a, deg, res, n)


def op_ls_laplacian_deg(a: Int, deg: Int, res: Int, n: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * n, True)
    var d_deg = _buf(ctx, deg, n, True)
    var d_res = _buf(ctx, res, n * n, False)
    ctx.enqueue_function[ls_laplacian_deg_kernel](
        d_a.unsafe_ptr(), d_deg.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n),
        grid_dim=_grid(n * n), block_dim=(BLOCK if n * n > 1 else 1),
    )
    _down(ctx, d_res, res, n * n)
    ctx.synchronize()
    _ = d_a^
    _ = d_deg^
    _ = d_res^
    _ = ctx^


def row_all_zero_kernel(a: IP, res: IP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < n:
        row_all_zero_item(t, a, res, n, m)


def op_row_all_zero(a: Int, res: Int, n: Int, m: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf_i(ctx, a, n * m, True)
    var d_res = _buf_i(ctx, res, n, False)
    ctx.enqueue_function[row_all_zero_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down_i(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^
    _ = ctx^


def pcs_sketch_kernel(x: FP, hidx: IP, hbit: IP, sk: FP, n_: Int64, d_in_: Int64, nf_: Int64, nc_: Int64, degree_: Int64, gamma_: Float32, coef0_: Float32):
    var n = Int(n_)
    var d_in = Int(d_in_)
    var nf = Int(nf_)
    var nc = Int(nc_)
    var degree = Int(degree_)
    var gamma = gamma_
    var coef0 = coef0_
    var t = _tid()
    if t < n * degree:
        pcs_sketch_item(t, x, hidx, hbit, sk, n, d_in, nf, nc, degree, gamma, coef0)


def op_pcs_sketch(x: Int, hidx: Int, hbit: Int, sk: Int, n: Int, d_in: Int, nf: Int, nc: Int, degree: Int, gamma: Float32, coef0: Float32) raises:
    var ctx = xn_ctx()
    var d_x = _buf(ctx, x, n * d_in, True)
    var d_hidx = _buf_i(ctx, hidx, degree * nf, True)
    var d_hbit = _buf_i(ctx, hbit, degree * nf, True)
    var d_sk = _buf(ctx, sk, n * degree * nc, False)
    ctx.enqueue_function[pcs_sketch_kernel](
        d_x.unsafe_ptr(), d_hidx.unsafe_ptr(), d_hbit.unsafe_ptr(), d_sk.unsafe_ptr(), Int64(n), Int64(d_in), Int64(nf), Int64(nc), Int64(degree), gamma, coef0,
        grid_dim=_grid(n * degree), block_dim=(BLOCK if n * degree > 1 else 1),
    )
    _down(ctx, d_sk, sk, n * degree * nc)
    ctx.synchronize()
    _ = d_x^
    _ = d_hidx^
    _ = d_hbit^
    _ = d_sk^
    _ = ctx^


def pcs_conv_kernel(acc: FP, sk: FP, res: FP, n_: Int64, nc_: Int64, degree_: Int64, p_: Int64):
    var n = Int(n_)
    var nc = Int(nc_)
    var degree = Int(degree_)
    var p = Int(p_)
    var t = _tid()
    if t < n * nc:
        pcs_conv_item(t, acc, sk, res, n, nc, degree, p)


def op_pcs_conv(acc: Int, sk: Int, res: Int, n: Int, nc: Int, degree: Int, p: Int) raises:
    var ctx = xn_ctx()
    var d_acc = _buf(ctx, acc, n * nc, True)
    var d_sk = _buf(ctx, sk, n * degree * nc, True)
    var d_res = _buf(ctx, res, n * nc, False)
    ctx.enqueue_function[pcs_conv_kernel](
        d_acc.unsafe_ptr(), d_sk.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(nc), Int64(degree), Int64(p),
        grid_dim=_grid(n * nc), block_dim=(BLOCK if n * nc > 1 else 1),
    )
    _down(ctx, d_res, res, n * nc)
    ctx.synchronize()
    _ = d_acc^
    _ = d_sk^
    _ = d_res^
    _ = ctx^


def pcs_copy0_kernel(sk: FP, res: FP, n_: Int64, nc_: Int64, degree_: Int64):
    var n = Int(n_)
    var nc = Int(nc_)
    var degree = Int(degree_)
    var t = _tid()
    if t < n * nc:
        pcs_copy0_item(t, sk, res, n, nc, degree)


def op_pcs_copy0(sk: Int, res: Int, n: Int, nc: Int, degree: Int) raises:
    var ctx = xn_ctx()
    var d_sk = _buf(ctx, sk, n * degree * nc, True)
    var d_res = _buf(ctx, res, n * nc, False)
    ctx.enqueue_function[pcs_copy0_kernel](
        d_sk.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(nc), Int64(degree),
        grid_dim=_grid(n * nc), block_dim=(BLOCK if n * nc > 1 else 1),
    )
    _down(ctx, d_res, res, n * nc)
    ctx.synchronize()
    _ = d_sk^
    _ = d_res^
    _ = ctx^


def knn_impute_cells_kernel(cells: IP, x: FP, fx: FP, best_d: FP, best_i: IP, res: FP, n_: Int64, m_: Int64, d_: Int64, k_: Int64, weights_: Int64, nc_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var k = Int(k_)
    var weights = Int(weights_)
    var nc = Int(nc_)
    var t = _tid()
    if t < nc:
        knn_impute_cell_item(t, cells, x, fx, best_d, best_i, res, n, m, d, k, weights, nc)


def op_knn_impute_cells(cells: Int, x: Int, fx: Int, res: Int, n: Int, m: Int, d: Int, k: Int, weights: Int, nc: Int) raises:
    var ctx = xn_ctx()
    var d_cells = _buf_i(ctx, cells, nc, True)
    var d_x = _buf(ctx, x, n * d, True)
    var d_fx = _buf(ctx, fx, m * d, True)
    var d_best_d = _buf(ctx, 0, n * d * k, False)
    var d_best_i = _buf_i(ctx, 0, n * d * k, False)
    var d_res = _buf(ctx, res, n * d, True)
    ctx.enqueue_function[knn_impute_cells_kernel](
        d_cells.unsafe_ptr(), d_x.unsafe_ptr(), d_fx.unsafe_ptr(), d_best_d.unsafe_ptr(), d_best_i.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d), Int64(k), Int64(weights), Int64(nc),
        grid_dim=_grid(nc), block_dim=(BLOCK if nc > 1 else 1),
    )
    _down(ctx, d_res, res, n * d)
    ctx.synchronize()
    _ = d_cells^
    _ = d_x^
    _ = d_fx^
    _ = d_best_d^
    _ = d_best_i^
    _ = d_res^
    _ = ctx^


def pagerank_step_kernel(q: FP, x: FP, p: FP, dw: FP, dangling: IP, res: FP, n_: Int64, alpha_: Float32):
    var n = Int(n_)
    var alpha = alpha_
    var t = _tid()
    if t < n:
        pagerank_step_item(t, q, x, p, dw, dangling, res, n, alpha)


def op_pagerank_step(q: Int, x: Int, p: Int, dw: Int, dangling: Int, res: Int, n: Int, alpha: Float32) raises:
    var ctx = xn_ctx()
    var d_q = _buf(ctx, q, n * n, True)
    var d_x = _buf(ctx, x, n, True)
    var d_p = _buf(ctx, p, n, True)
    var d_dw = _buf(ctx, dw, n, True)
    var d_dangling = _buf_i(ctx, dangling, n, True)
    var d_res = _buf(ctx, res, n, False)
    ctx.enqueue_function[pagerank_step_kernel](
        d_q.unsafe_ptr(), d_x.unsafe_ptr(), d_p.unsafe_ptr(), d_dw.unsafe_ptr(), d_dangling.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), alpha,
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_q^
    _ = d_x^
    _ = d_p^
    _ = d_dw^
    _ = d_dangling^
    _ = d_res^
    _ = ctx^


def cc_step_kernel(a: FP, lab: IP, res: IP, n_: Int64):
    var n = Int(n_)
    var t = _tid()
    if t < n:
        cc_step_item(t, a, lab, res, n)


def op_cc_step(a: Int, lab: Int, res: Int, n: Int) raises:
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * n, True)
    var d_lab = _buf_i(ctx, lab, n, True)
    var d_res = _buf_i(ctx, res, n, False)
    ctx.enqueue_function[cc_step_kernel](
        d_a.unsafe_ptr(), d_lab.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down_i(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_a^
    _ = d_lab^
    _ = d_res^
    _ = ctx^


def graph_symmetry_kernel(a: FP, flags: IP, n_: Int64):
    var n = Int(n_)
    var t = _tid()
    if t < 1:
        graph_symmetry_item(t, a, flags, n)


def op_graph_symmetry(a: Int, flags: Int, n: Int) raises:
    comptime if not is_defined["MOJOLEARN_XN_SERIAL_GPU"]():
        for t in range(1):
            graph_symmetry_item(t, _f(a), _i(flags), n)
        return
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * n, True)
    var d_flags = _buf_i(ctx, flags, 2, False)
    ctx.enqueue_function[graph_symmetry_kernel](
        d_a.unsafe_ptr(), d_flags.unsafe_ptr(), Int64(n),
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down_i(ctx, d_flags, flags, 2)
    ctx.synchronize()
    _ = d_a^
    _ = d_flags^
    _ = ctx^


def louvain_kernel(a: FP, labels: IP, info: FP, w: FP, w2: FP, comm: IP, node_of: IP, deg: FP, stot: FP, k2c: FP, tmp: FP, n_: Int64, max_level_: Int64, resolution_: Float32, threshold_: Float32):
    var n = Int(n_)
    var max_level = Int(max_level_)
    var resolution = resolution_
    var threshold = threshold_
    var t = _tid()
    if t < 1:
        louvain_item(t, a, labels, info, w, w2, comm, node_of, deg, stot, k2c, tmp, n, max_level, resolution, threshold)


def op_louvain(a: Int, labels: Int, info: Int, n: Int, max_level: Int, resolution: Float32, threshold: Float32) raises:
    comptime if not is_defined["MOJOLEARN_XN_LOUVAIN_GPU"]():
        louvain_item_sparse(_f(a), _i(labels), _f(info), n, max_level, resolution, threshold)
        return
    var ctx = xn_ctx()
    var d_a = _buf(ctx, a, n * n, True)
    var d_labels = _buf_i(ctx, labels, n, False)
    var d_info = _buf(ctx, info, 2, False)
    var d_w = _buf(ctx, 0, n * n, False)
    var d_w2 = _buf(ctx, 0, n * n, False)
    var d_comm = _buf_i(ctx, 0, n, False)
    var d_node_of = _buf_i(ctx, 0, n, False)
    var d_deg = _buf(ctx, 0, n, False)
    var d_stot = _buf(ctx, 0, n, False)
    var d_k2c = _buf(ctx, 0, n, False)
    var d_tmp = _buf(ctx, 0, n, False)
    ctx.enqueue_function[louvain_kernel](
        d_a.unsafe_ptr(), d_labels.unsafe_ptr(), d_info.unsafe_ptr(), d_w.unsafe_ptr(), d_w2.unsafe_ptr(), d_comm.unsafe_ptr(), d_node_of.unsafe_ptr(), d_deg.unsafe_ptr(), d_stot.unsafe_ptr(), d_k2c.unsafe_ptr(), d_tmp.unsafe_ptr(), Int64(n), Int64(max_level), resolution, threshold,
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down_i(ctx, d_labels, labels, n)
    _down(ctx, d_info, info, 2)
    ctx.synchronize()
    _ = d_a^
    _ = d_labels^
    _ = d_info^
    _ = d_w^
    _ = d_w2^
    _ = d_comm^
    _ = d_node_of^
    _ = d_deg^
    _ = d_stot^
    _ = d_k2c^
    _ = d_tmp^
    _ = ctx^


def svgp_kernel(kuu: FP, bmat: FP, b: FP, y: FP, alpha: FP, cmat: FP, qmu: FP, qsqrt: FP, info: FP, luu: FP, ls: FP, e: FP, col: FP, m_: Int64, n_: Int64, noise_: Float32, jitter_: Float32, kdiag_: Float32):
    var m = Int(m_)
    var n = Int(n_)
    var noise = noise_
    var jitter = jitter_
    var kdiag = kdiag_
    var t = _tid()
    if t < 1:
        svgp_item(t, kuu, bmat, b, y, alpha, cmat, qmu, qsqrt, info, luu, ls, e, col, m, n, noise, jitter, kdiag)


def op_svgp(kuu: Int, bmat: Int, b: Int, y: Int, alpha: Int, cmat: Int, qmu: Int, qsqrt: Int, info: Int, m: Int, n: Int, noise: Float32, jitter: Float32, kdiag: Float32) raises:
    comptime if not is_defined["MOJOLEARN_XN_SERIAL_GPU"]():
        var s_luu = List[Float32](length=(m * m) if (m * m) > 0 else 1, fill=Float32(0))
        var s_ls = List[Float32](length=(m * m) if (m * m) > 0 else 1, fill=Float32(0))
        var s_e = List[Float32](length=(m) if (m) > 0 else 1, fill=Float32(0))
        var s_col = List[Float32](length=(m) if (m) > 0 else 1, fill=Float32(0))
        for t in range(1):
            svgp_item(t, _f(kuu), _f(bmat), _f(b), _f(y), _f(alpha), _f(cmat), _f(qmu), _f(qsqrt), _f(info), FP(unsafe_from_address=Int(s_luu.unsafe_ptr())), FP(unsafe_from_address=Int(s_ls.unsafe_ptr())), FP(unsafe_from_address=Int(s_e.unsafe_ptr())), FP(unsafe_from_address=Int(s_col.unsafe_ptr())), m, n, noise, jitter, kdiag)
        _ = s_luu^
        _ = s_ls^
        _ = s_e^
        _ = s_col^
        return
    var ctx = xn_ctx()
    var d_kuu = _buf(ctx, kuu, m * m, True)
    var d_bmat = _buf(ctx, bmat, m * m, True)
    var d_b = _buf(ctx, b, m, True)
    var d_y = _buf(ctx, y, n, True)
    var d_alpha = _buf(ctx, alpha, m, False)
    var d_cmat = _buf(ctx, cmat, m * m, False)
    var d_qmu = _buf(ctx, qmu, m, False)
    var d_qsqrt = _buf(ctx, qsqrt, m * m, False)
    var d_info = _buf(ctx, info, 2, False)
    var d_luu = _buf(ctx, 0, m * m, False)
    var d_ls = _buf(ctx, 0, m * m, False)
    var d_e = _buf(ctx, 0, m, False)
    var d_col = _buf(ctx, 0, m, False)
    ctx.enqueue_function[svgp_kernel](
        d_kuu.unsafe_ptr(), d_bmat.unsafe_ptr(), d_b.unsafe_ptr(), d_y.unsafe_ptr(), d_alpha.unsafe_ptr(), d_cmat.unsafe_ptr(), d_qmu.unsafe_ptr(), d_qsqrt.unsafe_ptr(), d_info.unsafe_ptr(), d_luu.unsafe_ptr(), d_ls.unsafe_ptr(), d_e.unsafe_ptr(), d_col.unsafe_ptr(), Int64(m), Int64(n), noise, jitter, kdiag,
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down(ctx, d_alpha, alpha, m)
    _down(ctx, d_cmat, cmat, m * m)
    _down(ctx, d_qmu, qmu, m)
    _down(ctx, d_qsqrt, qsqrt, m * m)
    _down(ctx, d_info, info, 2)
    ctx.synchronize()
    _ = d_kuu^
    _ = d_bmat^
    _ = d_b^
    _ = d_y^
    _ = d_alpha^
    _ = d_cmat^
    _ = d_qmu^
    _ = d_qsqrt^
    _ = d_info^
    _ = d_luu^
    _ = d_ls^
    _ = d_e^
    _ = d_col^
    _ = ctx^


def svgp_var_kernel(ksu: FP, cmat: FP, res: FP, n_: Int64, m_: Int64, kdiag_: Float32):
    var n = Int(n_)
    var m = Int(m_)
    var kdiag = kdiag_
    var t = _tid()
    if t < n:
        svgp_var_item(t, ksu, cmat, res, n, m, kdiag)


def op_svgp_var(ksu: Int, cmat: Int, res: Int, n: Int, m: Int, kdiag: Float32) raises:
    var ctx = xn_ctx()
    var d_ksu = _buf(ctx, ksu, n * m, True)
    var d_cmat = _buf(ctx, cmat, m * m, True)
    var d_res = _buf(ctx, res, n, False)
    ctx.enqueue_function[svgp_var_kernel](
        d_ksu.unsafe_ptr(), d_cmat.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), kdiag,
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_ksu^
    _ = d_cmat^
    _ = d_res^
    _ = ctx^
