# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""The neighbors lane's GPU drivers (see x_neighbors/gen.py)."""
from std.gpu import block_idx, block_dim, thread_idx
from max.gpu.host import DeviceBuffer, DeviceContext
from x_neighbors.items import FP, IP, sqdist_item, nan_sqdist_item, l1dist_item, kernel_item, matmul_item, rowsum_item, colsum_item, unary_item, knn_select_item, group_mean_item, take_rows_item, take_cols_item, variance_item, ocsvm_smo_item, lof_lrd_item, lof_score_item, kpca_center_item, scale_div_item, svd_flip_item, kpca_alpha_scale_item, nc_std_item, nc_shrink_item, nc_decision_item, softmax_item

comptime BLOCK = 128


@always_inline
def _tid() -> Int:
    return Int(block_idx.x) * Int(block_dim.x) + Int(thread_idx.x)


def _grid(count: Int) -> Int:
    return (count + BLOCK - 1) // BLOCK if count > 0 else 1


def _buf(ctx: DeviceContext, addr: Int, count: Int, upload: Bool) raises -> DeviceBuffer[DType.float32]:
    var buf = ctx.enqueue_create_buffer[DType.float32](count if count > 0 else 1)
    if upload and count > 0:
        ctx.enqueue_copy(dst_buf=buf, src_ptr=FP(unsafe_from_address=addr))
    return buf^


def _buf_i(ctx: DeviceContext, addr: Int, count: Int, upload: Bool) raises -> DeviceBuffer[DType.int32]:
    var buf = ctx.enqueue_create_buffer[DType.int32](count if count > 0 else 1)
    if upload and count > 0:
        ctx.enqueue_copy(dst_buf=buf, src_ptr=IP(unsafe_from_address=addr))
    return buf^


def _down(ctx: DeviceContext, buf: DeviceBuffer[DType.float32], addr: Int, count: Int) raises:
    if count > 0:
        ctx.enqueue_copy(dst_ptr=FP(unsafe_from_address=addr), src_buf=buf)


def _down_i(ctx: DeviceContext, buf: DeviceBuffer[DType.int32], addr: Int, count: Int) raises:
    if count > 0:
        ctx.enqueue_copy(dst_ptr=IP(unsafe_from_address=addr), src_buf=buf)


def sqdist_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var t = _tid()
    if t < n * m:
        sqdist_item(t, x, y, res, n, m, d)


def op_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[sqdist_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^


def nan_sqdist_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var t = _tid()
    if t < n * m:
        nan_sqdist_item(t, x, y, res, n, m, d)


def op_nan_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[nan_sqdist_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^


def l1dist_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var t = _tid()
    if t < n * m:
        l1dist_item(t, x, y, res, n, m, d)


def op_l1dist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[l1dist_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^


def kernel_kernel(x: FP, y: FP, res: FP, n_: Int64, m_: Int64, d_: Int64, kind_: Int64, gamma_: Float32, coef0_: Float32, degree_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var d = Int(d_)
    var kind = Int(kind_)
    var gamma = gamma_
    var coef0 = coef0_
    var degree = Int(degree_)
    var t = _tid()
    if t < n * m:
        kernel_item(t, x, y, res, n, m, d, kind, gamma, coef0, degree)


def op_kernel(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int, kind: Int, gamma: Float32, coef0: Float32, degree: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_y = _buf(ctx, y, m * d, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[kernel_kernel](
        d_x.unsafe_ptr(), d_y.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m), Int64(d), Int64(kind), gamma, coef0, Int64(degree),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_x^
    _ = d_y^
    _ = d_res^


def matmul_kernel(a: FP, b: FP, res: FP, n_: Int64, k_: Int64, m_: Int64):
    var n = Int(n_)
    var k = Int(k_)
    var m = Int(m_)
    var t = _tid()
    if t < n * m:
        matmul_item(t, a, b, res, n, k, m)


def op_matmul(a: Int, b: Int, res: Int, n: Int, k: Int, m: Int) raises:
    var ctx = DeviceContext()
    var d_a = _buf(ctx, a, n * k, True)
    var d_b = _buf(ctx, b, k * m, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[matmul_kernel](
        d_a.unsafe_ptr(), d_b.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(k), Int64(m),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_a^
    _ = d_b^
    _ = d_res^


def rowsum_kernel(a: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < n:
        rowsum_item(t, a, res, n, m)


def op_rowsum(a: Int, res: Int, n: Int, m: Int) raises:
    var ctx = DeviceContext()
    var d_a = _buf(ctx, a, n * m, True)
    var d_res = _buf(ctx, res, n, False)
    ctx.enqueue_function[rowsum_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^


def colsum_kernel(a: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < m:
        colsum_item(t, a, res, n, m)


def op_colsum(a: Int, res: Int, n: Int, m: Int) raises:
    var ctx = DeviceContext()
    var d_a = _buf(ctx, a, n * m, True)
    var d_res = _buf(ctx, res, m, False)
    ctx.enqueue_function[colsum_kernel](
        d_a.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(m), block_dim=(BLOCK if m > 1 else 1),
    )
    _down(ctx, d_res, res, m)
    ctx.synchronize()
    _ = d_a^
    _ = d_res^


def unary_kernel(x: FP, res: FP, count_: Int64, op_: Int64, a_: Float32, b_: Float32):
    var count = Int(count_)
    var op = Int(op_)
    var a = a_
    var b = b_
    var t = _tid()
    if t < count:
        unary_item(t, x, res, count, op, a, b)


def op_unary(x: Int, res: Int, count: Int, op: Int, a: Float32, b: Float32) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, count, True)
    var d_res = _buf(ctx, res, count, False)
    ctx.enqueue_function[unary_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count), Int64(op), a, b,
        grid_dim=_grid(count), block_dim=(BLOCK if count > 1 else 1),
    )
    _down(ctx, d_res, res, count)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^


def knn_select_kernel(dmat: FP, dist: FP, idx: IP, n_: Int64, m_: Int64, k_: Int64, exclude_self_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var k = Int(k_)
    var exclude_self = Int(exclude_self_)
    var t = _tid()
    if t < n:
        knn_select_item(t, dmat, dist, idx, n, m, k, exclude_self)


def op_knn_select(dmat: Int, dist: Int, idx: Int, n: Int, m: Int, k: Int, exclude_self: Int) raises:
    var ctx = DeviceContext()
    var d_dmat = _buf(ctx, dmat, n * m, True)
    var d_dist = _buf(ctx, dist, n * k, False)
    var d_idx = _buf_i(ctx, idx, n * k, False)
    ctx.enqueue_function[knn_select_kernel](
        d_dmat.unsafe_ptr(), d_dist.unsafe_ptr(), d_idx.unsafe_ptr(), Int64(n), Int64(m), Int64(k), Int64(exclude_self),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_dist, dist, n * k)
    _down_i(ctx, d_idx, idx, n * k)
    ctx.synchronize()
    _ = d_dmat^
    _ = d_dist^
    _ = d_idx^


def group_mean_kernel(x: FP, labels: IP, res: FP, n_: Int64, d_: Int64, g_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var g = Int(g_)
    var t = _tid()
    if t < g * d:
        group_mean_item(t, x, labels, res, n, d, g)


def op_group_mean(x: Int, labels: Int, res: Int, n: Int, d: Int, g: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_labels = _buf_i(ctx, labels, n, True)
    var d_res = _buf(ctx, res, g * d, False)
    ctx.enqueue_function[group_mean_kernel](
        d_x.unsafe_ptr(), d_labels.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(g),
        grid_dim=_grid(g * d), block_dim=(BLOCK if g * d > 1 else 1),
    )
    _down(ctx, d_res, res, g * d)
    ctx.synchronize()
    _ = d_x^
    _ = d_labels^
    _ = d_res^


def take_rows_kernel(src: FP, rows: IP, res: FP, n_out_: Int64, d_: Int64, n_src_: Int64):
    var n_out = Int(n_out_)
    var d = Int(d_)
    var n_src = Int(n_src_)
    var t = _tid()
    if t < n_out * d:
        take_rows_item(t, src, rows, res, n_out, d, n_src)


def op_take_rows(src: Int, rows: Int, res: Int, n_out: Int, d: Int, n_src: Int) raises:
    var ctx = DeviceContext()
    var d_src = _buf(ctx, src, n_src * d, True)
    var d_rows = _buf_i(ctx, rows, n_out, True)
    var d_res = _buf(ctx, res, n_out * d, False)
    ctx.enqueue_function[take_rows_kernel](
        d_src.unsafe_ptr(), d_rows.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n_out), Int64(d), Int64(n_src),
        grid_dim=_grid(n_out * d), block_dim=(BLOCK if n_out * d > 1 else 1),
    )
    _down(ctx, d_res, res, n_out * d)
    ctx.synchronize()
    _ = d_src^
    _ = d_rows^
    _ = d_res^


def take_cols_kernel(src: FP, cols: IP, res: FP, n_: Int64, src_c_: Int64, c_: Int64):
    var n = Int(n_)
    var src_c = Int(src_c_)
    var c = Int(c_)
    var t = _tid()
    if t < n * c:
        take_cols_item(t, src, cols, res, n, src_c, c)


def op_take_cols(src: Int, cols: Int, res: Int, n: Int, src_c: Int, c: Int) raises:
    var ctx = DeviceContext()
    var d_src = _buf(ctx, src, n * src_c, True)
    var d_cols = _buf_i(ctx, cols, c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[take_cols_kernel](
        d_src.unsafe_ptr(), d_cols.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(src_c), Int64(c),
        grid_dim=_grid(n * c), block_dim=(BLOCK if n * c > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_src^
    _ = d_cols^
    _ = d_res^


def variance_kernel(x: FP, res: FP, count_: Int64):
    var count = Int(count_)
    var t = _tid()
    if t < 1:
        variance_item(t, x, res, count)


def op_variance(x: Int, res: Int, count: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, count, True)
    var d_res = _buf(ctx, res, 1, False)
    ctx.enqueue_function[variance_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count),
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down(ctx, d_res, res, 1)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^


def ocsvm_kernel(q: FP, alpha: FP, g: FP, info: FP, iters: IP, n_: Int64, eps_: Float32, max_iter_: Int64):
    var n = Int(n_)
    var eps = eps_
    var max_iter = Int(max_iter_)
    var t = _tid()
    if t < 1:
        ocsvm_smo_item(t, q, alpha, g, info, iters, n, eps, max_iter)


def op_ocsvm(q: Int, alpha: Int, info: Int, iters: Int, n: Int, eps: Float32, max_iter: Int) raises:
    var ctx = DeviceContext()
    var d_q = _buf(ctx, q, n * n, True)
    var d_alpha = _buf(ctx, alpha, n, True)
    var d_g = _buf(ctx, 0, n, False)
    var d_info = _buf(ctx, info, 1, False)
    var d_iters = _buf_i(ctx, iters, 1, False)
    ctx.enqueue_function[ocsvm_kernel](
        d_q.unsafe_ptr(), d_alpha.unsafe_ptr(), d_g.unsafe_ptr(), d_info.unsafe_ptr(), d_iters.unsafe_ptr(), Int64(n), eps, Int64(max_iter),
        grid_dim=_grid(1), block_dim=(BLOCK if 1 > 1 else 1),
    )
    _down(ctx, d_alpha, alpha, n)
    _down(ctx, d_info, info, 1)
    _down_i(ctx, d_iters, iters, 1)
    ctx.synchronize()
    _ = d_q^
    _ = d_alpha^
    _ = d_g^
    _ = d_info^
    _ = d_iters^


def lof_lrd_kernel(dist: FP, idx: IP, fit_dist: FP, lrd: FP, k_: Int64, n_: Int64, n_fit_: Int64):
    var k = Int(k_)
    var n = Int(n_)
    var n_fit = Int(n_fit_)
    var t = _tid()
    if t < n:
        lof_lrd_item(t, dist, idx, fit_dist, lrd, k, n, n_fit)


def op_lof_lrd(dist: Int, idx: Int, fit_dist: Int, lrd: Int, k: Int, n: Int, n_fit: Int) raises:
    var ctx = DeviceContext()
    var d_dist = _buf(ctx, dist, n * k, True)
    var d_idx = _buf_i(ctx, idx, n * k, True)
    var d_fit_dist = _buf(ctx, fit_dist, n_fit * k, True)
    var d_lrd = _buf(ctx, lrd, n, False)
    ctx.enqueue_function[lof_lrd_kernel](
        d_dist.unsafe_ptr(), d_idx.unsafe_ptr(), d_fit_dist.unsafe_ptr(), d_lrd.unsafe_ptr(), Int64(k), Int64(n), Int64(n_fit),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_lrd, lrd, n)
    ctx.synchronize()
    _ = d_dist^
    _ = d_idx^
    _ = d_fit_dist^
    _ = d_lrd^


def lof_score_kernel(idx: IP, fit_lrd: FP, lrd: FP, score: FP, k_: Int64, n_: Int64, n_fit_: Int64):
    var k = Int(k_)
    var n = Int(n_)
    var n_fit = Int(n_fit_)
    var t = _tid()
    if t < n:
        lof_score_item(t, idx, fit_lrd, lrd, score, k, n, n_fit)


def op_lof_score(idx: Int, fit_lrd: Int, lrd: Int, score: Int, k: Int, n: Int, n_fit: Int) raises:
    var ctx = DeviceContext()
    var d_idx = _buf_i(ctx, idx, n * k, True)
    var d_fit_lrd = _buf(ctx, fit_lrd, n_fit, True)
    var d_lrd = _buf(ctx, lrd, n, True)
    var d_score = _buf(ctx, score, n, False)
    ctx.enqueue_function[lof_score_kernel](
        d_idx.unsafe_ptr(), d_fit_lrd.unsafe_ptr(), d_lrd.unsafe_ptr(), d_score.unsafe_ptr(), Int64(k), Int64(n), Int64(n_fit),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_score, score, n)
    ctx.synchronize()
    _ = d_idx^
    _ = d_fit_lrd^
    _ = d_lrd^
    _ = d_score^


def kpca_center_kernel(k: FP, fit_cols: FP, pred_rows: FP, fit_all: FP, res: FP, n_: Int64, m_: Int64):
    var n = Int(n_)
    var m = Int(m_)
    var t = _tid()
    if t < n * m:
        kpca_center_item(t, k, fit_cols, pred_rows, fit_all, res, n, m)


def op_kpca_center(k: Int, fit_cols: Int, pred_rows: Int, fit_all: Int, res: Int, n: Int, m: Int) raises:
    var ctx = DeviceContext()
    var d_k = _buf(ctx, k, n * m, True)
    var d_fit_cols = _buf(ctx, fit_cols, m, True)
    var d_pred_rows = _buf(ctx, pred_rows, n, True)
    var d_fit_all = _buf(ctx, fit_all, 1, True)
    var d_res = _buf(ctx, res, n * m, False)
    ctx.enqueue_function[kpca_center_kernel](
        d_k.unsafe_ptr(), d_fit_cols.unsafe_ptr(), d_pred_rows.unsafe_ptr(), d_fit_all.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(m),
        grid_dim=_grid(n * m), block_dim=(BLOCK if n * m > 1 else 1),
    )
    _down(ctx, d_res, res, n * m)
    ctx.synchronize()
    _ = d_k^
    _ = d_fit_cols^
    _ = d_pred_rows^
    _ = d_fit_all^
    _ = d_res^


def scale_div_kernel(x: FP, res: FP, count_: Int64, s_: Float32):
    var count = Int(count_)
    var s = s_
    var t = _tid()
    if t < count:
        scale_div_item(t, x, res, count, s)


def op_scale_div(x: Int, res: Int, count: Int, s: Float32) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, count, True)
    var d_res = _buf(ctx, res, count, False)
    ctx.enqueue_function[scale_div_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(count), s,
        grid_dim=_grid(count), block_dim=(BLOCK if count > 1 else 1),
    )
    _down(ctx, d_res, res, count)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^


def svd_flip_kernel(v: FP, n_: Int64, c_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var t = _tid()
    if t < c:
        svd_flip_item(t, v, n, c)


def op_svd_flip(v: Int, n: Int, c: Int) raises:
    var ctx = DeviceContext()
    var d_v = _buf(ctx, v, n * c, True)
    ctx.enqueue_function[svd_flip_kernel](
        d_v.unsafe_ptr(), Int64(n), Int64(c),
        grid_dim=_grid(c), block_dim=(BLOCK if c > 1 else 1),
    )
    _down(ctx, d_v, v, n * c)
    ctx.synchronize()
    _ = d_v^


def kpca_alpha_scale_kernel(v: FP, w: FP, res: FP, n_: Int64, c_: Int64, divide_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var divide = Int(divide_)
    var t = _tid()
    if t < n * c:
        kpca_alpha_scale_item(t, v, w, res, n, c, divide)


def op_kpca_alpha_scale(v: Int, w: Int, res: Int, n: Int, c: Int, divide: Int) raises:
    var ctx = DeviceContext()
    var d_v = _buf(ctx, v, n * c, True)
    var d_w = _buf(ctx, w, c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[kpca_alpha_scale_kernel](
        d_v.unsafe_ptr(), d_w.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(c), Int64(divide),
        grid_dim=_grid(n * c), block_dim=(BLOCK if n * c > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_v^
    _ = d_w^
    _ = d_res^


def nc_std_kernel(x: FP, lab: IP, cent: FP, std: FP, n_: Int64, d_: Int64, n_classes_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var t = _tid()
    if t < d:
        nc_std_item(t, x, lab, cent, std, n, d, n_classes)


def op_nc_std(x: Int, lab: Int, cent: Int, std: Int, n: Int, d: Int, n_classes: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_lab = _buf_i(ctx, lab, n, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_std = _buf(ctx, std, d, False)
    ctx.enqueue_function[nc_std_kernel](
        d_x.unsafe_ptr(), d_lab.unsafe_ptr(), d_cent.unsafe_ptr(), d_std.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes),
        grid_dim=_grid(d), block_dim=(BLOCK if d > 1 else 1),
    )
    _down(ctx, d_std, std, d)
    ctx.synchronize()
    _ = d_x^
    _ = d_lab^
    _ = d_cent^
    _ = d_std^


def nc_shrink_kernel(x: FP, cent: FP, nk: FP, std: FP, res: FP, n_: Int64, d_: Int64, n_classes_: Int64, do_shrink_: Int64, med_: Float32, shrink_: Float32):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var do_shrink = Int(do_shrink_)
    var med = med_
    var shrink = shrink_
    var t = _tid()
    if t < n_classes * d:
        nc_shrink_item(t, x, cent, nk, std, res, n, d, n_classes, do_shrink, med, shrink)


def op_nc_shrink(x: Int, cent: Int, nk: Int, std: Int, res: Int, n: Int, d: Int, n_classes: Int, do_shrink: Int, med: Float32, shrink: Float32) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * d, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_nk = _buf(ctx, nk, n_classes, True)
    var d_std = _buf(ctx, std, d, True)
    var d_res = _buf(ctx, res, n_classes * d, False)
    ctx.enqueue_function[nc_shrink_kernel](
        d_x.unsafe_ptr(), d_cent.unsafe_ptr(), d_nk.unsafe_ptr(), d_std.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes), Int64(do_shrink), med, shrink,
        grid_dim=_grid(n_classes * d), block_dim=(BLOCK if n_classes * d > 1 else 1),
    )
    _down(ctx, d_res, res, n_classes * d)
    ctx.synchronize()
    _ = d_x^
    _ = d_cent^
    _ = d_nk^
    _ = d_std^
    _ = d_res^


def nc_decision_kernel(q: FP, cent: FP, std: FP, prior: FP, res: FP, n_: Int64, d_: Int64, n_classes_: Int64):
    var n = Int(n_)
    var d = Int(d_)
    var n_classes = Int(n_classes_)
    var t = _tid()
    if t < n * n_classes:
        nc_decision_item(t, q, cent, std, prior, res, n, d, n_classes)


def op_nc_decision(q: Int, cent: Int, std: Int, prior: Int, res: Int, n: Int, d: Int, n_classes: Int) raises:
    var ctx = DeviceContext()
    var d_q = _buf(ctx, q, n * d, True)
    var d_cent = _buf(ctx, cent, n_classes * d, True)
    var d_std = _buf(ctx, std, d, True)
    var d_prior = _buf(ctx, prior, n_classes, True)
    var d_res = _buf(ctx, res, n * n_classes, False)
    ctx.enqueue_function[nc_decision_kernel](
        d_q.unsafe_ptr(), d_cent.unsafe_ptr(), d_std.unsafe_ptr(), d_prior.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(d), Int64(n_classes),
        grid_dim=_grid(n * n_classes), block_dim=(BLOCK if n * n_classes > 1 else 1),
    )
    _down(ctx, d_res, res, n * n_classes)
    ctx.synchronize()
    _ = d_q^
    _ = d_cent^
    _ = d_std^
    _ = d_prior^
    _ = d_res^


def softmax_kernel(x: FP, res: FP, n_: Int64, c_: Int64):
    var n = Int(n_)
    var c = Int(c_)
    var t = _tid()
    if t < n:
        softmax_item(t, x, res, n, c)


def op_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    var ctx = DeviceContext()
    var d_x = _buf(ctx, x, n * c, True)
    var d_res = _buf(ctx, res, n * c, False)
    ctx.enqueue_function[softmax_kernel](
        d_x.unsafe_ptr(), d_res.unsafe_ptr(), Int64(n), Int64(c),
        grid_dim=_grid(n), block_dim=(BLOCK if n > 1 else 1),
    )
    _down(ctx, d_res, res, n * c)
    ctx.synchronize()
    _ = d_x^
    _ = d_res^
