# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""The neighbors lane's CPU drivers: host loops over the SAME items (see x_neighbors/gen.py)."""
from std.sys.compile import is_defined
from x_neighbors.items import FP, IP, sqdist_item, nan_sqdist_item, l1dist_item, kernel_item, matmul_item, rowsum_item, colsum_item, unary_item, knn_select_item, knn_sq_item, group_mean_item, take_rows_item, take_cols_item, variance_item, ocsvm_smo_item, lof_lrd_item, lof_score_item, kpca_center_item, scale_div_item, svd_flip_item, kpca_alpha_scale_item, nc_std_item, nc_shrink_item, nc_decision_item, softmax_item, log_softmax_item, pcs_item, achi2_item, skew_weights_item, skew_transform_item, absdiff_sum_item, row_normalize_item, lp_clamp_item, ls_clamp_item, ls_laplacian_item, knn_graph_item, knn_impute_item, knn_impute_cell_item, pagerank_step_item, cc_step_item, louvain_item, svgp_item, svgp_var_item

#: the host gate's negative control (`MOJOLEARN_HOST_SABOTAGE`): every op's
#: first float output moves by 1e-3 in its first element
comptime X_NEIGHBORS_HOST_SABOTAGE = is_defined["MOJOLEARN_HOST_SABOTAGE"]()


@always_inline
def _f(addr: Int) -> FP:
    return FP(unsafe_from_address=addr)


@always_inline
def _i(addr: Int) -> IP:
    return IP(unsafe_from_address=addr)


def op_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    for t in range(n * m):
        sqdist_item(t, _f(x), _f(y), _f(res), n, m, d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nan_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    for t in range(n * m):
        nan_sqdist_item(t, _f(x), _f(y), _f(res), n, m, d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_l1dist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    for t in range(n * m):
        l1dist_item(t, _f(x), _f(y), _f(res), n, m, d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_kernel(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int, kind: Int, gamma: Float32, coef0: Float32, degree: Int) raises:
    for t in range(n * m):
        kernel_item(t, _f(x), _f(y), _f(res), n, m, d, kind, gamma, coef0, degree)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_matmul(a: Int, b: Int, res: Int, n: Int, k: Int, m: Int) raises:
    for t in range(n * m):
        matmul_item(t, _f(a), _f(b), _f(res), n, k, m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_rowsum(a: Int, res: Int, n: Int, m: Int) raises:
    for t in range(n):
        rowsum_item(t, _f(a), _f(res), n, m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_colsum(a: Int, res: Int, n: Int, m: Int) raises:
    for t in range(m):
        colsum_item(t, _f(a), _f(res), n, m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_unary(x: Int, res: Int, count: Int, op: Int, a: Float32, b: Float32) raises:
    for t in range(count):
        unary_item(t, _f(x), _f(res), count, op, a, b)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_select(dmat: Int, dist: Int, idx: Int, n: Int, m: Int, k: Int, exclude_self: Int) raises:
    for t in range(n):
        knn_select_item(t, _f(dmat), _f(dist), _i(idx), n, m, k, exclude_self)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * k) > 0:
            _f(dist).unsafe_store(0, _f(dist).unsafe_load(0) + Float32(1e-3))


def op_knn_sq(x: Int, y: Int, dist: Int, idx: Int, n: Int, m: Int, d: Int, k: Int, exclude_self: Int) raises:
    for t in range(n):
        knn_sq_item(t, _f(x), _f(y), _f(dist), _i(idx), n, m, d, k, exclude_self)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * k) > 0:
            _f(dist).unsafe_store(0, _f(dist).unsafe_load(0) + Float32(1e-3))


def op_group_mean(x: Int, labels: Int, res: Int, n: Int, d: Int, g: Int) raises:
    for t in range(g * d):
        group_mean_item(t, _f(x), _i(labels), _f(res), n, d, g)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (g * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_take_rows(src: Int, rows: Int, res: Int, n_out: Int, d: Int, n_src: Int) raises:
    for t in range(n_out * d):
        take_rows_item(t, _f(src), _i(rows), _f(res), n_out, d, n_src)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_out * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_take_cols(src: Int, cols: Int, res: Int, n: Int, src_c: Int, c: Int) raises:
    for t in range(n * c):
        take_cols_item(t, _f(src), _i(cols), _f(res), n, src_c, c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_variance(x: Int, res: Int, count: Int) raises:
    for t in range(1):
        variance_item(t, _f(x), _f(res), count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (1) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_ocsvm(q: Int, cv: Int, alpha: Int, info: Int, iters: Int, n: Int, eps: Float32, max_iter: Int) raises:
    var s_g = List[Float32](length=(n) if (n) > 0 else 1, fill=Float32(0))
    for t in range(1):
        ocsvm_smo_item(t, _f(q), _f(cv), _f(alpha), FP(unsafe_from_address=Int(s_g.unsafe_ptr())), _f(info), _i(iters), n, eps, max_iter)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(alpha).unsafe_store(0, _f(alpha).unsafe_load(0) + Float32(1e-3))
    _ = s_g^


def op_lof_lrd(dist: Int, idx: Int, fit_dist: Int, lrd: Int, k: Int, n: Int, n_fit: Int) raises:
    for t in range(n):
        lof_lrd_item(t, _f(dist), _i(idx), _f(fit_dist), _f(lrd), k, n, n_fit)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(lrd).unsafe_store(0, _f(lrd).unsafe_load(0) + Float32(1e-3))


def op_lof_score(idx: Int, fit_lrd: Int, lrd: Int, score: Int, k: Int, n: Int, n_fit: Int) raises:
    for t in range(n):
        lof_score_item(t, _i(idx), _f(fit_lrd), _f(lrd), _f(score), k, n, n_fit)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(score).unsafe_store(0, _f(score).unsafe_load(0) + Float32(1e-3))


def op_kpca_center(k: Int, fit_cols: Int, pred_rows: Int, fit_all: Int, res: Int, n: Int, m: Int) raises:
    for t in range(n * m):
        kpca_center_item(t, _f(k), _f(fit_cols), _f(pred_rows), _f(fit_all), _f(res), n, m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_scale_div(x: Int, res: Int, count: Int, s: Float32) raises:
    for t in range(count):
        scale_div_item(t, _f(x), _f(res), count, s)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_svd_flip(v: Int, n: Int, c: Int) raises:
    for t in range(c):
        svd_flip_item(t, _f(v), n, c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(v).unsafe_store(0, _f(v).unsafe_load(0) + Float32(1e-3))


def op_kpca_alpha_scale(v: Int, w: Int, res: Int, n: Int, c: Int, divide: Int) raises:
    for t in range(n * c):
        kpca_alpha_scale_item(t, _f(v), _f(w), _f(res), n, c, divide)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nc_std(x: Int, lab: Int, cent: Int, std: Int, n: Int, d: Int, n_classes: Int) raises:
    for t in range(d):
        nc_std_item(t, _f(x), _i(lab), _f(cent), _f(std), n, d, n_classes)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (d) > 0:
            _f(std).unsafe_store(0, _f(std).unsafe_load(0) + Float32(1e-3))


def op_nc_shrink(x: Int, cent: Int, nk: Int, std: Int, res: Int, devs: Int, n: Int, d: Int, n_classes: Int, do_shrink: Int, med: Float32, shrink: Float32) raises:
    for t in range(n_classes * d):
        nc_shrink_item(t, _f(x), _f(cent), _f(nk), _f(std), _f(res), _f(devs), n, d, n_classes, do_shrink, med, shrink)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_classes * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nc_decision(q: Int, cent: Int, std: Int, prior: Int, res: Int, n: Int, d: Int, n_classes: Int) raises:
    for t in range(n * n_classes):
        nc_decision_item(t, _f(q), _f(cent), _f(std), _f(prior), _f(res), n, d, n_classes)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * n_classes) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    for t in range(n):
        softmax_item(t, _f(x), _f(res), n, c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_log_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    for t in range(n):
        log_softmax_item(t, _f(x), _f(res), n, c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_pcs(x: Int, hidx: Int, hbit: Int, res: Int, n: Int, d_in: Int, nf: Int, nc: Int, degree: Int, gamma: Float32, coef0: Float32) raises:
    var s_scr = List[Float32](length=(n * 2 * nc) if (n * 2 * nc) > 0 else 1, fill=Float32(0))
    for t in range(n):
        pcs_item(t, _f(x), _i(hidx), _i(hbit), _f(res), FP(unsafe_from_address=Int(s_scr.unsafe_ptr())), n, d_in, nf, nc, degree, gamma, coef0)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * nc) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_scr^


def op_achi2(x: Int, res: Int, n: Int, d: Int, steps: Int, interval: Float32) raises:
    for t in range(n * d):
        achi2_item(t, _f(x), _f(res), n, d, steps, interval)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d * (2 * steps - 1)) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_skew_weights(z: Int, res: Int, count: Int) raises:
    for t in range(count):
        skew_weights_item(t, _f(z), _f(res), count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_skew_transform(lx: Int, w: Int, off: Int, res: Int, n: Int, d: Int, nc: Int) raises:
    for t in range(n * nc):
        skew_transform_item(t, _f(lx), _f(w), _f(off), _f(res), n, d, nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * nc) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_absdiff_sum(a: Int, b: Int, res: Int, count: Int) raises:
    for t in range(1):
        absdiff_sum_item(t, _f(a), _f(b), _f(res), count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (1) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_row_normalize(a: Int, res: Int, n: Int, m: Int) raises:
    for t in range(n):
        row_normalize_item(t, _f(a), _f(res), n, m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_lp_clamp(ld: Int, ystatic: Int, unlabeled: Int, res: Int, n: Int, c: Int) raises:
    for t in range(n):
        lp_clamp_item(t, _f(ld), _f(ystatic), _i(unlabeled), _f(res), n, c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_ls_clamp(ld: Int, ystatic: Int, res: Int, count: Int, alpha: Float32) raises:
    for t in range(count):
        ls_clamp_item(t, _f(ld), _f(ystatic), _f(res), count, alpha)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_ls_laplacian(a: Int, res: Int, n: Int) raises:
    for t in range(n * n):
        ls_laplacian_item(t, _f(a), _f(res), n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_graph(idx: Int, res: Int, n: Int, m: Int, k: Int) raises:
    for t in range(n):
        knn_graph_item(t, _i(idx), _f(res), n, m, k)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_impute(x: Int, fx: Int, res: Int, n: Int, m: Int, d: Int, k: Int, weights: Int) raises:
    var s_best_d = List[Float32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Float32(0))
    var s_best_i = List[Int32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Int32(0))
    for t in range(n * d):
        knn_impute_item(t, _f(x), _f(fx), FP(unsafe_from_address=Int(s_best_d.unsafe_ptr())), IP(unsafe_from_address=Int(s_best_i.unsafe_ptr())), _f(res), n, m, d, k, weights)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_best_d^
    _ = s_best_i^


def op_knn_impute_cells(cells: Int, x: Int, fx: Int, res: Int, n: Int, m: Int, d: Int, k: Int, weights: Int, nc: Int) raises:
    var s_best_d = List[Float32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Float32(0))
    var s_best_i = List[Int32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Int32(0))
    for t in range(nc):
        knn_impute_cell_item(t, _i(cells), _f(x), _f(fx), FP(unsafe_from_address=Int(s_best_d.unsafe_ptr())), IP(unsafe_from_address=Int(s_best_i.unsafe_ptr())), _f(res), n, m, d, k, weights, nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_best_d^
    _ = s_best_i^


def op_pagerank_step(q: Int, x: Int, p: Int, dw: Int, dangling: Int, res: Int, n: Int, alpha: Float32) raises:
    for t in range(n):
        pagerank_step_item(t, _f(q), _f(x), _f(p), _f(dw), _i(dangling), _f(res), n, alpha)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_cc_step(a: Int, lab: Int, res: Int, n: Int) raises:
    for t in range(n):
        cc_step_item(t, _f(a), _i(lab), _i(res), n)


def op_louvain(a: Int, labels: Int, info: Int, n: Int, max_level: Int, resolution: Float32, threshold: Float32) raises:
    var s_w = List[Float32](length=(n * n) if (n * n) > 0 else 1, fill=Float32(0))
    var s_w2 = List[Float32](length=(n * n) if (n * n) > 0 else 1, fill=Float32(0))
    var s_comm = List[Int32](length=(n) if (n) > 0 else 1, fill=Int32(0))
    var s_node_of = List[Int32](length=(n) if (n) > 0 else 1, fill=Int32(0))
    var s_deg = List[Float32](length=(n) if (n) > 0 else 1, fill=Float32(0))
    var s_stot = List[Float32](length=(n) if (n) > 0 else 1, fill=Float32(0))
    var s_k2c = List[Float32](length=(n) if (n) > 0 else 1, fill=Float32(0))
    var s_tmp = List[Float32](length=(n) if (n) > 0 else 1, fill=Float32(0))
    for t in range(1):
        louvain_item(t, _f(a), _i(labels), _f(info), FP(unsafe_from_address=Int(s_w.unsafe_ptr())), FP(unsafe_from_address=Int(s_w2.unsafe_ptr())), IP(unsafe_from_address=Int(s_comm.unsafe_ptr())), IP(unsafe_from_address=Int(s_node_of.unsafe_ptr())), FP(unsafe_from_address=Int(s_deg.unsafe_ptr())), FP(unsafe_from_address=Int(s_stot.unsafe_ptr())), FP(unsafe_from_address=Int(s_k2c.unsafe_ptr())), FP(unsafe_from_address=Int(s_tmp.unsafe_ptr())), n, max_level, resolution, threshold)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (2) > 0:
            _f(info).unsafe_store(0, _f(info).unsafe_load(0) + Float32(1e-3))
    _ = s_w^
    _ = s_w2^
    _ = s_comm^
    _ = s_node_of^
    _ = s_deg^
    _ = s_stot^
    _ = s_k2c^
    _ = s_tmp^


def op_svgp(kuu: Int, bmat: Int, b: Int, y: Int, alpha: Int, cmat: Int, qmu: Int, qsqrt: Int, info: Int, m: Int, n: Int, noise: Float32, jitter: Float32, kdiag: Float32) raises:
    var s_luu = List[Float32](length=(m * m) if (m * m) > 0 else 1, fill=Float32(0))
    var s_ls = List[Float32](length=(m * m) if (m * m) > 0 else 1, fill=Float32(0))
    var s_e = List[Float32](length=(m) if (m) > 0 else 1, fill=Float32(0))
    var s_col = List[Float32](length=(m) if (m) > 0 else 1, fill=Float32(0))
    for t in range(1):
        svgp_item(t, _f(kuu), _f(bmat), _f(b), _f(y), _f(alpha), _f(cmat), _f(qmu), _f(qsqrt), _f(info), FP(unsafe_from_address=Int(s_luu.unsafe_ptr())), FP(unsafe_from_address=Int(s_ls.unsafe_ptr())), FP(unsafe_from_address=Int(s_e.unsafe_ptr())), FP(unsafe_from_address=Int(s_col.unsafe_ptr())), m, n, noise, jitter, kdiag)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (m) > 0:
            _f(alpha).unsafe_store(0, _f(alpha).unsafe_load(0) + Float32(1e-3))
    _ = s_luu^
    _ = s_ls^
    _ = s_e^
    _ = s_col^


def op_svgp_var(ksu: Int, cmat: Int, res: Int, n: Int, m: Int, kdiag: Float32) raises:
    for t in range(n):
        svgp_var_item(t, _f(ksu), _f(cmat), _f(res), n, m, kdiag)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
