# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""The neighbors lane's CPU drivers: host loops over the SAME items (see x_neighbors/gen.py)."""
from std.sys.compile import is_defined
from std.os import getenv
from core.host_parallel import host_parallelize
from core.host_predict_threads import host_predict_chunk, host_predict_task_count
from x_neighbors.items import FP, IP, xn_fold_blocks, sqdist_item, nan_sqdist_item, l1dist_item, kernel_item, matmul_item, rowsum_item, colsum_item, unary_item, knn_select_item, knn_sq_item, group_mean_item, take_rows_item, take_cols_item, variance_part_item, variance_mean_item, variance_ss_part_item, variance_fin_item, lof_lrd_item, lof_score_item, kpca_center_item, scale_div_item, svd_flip_item, kpca_alpha_scale_item, nc_std_item, nc_shrink_d_item, nc_shrink_item, nc_decision_item, softmax_item, log_softmax_item, pcs_item, achi2_item, skew_weights_item, skew_transform_item, absdiff_part_item, absdiff_fin_item, row_normalize_item, lp_clamp_item, ls_clamp_item, ls_laplacian_item, knn_graph_item, knn_impute_item, col_degree_item, ls_laplacian_deg_item, row_all_zero_item, pcs_sketch_item, pcs_conv_item, pcs_copy0_item, knn_impute_cell_item, pagerank_step_item, cc_step_item, graph_symmetry_row_item, graph_symmetry_fin_item, svgp_var_item, row_argmax_item
from x_neighbors.kap2_items import any_below_item, schi2_draw_item
from x_neighbors.sort_items import nc_median_init_item, nc_median_step_item, nc_median_pick_item, nc_med_std_init_item, nc_med_std_step_item, nc_med_std_pick_item, pos_count_item, pos_scan_item, pos_emit_item
from x_neighbors.py2mojo_items import p2m_mask_value_item, p2m_zero_cols_item, p2m_nan_indicator_item, p2m_sign_label_item, p2m_relabel_init_item, p2m_relabel_first_item, p2m_relabel_count_item, p2m_relabel_scan_item, p2m_relabel_emit_item, p2m_relabel_map_item, p2m_ccount_zero_item, p2m_ccount_add_item, p2m_ccount_emit_item, p2m_const_init_item, p2m_const_cmp_item, p2m_lp_labels_item, p2m_fill_item, p2m_iota_item, p2m_negate_item, p2m_transpose_item, p2m_transpose_i_item, p2m_row_sort_init_item, p2m_row_sort_step_item, p2m_row_sort_emit_item

#: the host gate's negative control (`MOJOLEARN_HOST_SABOTAGE`): every op's
#: first float output moves by 1e-3 in its first element
comptime X_NEIGHBORS_HOST_SABOTAGE = is_defined["MOJOLEARN_HOST_SABOTAGE"]()


#: MOJOLEARN_XN_HOST_SERIAL=1: every op's items one after another on one
#: thread (the loop before lane/neural-pass72)
def _xn_host_serial() -> Bool:
    return String(getenv("MOJOLEARN_XN_HOST_SERIAL")) == "1"


#: lane/neural-pass72 (2026-10-01): f(t) for t in [0, count), the items cut
#: over host tasks by count only. An item is one device thread's work and
#: writes only its own cells, so the task count and the cut move no bit; the
#: ops with a shared scratch list and the HOST_SERIAL folds keep the
#: one-thread loop.
def _items[F: def(Int) -> None](ref f: F, count: Int):
    if count <= 0:
        return
    var tasks = host_predict_task_count(count)
    if tasks <= 1 or _xn_host_serial():
        for t in range(count):
            f(t)
        return
    var part = host_predict_chunk(count, tasks)
    def _task(k: Int) {imm f, imm part, imm count}:
        var lo = k * part
        var hi = min(lo + part, count)
        for t in range(lo, hi):
            f(t)
    host_parallelize(_task, tasks)


@always_inline
def _f(addr: Int) -> FP:
    return FP(unsafe_from_address=addr)


@always_inline
def _i(addr: Int) -> IP:
    return IP(unsafe_from_address=addr)


def op_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var p_x = _f(x)
    var p_y = _f(y)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_y, imm p_res, imm n, imm m, imm d}:
        sqdist_item(t, p_x, p_y, p_res, n, m, d)
    _items(_item, n * m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nan_sqdist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var p_x = _f(x)
    var p_y = _f(y)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_y, imm p_res, imm n, imm m, imm d}:
        nan_sqdist_item(t, p_x, p_y, p_res, n, m, d)
    _items(_item, n * m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_l1dist(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int) raises:
    var p_x = _f(x)
    var p_y = _f(y)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_y, imm p_res, imm n, imm m, imm d}:
        l1dist_item(t, p_x, p_y, p_res, n, m, d)
    _items(_item, n * m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_kernel(x: Int, y: Int, res: Int, n: Int, m: Int, d: Int, kind: Int, gamma: Float32, coef0: Float32, degree: Int) raises:
    var p_x = _f(x)
    var p_y = _f(y)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_y, imm p_res, imm n, imm m, imm d, imm kind, imm gamma, imm coef0, imm degree}:
        kernel_item(t, p_x, p_y, p_res, n, m, d, kind, gamma, coef0, degree)
    _items(_item, n * m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_matmul(a: Int, b: Int, res: Int, n: Int, k: Int, m: Int) raises:
    var p_a = _f(a)
    var p_b = _f(b)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_b, imm p_res, imm n, imm k, imm m}:
        matmul_item(t, p_a, p_b, p_res, n, k, m)
    _items(_item, n * m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_rowsum(a: Int, res: Int, n: Int, m: Int) raises:
    var p_a = _f(a)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n, imm m}:
        rowsum_item(t, p_a, p_res, n, m)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_colsum(a: Int, res: Int, n: Int, m: Int) raises:
    var p_a = _f(a)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n, imm m}:
        colsum_item(t, p_a, p_res, n, m)
    _items(_item, m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_unary(x: Int, res: Int, count: Int, op: Int, a: Float32, b: Float32) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm count, imm op, imm a, imm b}:
        unary_item(t, p_x, p_res, count, op, a, b)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_select(dmat: Int, dist: Int, idx: Int, n: Int, m: Int, k: Int, exclude_self: Int) raises:
    var p_dmat = _f(dmat)
    var p_dist = _f(dist)
    var p_idx = _i(idx)
    def _item(t: Int) {imm p_dmat, imm p_dist, imm p_idx, imm n, imm m, imm k, imm exclude_self}:
        knn_select_item(t, p_dmat, p_dist, p_idx, n, m, k, exclude_self)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * k) > 0:
            _f(dist).unsafe_store(0, _f(dist).unsafe_load(0) + Float32(1e-3))


def op_knn_sq(x: Int, y: Int, dist: Int, idx: Int, n: Int, m: Int, d: Int, k: Int, exclude_self: Int) raises:
    var p_x = _f(x)
    var p_y = _f(y)
    var p_dist = _f(dist)
    var p_idx = _i(idx)
    def _item(t: Int) {imm p_x, imm p_y, imm p_dist, imm p_idx, imm n, imm m, imm d, imm k, imm exclude_self}:
        knn_sq_item(t, p_x, p_y, p_dist, p_idx, n, m, d, k, exclude_self)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * k) > 0:
            _f(dist).unsafe_store(0, _f(dist).unsafe_load(0) + Float32(1e-3))


def op_group_mean(x: Int, labels: Int, res: Int, n: Int, d: Int, g: Int) raises:
    for t in range(g * d):
        group_mean_item(t, _f(x), _i(labels), _f(res), n, d, g)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (g * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_take_rows(src: Int, rows: Int, res: Int, n_out: Int, d: Int, n_src: Int) raises:
    var p_src = _f(src)
    var p_rows = _i(rows)
    var p_res = _f(res)
    def _item(t: Int) {imm p_src, imm p_rows, imm p_res, imm n_out, imm d, imm n_src}:
        take_rows_item(t, p_src, p_rows, p_res, n_out, d, n_src)
    _items(_item, n_out * d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_out * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_take_cols(src: Int, cols: Int, res: Int, n: Int, src_c: Int, c: Int) raises:
    var p_src = _f(src)
    var p_cols = _i(cols)
    var p_res = _f(res)
    def _item(t: Int) {imm p_src, imm p_cols, imm p_res, imm n, imm src_c, imm c}:
        take_cols_item(t, p_src, p_cols, p_res, n, src_c, c)
    _items(_item, n * c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_variance(x: Int, res: Int, count: Int) raises:
    var s_part = List[Float32](length=(xn_fold_blocks(count)) if (xn_fold_blocks(count)) > 0 else 1, fill=Float32(0))
    for t in range(xn_fold_blocks(count)):
        variance_part_item(t, _f(x), _f(res), FP(unsafe_from_address=Int(s_part.unsafe_ptr())), count)
    for t in range(1):
        variance_mean_item(t, _f(x), _f(res), FP(unsafe_from_address=Int(s_part.unsafe_ptr())), count)
    for t in range(xn_fold_blocks(count)):
        variance_ss_part_item(t, _f(x), _f(res), FP(unsafe_from_address=Int(s_part.unsafe_ptr())), count)
    for t in range(1):
        variance_fin_item(t, _f(x), _f(res), FP(unsafe_from_address=Int(s_part.unsafe_ptr())), count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (1) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_part^


def op_lof_lrd(dist: Int, idx: Int, fit_dist: Int, lrd: Int, k: Int, n: Int, n_fit: Int) raises:
    var p_dist = _f(dist)
    var p_idx = _i(idx)
    var p_fit_dist = _f(fit_dist)
    var p_lrd = _f(lrd)
    def _item(t: Int) {imm p_dist, imm p_idx, imm p_fit_dist, imm p_lrd, imm k, imm n, imm n_fit}:
        lof_lrd_item(t, p_dist, p_idx, p_fit_dist, p_lrd, k, n, n_fit)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(lrd).unsafe_store(0, _f(lrd).unsafe_load(0) + Float32(1e-3))


def op_lof_score(idx: Int, fit_lrd: Int, lrd: Int, score: Int, k: Int, n: Int, n_fit: Int) raises:
    var p_idx = _i(idx)
    var p_fit_lrd = _f(fit_lrd)
    var p_lrd = _f(lrd)
    var p_score = _f(score)
    def _item(t: Int) {imm p_idx, imm p_fit_lrd, imm p_lrd, imm p_score, imm k, imm n, imm n_fit}:
        lof_score_item(t, p_idx, p_fit_lrd, p_lrd, p_score, k, n, n_fit)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(score).unsafe_store(0, _f(score).unsafe_load(0) + Float32(1e-3))


def op_kpca_center(k: Int, fit_cols: Int, pred_rows: Int, fit_all: Int, res: Int, n: Int, m: Int) raises:
    var p_k = _f(k)
    var p_fit_cols = _f(fit_cols)
    var p_pred_rows = _f(pred_rows)
    var p_fit_all = _f(fit_all)
    var p_res = _f(res)
    def _item(t: Int) {imm p_k, imm p_fit_cols, imm p_pred_rows, imm p_fit_all, imm p_res, imm n, imm m}:
        kpca_center_item(t, p_k, p_fit_cols, p_pred_rows, p_fit_all, p_res, n, m)
    _items(_item, n * m)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_scale_div(x: Int, res: Int, count: Int, s: Float32) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm count, imm s}:
        scale_div_item(t, p_x, p_res, count, s)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_svd_flip(v: Int, n: Int, c: Int) raises:
    var p_v = _f(v)
    def _item(t: Int) {imm p_v, imm n, imm c}:
        svd_flip_item(t, p_v, n, c)
    _items(_item, c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(v).unsafe_store(0, _f(v).unsafe_load(0) + Float32(1e-3))


def op_kpca_alpha_scale(v: Int, w: Int, res: Int, n: Int, c: Int, divide: Int) raises:
    var p_v = _f(v)
    var p_w = _f(w)
    var p_res = _f(res)
    def _item(t: Int) {imm p_v, imm p_w, imm p_res, imm n, imm c, imm divide}:
        kpca_alpha_scale_item(t, p_v, p_w, p_res, n, c, divide)
    _items(_item, n * c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nc_std(x: Int, lab: Int, cent: Int, std: Int, n: Int, d: Int, n_classes: Int) raises:
    for t in range(d):
        nc_std_item(t, _f(x), _i(lab), _f(cent), _f(std), n, d, n_classes)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (d) > 0:
            _f(std).unsafe_store(0, _f(std).unsafe_load(0) + Float32(1e-3))


def op_nc_shrink_d(dsc: Int, cent: Int, nk: Int, std: Int, res: Int, devs: Int, n: Int, d: Int, n_classes: Int, do_shrink: Int, med: Float32, shrink: Float32) raises:
    var p_dsc = _f(dsc)
    var p_cent = _f(cent)
    var p_nk = _f(nk)
    var p_std = _f(std)
    var p_res = _f(res)
    var p_devs = _f(devs)
    def _item(t: Int) {imm p_dsc, imm p_cent, imm p_nk, imm p_std, imm p_res, imm p_devs, imm n, imm d, imm n_classes, imm do_shrink, imm med, imm shrink}:
        nc_shrink_d_item(t, p_dsc, p_cent, p_nk, p_std, p_res, p_devs, n, d, n_classes, do_shrink, med, shrink)
    _items(_item, n_classes * d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_classes * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nc_shrink(x: Int, cent: Int, nk: Int, std: Int, res: Int, devs: Int, n: Int, d: Int, n_classes: Int, do_shrink: Int, med: Float32, shrink: Float32) raises:
    var p_x = _f(x)
    var p_cent = _f(cent)
    var p_nk = _f(nk)
    var p_std = _f(std)
    var p_res = _f(res)
    var p_devs = _f(devs)
    def _item(t: Int) {imm p_x, imm p_cent, imm p_nk, imm p_std, imm p_res, imm p_devs, imm n, imm d, imm n_classes, imm do_shrink, imm med, imm shrink}:
        nc_shrink_item(t, p_x, p_cent, p_nk, p_std, p_res, p_devs, n, d, n_classes, do_shrink, med, shrink)
    _items(_item, n_classes * d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_classes * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nc_decision(q: Int, cent: Int, std: Int, prior: Int, res: Int, n: Int, d: Int, n_classes: Int) raises:
    var p_q = _f(q)
    var p_cent = _f(cent)
    var p_std = _f(std)
    var p_prior = _f(prior)
    var p_res = _f(res)
    def _item(t: Int) {imm p_q, imm p_cent, imm p_std, imm p_prior, imm p_res, imm n, imm d, imm n_classes}:
        nc_decision_item(t, p_q, p_cent, p_std, p_prior, p_res, n, d, n_classes)
    _items(_item, n * n_classes)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * n_classes) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm n, imm c}:
        softmax_item(t, p_x, p_res, n, c)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_log_softmax(x: Int, res: Int, n: Int, c: Int) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm n, imm c}:
        log_softmax_item(t, p_x, p_res, n, c)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_pcs(x: Int, hidx: Int, hbit: Int, res: Int, n: Int, d_in: Int, nf: Int, nc: Int, degree: Int, gamma: Float32, coef0: Float32) raises:
    var s_scr = List[Float32](length=(n * 2 * nc) if (n * 2 * nc) > 0 else 1, fill=Float32(0))
    var p_x = _f(x)
    var p_hidx = _i(hidx)
    var p_hbit = _i(hbit)
    var p_res = _f(res)
    var p_scr = FP(unsafe_from_address=Int(s_scr.unsafe_ptr()))
    def _item(t: Int) {imm p_x, imm p_hidx, imm p_hbit, imm p_res, imm p_scr, imm n, imm d_in, imm nf, imm nc, imm degree, imm gamma, imm coef0}:
        pcs_item(t, p_x, p_hidx, p_hbit, p_res, p_scr, n, d_in, nf, nc, degree, gamma, coef0)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * nc) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_scr^


def op_achi2(x: Int, res: Int, n: Int, d: Int, steps: Int, interval: Float32) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm n, imm d, imm steps, imm interval}:
        achi2_item(t, p_x, p_res, n, d, steps, interval)
    _items(_item, n * d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d * (2 * steps - 1)) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_any_below(x: Int, res: Int, count: Int, incl: Int, thr: Float32) raises:
    var p_x = _f(x)
    var p_res = _i(res)
    def _item(t: Int) {imm p_x, imm p_res, imm count, imm incl, imm thr}:
        any_below_item(t, p_x, p_res, count, incl, thr)
    _items(_item, count)


def op_schi2_draw(w: Int, off: Int, d: Int, nc: Int, seed: Int) raises:
    var p_w = _f(w)
    var p_off = _f(off)
    def _item(t: Int) {imm p_w, imm p_off, imm d, imm nc, imm seed}:
        schi2_draw_item(t, p_w, p_off, d, nc, seed)
    _items(_item, d * nc + nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (d * nc) > 0:
            _f(w).unsafe_store(0, _f(w).unsafe_load(0) + Float32(1e-3))


def op_skew_weights(z: Int, res: Int, count: Int) raises:
    var p_z = _f(z)
    var p_res = _f(res)
    def _item(t: Int) {imm p_z, imm p_res, imm count}:
        skew_weights_item(t, p_z, p_res, count)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_skew_transform(lx: Int, w: Int, off: Int, res: Int, n: Int, d: Int, nc: Int) raises:
    var p_lx = _f(lx)
    var p_w = _f(w)
    var p_off = _f(off)
    var p_res = _f(res)
    def _item(t: Int) {imm p_lx, imm p_w, imm p_off, imm p_res, imm n, imm d, imm nc}:
        skew_transform_item(t, p_lx, p_w, p_off, p_res, n, d, nc)
    _items(_item, n * nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * nc) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_absdiff_sum(a: Int, b: Int, res: Int, count: Int) raises:
    var s_part = List[Float32](length=(xn_fold_blocks(count)) if (xn_fold_blocks(count)) > 0 else 1, fill=Float32(0))
    for t in range(xn_fold_blocks(count)):
        absdiff_part_item(t, _f(a), _f(b), _f(res), FP(unsafe_from_address=Int(s_part.unsafe_ptr())), count)
    for t in range(1):
        absdiff_fin_item(t, _f(a), _f(b), _f(res), FP(unsafe_from_address=Int(s_part.unsafe_ptr())), count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (1) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_part^


def op_row_normalize(a: Int, res: Int, n: Int, m: Int) raises:
    var p_a = _f(a)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n, imm m}:
        row_normalize_item(t, p_a, p_res, n, m)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_lp_clamp(ld: Int, ystatic: Int, unlabeled: Int, res: Int, n: Int, c: Int) raises:
    var p_ld = _f(ld)
    var p_ystatic = _f(ystatic)
    var p_unlabeled = _i(unlabeled)
    var p_res = _f(res)
    def _item(t: Int) {imm p_ld, imm p_ystatic, imm p_unlabeled, imm p_res, imm n, imm c}:
        lp_clamp_item(t, p_ld, p_ystatic, p_unlabeled, p_res, n, c)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_ls_clamp(ld: Int, ystatic: Int, res: Int, count: Int, alpha: Float32) raises:
    var p_ld = _f(ld)
    var p_ystatic = _f(ystatic)
    var p_res = _f(res)
    def _item(t: Int) {imm p_ld, imm p_ystatic, imm p_res, imm count, imm alpha}:
        ls_clamp_item(t, p_ld, p_ystatic, p_res, count, alpha)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_ls_laplacian(a: Int, res: Int, n: Int) raises:
    var p_a = _f(a)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n}:
        ls_laplacian_item(t, p_a, p_res, n)
    _items(_item, n * n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_graph(idx: Int, res: Int, n: Int, m: Int, k: Int) raises:
    var p_idx = _i(idx)
    var p_res = _f(res)
    def _item(t: Int) {imm p_idx, imm p_res, imm n, imm m, imm k}:
        knn_graph_item(t, p_idx, p_res, n, m, k)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * m) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_impute(x: Int, fx: Int, res: Int, n: Int, m: Int, d: Int, k: Int, weights: Int) raises:
    var s_best_d = List[Float32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Float32(0))
    var s_best_i = List[Int32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Int32(0))
    var p_x = _f(x)
    var p_fx = _f(fx)
    var p_best_d = FP(unsafe_from_address=Int(s_best_d.unsafe_ptr()))
    var p_best_i = IP(unsafe_from_address=Int(s_best_i.unsafe_ptr()))
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_fx, imm p_best_d, imm p_best_i, imm p_res, imm n, imm m, imm d, imm k, imm weights}:
        knn_impute_item(t, p_x, p_fx, p_best_d, p_best_i, p_res, n, m, d, k, weights)
    _items(_item, n * d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_best_d^
    _ = s_best_i^


def op_col_degree(a: Int, res: Int, n: Int) raises:
    var p_a = _f(a)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n}:
        col_degree_item(t, p_a, p_res, n)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_ls_laplacian_deg(a: Int, deg: Int, res: Int, n: Int) raises:
    var p_a = _f(a)
    var p_deg = _f(deg)
    var p_res = _f(res)
    def _item(t: Int) {imm p_a, imm p_deg, imm p_res, imm n}:
        ls_laplacian_deg_item(t, p_a, p_deg, p_res, n)
    _items(_item, n * n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_row_all_zero(a: Int, res: Int, n: Int, m: Int) raises:
    var p_a = _i(a)
    var p_res = _i(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n, imm m}:
        row_all_zero_item(t, p_a, p_res, n, m)
    _items(_item, n)


def op_pcs_sketch(x: Int, hidx: Int, hbit: Int, sk: Int, n: Int, d_in: Int, nf: Int, nc: Int, degree: Int, gamma: Float32, coef0: Float32) raises:
    var p_x = _f(x)
    var p_hidx = _i(hidx)
    var p_hbit = _i(hbit)
    var p_sk = _f(sk)
    def _item(t: Int) {imm p_x, imm p_hidx, imm p_hbit, imm p_sk, imm n, imm d_in, imm nf, imm nc, imm degree, imm gamma, imm coef0}:
        pcs_sketch_item(t, p_x, p_hidx, p_hbit, p_sk, n, d_in, nf, nc, degree, gamma, coef0)
    _items(_item, n * degree)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * degree * nc) > 0:
            _f(sk).unsafe_store(0, _f(sk).unsafe_load(0) + Float32(1e-3))


def op_pcs_conv(acc: Int, sk: Int, res: Int, n: Int, nc: Int, degree: Int, p: Int) raises:
    var p_acc = _f(acc)
    var p_sk = _f(sk)
    var p_res = _f(res)
    def _item(t: Int) {imm p_acc, imm p_sk, imm p_res, imm n, imm nc, imm degree, imm p}:
        pcs_conv_item(t, p_acc, p_sk, p_res, n, nc, degree, p)
    _items(_item, n * nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * nc) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_pcs_copy0(sk: Int, res: Int, n: Int, nc: Int, degree: Int) raises:
    var p_sk = _f(sk)
    var p_res = _f(res)
    def _item(t: Int) {imm p_sk, imm p_res, imm n, imm nc, imm degree}:
        pcs_copy0_item(t, p_sk, p_res, n, nc, degree)
    _items(_item, n * nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * nc) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_knn_impute_cells(cells: Int, x: Int, fx: Int, res: Int, n: Int, m: Int, d: Int, k: Int, weights: Int, nc: Int) raises:
    var s_best_d = List[Float32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Float32(0))
    var s_best_i = List[Int32](length=(n * d * k) if (n * d * k) > 0 else 1, fill=Int32(0))
    var p_cells = _i(cells)
    var p_x = _f(x)
    var p_fx = _f(fx)
    var p_best_d = FP(unsafe_from_address=Int(s_best_d.unsafe_ptr()))
    var p_best_i = IP(unsafe_from_address=Int(s_best_i.unsafe_ptr()))
    var p_res = _f(res)
    def _item(t: Int) {imm p_cells, imm p_x, imm p_fx, imm p_best_d, imm p_best_i, imm p_res, imm n, imm m, imm d, imm k, imm weights, imm nc}:
        knn_impute_cell_item(t, p_cells, p_x, p_fx, p_best_d, p_best_i, p_res, n, m, d, k, weights, nc)
    _items(_item, nc)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_best_d^
    _ = s_best_i^


def op_pagerank_step(q: Int, x: Int, p: Int, dw: Int, dangling: Int, res: Int, n: Int, alpha: Float32) raises:
    var p_q = _f(q)
    var p_x = _f(x)
    var p_p = _f(p)
    var p_dw = _f(dw)
    var p_dangling = _i(dangling)
    var p_res = _f(res)
    def _item(t: Int) {imm p_q, imm p_x, imm p_p, imm p_dw, imm p_dangling, imm p_res, imm n, imm alpha}:
        pagerank_step_item(t, p_q, p_x, p_p, p_dw, p_dangling, p_res, n, alpha)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_cc_step(a: Int, lab: Int, res: Int, n: Int) raises:
    var p_a = _f(a)
    var p_lab = _i(lab)
    var p_res = _i(res)
    def _item(t: Int) {imm p_a, imm p_lab, imm p_res, imm n}:
        cc_step_item(t, p_a, p_lab, p_res, n)
    _items(_item, n)


def op_graph_symmetry(a: Int, flags: Int, n: Int) raises:
    var s_rf = List[Int32](length=(2 * n) if (2 * n) > 0 else 1, fill=Int32(0))
    for t in range(n):
        graph_symmetry_row_item(t, _f(a), _i(flags), IP(unsafe_from_address=Int(s_rf.unsafe_ptr())), n)
    for t in range(1):
        graph_symmetry_fin_item(t, _f(a), _i(flags), IP(unsafe_from_address=Int(s_rf.unsafe_ptr())), n)
    _ = s_rf^


def op_svgp_var(ksu: Int, cmat: Int, res: Int, n: Int, m: Int, kdiag: Float32) raises:
    var p_ksu = _f(ksu)
    var p_cmat = _f(cmat)
    var p_res = _f(res)
    def _item(t: Int) {imm p_ksu, imm p_cmat, imm p_res, imm n, imm m, imm kdiag}:
        svgp_var_item(t, p_ksu, p_cmat, p_res, n, m, kdiag)
    _items(_item, n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_nc_median(x: Int, lab: Int, start: Int, cent: Int, n: Int, d: Int, n_classes: Int, p: Int, n_steps: Int) raises:
    var s_perm = List[Int32](length=(d * p) if (d * p) > 0 else 1, fill=Int32(0))
    for t in range(d * p):
        nc_median_init_item(t, _f(x), _i(lab), _i(start), _f(cent), IP(unsafe_from_address=Int(s_perm.unsafe_ptr())), n, d, n_classes, p, n_steps)
    for lj in range(n_steps):
        for t in range(d * (p // 2)):
            nc_median_step_item(t, lj, _f(x), _i(lab), _i(start), _f(cent), IP(unsafe_from_address=Int(s_perm.unsafe_ptr())), n, d, n_classes, p, n_steps)
    for t in range(n_classes * d):
        nc_median_pick_item(t, _f(x), _i(lab), _i(start), _f(cent), IP(unsafe_from_address=Int(s_perm.unsafe_ptr())), n, d, n_classes, p, n_steps)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_classes * d) > 0:
            _f(cent).unsafe_store(0, _f(cent).unsafe_load(0) + Float32(1e-3))
    _ = s_perm^


def op_row_argmax(a: Int, res: Int, n: Int, m: Int) raises:
    var p_a = _f(a)
    var p_res = _i(res)
    def _item(t: Int) {imm p_a, imm p_res, imm n, imm m}:
        row_argmax_item(t, p_a, p_res, n, m)
    _items(_item, n)


def op_nc_med_std(std: Int, res: Int, d: Int, p: Int, n_steps: Int) raises:
    var s_key = List[Float32](length=(p) if (p) > 0 else 1, fill=Float32(0))
    for t in range(p):
        nc_med_std_init_item(t, _f(std), _f(res), FP(unsafe_from_address=Int(s_key.unsafe_ptr())), d, p, n_steps)
    for lj in range(n_steps):
        for t in range(p // 2):
            nc_med_std_step_item(t, lj, _f(std), _f(res), FP(unsafe_from_address=Int(s_key.unsafe_ptr())), d, p, n_steps)
    for t in range(1):
        nc_med_std_pick_item(t, _f(std), _f(res), FP(unsafe_from_address=Int(s_key.unsafe_ptr())), d, p, n_steps)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (2) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))
    _ = s_key^


def op_pos_compact(w: Int, rows: Int, vals: Int, info: Int, n: Int) raises:
    var s_part = List[Int32](length=(xn_fold_blocks(n)) if (xn_fold_blocks(n)) > 0 else 1, fill=Int32(0))
    for t in range(xn_fold_blocks(n)):
        pos_count_item(t, _f(w), _i(rows), _f(vals), _i(info), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(1):
        pos_scan_item(t, _f(w), _i(rows), _f(vals), _i(info), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(xn_fold_blocks(n)):
        pos_emit_item(t, _f(w), _i(rows), _f(vals), _i(info), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n) > 0:
            _f(vals).unsafe_store(0, _f(vals).unsafe_load(0) + Float32(1e-3))
    _ = s_part^


def op_p2m_mask_value(x: Int, res: Int, count: Int, want: Float32) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm count, imm want}:
        p2m_mask_value_item(t, p_x, p_res, count, want)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_p2m_zero_cols(x: Int, flags: Int, res: Int, n: Int, d: Int) raises:
    var p_x = _f(x)
    var p_flags = _i(flags)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_flags, imm p_res, imm n, imm d}:
        p2m_zero_cols_item(t, p_x, p_flags, p_res, n, d)
    _items(_item, n * d)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * d) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_p2m_nan_indicator(src: Int, cur: Int, cols: Int, res: Int, n: Int, d: Int, c: Int, q: Int) raises:
    var p_src = _f(src)
    var p_cur = _f(cur)
    var p_cols = _i(cols)
    var p_res = _f(res)
    def _item(t: Int) {imm p_src, imm p_cur, imm p_cols, imm p_res, imm n, imm d, imm c, imm q}:
        p2m_nan_indicator_item(t, p_src, p_cur, p_cols, p_res, n, d, c, q)
    _items(_item, n * (c + q))
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * (c + q)) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_p2m_sign_label(x: Int, res: Int, count: Int, mode: Int, thr: Float32) raises:
    var p_x = _f(x)
    var p_res = _i(res)
    def _item(t: Int) {imm p_x, imm p_res, imm count, imm mode, imm thr}:
        p2m_sign_label_item(t, p_x, p_res, count, mode, thr)
    _items(_item, count)


def op_p2m_relabel(lab: Int, res: Int, info: Int, n: Int) raises:
    var s_first = List[Int32](length=(n) if (n) > 0 else 1, fill=Int32(0))
    var s_rk = List[Int32](length=(n) if (n) > 0 else 1, fill=Int32(0))
    var s_part = List[Int32](length=(xn_fold_blocks(n)) if (xn_fold_blocks(n)) > 0 else 1, fill=Int32(0))
    for t in range(n):
        p2m_relabel_init_item(t, _i(lab), _i(res), _i(info), IP(unsafe_from_address=Int(s_first.unsafe_ptr())), IP(unsafe_from_address=Int(s_rk.unsafe_ptr())), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(n):
        p2m_relabel_first_item(t, _i(lab), _i(res), _i(info), IP(unsafe_from_address=Int(s_first.unsafe_ptr())), IP(unsafe_from_address=Int(s_rk.unsafe_ptr())), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(xn_fold_blocks(n)):
        p2m_relabel_count_item(t, _i(lab), _i(res), _i(info), IP(unsafe_from_address=Int(s_first.unsafe_ptr())), IP(unsafe_from_address=Int(s_rk.unsafe_ptr())), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(1):
        p2m_relabel_scan_item(t, _i(lab), _i(res), _i(info), IP(unsafe_from_address=Int(s_first.unsafe_ptr())), IP(unsafe_from_address=Int(s_rk.unsafe_ptr())), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(xn_fold_blocks(n)):
        p2m_relabel_emit_item(t, _i(lab), _i(res), _i(info), IP(unsafe_from_address=Int(s_first.unsafe_ptr())), IP(unsafe_from_address=Int(s_rk.unsafe_ptr())), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    for t in range(n):
        p2m_relabel_map_item(t, _i(lab), _i(res), _i(info), IP(unsafe_from_address=Int(s_first.unsafe_ptr())), IP(unsafe_from_address=Int(s_rk.unsafe_ptr())), IP(unsafe_from_address=Int(s_part.unsafe_ptr())), n)
    _ = s_first^
    _ = s_rk^
    _ = s_part^


def op_p2m_class_counts(lab: Int, nk: Int, info: Int, n: Int, n_classes: Int) raises:
    var s_cnt = List[Int32](length=(n_classes) if (n_classes) > 0 else 1, fill=Int32(0))
    for t in range(n_classes):
        p2m_ccount_zero_item(t, _i(lab), _f(nk), _i(info), IP(unsafe_from_address=Int(s_cnt.unsafe_ptr())), n, n_classes)
    for t in range(n):
        p2m_ccount_add_item(t, _i(lab), _f(nk), _i(info), IP(unsafe_from_address=Int(s_cnt.unsafe_ptr())), n, n_classes)
    for t in range(n_classes):
        p2m_ccount_emit_item(t, _i(lab), _f(nk), _i(info), IP(unsafe_from_address=Int(s_cnt.unsafe_ptr())), n, n_classes)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n_classes) > 0:
            _f(nk).unsafe_store(0, _f(nk).unsafe_load(0) + Float32(1e-3))
    _ = s_cnt^


def op_p2m_const_cols(x: Int, flag: Int, n: Int, d: Int) raises:
    for t in range(1):
        p2m_const_init_item(t, _f(x), _i(flag), n, d)
    for t in range(n * d):
        p2m_const_cmp_item(t, _f(x), _i(flag), n, d)


def op_p2m_lp_labels(codes: Int, ld: Int, ys: Int, unl: Int, n: Int, c: Int, skip: Int, a: Float32) raises:
    var p_codes = _i(codes)
    var p_ld = _f(ld)
    var p_ys = _f(ys)
    var p_unl = _i(unl)
    def _item(t: Int) {imm p_codes, imm p_ld, imm p_ys, imm p_unl, imm n, imm c, imm skip, imm a}:
        p2m_lp_labels_item(t, p_codes, p_ld, p_ys, p_unl, n, c, skip, a)
    _items(_item, n * c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (n * c) > 0:
            _f(ld).unsafe_store(0, _f(ld).unsafe_load(0) + Float32(1e-3))


def op_p2m_fill(res: Int, count: Int, value: Float32) raises:
    var p_res = _f(res)
    def _item(t: Int) {imm p_res, imm count, imm value}:
        p2m_fill_item(t, p_res, count, value)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_p2m_iota(res: Int, count: Int) raises:
    var p_res = _i(res)
    def _item(t: Int) {imm p_res, imm count}:
        p2m_iota_item(t, p_res, count)
    _items(_item, count)


def op_p2m_negate(x: Int, res: Int, count: Int) raises:
    var p_x = _f(x)
    var p_res = _f(res)
    def _item(t: Int) {imm p_x, imm p_res, imm count}:
        p2m_negate_item(t, p_x, p_res, count)
    _items(_item, count)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (count) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_p2m_transpose(src: Int, res: Int, r: Int, c: Int) raises:
    var p_src = _f(src)
    var p_res = _f(res)
    def _item(t: Int) {imm p_src, imm p_res, imm r, imm c}:
        p2m_transpose_item(t, p_src, p_res, r, c)
    _items(_item, r * c)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (r * c) > 0:
            _f(res).unsafe_store(0, _f(res).unsafe_load(0) + Float32(1e-3))


def op_p2m_transpose_i(src: Int, res: Int, r: Int, c: Int) raises:
    var p_src = _i(src)
    var p_res = _i(res)
    def _item(t: Int) {imm p_src, imm p_res, imm r, imm c}:
        p2m_transpose_i_item(t, p_src, p_res, r, c)
    _items(_item, r * c)


def op_p2m_row_sort(indptr: Int, cols: Int, dists: Int, out_cols: Int, out_d: Int, nq: Int, nnz: Int, p: Int, n_steps: Int) raises:
    var s_perm = List[Int32](length=(p) if (p) > 0 else 1, fill=Int32(0))
    var s_rowid = List[Int32](length=(nnz) if (nnz) > 0 else 1, fill=Int32(0))
    for t in range(p):
        p2m_row_sort_init_item(t, _i(indptr), _i(cols), _f(dists), _i(out_cols), _f(out_d), IP(unsafe_from_address=Int(s_perm.unsafe_ptr())), IP(unsafe_from_address=Int(s_rowid.unsafe_ptr())), nq, nnz, p, n_steps)
    for lj in range(n_steps):
        for t in range(p // 2):
            p2m_row_sort_step_item(t, lj, _i(indptr), _i(cols), _f(dists), _i(out_cols), _f(out_d), IP(unsafe_from_address=Int(s_perm.unsafe_ptr())), IP(unsafe_from_address=Int(s_rowid.unsafe_ptr())), nq, nnz, p, n_steps)
    for t in range(nnz):
        p2m_row_sort_emit_item(t, _i(indptr), _i(cols), _f(dists), _i(out_cols), _f(out_d), IP(unsafe_from_address=Int(s_perm.unsafe_ptr())), IP(unsafe_from_address=Int(s_rowid.unsafe_ptr())), nq, nnz, p, n_steps)
    comptime if X_NEIGHBORS_HOST_SABOTAGE:
        if (nnz) > 0:
            _f(out_d).unsafe_store(0, _f(out_d).unsafe_load(0) + Float32(1e-3))
    _ = s_perm^
    _ = s_rowid^
