# Emit gfx942 LLVM IR (unoptimized, optimized) and assembly of the IDENTICAL GEMM
# kernels at the plan instantiations gemm_identical.mojo dispatches.
from std.compile import compile_info
from max.gpu.host import get_gpu_target
from gemm.checks.gemm_identical import *
from gemm.checks.gemm_identical import TARGET_COLUMN, lib_smem_pages_for

comptime T = get_gpu_target["mi300x"]()

def pages[RPT: Int, CPT: Int, TC: Int, KS: Int]() -> Int:
    comptime TR = TUNED_TPB // TC
    comptime PAGE_BYTES = (RPT * TR + CPT * TC) * (KS + TUNED_VECLEN) * 4
    return lib_smem_pages_for[TARGET_COLUMN, PAGE_BYTES]()

def main():
    comptime P_t0 = pages[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, 16]()
    print("### tuned0 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, 16, TUNED_FOLD_SLOTS, P_t0], emission_kind="llvm", target=T]().asm)
    print("### tuned0 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, 16, TUNED_FOLD_SLOTS, P_t0], emission_kind="llvm-opt", target=T]().asm)
    print("### tuned0 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, 16, TUNED_FOLD_SLOTS, P_t0], emission_kind="asm", target=T]().asm)
    comptime P_t1 = pages[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_64_KS]()
    print("### tuned1 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_64_KS, TUNED_FOLD_SLOTS, P_t1], emission_kind="llvm", target=T]().asm)
    print("### tuned1 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_64_KS, TUNED_FOLD_SLOTS, P_t1], emission_kind="llvm-opt", target=T]().asm)
    print("### tuned1 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_64_KS, TUNED_FOLD_SLOTS, P_t1], emission_kind="asm", target=T]().asm)
    comptime P_t2 = pages[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16]()
    print("### tuned2 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16, TUNED_FOLD_SLOTS, P_t2], emission_kind="llvm", target=T]().asm)
    print("### tuned2 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16, TUNED_FOLD_SLOTS, P_t2], emission_kind="llvm-opt", target=T]().asm)
    print("### tuned2 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16, TUNED_FOLD_SLOTS, P_t2], emission_kind="asm", target=T]().asm)
    comptime P_t3 = pages[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK]()
    print("### tuned3 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK, TUNED_FOLD_SLOTS, P_t3], emission_kind="llvm", target=T]().asm)
    print("### tuned3 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK, TUNED_FOLD_SLOTS, P_t3], emission_kind="llvm-opt", target=T]().asm)
    print("### tuned3 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK, TUNED_FOLD_SLOTS, P_t3], emission_kind="asm", target=T]().asm)
    comptime P_t4 = pages[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, TUNED_128_KS]()
    print("### tuned4 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, TUNED_128_KS, TUNED_FOLD_SLOTS, P_t4], emission_kind="llvm", target=T]().asm)
    print("### tuned4 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, TUNED_128_KS, TUNED_FOLD_SLOTS, P_t4], emission_kind="llvm-opt", target=T]().asm)
    print("### tuned4 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, TUNED_128_KS, TUNED_FOLD_SLOTS, P_t4], emission_kind="asm", target=T]().asm)
    comptime P_s0 = pages[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, TUNED_KBLK]()
    print("### split0 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, TUNED_KBLK, 1, P_s0, True], emission_kind="llvm", target=T]().asm)
    print("### split0 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, TUNED_KBLK, 1, P_s0, True], emission_kind="llvm-opt", target=T]().asm)
    print("### split0 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT // 2, TUNED_CPT // 2, TUNED_TC, TUNED_KBLK, 1, P_s0, True], emission_kind="asm", target=T]().asm)
    comptime P_s1 = pages[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK]()
    print("### split1 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK, 1, P_s1, True], emission_kind="llvm", target=T]().asm)
    print("### split1 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK, 1, P_s1, True], emission_kind="llvm-opt", target=T]().asm)
    print("### split1 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT, TUNED_CPT, TUNED_TC, TUNED_KBLK, 1, P_s1, True], emission_kind="asm", target=T]().asm)
    comptime P_s2 = pages[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16]()
    print("### split2 llvm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16, 1, P_s2, True], emission_kind="llvm", target=T]().asm)
    print("### split2 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16, 1, P_s2, True], emission_kind="llvm-opt", target=T]().asm)
    print("### split2 asm"); print(compile_info[identical_gemm_tuned_kernel[TUNED_RPT * 2, TUNED_CPT * 2, TUNED_TC, 16, 1, P_s2, True], emission_kind="asm", target=T]().asm)
    comptime P_s3 = pages[1, 1, TUNED_TC, TUNED_KBLK]()
    print("### split3 llvm"); print(compile_info[identical_gemm_tuned_kernel[1, 1, TUNED_TC, TUNED_KBLK, 1, P_s3, True], emission_kind="llvm", target=T]().asm)
    print("### split3 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[1, 1, TUNED_TC, TUNED_KBLK, 1, P_s3, True], emission_kind="llvm-opt", target=T]().asm)
    print("### split3 asm"); print(compile_info[identical_gemm_tuned_kernel[1, 1, TUNED_TC, TUNED_KBLK, 1, P_s3, True], emission_kind="asm", target=T]().asm)
    comptime P_s4 = pages[1, 1, TUNED_TPB, 16]()
    print("### split4 llvm"); print(compile_info[identical_gemm_tuned_kernel[1, 1, TUNED_TPB, 16, 1, P_s4, True], emission_kind="llvm", target=T]().asm)
    print("### split4 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[1, 1, TUNED_TPB, 16, 1, P_s4, True], emission_kind="llvm-opt", target=T]().asm)
    print("### split4 asm"); print(compile_info[identical_gemm_tuned_kernel[1, 1, TUNED_TPB, 16, 1, P_s4, True], emission_kind="asm", target=T]().asm)
    comptime P_s5 = pages[1, 2, TUNED_TPB // 8, 16]()
    print("### split5 llvm"); print(compile_info[identical_gemm_tuned_kernel[1, 2, TUNED_TPB // 8, 16, 1, P_s5, True], emission_kind="llvm", target=T]().asm)
    print("### split5 llvm-opt"); print(compile_info[identical_gemm_tuned_kernel[1, 2, TUNED_TPB // 8, 16, 1, P_s5, True], emission_kind="llvm-opt", target=T]().asm)
    print("### split5 asm"); print(compile_info[identical_gemm_tuned_kernel[1, 2, TUNED_TPB // 8, 16, 1, P_s5, True], emission_kind="asm", target=T]().asm)
    print("### tiled0 llvm"); print(compile_info[identical_gemm_tiled_kernel[16, 16, 32], emission_kind="llvm", target=T]().asm)
    print("### tiled0 llvm-opt"); print(compile_info[identical_gemm_tiled_kernel[16, 16, 32], emission_kind="llvm-opt", target=T]().asm)
    print("### tiled0 asm"); print(compile_info[identical_gemm_tiled_kernel[16, 16, 32], emission_kind="asm", target=T]().asm)
    print("### tiled1 llvm"); print(compile_info[identical_gemm_tiled_kernel[8, 32, 32], emission_kind="llvm", target=T]().asm)
    print("### tiled1 llvm-opt"); print(compile_info[identical_gemm_tiled_kernel[8, 32, 32], emission_kind="llvm-opt", target=T]().asm)
    print("### tiled1 asm"); print(compile_info[identical_gemm_tiled_kernel[8, 32, 32], emission_kind="asm", target=T]().asm)
    print("### tiled2 llvm"); print(compile_info[identical_gemm_tiled_kernel[32, 8, 16], emission_kind="llvm", target=T]().asm)
    print("### tiled2 llvm-opt"); print(compile_info[identical_gemm_tiled_kernel[32, 8, 16], emission_kind="llvm-opt", target=T]().asm)
    print("### tiled2 asm"); print(compile_info[identical_gemm_tiled_kernel[32, 8, 16], emission_kind="asm", target=T]().asm)
    print("### tiled3 llvm"); print(compile_info[identical_gemm_tiled_kernel[16, 16, 8], emission_kind="llvm", target=T]().asm)
    print("### tiled3 llvm-opt"); print(compile_info[identical_gemm_tiled_kernel[16, 16, 8], emission_kind="llvm-opt", target=T]().asm)
    print("### tiled3 asm"); print(compile_info[identical_gemm_tiled_kernel[16, 16, 8], emission_kind="asm", target=T]().asm)
    print("### tiled4 llvm"); print(compile_info[identical_gemm_tiled_kernel[4, 4, 32], emission_kind="llvm", target=T]().asm)
    print("### tiled4 llvm-opt"); print(compile_info[identical_gemm_tiled_kernel[4, 4, 32], emission_kind="llvm-opt", target=T]().asm)
    print("### tiled4 asm"); print(compile_info[identical_gemm_tiled_kernel[4, 4, 32], emission_kind="asm", target=T]().asm)
    print("### flat llvm"); print(compile_info[identical_gemm_flat_kernel, emission_kind="llvm", target=T]().asm)
    print("### flat llvm-opt"); print(compile_info[identical_gemm_flat_kernel, emission_kind="llvm-opt", target=T]().asm)
    print("### flat asm"); print(compile_info[identical_gemm_flat_kernel, emission_kind="asm", target=T]().asm)
    print("### leaf llvm"); print(compile_info[identical_gemm_leaf_kernel, emission_kind="llvm", target=T]().asm)
    print("### leaf llvm-opt"); print(compile_info[identical_gemm_leaf_kernel, emission_kind="llvm-opt", target=T]().asm)
    print("### leaf asm"); print(compile_info[identical_gemm_leaf_kernel, emission_kind="asm", target=T]().asm)
    print("### foldF llvm"); print(compile_info[identical_gemm_fold_kernel[False], emission_kind="llvm", target=T]().asm)
    print("### foldF llvm-opt"); print(compile_info[identical_gemm_fold_kernel[False], emission_kind="llvm-opt", target=T]().asm)
    print("### foldF asm"); print(compile_info[identical_gemm_fold_kernel[False], emission_kind="asm", target=T]().asm)
    print("### foldT llvm"); print(compile_info[identical_gemm_fold_kernel[True], emission_kind="llvm", target=T]().asm)
    print("### foldT llvm-opt"); print(compile_info[identical_gemm_fold_kernel[True], emission_kind="llvm-opt", target=T]().asm)
    print("### foldT asm"); print(compile_info[identical_gemm_fold_kernel[True], emission_kind="asm", target=T]().asm)
    print("### foldlevel llvm"); print(compile_info[identical_gemm_fold_level_kernel, emission_kind="llvm", target=T]().asm)
    print("### foldlevel llvm-opt"); print(compile_info[identical_gemm_fold_level_kernel, emission_kind="llvm-opt", target=T]().asm)
    print("### foldlevel asm"); print(compile_info[identical_gemm_fold_level_kernel, emission_kind="asm", target=T]().asm)
    print("### emit llvm"); print(compile_info[identical_gemm_emit_kernel, emission_kind="llvm", target=T]().asm)
    print("### emit llvm-opt"); print(compile_info[identical_gemm_emit_kernel, emission_kind="llvm-opt", target=T]().asm)
    print("### emit asm"); print(compile_info[identical_gemm_emit_kernel, emission_kind="asm", target=T]().asm)
    print("### foldstack llvm"); print(compile_info[identical_gemm_fold_stack_kernel, emission_kind="llvm", target=T]().asm)
    print("### foldstack llvm-opt"); print(compile_info[identical_gemm_fold_stack_kernel, emission_kind="llvm-opt", target=T]().asm)
    print("### foldstack asm"); print(compile_info[identical_gemm_fold_stack_kernel, emission_kind="asm", target=T]().asm)
