#!/bin/bash
# tools/lowbit_mma_speed/ptx_probe.sh -- lane/lowbit-mma-speed, a COUNTER,
# not a timing: what the compiler made of the int8 unit kernels' loads.
#
# The question it answers (the brief, 2026-09-29): the reference unit plan
# takes 0.28 of fp32.v1's time on the AMD unit and 1.39 on the NVIDIA one,
# so what is NVIDIA-specific in it? The reference reads each fragment word
# with a four-wide int8 load whose alignment it does not state. If the
# NVIDIA backend assembles that word from four byte loads, the PTX shows
# `ld.global.u8` (or .s8) where a stated alignment shows `ld.global.u32`.
#
# A generated driver (never checked in: it tracks the kernels' parameter
# lists) compiles each kernel for this device through
#   DeviceContext.compile_function[kern, dump_asm=Path(...)]()
# (tools/gemm_kernel_census_leg.sh's route), prints the runtime's own
# NUM_REGS and SHARED_SIZE_BYTES, and this script counts the load, store,
# unit and barrier instructions of each PTX. Launches nothing, times nothing.
# It builds under a PRIVATE Mojo cache (MODULAR_CACHE_DIR), never the tree's.
# NVIDIA only; on any other box it is NOT RUN.
set -u
cd "$(dirname "$0")/../.." || exit 9
BOX=${MOJOLEARN_LOWBIT_BOX:-$(hostname -s)}
OUT="$PWD/${MOJOLEARN_LOWBIT_RESULTS:-bench/results/lowbit_mma_speed}/$BOX/ptx"
rm -rf "$OUT"
mkdir -p "$OUT"
export PATH="$HOME/.pixi/bin:$PATH"
. tools/lowbit_mma_speed/box_env.sh
if ! { command -v nvidia-smi > /dev/null 2>&1 && nvidia-smi -L > /dev/null 2>&1; }; then
    echo "ptx_probe: box=$BOX is not an NVIDIA box. NOT RUN." | tee "$OUT/probe.txt"
    exit 3
fi
WORK="${TMPDIR:-/tmp}/lowbit-mma-speed-ptx"
rm -rf "$WORK"
mkdir -p "$WORK/dumps" "$WORK/mojo-cache"
export MODULAR_CACHE_DIR="$WORK/mojo-cache"
DRIVER="$WORK/ptx_driver.mojo"
{
cat <<'MOJO'
# Generated by tools/lowbit_mma_speed/ptx_probe.sh. Compiles the int8 unit
# kernels for this device and dumps their PTX. Launches nothing.
from std.pathlib import Path
from max.gpu.host import Attribute, DeviceContext
from gemm.checks.gemm_int8_mma import identical_gemm_int8_mma_kernel
from gemm.checks.gemm_int8_mma_tuned import (
    identical_gemm_int8_mma_direct_kernel,
    identical_gemm_int8_mma_tuned_kernel,
)
from gemm.checks.gemm_lowbit import quantize_rows_int8_kernel
from gemm.checks.quantize_int8_par import quantize_rows_int8_par_kernel

MOJO
gen() {
    cat <<MOJO
def stat_$1(ctx: DeviceContext) raises:
    comptime kern = $2
    var f = ctx.compile_function[kern, dump_asm=Path("$WORK/dumps/$1.ptx")]()
    print(
        "PTX_PROBE label=$1",
        " regs=", f.get_attribute(Attribute.NUM_REGS),
        " local=", f.get_attribute(Attribute.LOCAL_SIZE_BYTES),
        " shared=", f.get_attribute(Attribute.SHARED_SIZE_BYTES),
        sep="",
    )

MOJO
}
LABELS=""
add() { gen "$1" "$2"; LABELS="$LABELS $1"; }
add reference "identical_gemm_int8_mma_kernel"
add direct_reference_loads "identical_gemm_int8_mma_direct_kernel[0]"
add direct_aligned_loads "identical_gemm_int8_mma_direct_kernel[1]"
add direct_scalar_acc "identical_gemm_int8_mma_direct_kernel[2]"
add probe_loads_hoisted "identical_gemm_int8_mma_direct_kernel[3]"
add staged_w16_b32_k32_l4 "identical_gemm_int8_mma_tuned_kernel[1, 1, 2, 2, 32, 4]"
add staged_w64_b128_k32_l4 "identical_gemm_int8_mma_tuned_kernel[4, 4, 2, 2, 32, 4]"
add staged_w64_b128_k64_l16 "identical_gemm_int8_mma_tuned_kernel[4, 4, 2, 2, 64, 16]"
add staged_w64_b128x256_k64_l16 "identical_gemm_int8_mma_tuned_kernel[4, 4, 2, 4, 64, 16]"
add staged_w32_b64_k64_l16 "identical_gemm_int8_mma_tuned_kernel[2, 2, 2, 2, 64, 16]"
add staged_w32_b128_k64_l16 "identical_gemm_int8_mma_tuned_kernel[2, 2, 4, 4, 64, 16]"
add staged_w16x32_b128_k64_l16 "identical_gemm_int8_mma_tuned_kernel[1, 2, 8, 4, 64, 16]"
add quantize_reference "quantize_rows_int8_kernel"
add quantize_par_256 "quantize_rows_int8_par_kernel[256]"
echo 'def main() raises:'
echo '    var ctx = DeviceContext()'
for l in $LABELS; do
    printf '    try:\n        stat_%s(ctx)\n    except e:\n        print("PTX_PROBE_ERROR label=%s error=", e, sep="")\n' "$l" "$l"
done
echo '    print("PTX_PROBE_DONE")'
} > "$DRIVER"
cp "$DRIVER" "$OUT/ptx_driver.mojo.txt"
{
    echo "box=$BOX"
    echo "started=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "tree_head=$(git rev-parse HEAD 2>/dev/null) dirty_files=$(git status --porcelain 2>/dev/null | grep -c .)"
    box_describe
    echo "mojo_cache=$MODULAR_CACHE_DIR (private)"
} > "$OUT/probe.txt"
pixi run mojo build -D MOJOLEARN_NUMERIC_IDENTICAL=1 -I . "$DRIVER" -o "$WORK/ptx_driver" > "$OUT/build.log" 2>&1
rc=$?
echo "build exit=$rc" >> "$OUT/probe.txt"
if [ "$rc" -ne 0 ]; then
    cat "$OUT/probe.txt"; tail -60 "$OUT/build.log"
    echo "ptx_probe: box=$BOX red=1 (the driver did not build)"
    exit 1
fi
pixi run "$WORK/ptx_driver" > "$OUT/probe.log" 2>&1
rc=$?
echo "run exit=$rc" >> "$OUT/probe.txt"
grep -h '^PTX_PROBE' "$OUT/probe.log" >> "$OUT/probe.txt"
{
    printf 'label\tmma.sync\tbar.sync\tloads and stores by kind\n'
    for p in "$WORK"/dumps/*.ptx; do
        [ -f "$p" ] || continue
        label=$(basename "$p" .ptx)
        kinds=$(grep -oE '\b(ld|st)\.(global|shared|local|param)?\.?(v[24]\.)?[a-z][0-9]+\b' "$p" | sort | uniq -c | awk '{printf "%s=%s ", $2, $1}')
        printf '%s\t%s\t%s\t%s\n' "$label" "$(grep -c 'mma\.sync' "$p")" "$(grep -c 'bar\.sync' "$p")" "$kinds"
        gzip -9 -c "$p" > "$OUT/$label.ptx.gz"
    done
} > "$OUT/counts.tsv"
echo "finished=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUT/probe.txt"
cat "$OUT/probe.txt"
echo "== counts.tsv"
cat "$OUT/counts.tsv"
[ "$rc" -eq 0 ] || { echo "ptx_probe: box=$BOX red=1"; exit 1; }
echo "ptx_probe: box=$BOX red=0"
