// Dumps what cuML's OWN decision-tree code computes, so this port can be
// diffed against it per cell instead of against an analytic fixture.
//
// WHY THIS IS POSSIBLE WITHOUT A GPU, and why it took until now to notice.
// cuML's numeric core is `HDI`/`DI` -- host-device inline. `Split::update`'s
// total order, all six gain functions, every `bins.cuh` operator and
// `lower_bound` are ordinary C++ that a plain compiler runs unchanged. Only
// the four `__global__` kernels need CUDA, and NONE of the arithmetic lives
// in them: the kernels gather, atomically accumulate, scan and reduce, then
// hand the numbers to these functions.
//
// So the headers below are included VERBATIM from the pin -- not
// transcribed, not paraphrased -- and `shims.h` supplies only the
// CUDA-shaped names they reference. Every number this program prints is
// computed by rapidsai/cuml v26.08.00 (265b9da6a0e75dbef071a3168398b993a5ff6f0e).
//
// Same discipline as ensemble/tools/shuffle_oracle (CCCL) and
// ensemble/tools/philox_oracle (RAFT). This one covers the learner itself.
//
// WHAT IT DOES NOT COVER, stated so the check cannot overclaim: the kernels'
// own gather/scan/partition schedule, which needs a GPU, and the end-to-end
// tree. It covers the arithmetic, which is where a port silently diverges.

#include "shims.h"
#include "bins_shim.h"
#include "dataset_shim.h"
#include "split_shim.h"
#include "objectives_shim.h"
#include "lower_bound_shim.h"

using namespace ML::DT;

static uint64_t mix(uint64_t x) {
  x ^= x >> 33; x *= 0xFF51AFD7ED558CCDull;
  x ^= x >> 33; x *= 0xC4CEB9FE1A85EC53ull;
  x ^= x >> 33; return x;
}

// Print a float as decimal AND raw hex bits. Decimal alone does not
// round-trip -- this repository measured 0.46% of float32 values coming back
// one ULP wrong through a decimal string -- so the checker reads the HEX.
static void pf(float v) {
  uint32_t b; std::memcpy(&b, &v, 4);
  printf(" %.9g/%08x", (double)v, b);
}

int main() {
  printf("# cuML decision-tree reference, rapidsai/cuml v26.08.00\n");
  printf("# 265b9da6a0e75dbef071a3168398b993a5ff6f0e, headers included verbatim\n");
  printf("# generated by ensemble/tools/cuml_oracle/oracle.cpp -- do not hand-edit\n");
  printf("# floats printed as decimal/hexbits; the checker compares the HEX\n");

  // ---- lower_bound, their builder_kernels.cuh:118-133 -----------------
  // Note the CLAMPS: below the first quantile returns 0, above the last
  // returns len-1. That is not std::lower_bound.
  printf("section lower_bound\n");
  {
    const int len = 16;
    float q[len];
    for (int i = 0; i < len; i++) q[i] = (float)(i * 7 + 3);
    for (int t = -20; t <= 130; t += 7) {
      printf("lb %d %d %d\n", len, t, (int)lower_bound<float, int>(q, len, (float)t));
    }
    // exact hits on every quantile, and either side of each
    for (int i = 0; i < len; i++) {
      float v = q[i];
      printf("lb %d %d %d\n", len, (int)v, (int)lower_bound<float, int>(q, len, v));
      printf("lb %d %d %d\n", len, (int)v - 1, (int)lower_bound<float, int>(q, len, v - 1));
    }
  }

  // ---- classification gains, THEIR ClassificationObjectiveFunction ----
  // The histogram handed to Gain is CUMULATIVE (their kernel prefix-sums it
  // before calling), so cell i holds the LEFT partition and cell n_bins-1
  // holds the total.
  printf("section gain_cls\n");
  {
    const int n_bins = 12;
    for (int nclasses = 2; nclasses <= 4; nclasses++) {
      for (int crit_i = 0; crit_i < 2; crit_i++) {
        CRITERION crit = crit_i == 0 ? GINI : ENTROPY;
        ClassificationBin hist[64 * 8];
        // hashed per-bin increments, then prefix-summed per class
        int64_t total = 0;
        for (int c = 0; c < nclasses; c++) {
          uint64_t run = 0;
          for (int b = 0; b < n_bins; b++) {
            run += (mix((uint64_t)(c * 131 + b + 7)) % 9);
            hist[c * n_bins + b] = ClassificationBin{run};
          }
          total += (int64_t)run;
        }
        float quant[64];
        for (int b = 0; b < n_bins; b++) quant[b] = (float)(b * 3 + 1);

        ClassificationObjectiveFunction<float, int, int, false> obj(
          nclasses, 1, crit, 0.0f);

        printf("gain_cls %d %d %d %lld", nclasses, n_bins, crit_i, (long long)total);
        for (int b = 0; b < n_bins; b++) {
          int64_t nLeft = detail::CountLeft<ClassificationBin, int>(hist, b, n_bins, nclasses);
          int64_t nRight = total - nLeft;
          pf(obj.GainPerSplit(hist, b, n_bins, total, nLeft, nRight));
        }
        printf("\n");

        // and the Split their Gain() reduces to, over every bin
        Split<float, int> sp = obj.Gain(hist, quant, 5, total, n_bins);
        printf("split_cls %d %d %d %d", nclasses, n_bins, crit_i, sp.colid);
        pf(sp.quesval); pf(sp.best_metric_val);
        printf(" %lld %d %d\n", (long long)sp.global_nLeft, sp.split_start, sp.split_end);
      }
    }
  }

  // ---- regression gains, THEIR RegressionObjectiveFunction ------------
  printf("section gain_reg\n");
  {
    const int n_bins = 12;
    for (int crit_i = 0; crit_i < 4; crit_i++) {
      CRITERION crit = crit_i == 0 ? MSE
                     : crit_i == 1 ? POISSON
                     : crit_i == 2 ? GAMMA : INVERSE_GAUSSIAN;
      RegressionBin hist[64];
      double run_l = 0.0; uint64_t run_c = 0;
      for (int b = 0; b < n_bins; b++) {
        run_c += (mix((uint64_t)(b * 17 + 3)) % 7) + 1;
        run_l += (double)((mix((uint64_t)(b * 29 + 11)) % 50) + 1);
        hist[b] = RegressionBin{run_l, run_c};
      }
      float quant[64];
      for (int b = 0; b < n_bins; b++) quant[b] = (float)(b * 5 + 2);
      int64_t total = (int64_t)run_c;

      RegressionObjectiveFunction<float, float, int, false> obj(1, 1, crit, 0.0f);
      printf("gain_reg %d %d %lld", n_bins, crit_i, (long long)total);
      for (int b = 0; b < n_bins; b++) {
        int64_t nLeft = detail::CountLeft<RegressionBin, int>(hist, b, n_bins, 1);
        pf(obj.GainPerSplit(hist, b, n_bins, total, nLeft, total - nLeft));
      }
      printf("\n");
      Split<float, int> sp = obj.Gain(hist, quant, 2, total, n_bins);
      printf("split_reg %d %d %d", n_bins, crit_i, sp.colid);
      pf(sp.quesval); pf(sp.best_metric_val);
      printf(" %lld %d %d\n", (long long)sp.global_nLeft, sp.split_start, sp.split_end);
    }
  }

  // ---- Split::update, THEIR total order -------------------------------
  // Sequences chosen to walk every branch of :142-191 including the
  // equivalent-range merge, in an order a warp reduction could produce.
  printf("section update\n");
  {
    struct Cand { float qu; int co; float be; long long gnl; int bs; int bn; };
    Cand seqs[][5] = {
      {{1,3,10,5,1,1},{2,0,20,9,2,2},{3,7,20,9,3,3},{4,7,20,9,4,4},{5,1,5,2,5,5}},
      {{10,4,10,5,1,1},{30,4,10,5,3,3},{20,4,10,7,2,2},{40,4,10,5,4,4},{0,0,0,0,-1,-1}},
      {{10,4,10,5,1,1},{20,4,10,7,2,2},{30,4,10,5,3,3},{5,4,10,5,0,0},{0,0,0,0,-1,-1}},
      {{1,1,-1e30f,0,-1,-1},{2,2,-1e30f,0,-1,-1},{3,3,1,1,3,3},{4,4,1,1,4,4},{5,5,1,2,5,5}},
    };
    float quant[64];
    for (int b = 0; b < 64; b++) quant[b] = (float)(b * 10);
    for (int s = 0; s < 4; s++) {
      Split<float, int> sp;
      printf("update %d", s);
      for (int i = 0; i < 5; i++) {
        Cand& c = seqs[s][i];
        bool r = sp.update(c.qu, c.co, c.be, c.gnl, c.bs, c.bn);
        printf(" %d", r ? 1 : 0);
      }
      printf(" |");
      pf(sp.quesval); pf(sp.best_metric_val);
      printf(" %d %lld %d %d", sp.colid, (long long)sp.global_nLeft,
             sp.split_start, sp.split_end);
      sp.select_split_range_midpoint(quant, 64);
      printf(" | mid");
      pf(sp.quesval);
      printf(" %d %d\n", sp.split_start, sp.split_end);
    }
  }

  printf("end\n");
  return 0;
}
