// Dumps what CCCL's own cuda::shuffle_iterator returns, so the Mojo port can
// be diffed against it index for index rather than against our belief about it.
//
// WHY THIS FILE EXISTS. cuML's GPU Random Forest picks the features every node
// considers with exactly one expression
// (cpp/src/decisiontree/batched-levelalgo/kernels/builder_kernels.cuh:88-92):
//
//     uint32_t rng_seed = fnv1a32_hash(seed, treeid, nodeid);
//     cuda::shuffle_iterator<IdxT> shuffled_features(
//         n, cuda::std::minstd_rand(rng_seed), sample_offset);
//     column_samples[sample_idx] = shuffled_features[column_index];
//
// If our transcription of that is off by one index, every tree in the forest
// differs and NO downstream check can attribute the difference -- a wrong
// permutation is still a uniform-looking permutation. So the reference values
// come from THEIR headers, compiled and run, and not from a reading of them.
// Same discipline, and the same shape, as tools/permutation_oracle/, which
// compiles CatBoost's Mersenne twister for the same reason.
//
// It needs NO CUDA TOOLKIT AND NO GPU: cuda::shuffle_iterator and
// cuda::std::minstd_rand are _CCCL_HOST_DEVICE, so a host compile runs them.
//
// Build and run with build.sh, which pins the CCCL commit cuML v26.08.00
// resolves to. Output goes to ensemble/bench/shuffle_oracle.txt, which IS
// COMMITTED -- regenerate it when the pin moves, and read the diff, because
// that diff is the behaviour change.

#include <cuda/iterator>
#include <cuda/std/random>

#include <cstdint>
#include <cstdio>

// random_utils.cuh:17-18
constexpr uint32_t kFnvPrime = 16777619u;
constexpr uint32_t kFnvBasis = 2166136261u;

// random_utils.cuh:20-31
static uint32_t fnv1a32(uint32_t hash, uint32_t txt)
{
  hash ^= (txt >> 0) & 0xFF;  hash *= kFnvPrime;
  hash ^= (txt >> 8) & 0xFF;  hash *= kFnvPrime;
  hash ^= (txt >> 16) & 0xFF; hash *= kFnvPrime;
  hash ^= (txt >> 24) & 0xFF; hash *= kFnvPrime;
  return hash;
}

// random_utils.cuh:43-49 at the arity builder_kernels.cuh:88 instantiates:
// fnv1a32_hash(uint64_t seed, int treeid, uint32_t nodeid). The uint64 folds
// as TWO rounds, low word first (the sizeof(T) > 4 branch at :37-39).
static uint32_t fnv1a32_hash_seed_tree_node(uint64_t seed, int treeid, uint32_t nodeid)
{
  uint32_t h = kFnvBasis;
  h = fnv1a32(h, (uint32_t)(seed & 0xFFFFFFFFull));
  h = fnv1a32(h, (uint32_t)(seed >> 32));
  h = fnv1a32(h, (uint32_t)treeid);
  h = fnv1a32(h, nodeid);
  return h;
}

int main()
{
  printf("# cuda::shuffle_iterator reference, CCCL 3.4.3 "
         "(9d65c77f9763cfec20452e4071128d3f0bd2625b)\n");
  printf("# the CCCL that rapids-cmake v26.08.00 versions.json pins for cuML v26.08.00\n");
  printf("# generated by ensemble/tools/shuffle_oracle/oracle.cpp -- do not hand-edit\n");

  // --- layer 1: the raw LCG, so a failing port can be localized -----------
  // minstd_rand = linear_congruential_engine<uint_fast32_t, 48271, 0, 2^31-1>
  // Seeding: x0 = s % m, and 0 becomes 1. operator() ADVANCES THEN RETURNS.
  printf("section lcg\n");
  {
    const uint32_t seeds[] = {0u, 1u, 2u, 12345u, 2147483647u, 2147483648u,
                              4294967295u, 0xDEADBEEFu};
    for (uint32_t s : seeds) {
      cuda::std::minstd_rand g(s);
      printf("lcg %u", s);
      for (int i = 0; i < 8; i++) printf(" %llu", (unsigned long long)g());
      printf("\n");
    }
  }

  // --- layer 2: the 24 Feistel keys -------------------------------------
  // Each key is uniform_int_distribution<uint32_t>{}(gen), which for a
  // full-range uint32 request routes into __independent_bits_engine with
  // w=32, n=2, w0=16 -- TWO draws per key, high 16 bits first, each draw
  // reduced by min()==1 and rejection-tested against 2147418112. This layer
  // is separated out deliberately: it is the single easiest place to be
  // plausibly wrong, and a port that fails here but passes nothing else is
  // told exactly where it failed.
  printf("section keys\n");
  {
    const uint32_t seeds[] = {12345u, 42u, 1u, 0xDEADBEEFu};
    for (uint32_t s : seeds) {
      cuda::std::minstd_rand g(s);
      cuda::std::uniform_int_distribution<uint32_t> d{};
      printf("keys %u", s);
      for (int i = 0; i < 24; i++) printf(" %u", d(g));
      printf("\n");
    }
  }

  // --- layer 3: the permutation itself -----------------------------------
  // Adversarial n on purpose: exact powers of two, one below and one above a
  // power of two, everything at or under the Feistel's max(8, bit_width)
  // floor of 256 (where a naive bit_width(n-1) is wrong), and one that
  // crosses 2^8.
  printf("section perm\n");
  {
    struct Case { int n; uint32_t seed; int off; int cnt; };
    const Case cases[] = {
      {1, 12345u, 0, 1},      {2, 12345u, 0, 2},     {3, 12345u, 0, 3},
      {4, 0xDEADBEEFu, 0, 4}, {5, 12345u, 0, 5},     {7, 12345u, 0, 7},
      {8, 12345u, 0, 8},      {9, 12345u, 0, 9},     {10, 12345u, 0, 10},
      {10, 12345u, 3, 7},     {16, 12345u, 0, 16},   {17, 12345u, 0, 17},
      {31, 7u, 0, 31},        {32, 7u, 0, 32},       {33, 7u, 0, 33},
      {54, 987654321u, 0, 54},{54, 987654321u, 20, 34},
      {64, 7u, 0, 64},        {100, 42u, 0, 100},    {100, 42u, 10, 90},
      {255, 1u, 0, 32},       {256, 1u, 0, 32},      {257, 12345u, 0, 32},
      {300, 99u, 0, 32},      {1000, 12345u, 0, 32}, {1000, 12345u, 100, 32},
      {1024, 12345u, 0, 32},  {1025, 12345u, 0, 32}, {4096, 5u, 0, 32},
      {100000, 31337u, 0, 32},
    };
    for (const Case& c : cases) {
      cuda::shuffle_iterator<int> it(c.n, cuda::std::minstd_rand(c.seed), c.off);
      printf("perm %d %u %d %d", c.n, c.seed, c.off, c.cnt);
      for (int i = 0; i < c.cnt; i++) printf(" %d", (int)it[i]);
      printf("\n");
    }
  }

  // --- layer 4: end to end, exactly as cuML calls it ---------------------
  // Including their seed chain and their round/sample_offset loop, so the
  // port is checked at the call site and not only at the primitive.
  // sample_offset = round * n_sampled_cols (builder.cuh:438), and
  // n_sampled_cols is clamped to n_cols - sample_offset on the last round
  // (builder.cuh:439-440).
  printf("section e2e\n");
  {
    struct Case { uint64_t seed; int treeid; uint32_t nodeid; int n; int k; int round; };
    const Case cases[] = {
      {0ull, 0, 0u, 10, 3, 0},   {0ull, 0, 0u, 10, 3, 1},
      {0ull, 0, 0u, 10, 3, 2},   {0ull, 0, 0u, 10, 3, 3},
      {12345ull, 2, 7u, 54, 8, 0},  {12345ull, 2, 7u, 54, 8, 1},
      {12345ull, 2, 7u, 54, 8, 6},
      {0xDEADBEEFCAFEBABEull, 5, 123u, 64, 8, 0},
      {0xDEADBEEFCAFEBABEull, 5, 123u, 64, 8, 7},
      {1ull, 0, 4095u, 100, 10, 0}, {1ull, 3, 4095u, 100, 10, 0},
      {1ull, 0, 4096u, 100, 10, 0},
    };
    for (const Case& c : cases) {
      uint32_t rs = fnv1a32_hash_seed_tree_node(c.seed, c.treeid, c.nodeid);
      int off = c.round * c.k;
      int kk = c.k < (c.n - off) ? c.k : (c.n - off);
      if (kk <= 0) continue;
      cuda::shuffle_iterator<int> it(c.n, cuda::std::minstd_rand(rs), off);
      printf("e2e %llu %d %u %d %d %d %u %d",
             (unsigned long long)c.seed, c.treeid, c.nodeid, c.n, c.k, c.round, rs, kk);
      for (int i = 0; i < kk; i++) printf(" %d", (int)it[i]);
      printf("\n");
    }
  }

  printf("end\n");
  return 0;
}
