"""THE NEIGHBORS LANE'S HOST SURFACE FRAGMENT.

Owned by the `neighbors` expansion lane and merged by host_surface.py at import
(`EXPANSION_LANES`). Literal data only: no imports, no calls but dict(...).
The `exports` tuple is written by x_neighbors/gen.py from its op table.
"""
GPU_BINDINGS = ("_mojolearn_x_neighbors",)
FAMILIES = (
    dict(
        family="x_neighbors",
        binding="_mojolearn_x_neighbors_host",
        routes="_mojolearn_x_neighbors",
        loaded_by="_backend._HOST_MODULES",
        sabotage_define="MOJOLEARN_HOST_SABOTAGE",
        training_lanes=(
            "x-neighbors-lof", "x-neighbors-nearest-centroid", "x-neighbors-ocsvm", "x-neighbors-kpca",
            "x-neighbors-poly-sketch", "x-neighbors-additive-chi2", "x-neighbors-skewed-chi2",
            "x-neighbors-label-propagation", "x-neighbors-label-spreading", "x-neighbors-knn-imputer",
            "x-neighbors-pagerank", "x-neighbors-connected-components", "x-neighbors-louvain", "x-neighbors-svgp",
            "x-neighbors-gamma-scale", "x-neighbors-svm-weights", "x-neighbors-svc-sigmoid", "x-neighbors-svc-multiclass",
            "x-neighbors-krr-options", "x-neighbors-svm-precomputed", "x-neighbors-km-kernels",
            "x-neighbors-gp-cov", "x-neighbors-metrics",
            "x-neighbors-svr-kernels", "x-neighbors-svc-probability",
        ),
        inference_lanes=(),
        forest_kinds=(),
        classes=("LocalOutlierFactor", "NearestCentroid", "OneClassSVM", "KernelPCA", "PolynomialCountSketch", "AdditiveChi2Sampler", "SkewedChi2Sampler", "LabelPropagation", "LabelSpreading", "KNNImputer", "PageRank", "connected_components", "Louvain", "SVGP"),
        display="the neighbors + kernel expansion lane",
        host_modules=("x_neighbors/items.mojo", "x_neighbors/host_ops.mojo", "x_neighbors/eigh.mojo"),
        exports=(
            # BEGIN GENERATED EXPORTS
            "x_neighbors_host_numeric_mode",
            "x_neighbors_host_vendor",
            "x_neighbors_host_column",
            "x_neighbors_host_sabotage",
            "xn_sqdist",
            "xn_nan_sqdist",
            "xn_l1dist",
            "xn_kernel",
            "xn_matmul",
            "xn_rowsum",
            "xn_colsum",
            "xn_unary",
            "xn_knn_select",
            "xn_knn_sq",
            "xn_group_mean",
            "xn_take_rows",
            "xn_take_cols",
            "xn_variance",
            "xn_lof_lrd",
            "xn_lof_score",
            "xn_kpca_center",
            "xn_scale_div",
            "xn_svd_flip",
            "xn_kpca_alpha_scale",
            "xn_nc_std",
            "xn_nc_shrink_d",
            "xn_nc_shrink",
            "xn_nc_decision",
            "xn_softmax",
            "xn_log_softmax",
            "xn_pcs",
            "xn_achi2",
            "xn_skew_weights",
            "xn_skew_transform",
            "xn_absdiff_sum",
            "xn_row_normalize",
            "xn_lp_clamp",
            "xn_ls_clamp",
            "xn_ls_laplacian",
            "xn_knn_graph",
            "xn_knn_impute",
            "xn_col_degree",
            "xn_ls_laplacian_deg",
            "xn_row_all_zero",
            "xn_pcs_sketch",
            "xn_pcs_conv",
            "xn_pcs_copy0",
            "xn_knn_impute_cells",
            "xn_pagerank_step",
            "xn_cc_step",
            "xn_graph_symmetry",
            "xn_svgp_var",
            "xn_nc_median",
            "xn_row_argmax",
            "xn_nc_med_std",
            "xn_pos_compact",
            "xn_p2m_mask_value",
            "xn_p2m_zero_cols",
            "xn_p2m_nan_indicator",
            "xn_p2m_sign_label",
            "xn_p2m_relabel",
            "xn_p2m_fill",
            "xn_p2m_iota",
            "xn_p2m_negate",
            "xn_p2m_transpose",
            "xn_p2m_transpose_i",
            "xn_p2m_row_sort",
            "xn_nc_stats",
            "xn_lp_knn_graph",
            "xn_lp_knn_product",
            "xn_lp_iterate",
            "xn_pr_iterate",
            "xn_pr_iterate_sparse",
            "xn_pcs_resident",
            "xn_knn_sq_tiled",
            "xn_knn_impute_tiled",
            "xn_cc_iterate",
            "xn_cc_iterate_csr",
            "xn_nan_cells",
            "xn_kpca_transform",
            "xn_kernel_matmul",
            "xn_svgp_fit_ff",
            "xn_svgp_predict",
            "xn_lp_iterate_knn",
            "xn_kernel_tiled",
            "xn_ocsvm",
            "xn_louvain",
            "xn_kapprox_check",
            "xn_kapprox_achi2",
            "xn_kapprox_skew_fit",
            "xn_kapprox_skew_transform",
            "xn_kapprox_sparse_rp",
            "xn_eigh",
            "x_neighbors_numeric_mode",
            "x_neighbors_py2mojo_off",
            "x_neighbors_vendor",
            "x_neighbors_kapprox_fast",
            "x_neighbors_kpca_resident",
            "x_neighbors_sparse_rp_device",
            "x_neighbors_purity_flags",
            # END GENERATED EXPORTS
        ),
        gate="tools/identity_break.py (cpu-identity-gate.yml)",
        wheel_note="Ships: the neighbors + kernel expansion lane's CPU route (x_neighbors/).",
        ships_in_wheel=True,
    ),
)
TRAINING_LANE_NAMES = {
    "x-neighbors-lof": "LocalOutlierFactor",
    "x-neighbors-nearest-centroid": "NearestCentroid",
    "x-neighbors-ocsvm": "OneClassSVM",
    "x-neighbors-kpca": "KernelPCA",
    "x-neighbors-poly-sketch": "PolynomialCountSketch",
    "x-neighbors-additive-chi2": "AdditiveChi2Sampler",
    "x-neighbors-skewed-chi2": "SkewedChi2Sampler",
    "x-neighbors-label-propagation": "LabelPropagation",
    "x-neighbors-label-spreading": "LabelSpreading",
    "x-neighbors-knn-imputer": "KNNImputer",
    "x-neighbors-pagerank": "PageRank",
    "x-neighbors-connected-components": "connected_components",
    "x-neighbors-louvain": "Louvain",
    "x-neighbors-svgp": "SVGP",
    "x-neighbors-gamma-scale": "SVC / SVR / RBFSampler gamma='scale'",
    "x-neighbors-svm-weights": "SVC / SVR sample_weight, SVC class_weight",
    "x-neighbors-svc-sigmoid": "SVC kernel='sigmoid'",
    "x-neighbors-svr-kernels": "SVR kernel='poly' / 'sigmoid'",
    "x-neighbors-svc-multiclass": "SVC one-vs-one multiclass",
    "x-neighbors-krr-options": "KernelRidge sample_weight, kernel='precomputed'",
    "x-neighbors-svm-precomputed": "SVC / SVR kernel='precomputed'",
    "x-neighbors-km-kernels": "KernelRidge / Nystroem cosine, chi2, additive_chi2",
    "x-neighbors-gp-cov": "GaussianProcessRegressor predict(return_cov=True)",
    "x-neighbors-metrics": "k-NN canberra, braycurtis, correlation, jensenshannon, inner_product",
    "x-neighbors-svc-probability": "SVC probability=True (libsvm Platt, seeded 5-fold CV)",
}
PUBLIC_PENDING_LANES = {
    }
