"""The algorithm inventory, mapped explicitly to verification lanes.

A mapping is scope, not execution or certification. Unmapped public additions
remain visible as additional lanes. No runtime dependency on a source checkout.
"""
PROVENANCE = {'repository': 'mojolearn',
 'source_file': 'python/mojolearn/host_surface.py',
 'date': '2026-09-16',
 'head_commit': 'a2f05dbe8',
 'settings': 'TRAINING_LANE_NAMES and the inference lanes of host_surface.py, '
             'the @lane registry of tools/identity_break.py (189 lanes), the '
             'metrics functions of the metrics family; 39 harness lanes '
             'without a manifest title are titled here; one refusal lane and '
             'three umbrella metric lanes dropped'}

ENTRIES = [{'id': 'appendix-001',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte-level BPE tokenizer training',
  'lanes': ['bpe-trainer'],
  'parts': ['train']},
 {'id': 'appendix-002',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM trainer',
  'lanes': ['byte-lm'],
  'parts': ['train']},
 {'id': 'appendix-003',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM forward pass on its reference path (inference)',
  'lanes': ['byte-lm-host-infer'],
  'parts': ['train']},
 {'id': 'appendix-004',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM forward pass on its threaded path (inference)',
  'lanes': ['byte-lm-host-infer-threaded'],
  'parts': ['train']},
 {'id': 'appendix-005',
  'group': 'byte-level language model and tokenizer',
  'title': 'published byte LM host training step',
  'lanes': ['byte-lm-host-train'],
  'parts': ['train']},
 {'id': 'appendix-006',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM trainer on its resident session',
  'lanes': ['byte-lm-resident'],
  'parts': ['train']},
 {'id': 'appendix-007',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM training over ordered gradient shards',
  'lanes': ['par-byte-lm'],
  'parts': ['train']},
 {'id': 'appendix-008',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM training with a pooled model',
  'lanes': ['par-byte-lm-model-pool'],
  'parts': ['train']},
 {'id': 'appendix-009',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte LM training with parameter offload',
  'lanes': ['par-byte-lm-offload'],
  'parts': ['train']},
 {'id': 'appendix-010',
  'group': 'byte-level language model and tokenizer',
  'title': 'byte-level BPE tokenizer (inference, host integers)',
  'lanes': ['tokenizer'],
  'parts': ['train']},
 {'id': 'appendix-011',
  'group': 'neural blocks, training and optimizers',
  'title': 'cross-entropy loss arms',
  'lanes': ['cross-entropy-arms'],
  'parts': ['train']},
 {'id': 'appendix-012',
  'group': 'neural blocks, training and optimizers',
  'title': 'Embedding layer',
  'lanes': ['embedding'],
  'parts': ['train']},
 {'id': 'appendix-013',
  'group': 'neural blocks, training and optimizers',
  'title': 'Embedding layer on its sorted execution plan',
  'lanes': ['embedding-sort'],
  'parts': ['train']},
 {'id': 'appendix-014',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-1 block',
  'lanes': ['mamba1'],
  'parts': ['train']},
 {'id': 'appendix-015',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-2 block',
  'lanes': ['mamba2'],
  'parts': ['train']},
 {'id': 'appendix-016',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-2 block with an active dt clamp',
  'lanes': ['mamba2-dtlimit'],
  'parts': ['train']},
 {'id': 'appendix-017',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-3 block',
  'lanes': ['mamba3'],
  'parts': ['train']},
 {'id': 'appendix-018',
  'group': 'neural blocks, training and optimizers',
  'title': 'small MLP',
  'lanes': ['mlp'],
  'parts': ['train']},
 {'id': 'appendix-019',
  'group': 'neural blocks, training and optimizers',
  'title': 'Adam and AdamW with the gradient clip and accumulation',
  'lanes': ['optim-adam-clip'],
  'parts': ['train']},
 {'id': 'appendix-020',
  'group': 'neural blocks, training and optimizers',
  'title': 'SGD with momentum, Nesterov and dampening',
  'lanes': ['optim-sgd'],
  'parts': ['train']},
 {'id': 'appendix-021',
  'group': 'neural blocks, training and optimizers',
  'title': 'small MLP trained over ordered logical gradient shards',
  'lanes': ['par-mlp'],
  'parts': ['train']},
 {'id': 'appendix-022',
  'group': 'neural blocks, training and optimizers',
  'title': 'Samba stack trained over ordered logical gradient shards',
  'lanes': ['par-samba'],
  'parts': ['train']},
 {'id': 'appendix-023',
  'group': 'neural blocks, training and optimizers',
  'title': 'Samba stack trained over ordered logical gradient shards under a global norm clip',
  'lanes': ['par-samba-clip'],
  'parts': ['train']},
 {'id': 'appendix-024',
  'group': 'neural blocks, training and optimizers',
  'title': 'Samba stack',
  'lanes': ['samba'],
  'parts': ['train']},
 {'id': 'appendix-025',
  'group': 'neural blocks, training and optimizers',
  'title': 'Samba stack with untied embeddings, dropout, accumulation, clipping and a cosine schedule',
  'lanes': ['samba-untied-dropout-accum'],
  'parts': ['train']},
 {'id': 'appendix-026',
  'group': 'neural blocks, training and optimizers',
  'title': 'embedding, RMSNorm and linear training primitives',
  'lanes': ['training-primitives'],
  'parts': ['train']},
 {'id': 'appendix-027',
  'group': 'neural blocks, training and optimizers',
  'title': 'Transformer block',
  'lanes': ['transformer'],
  'parts': ['train']},
 {'id': 'appendix-028',
  'group': 'neural blocks, training and optimizers',
  'title': 'sliding-window Transformer block',
  'lanes': ['transformer-window'],
  'parts': ['train']},
 {'id': 'appendix-029',
  'group': 'neural blocks, training and optimizers',
  'title': 'MLP inference',
  'lanes': ['mlp'],
  'parts': ['infer', 'model', 'batch']},
 {'id': 'appendix-030',
  'group': 'neural blocks, training and optimizers',
  'title': 'Transformer block inference',
  'lanes': ['transformer'],
  'parts': ['infer', 'model', 'batch']},
 {'id': 'appendix-031',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-1 block inference',
  'lanes': ['mamba1'],
  'parts': ['infer', 'model', 'batch']},
 {'id': 'appendix-032',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-2 block inference',
  'lanes': ['mamba2'],
  'parts': ['infer', 'model', 'batch']},
 {'id': 'appendix-033',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-3 block inference',
  'lanes': ['mamba3'],
  'parts': ['infer', 'model', 'batch']},
 {'id': 'appendix-034',
  'group': 'neural blocks, training and optimizers',
  'title': 'Samba inference',
  'lanes': ['samba'],
  'parts': ['infer', 'model', 'batch']},
 {'id': 'appendix-035',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-1 stateful decode',
  'lanes': ['mamba1'],
  'parts': ['stepfull']},
 {'id': 'appendix-036',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-2 stateful decode',
  'lanes': ['mamba2'],
  'parts': ['stepfull']},
 {'id': 'appendix-037',
  'group': 'neural blocks, training and optimizers',
  'title': 'Mamba-3 stateful decode',
  'lanes': ['mamba3'],
  'parts': ['stepfull']},
 {'id': 'appendix-038',
  'group': 'neural blocks, training and optimizers',
  'title': 'transformer stateful decode',
  'lanes': ['transformer'],
  'parts': ['stepfull']},
 {'id': 'appendix-039',
  'group': 'gradient boosting',
  'title': 'cross-validation of gradient boosting',
  'lanes': ['cross-val'],
  'parts': ['train']},
 {'id': 'appendix-040',
  'group': 'gradient boosting',
  'title': 'cross-validation fold assignment',
  'lanes': ['cross-val-folds'],
  'parts': ['train']},
 {'id': 'appendix-041',
  'group': 'gradient boosting',
  'title': 'gradient boosting classifier',
  'lanes': ['gbdt-adapter-clf'],
  'parts': ['train']},
 {'id': 'appendix-042',
  'group': 'gradient boosting',
  'title': 'gradient boosting regressor',
  'lanes': ['gbdt-adapter-reg'],
  'parts': ['train']},
 {'id': 'appendix-043',
  'group': 'gradient boosting',
  'title': 'weighted scores of the gradient boosting classifier and regressor',
  'lanes': ['gbdt-adapter-score-weighted'],
  'parts': ['train']},
 {'id': 'appendix-044',
  'group': 'gradient boosting',
  'title': 'gradient boosting with one-hot categorical columns',
  'lanes': ['gbdt-categorical-ctr'],
  'parts': ['train']},
 {'id': 'appendix-045',
  'group': 'gradient boosting',
  'title': 'predictions of Metal-saved gradient boosting models with CTR tables (inference)',
  'lanes': ['gbdt-categorical-ctr-tables'],
  'parts': ['train']},
 {'id': 'appendix-046',
  'group': 'gradient boosting',
  'title': 'gradient boosting on depthwise trees with the Logloss loss',
  'lanes': ['gbdt-depthwise'],
  'parts': ['train']},
 {'id': 'appendix-047',
  'group': 'gradient boosting',
  'title': 'gradient boosting with Exact leaves and the Poisson bootstrap',
  'lanes': ['gbdt-exact-mae'],
  'parts': ['train']},
 {'id': 'appendix-048',
  'group': 'gradient boosting',
  'title': 'two-level FeatureFreq estimator',
  'lanes': ['gbdt-feature-freq'],
  'parts': ['train']},
 {'id': 'appendix-049',
  'group': 'gradient boosting',
  'title': 'gradient boosting on lossguide trees with the Logloss loss',
  'lanes': ['gbdt-lossguide'],
  'parts': ['train']},
 {'id': 'appendix-050',
  'group': 'gradient boosting',
  'title': 'gradient boosting on lossguide trees with the NewtonCosine score and the searcher options',
  'lanes': ['gbdt-lossguide-newtoncosine'],
  'parts': ['train']},
 {'id': 'appendix-051',
  'group': 'gradient boosting',
  'title': 'multiclass gradient boosting',
  'lanes': ['gbdt-multiclass'],
  'parts': ['train']},
 {'id': 'appendix-052',
  'group': 'gradient boosting',
  'title': 'gradient boosting with the Min and Max NaN modes',
  'lanes': ['gbdt-nan-modes'],
  'parts': ['train']},
 {'id': 'appendix-053',
  'group': 'gradient boosting',
  'title': 'one-vs-all gradient boosting',
  'lanes': ['gbdt-onevsall'],
  'parts': ['train']},
 {'id': 'appendix-054',
  'group': 'gradient boosting',
  'title': 'ordered boosting with the RMSE loss (OrderedRMSE)',
  'lanes': ['gbdt-ordered-rmse'],
  'parts': ['train']},
 {'id': 'appendix-055',
  'group': 'gradient boosting',
  'title': 'gradient boosting with the PairLogit ranking loss on generated and explicit pairs',
  'lanes': ['gbdt-pair-logit'],
  'parts': ['train']},
 {'id': 'appendix-056',
  'group': 'gradient boosting',
  'title': 'gradient boosting with the Quantile, MAE, LogLinQuantile, MAPE, Poisson, Lq, Expectile, Tweedie, '
           'Huber and CrossEntropy losses',
  'lanes': ['gbdt-parametric-losses'],
  'parts': ['train']},
 {'id': 'appendix-057',
  'group': 'gradient boosting',
  'title': 'gradient boosting with the pointwise searcher, L2 scores, the Bayesian bootstrap and an eval set',
  'lanes': ['gbdt-pointwise-l2-bayesian-eval'],
  'parts': ['train']},
 {'id': 'appendix-058',
  'group': 'gradient boosting',
  'title': 'gradient boosting with the QueryRMSE ranking loss on query groups',
  'lanes': ['gbdt-query-rmse'],
  'parts': ['train']},
 {'id': 'appendix-059',
  'group': 'gradient boosting',
  'title': 'gradient boosting on symmetric trees with the RMSE loss',
  'lanes': ['gbdt-rmse'],
  'parts': ['train']},
 {'id': 'appendix-060',
  'group': 'gradient boosting',
  'title': 'gradient boosting on symmetric trees with the Logloss loss',
  'lanes': ['gbdt-symmetric'],
  'parts': ['train']},
 {'id': 'appendix-061',
  'group': 'gradient boosting',
  'title': 'predictions of Metal-saved gradient boosting models with tensor CTRs (inference)',
  'lanes': ['gbdt-tensor-ctr-tables'],
  'parts': ['train']},
 {'id': 'appendix-062',
  'group': 'gradient boosting',
  'title': 'gradient boosting with the YetiRank ranking loss on query groups',
  'lanes': ['gbdt-yeti-rank'],
  'parts': ['train']},
 {'id': 'appendix-063',
  'group': 'gradient boosting',
  'title': 'gradient boosting over ordered gradient shards',
  'lanes': ['par-boosting'],
  'parts': ['train']},
 {'id': 'appendix-064',
  'group': 'gradient boosting',
  'title': 'gradient boosting classifier over ordered gradient shards',
  'lanes': ['par-boosting-clf'],
  'parts': ['train']},
 {'id': 'appendix-065',
  'group': 'gradient boosting',
  'title': 'pointwise gradient boosting over ordered gradient shards',
  'lanes': ['par-boosting-pointwise'],
  'parts': ['train']},
 {'id': 'appendix-066',
  'group': 'gradient boosting',
  'title': 'gradient boosting regressor over ordered gradient shards',
  'lanes': ['par-boosting-reg'],
  'parts': ['train']},
 {'id': 'appendix-067',
  'group': 'gradient boosting',
  'title': 'two-level feature-frequency estimator over shards',
  'lanes': ['par-feature-freq'],
  'parts': ['train']},
 {'id': 'appendix-068',
  'group': 'gradient boosting',
  'title': 'ordered boosting over shards',
  'lanes': ['par-ordered-rmse'],
  'parts': ['train']},
 {'id': 'appendix-069',
  'group': 'gradient boosting',
  'title': 'saved gradient boosting models on a CPU (HostGBDT)',
  'lanes': [],
  'parts': ['model', 'batch'],
  'api': 'HostGBDT',
  'portable_models': ['gbdt-symmetric/base'],
  'alternative_gate': 'tools/classical_host_gate.py',
  'limitation': 'Portable-model checks cover representative saved models on CPU; dedicated gates cover '
                'additional configurations.'},
 {'id': 'appendix-070',
  'group': 'forests',
  'title': 'Extra Trees classifier',
  'lanes': ['et-clf'],
  'parts': ['train']},
 {'id': 'appendix-071',
  'group': 'forests',
  'title': 'best-first Extra Trees classifier with entropy splits',
  'lanes': ['et-clf-entropy-bestfirst'],
  'parts': ['train']},
 {'id': 'appendix-072',
  'group': 'forests',
  'title': 'Extra Trees regressor',
  'lanes': ['et-reg'],
  'parts': ['train']},
 {'id': 'appendix-073',
  'group': 'forests',
  'title': 'bootstrapped Extra Trees regressor with the parallel groves engine',
  'lanes': ['et-reg-bootstrap-parallel'],
  'parts': ['train']},
 {'id': 'appendix-074',
  'group': 'forests',
  'title': 'isolation forest',
  'lanes': ['iforest'],
  'parts': ['train']},
 {'id': 'appendix-075',
  'group': 'forests',
  'title': 'tuned isolation forest',
  'lanes': ['iforest-tuned'],
  'parts': ['train']},
 {'id': 'appendix-076',
  'group': 'forests',
  'title': 'tree-range-sharded random forest classifier',
  'lanes': ['par-forest'],
  'parts': ['train']},
 {'id': 'appendix-077',
  'group': 'forests',
  'title': 'tree-range-sharded Extra Trees regressor',
  'lanes': ['par-forest-et'],
  'parts': ['train']},
 {'id': 'appendix-078',
  'group': 'forests',
  'title': 'Extra Trees classifier over tree-range shards',
  'lanes': ['par-forest-et-clf'],
  'parts': ['train']},
 {'id': 'appendix-079',
  'group': 'forests',
  'title': 'forest training with a pooled tree set',
  'lanes': ['par-forest-pool'],
  'parts': ['train']},
 {'id': 'appendix-080',
  'group': 'forests',
  'title': 'random forest regressor over tree-range shards',
  'lanes': ['par-forest-reg'],
  'parts': ['train']},
 {'id': 'appendix-081',
  'group': 'forests',
  'title': 'isolation forest over tree shards',
  'lanes': ['par-iforest'],
  'parts': ['train']},
 {'id': 'appendix-082',
  'group': 'forests',
  'title': 'random forest classifier',
  'lanes': ['rf-clf'],
  'parts': ['train']},
 {'id': 'appendix-083',
  'group': 'forests',
  'title': 'class-weighted random forest classifier with the parallel groves engine',
  'lanes': ['rf-clf-balanced-parallel'],
  'parts': ['train']},
 {'id': 'appendix-084',
  'group': 'forests',
  'title': 'random forest classifier with entropy splits, log2 features and no bootstrap',
  'lanes': ['rf-clf-entropy-log2-noboot'],
  'parts': ['train']},
 {'id': 'appendix-085',
  'group': 'forests',
  'title': 'random forest regressor',
  'lanes': ['rf-reg'],
  'parts': ['train']},
 {'id': 'appendix-086',
  'group': 'forests',
  'title': 'random forest regressor with the gamma and inverse Gaussian criteria',
  'lanes': ['rf-reg-gamma-ig'],
  'parts': ['train']},
 {'id': 'appendix-087',
  'group': 'forests',
  'title': 'random forest regressor with the Poisson criterion',
  'lanes': ['rf-reg-poisson'],
  'parts': ['train']},
 {'id': 'appendix-088',
  'group': 'forests',
  'title': 'weighted scores of the random forest classifier and regressor',
  'lanes': ['rf-score-weighted'],
  'parts': ['train']},
 {'id': 'appendix-089',
  'group': 'forests',
  'title': 'saved forests on a CPU (HostForest)',
  'lanes': [],
  'parts': ['model', 'batch'],
  'api': 'HostForest',
  'portable_models': ['rf-clf/base'],
  'alternative_gate': 'tools/forest_host_gate.py',
  'limitation': 'Portable-model checks cover representative saved models on CPU; dedicated gates cover '
                'additional configurations.'},
 {'id': 'appendix-090',
  'group': 'clustering',
  'title': 'agglomerative clustering',
  'lanes': ['agglomerative'],
  'parts': ['train']},
 {'id': 'appendix-091', 'group': 'clustering', 'title': 'DBSCAN', 'lanes': ['dbscan'], 'parts': ['train']},
 {'id': 'appendix-092',
  'group': 'clustering',
  'title': 'brute-force DBSCAN under manhattan distance',
  'lanes': ['dbscan-brute-l1'],
  'parts': ['train']},
 {'id': 'appendix-093',
  'group': 'clustering',
  'title': 'weighted DBSCAN',
  'lanes': ['dbscan-weighted'],
  'parts': ['train']},
 {'id': 'appendix-094',
  'group': 'clustering',
  'title': 'Gaussian mixture',
  'lanes': ['gmm'],
  'parts': ['train']},
 {'id': 'appendix-095',
  'group': 'clustering',
  'title': 'Gaussian mixture with a random start',
  'lanes': ['gmm-random-init'],
  'parts': ['train']},
 {'id': 'appendix-096',
  'group': 'clustering',
  'title': 'samples from the Gaussian mixture with a random start',
  'lanes': ['gmm-random-init-sample'],
  'parts': ['train']},
 {'id': 'appendix-097',
  'group': 'clustering',
  'title': 'samples from the Gaussian mixture',
  'lanes': ['gmm-sample'],
  'parts': ['train']},
 {'id': 'appendix-098', 'group': 'clustering', 'title': 'HDBSCAN', 'lanes': ['hdbscan'], 'parts': ['train']},
 {'id': 'appendix-099',
  'group': 'clustering',
  'title': 'HDBSCAN with leaf selection',
  'lanes': ['hdbscan-leaf'],
  'parts': ['train']},
 {'id': 'appendix-100', 'group': 'clustering', 'title': 'k-means', 'lanes': ['kmeans'], 'parts': ['train']},
 {'id': 'appendix-101',
  'group': 'clustering',
  'title': 'k-means from given centroids',
  'lanes': ['kmeans-array'],
  'parts': ['train']},
 {'id': 'appendix-102',
  'group': 'clustering',
  'title': 'k-means from the classic k-means++ start',
  'lanes': ['kmeans-classic-pp'],
  'parts': ['train']},
 {'id': 'appendix-103',
  'group': 'clustering',
  'title': 'k-means with a random start',
  'lanes': ['kmeans-random'],
  'parts': ['train']},
 {'id': 'appendix-104',
  'group': 'clustering',
  'title': 'k-means under the rooted euclidean metric',
  'lanes': ['kmeans-sqrt'],
  'parts': ['train']},
 {'id': 'appendix-105',
  'group': 'clustering',
  'title': 'weighted k-means',
  'lanes': ['kmeans-weighted'],
  'parts': ['train']},
 {'id': 'appendix-106',
  'group': 'clustering',
  'title': 'DBSCAN over query shards',
  'lanes': ['par-dbscan'],
  'parts': ['train']},
 {'id': 'appendix-107',
  'group': 'clustering',
  'title': 'Gaussian mixture over row shards',
  'lanes': ['par-gmm'],
  'parts': ['train']},
 {'id': 'appendix-108',
  'group': 'clustering',
  'title': 'agglomerative clustering over graph shards',
  'lanes': ['par-graph-agglomerative'],
  'parts': ['train']},
 {'id': 'appendix-109',
  'group': 'clustering',
  'title': 'spectral clustering over graph shards',
  'lanes': ['par-graph-spectral'],
  'parts': ['train']},
 {'id': 'appendix-110',
  'group': 'clustering',
  'title': 'HDBSCAN over row shards',
  'lanes': ['par-hdbscan'],
  'parts': ['train']},
 {'id': 'appendix-111',
  'group': 'clustering',
  'title': 'k-means over row shards',
  'lanes': ['par-kmeans'],
  'parts': ['train']},
 {'id': 'appendix-112',
  'group': 'clustering',
  'title': 'spectral clustering',
  'lanes': ['spectral'],
  'parts': ['train']},
 {'id': 'appendix-113',
  'group': 'clustering',
  'title': 'spectral clustering on a precomputed affinity',
  'lanes': ['spectral-precomputed'],
  'parts': ['train']},
 {'id': 'appendix-114',
  'group': 'neighbors, density and search',
  'title': 'IVF-Flat index',
  'lanes': ['ivf'],
  'parts': ['train']},
 {'id': 'appendix-115',
  'group': 'neighbors, density and search',
  'title': 'IVF-Flat index under euclidean distance',
  'lanes': ['ivf-euclidean'],
  'parts': ['train']},
 {'id': 'appendix-116',
  'group': 'neighbors, density and search',
  'title': 'extending a built IVF-Flat index',
  'lanes': ['ivf-extend'],
  'parts': ['train']},
 {'id': 'appendix-117',
  'group': 'neighbors, density and search',
  'title': 'kernel density',
  'lanes': ['kde'],
  'parts': ['train']},
 {'id': 'appendix-118',
  'group': 'neighbors, density and search',
  'title': 'kernel density with the cosine kernel under minkowski distance',
  'lanes': ['kde-cosine-minkowski'],
  'parts': ['train']},
 {'id': 'appendix-119',
  'group': 'neighbors, density and search',
  'title': 'kernel density with the Epanechnikov kernel under manhattan distance',
  'lanes': ['kde-epanechnikov-l1'],
  'parts': ['train']},
 {'id': 'appendix-120',
  'group': 'neighbors, density and search',
  'title': 'kernel density with the exponential kernel under chebyshev distance',
  'lanes': ['kde-exponential-chebyshev'],
  'parts': ['train']},
 {'id': 'appendix-121',
  'group': 'neighbors, density and search',
  'title': 'kernel density with the linear kernel under cosine distance',
  'lanes': ['kde-linear-cosine'],
  'parts': ['train']},
 {'id': 'appendix-122',
  'group': 'neighbors, density and search',
  'title': 'kernel density with the tophat kernel under squared euclidean distance',
  'lanes': ['kde-tophat-sqeuclidean'],
  'parts': ['train']},
 {'id': 'appendix-123',
  'group': 'neighbors, density and search',
  'title': 'weighted kernel density',
  'lanes': ['kde-weighted'],
  'parts': ['train']},
 {'id': 'appendix-124',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors',
  'lanes': ['knn'],
  'parts': ['train']},
 {'id': 'appendix-125',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors under chebyshev distance',
  'lanes': ['knn-chebyshev'],
  'parts': ['train']},
 {'id': 'appendix-126',
  'group': 'neighbors, density and search',
  'title': 'k-NN classifier',
  'lanes': ['knn-clf'],
  'parts': ['train']},
 {'id': 'appendix-127',
  'group': 'neighbors, density and search',
  'title': 'distance-weighted k-NN classifier',
  'lanes': ['knn-clf-distance'],
  'parts': ['train']},
 {'id': 'appendix-128',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors under cosine distance',
  'lanes': ['knn-cosine'],
  'parts': ['train']},
 {'id': 'appendix-129',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors under manhattan distance',
  'lanes': ['knn-manhattan'],
  'parts': ['train']},
 {'id': 'appendix-130',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors under minkowski distance at p 3',
  'lanes': ['knn-minkowski-p3'],
  'parts': ['train']},
 {'id': 'appendix-131',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors over the random ball cover',
  'lanes': ['knn-rbc'],
  'parts': ['train']},
 {'id': 'appendix-132',
  'group': 'neighbors, density and search',
  'title': 'k-NN regressor',
  'lanes': ['knn-reg'],
  'parts': ['train']},
 {'id': 'appendix-133',
  'group': 'neighbors, density and search',
  'title': 'distance-weighted k-NN regressor',
  'lanes': ['knn-reg-distance'],
  'parts': ['train']},
 {'id': 'appendix-134',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors under squared euclidean distance',
  'lanes': ['knn-sqeuclidean'],
  'parts': ['train']},
 {'id': 'appendix-135',
  'group': 'neighbors, density and search',
  'title': 'query-sharded kernel density',
  'lanes': ['par-queries-kde'],
  'parts': ['train']},
 {'id': 'appendix-136',
  'group': 'neighbors, density and search',
  'title': 'query-sharded k-NN classification',
  'lanes': ['par-queries-knn'],
  'parts': ['train']},
 {'id': 'appendix-137',
  'group': 'neighbors, density and search',
  'title': 'nearest neighbors over query shards',
  'lanes': ['par-queries-nn'],
  'parts': ['train']},
 {'id': 'appendix-138',
  'group': 'neighbors, density and search',
  'title': 'query-sharded radius neighbors',
  'lanes': ['par-queries-radius'],
  'parts': ['train']},
 {'id': 'appendix-139',
  'group': 'neighbors, density and search',
  'title': 'reference-sharded k-NN classification',
  'lanes': ['par-reference-knn'],
  'parts': ['train']},
 {'id': 'appendix-140',
  'group': 'neighbors, density and search',
  'title': 'reference-sharded k-NN regression',
  'lanes': ['par-reference-knn-reg'],
  'parts': ['train']},
 {'id': 'appendix-141',
  'group': 'neighbors, density and search',
  'title': 'radius neighbors',
  'lanes': ['radius'],
  'parts': ['train']},
 {'id': 'appendix-142',
  'group': 'neighbors, density and search',
  'title': 'radius neighbors under chebyshev distance',
  'lanes': ['radius-chebyshev'],
  'parts': ['train']},
 {'id': 'appendix-143',
  'group': 'neighbors, density and search',
  'title': 'radius neighbors under manhattan distance',
  'lanes': ['radius-manhattan'],
  'parts': ['train']},
 {'id': 'appendix-144',
  'group': 'neighbors, density and search',
  'title': 'radius neighbors under minkowski distance at p 3',
  'lanes': ['radius-minkowski-p3'],
  'parts': ['train']},
 {'id': 'appendix-145',
  'group': 'neighbors, density and search',
  'title': 'HDBSCAN approximate predict',
  'lanes': ['hdbscan'],
  'parts': ['infer'],
  'api': 'hdbscan.approximate_predict'},
 {'id': 'appendix-146',
  'group': 'neighbors, density and search',
  'title': 'HDBSCAN membership vector',
  'lanes': ['hdbscan'],
  'parts': ['infer'],
  'api': 'hdbscan.membership_vector'},
 {'id': 'appendix-147',
  'group': 'neighbors, density and search',
  'title': 'HDBSCAN all-points membership',
  'lanes': ['hdbscan'],
  'parts': ['infer'],
  'api': 'hdbscan.all_points_membership_vectors',
  'batch': 'n/a:fitted-dataset-memberships (no query batch)'},
 {'id': 'appendix-148',
  'group': 'linear models',
  'title': 'elasticnet',
  'lanes': ['elasticnet'],
  'parts': ['train']},
 {'id': 'appendix-149',
  'group': 'linear models',
  'title': 'elasticnet at the l2 end without an intercept',
  'lanes': ['elasticnet-l2end-no-intercept'],
  'parts': ['train']},
 {'id': 'appendix-150',
  'group': 'linear models',
  'title': 'kernel ridge',
  'lanes': ['kernel-ridge'],
  'parts': ['train']},
 {'id': 'appendix-151', 'group': 'linear models', 'title': 'lasso', 'lanes': ['lasso'], 'parts': ['train']},
 {'id': 'appendix-152',
  'group': 'linear models',
  'title': 'logistic regression',
  'lanes': ['logistic'],
  'parts': ['train']},
 {'id': 'appendix-153',
  'group': 'linear models',
  'title': 'elasticnet-penalized logistic regression',
  'lanes': ['logistic-elasticnet'],
  'parts': ['train']},
 {'id': 'appendix-154',
  'group': 'linear models',
  'title': 'l1-penalized logistic regression',
  'lanes': ['logistic-l1'],
  'parts': ['train']},
 {'id': 'appendix-155',
  'group': 'linear models',
  'title': 'multiclass logistic regression',
  'lanes': ['logistic-multiclass'],
  'parts': ['train']},
 {'id': 'appendix-156',
  'group': 'linear models',
  'title': 'unpenalized logistic regression without an intercept',
  'lanes': ['logistic-unpenalized-no-intercept'],
  'parts': ['train']},
 {'id': 'appendix-157',
  'group': 'linear models',
  'title': 'linear regression',
  'lanes': ['ols'],
  'parts': ['train']},
 {'id': 'appendix-158',
  'group': 'linear models',
  'title': 'linear regression without an intercept',
  'lanes': ['ols-no-intercept'],
  'parts': ['train']},
 {'id': 'appendix-159',
  'group': 'linear models',
  'title': 'weighted linear regression',
  'lanes': ['ols-weighted'],
  'parts': ['train']},
 {'id': 'appendix-160',
  'group': 'linear models',
  'title': 'coordinate descent over column shards',
  'lanes': ['par-cd'],
  'parts': ['train']},
 {'id': 'appendix-161',
  'group': 'linear models',
  'title': 'elastic net over column shards',
  'lanes': ['par-cd-elasticnet'],
  'parts': ['train']},
 {'id': 'appendix-162',
  'group': 'linear models',
  'title': 'Gram product over row shards',
  'lanes': ['par-gram'],
  'parts': ['train']},
 {'id': 'appendix-163',
  'group': 'linear models',
  'title': 'least squares over row-sharded Gram',
  'lanes': ['par-gram-ols'],
  'parts': ['train']},
 {'id': 'appendix-164',
  'group': 'linear models',
  'title': 'kernel ridge over tile shards',
  'lanes': ['par-kernel-ridge'],
  'parts': ['train']},
 {'id': 'appendix-165',
  'group': 'linear models',
  'title': 'logistic regression over row shards',
  'lanes': ['par-logistic'],
  'parts': ['train']},
 {'id': 'appendix-166', 'group': 'linear models', 'title': 'ridge', 'lanes': ['ridge'], 'parts': ['train']},
 {'id': 'appendix-167',
  'group': 'linear models',
  'title': 'ridge without an intercept',
  'lanes': ['ridge-no-intercept'],
  'parts': ['train']},
 {'id': 'appendix-168',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Gaussian process with an RBF kernel',
  'lanes': ['gp'],
  'parts': ['train']},
 {'id': 'appendix-169',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Gaussian process with a Matern kernel at nu 0.5',
  'lanes': ['gp-matern12'],
  'parts': ['train']},
 {'id': 'appendix-170',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Gaussian process with a Matern kernel at nu 1.5',
  'lanes': ['gp-matern32'],
  'parts': ['train']},
 {'id': 'appendix-171',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Gaussian process with an ARD Matern kernel at nu 2.5',
  'lanes': ['gp-matern52-ard'],
  'parts': ['train']},
 {'id': 'appendix-172',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Gaussian process with normalized targets',
  'lanes': ['gp-normalize-y'],
  'parts': ['train']},
 {'id': 'appendix-173',
  'group': 'kernel methods and Gaussian processes',
  'title': 'posterior draws from the Gaussian process',
  'lanes': ['gp-sample-y'],
  'parts': ['train']},
 {'id': 'appendix-174',
  'group': 'kernel methods and Gaussian processes',
  'title': 'posterior draws from the Gaussian process with normalized targets',
  'lanes': ['gp-sample-y-normalize'],
  'parts': ['train']},
 {'id': 'appendix-175',
  'group': 'kernel methods and Gaussian processes',
  'title': 'binary Gaussian process classifier',
  'lanes': ['gpc'],
  'parts': ['train']},
 {'id': 'appendix-176',
  'group': 'kernel methods and Gaussian processes',
  'title': 'one-vs-rest Gaussian process classifier',
  'lanes': ['gpc-multiclass'],
  'parts': ['train']},
 {'id': 'appendix-177',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Nystroem kernel approximation',
  'lanes': ['nystroem'],
  'parts': ['train']},
 {'id': 'appendix-178',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Gaussian process over tile shards',
  'lanes': ['par-gp'],
  'parts': ['train']},
 {'id': 'appendix-179',
  'group': 'kernel methods and Gaussian processes',
  'title': 'Nystroem over row shards',
  'lanes': ['par-nystroem'],
  'parts': ['train']},
 {'id': 'appendix-180',
  'group': 'kernel methods and Gaussian processes',
  'title': 'random Fourier features over row shards',
  'lanes': ['par-rbf-sampler'],
  'parts': ['train']},
 {'id': 'appendix-181',
  'group': 'kernel methods and Gaussian processes',
  'title': 'SVC over row shards',
  'lanes': ['par-svm'],
  'parts': ['train']},
 {'id': 'appendix-182',
  'group': 'kernel methods and Gaussian processes',
  'title': 'SVR over row shards',
  'lanes': ['par-svm-svr'],
  'parts': ['train']},
 {'id': 'appendix-183',
  'group': 'kernel methods and Gaussian processes',
  'title': 'random Fourier features',
  'lanes': ['rbf-sampler'],
  'parts': ['train']},
 {'id': 'appendix-184',
  'group': 'kernel methods and Gaussian processes',
  'title': 'SVC',
  'lanes': ['svc'],
  'parts': ['train']},
 {'id': 'appendix-185',
  'group': 'kernel methods and Gaussian processes',
  'title': 'linear SVC',
  'lanes': ['svc-linear'],
  'parts': ['train']},
 {'id': 'appendix-186',
  'group': 'kernel methods and Gaussian processes',
  'title': 'polynomial SVC',
  'lanes': ['svc-poly'],
  'parts': ['train']},
 {'id': 'appendix-187',
  'group': 'kernel methods and Gaussian processes',
  'title': 'SVR',
  'lanes': ['svr'],
  'parts': ['train']},
 {'id': 'appendix-188',
  'group': 'kernel methods and Gaussian processes',
  'title': 'linear SVR',
  'lanes': ['svr-linear'],
  'parts': ['train']},
 {'id': 'appendix-189',
  'group': 'decomposition and manifold',
  'title': 'PCA over row-sharded Gram',
  'lanes': ['par-gram-pca'],
  'parts': ['train']},
 {'id': 'appendix-190',
  'group': 'decomposition and manifold',
  'title': 'truncated SVD over row-sharded Gram',
  'lanes': ['par-gram-tsvd'],
  'parts': ['train']},
 {'id': 'appendix-191',
  'group': 'decomposition and manifold',
  'title': 'UMAP over graph shards',
  'lanes': ['par-graph-umap'],
  'parts': ['train']},
 {'id': 'appendix-192',
  'group': 'decomposition and manifold',
  'title': 'PCA',
  'lanes': ['pca'],
  'parts': ['train']},
 {'id': 'appendix-193',
  'group': 'decomposition and manifold',
  'title': 'whitened PCA through the full SVD',
  'lanes': ['pca-full-whiten'],
  'parts': ['train']},
 {'id': 'appendix-194',
  'group': 'decomposition and manifold',
  'title': 'whitened PCA',
  'lanes': ['pca-whiten'],
  'parts': ['train']},
 {'id': 'appendix-195',
  'group': 'decomposition and manifold',
  'title': 'truncated SVD',
  'lanes': ['tsvd'],
  'parts': ['train']},
 {'id': 'appendix-196',
  'group': 'decomposition and manifold',
  'title': 'UMAP',
  'lanes': ['umap'],
  'parts': ['train']},
 {'id': 'appendix-197',
  'group': 'preprocessing and resampling',
  'title': 'bootstrap',
  'lanes': ['bootstrap'],
  'parts': ['train']},
 {'id': 'appendix-198',
  'group': 'preprocessing and resampling',
  'title': 'min-max scaler',
  'lanes': ['minmax-scaler'],
  'parts': ['train']},
 {'id': 'appendix-199',
  'group': 'preprocessing and resampling',
  'title': 'clipped min-max scaler',
  'lanes': ['minmax-scaler-clip'],
  'parts': ['train']},
 {'id': 'appendix-200',
  'group': 'preprocessing and resampling',
  'title': 'Monte Carlo integration',
  'lanes': ['monte-carlo'],
  'parts': ['train']},
 {'id': 'appendix-201',
  'group': 'preprocessing and resampling',
  'title': 'resampling over draw shards',
  'lanes': ['par-resample'],
  'parts': ['train']},
 {'id': 'appendix-202',
  'group': 'preprocessing and resampling',
  'title': 'column-sharded standard scaler',
  'lanes': ['par-scaler'],
  'parts': ['train']},
 {'id': 'appendix-203',
  'group': 'preprocessing and resampling',
  'title': 'min-max scaler over column shards',
  'lanes': ['par-scaler-minmax'],
  'parts': ['train']},
 {'id': 'appendix-204',
  'group': 'preprocessing and resampling',
  'title': 'permutation test',
  'lanes': ['permutation-test'],
  'parts': ['train']},
 {'id': 'appendix-205',
  'group': 'preprocessing and resampling',
  'title': 'standard scaler',
  'lanes': ['standard-scaler'],
  'parts': ['train']},
 {'id': 'appendix-206',
  'group': 'preprocessing and resampling',
  'title': 'standard scaler without centering',
  'lanes': ['standard-scaler-no-mean'],
  'parts': ['train']},
 {'id': 'appendix-207',
  'group': 'preprocessing and resampling',
  'title': 'standard scaler without scaling',
  'lanes': ['standard-scaler-no-std'],
  'parts': ['train']},
 {'id': 'appendix-208', 'group': 'time series', 'title': 'ARIMA', 'lanes': ['arima'], 'parts': ['train']},
 {'id': 'appendix-209',
  'group': 'time series',
  'title': 'differenced ARIMA',
  'lanes': ['arima-011'],
  'parts': ['train']},
 {'id': 'appendix-210',
  'group': 'time series',
  'title': 'ARIMA with exogenous regressors',
  'lanes': ['arima-exog'],
  'parts': ['train']},
 {'id': 'appendix-211',
  'group': 'time series',
  'title': 'differenced seasonal ARIMA with exogenous regressors',
  'lanes': ['arima-exog-seasonal'],
  'parts': ['train']},
 {'id': 'appendix-212',
  'group': 'time series',
  'title': 'seasonal ARIMA',
  'lanes': ['arima-seasonal-c'],
  'parts': ['train']},
 {'id': 'appendix-213',
  'group': 'time series',
  'title': 'Holt-Winters',
  'lanes': ['holtwinters'],
  'parts': ['train']},
 {'id': 'appendix-214',
  'group': 'time series',
  'title': 'multiplicative Holt-Winters',
  'lanes': ['holtwinters-multiplicative'],
  'parts': ['train']},
 {'id': 'appendix-215',
  'group': 'time series',
  'title': 'KPSS stationarity test',
  'lanes': ['kpss'],
  'parts': ['train']},
 {'id': 'appendix-216',
  'group': 'time series',
  'title': 'series-sharded ARIMA',
  'lanes': ['par-arima'],
  'parts': ['train']},
 {'id': 'appendix-217',
  'group': 'time series',
  'title': 'series-sharded Holt-Winters',
  'lanes': ['par-holtwinters'],
  'parts': ['train']},
 {'id': 'appendix-218',
  'group': 'time series',
  'title': 'seasonal-difference selection',
  'lanes': ['select-d'],
  'parts': ['train'],
  'api': 'select_d',
  'limitation': 'The appendix label is imprecise: select_d chooses ordinary differencing d with '
                'caller-supplied seasonal D; automatic seasonal-D selection is not implemented.'},
 {'id': 'appendix-219',
  'group': 'linear algebra and metrics',
  'title': 'Cholesky factorization and solve',
  'lanes': ['cholesky'],
  'parts': ['train']},
 {'id': 'appendix-220',
  'group': 'linear algebra and metrics',
  'title': 'pinned GEMM',
  'lanes': ['gemm-pinned'],
  'parts': ['train']},
 {'id': 'appendix-221',
  'group': 'linear algebra and metrics',
  'title': 'transposed GEMM ops',
  'lanes': ['gemm-transposed'],
  'parts': ['train']},
 {'id': 'appendix-222',
  'group': 'linear algebra and metrics',
  'title': 'Cholesky over tile shards',
  'lanes': ['par-cholesky'],
  'parts': ['train']},
 {'id': 'appendix-223',
  'group': 'linear algebra and metrics',
  'title': 'accuracy score',
  'lanes': ['metrics'],
  'parts': ['train'],
  'api': 'metrics.accuracy_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-224',
  'group': 'linear algebra and metrics',
  'title': 'adjusted rand score',
  'lanes': ['metrics'],
  'parts': ['train'],
  'api': 'metrics.adjusted_rand_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-225',
  'group': 'linear algebra and metrics',
  'title': 'entropy',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.entropy',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-226',
  'group': 'linear algebra and metrics',
  'title': 'mutual info score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.mutual_info_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-227',
  'group': 'linear algebra and metrics',
  'title': 'homogeneity score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.homogeneity_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-228',
  'group': 'linear algebra and metrics',
  'title': 'completeness score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.completeness_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-229',
  'group': 'linear algebra and metrics',
  'title': 'v measure score',
  'lanes': ['metrics'],
  'parts': ['train'],
  'api': 'metrics.v_measure_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-230',
  'group': 'linear algebra and metrics',
  'title': 'r2 score',
  'lanes': ['metrics'],
  'parts': ['train'],
  'api': 'metrics.r2_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-231',
  'group': 'linear algebra and metrics',
  'title': 'silhouette score',
  'lanes': ['metrics'],
  'parts': ['train'],
  'api': 'metrics.silhouette_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-232',
  'group': 'linear algebra and metrics',
  'title': 'silhouette samples',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.silhouette_samples'},
 {'id': 'appendix-233',
  'group': 'linear algebra and metrics',
  'title': 'rand score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.rand_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-234',
  'group': 'linear algebra and metrics',
  'title': 'precision score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.precision_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-235',
  'group': 'linear algebra and metrics',
  'title': 'recall score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.recall_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-236',
  'group': 'linear algebra and metrics',
  'title': 'f1 score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.f1_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-237',
  'group': 'linear algebra and metrics',
  'title': 'log loss',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.log_loss',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-238',
  'group': 'linear algebra and metrics',
  'title': 'roc auc score',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.roc_auc_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-239',
  'group': 'linear algebra and metrics',
  'title': 'confusion matrix',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.confusion_matrix',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-240',
  'group': 'linear algebra and metrics',
  'title': 'precision recall curve',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.precision_recall_curve',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-241',
  'group': 'linear algebra and metrics',
  'title': 'mean squared error',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.mean_squared_error',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-242',
  'group': 'linear algebra and metrics',
  'title': 'mean absolute error',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.mean_absolute_error',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-243',
  'group': 'linear algebra and metrics',
  'title': 'root mean squared error',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.root_mean_squared_error',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-244',
  'group': 'linear algebra and metrics',
  'title': 'kl divergence',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.kl_divergence',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-245',
  'group': 'linear algebra and metrics',
  'title': 'trustworthiness',
  'lanes': ['metrics-classification'],
  'parts': ['train'],
  'api': 'metrics.trustworthiness',
  'batch': 'n/a:global-reduction (one result over the complete input)'},
 {'id': 'appendix-246',
  'group': 'linear algebra and metrics',
  'title': 'fowlkes mallows score',
  'lanes': ['metrics-fowlkes-mallows'],
  'parts': ['train'],
  'api': 'metrics.fowlkes_mallows_score',
  'batch': 'n/a:global-reduction (one result over the complete input)'}]
