# SPDX-License-Identifier: Apache-2.0
"""The IDENTICAL fatbin pass and its audit, on fake PTX and fake CUDA tools (no GPU, no CUDA)."""
from pathlib import Path
import stat
import struct
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import cubin_contract as cc  # noqa: E402

BODY = b"\tmul.rn.f32 %r4,%r2, %r3;\n" * 40
PTX89 = (b"//\n// Generated by LLVM NVPTX Back-End\n//\n\n.version 8.1\n.target sm_89\n"
         b".address_size 64\n\n.visible .entry k(\n)\n{\n" + BODY + b"\tret;\n}\n")


def fake_fatbin(sm, accel=False, kind=2, payload=24):
    """The header layout fatbinary 13.0 writes (measured 2026-09-26)."""
    entry = bytearray(64)
    struct.pack_into("<HHIQ", entry, 0, kind, 0x0101, 64, payload)
    struct.pack_into("<I", entry, 28, sm)
    struct.pack_into("<Q", entry, 40, 0x8011 | (cc._FATBIN_ARCH_SPECIFIC if accel else 0))
    body = bytes(entry) + b"\x28\xb5\x2f\xfd" + b"\x11" * (payload - 4)
    return cc._FATBIN_MAGIC + struct.pack("<HHQ", 1, 16, len(body)) + body


def blob(*mods):
    return b"\x7fELF\x02\x01\x01\x00" + b"\0" * 56 + b"\0".join(mods) + b"\0" + b"trailing\0"


def fake_tools(tmp_path, size=None):
    """ptxas and fatbinary stand-ins; the fatbin is `size` bytes (default: a small valid one)."""
    ptxas = tmp_path / "ptxas"
    ptxas.write_text(
        "#!/usr/bin/env python3\nimport sys\na = sys.argv[1:]\n"
        "if '--version' in a: print('Cuda compilation tools, release 13.0, fake'); sys.exit(0)\n"
        "assert '--fmad=false' in a, a\n"
        "open(a[a.index('-o') + 1], 'wb').write(b'CUBIN' + a[0].encode())\n")
    fat = tmp_path / "fatbinary"
    fat.write_text(
        "#!/usr/bin/env python3\nimport sys\nsys.path.insert(0, %r)\n" % str(HERE)
        + "import test_cubin_contract as t\na = sys.argv[1:]\n"
        "if '--version' in a: print('fatbinary 13.0, fake'); sys.exit(0)\n"
        "assert '--compress-all' in a, a\n"
        "spec = [x for x in a if x.startswith('--image3=')][0]\n"
        "sm = spec.split('sm=')[1].split(',')[0]\n"
        "img = t.fake_fatbin(int(sm.rstrip('a')), sm.endswith('a'))\n"
        f"size = {size!r}\n"
        "if size: img = img + b'\\x11' * (size - len(img))\n"
        "open([x for x in a if x.startswith('--create=')][0][9:], 'wb').write(img)\n")
    for p in (ptxas, fat):
        p.chmod(p.stat().st_mode | stat.S_IEXEC)
    return str(ptxas), str(fat)


def test_fatbin_header_arches():
    assert cc.fatbin_images(fake_fatbin(89), 0) == [(2, "sm_89")]
    assert cc.fatbin_images(fake_fatbin(90, accel=True), 0) == [(2, "sm_90a")]
    assert cc.fatbin_images(fake_fatbin(90), 0) == [(2, "sm_90")]
    assert cc.fatbin_images(b"\x7fELF" + b"\0" * 80, 0) is None


def test_patch_replaces_ptx_in_place_and_audit_passes(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89, PTX89))
    before = so.read_bytes()
    rows = cc.patch_files([so], *fake_tools(tmp_path), arch="sm_89")
    after = so.read_bytes()
    assert len(after) == len(before)
    assert rows[0]["modules"] == 2 and rows[0]["converted"] == 2
    assert not rows[0]["too_big"] and not rows[0]["left_ptx"]
    assert after.endswith(b"trailing\0")
    r = cc.audit_bytes(after, arch="sm_89")
    assert r["ptx_modules"] == 0 and r["fatbins"] == 2 and r["errors"] == []


def test_audit_refuses_ptx_wrong_arch_and_ptx_inside_a_fatbin():
    big = PTX89.replace(BODY, BODY * 10)
    r = cc.audit_bytes(blob(big, fake_fatbin(89)), arch="sm_89")
    assert any("JIT" in e for e in r["errors"])
    r = cc.audit_bytes(blob(fake_fatbin(90, accel=True)), arch="sm_89")
    assert any("architecture" in e for e in r["errors"])
    r = cc.audit_bytes(blob(fake_fatbin(89, kind=1)), arch="sm_89")
    assert any("non-ELF" in e for e in r["errors"])
    r = cc.audit_bytes(blob(b"nothing here"), arch="sm_89")
    assert any("no fatbin" in e for e in r["errors"])


def test_a_small_exact_module_may_stay_ptx(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89, PTX89.replace(BODY, BODY * 2)))
    rows = cc.patch_files([so], *fake_tools(tmp_path, size=len(PTX89) + 1))
    # the fatbin fits the larger module only; the small one stays PTX as JIT-invariant
    assert rows[0]["converted"] == 1 and len(rows[0]["left_ptx"]) == 1 and not rows[0]["too_big"]
    r = cc.audit_bytes(so.read_bytes(), arch="sm_89")
    assert r["ptx_modules"] == 1 and r["jit_invariant_ptx"] == 1 and r["errors"] == []


def test_a_leftover_with_an_approximate_op_is_refused(tmp_path):
    approx = PTX89.replace(b"\tret;", b"\tex2.approx.ftz.f32 %r1, %r2;\n\tret;")
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(approx))
    rows = cc.patch_files([so], *fake_tools(tmp_path, size=len(approx) + 1))
    assert len(rows[0]["too_big"]) == 1
    assert cc.audit_bytes(so.read_bytes(), arch="sm_89")["errors"]


def test_patch_refuses_a_module_of_another_arch(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89))
    try:
        cc.patch_files([so], *fake_tools(tmp_path), arch="sm_90a")
    except ValueError as e:
        assert "sm_89" in str(e)
    else:
        raise AssertionError("a module of another architecture was accepted")
