# SPDX-License-Identifier: Apache-2.0
"""The IDENTICAL PTX .rn pass and its audit, on small fake PTX (no GPU, no build)."""
import importlib.util
from pathlib import Path
import sys

import pytest

HERE = Path(__file__).resolve().parent
MATH = HERE.parent / "portable_math"
sys.path.insert(0, str(HERE))
import ptx_contract as pc  # noqa: E402

# The shape LLVM's NVPTX printer emits, byte for byte (tab, op, space, tab).
PTX = (b"//\n// Generated by LLVM NVPTX Back-End\n//\n\n.version 8.5\n.target sm_90a\n"
       b".address_size 64\n\n.visible .entry k(\n)\n{\n"
       b"\tmul.f32 \t%r4, %r2, %r3;\n"
       b"\tadd.f32 \t%r6, %r4, %r5;\n"
       b"\tsub.f32 \t%r8, %r7, %r4;\n"
       b"\tmul.f32 \t%r9, %r3, 0f33800000;\n"
       b"\tadd.f64 \t%rd13, %rd11, %rd12;\n"
       b"\tfma.rn.f32 \t%r10, %r2, %r3, %r4;\n"
       b"\tmul.rn.ftz.f32 \t%r11, %r10, %r9;\n"
       b"\tadd.s64 \t%rd2, %rd5, %rd6;\n"
       b"\tatom.acquire.sys.global.add.f32 \t%r12, [%rd1], 0f3F800000;\n"
       b"\tlg2.approx.ftz.f32 %r13, %r14;\n"
       b"\tret;\n}\n")


def blob(*modules):
    """A fake shared object: ELF-ish bytes with NUL-terminated PTX strings inside."""
    return b"\x7fELF" + b"\0" * 60 + b"\0".join(modules) + b"\0" + b"trailing\0"


def test_rewrite_is_length_preserving_and_complete():
    new, n = pc.rewrite_ptx(PTX)
    assert n == 5
    assert len(new) == len(PTX)
    assert pc.plain_ops(new) == []
    assert b"\nmul.rn.f32 %r4,%r2, %r3;\n" in new
    assert b"\nadd.rn.f64 %rd13,%rd11, %rd12;\n" in new
    # untouched: already rounded, integer, atomic, approximate
    for keep in (b"\tfma.rn.f32 \t%r10", b"\tmul.rn.ftz.f32 \t%r11", b"\tadd.s64 \t%rd2",
                 b"\tatom.acquire.sys.global.add.f32", b"\tlg2.approx.ftz.f32"):
        assert keep in new


def test_rewrite_is_idempotent():
    once, _ = pc.rewrite_ptx(PTX)
    twice, n = pc.rewrite_ptx(once)
    assert n == 0 and twice == once


def test_audit_names_every_plain_float_op():
    bad = pc.plain_ops(PTX)
    assert len(bad) == 5 and bad[0].startswith("mul.f32")
    for line in (b"\tfma.f32 \t%r1, %r2, %r3, %r4;\n", b"\t@%p1 add.f32 \t%r1, %r2, %r3;\n",
                 b"\tmul.ftz.f32 \t%r1, %r2, %r3;\n", b"\tadd.f16x2 \t%r1, %r2, %r3;\n",
                 b"\tmad.f32 \t%r1, %r2, %r3, %r4;\n"):
        assert len(pc.plain_ops(line)) == 1, line
    for line in (b"\tadd.rn.f32 \t%r1, %r2, %r3;\n", b"\tsub.rz.f64 \t%rd1, %rd2, %rd3;\n",
                 b"\tmul.rn.ftz.f32 \t%r1, %r2, %r3;\n", b"\tadd.s32 \t%r1, %r2, %r3;\n",
                 b"\tmul.wide.u32 \t%rd1, %r2, %r3;\n"):
        assert pc.plain_ops(line) == [], line


def test_patch_bytes_touches_only_ptx_and_keeps_size():
    other = PTX.replace(b"sm_90a", b"sm_89")
    data = blob(PTX, b"\tmul.f32 \tnot ptx, x, y;\n", other)
    new, n_mod, n_rw = pc.patch_bytes(data)
    assert (n_mod, n_rw) == (2, 10)
    assert len(new) == len(data)
    assert b"\tmul.f32 \tnot ptx, x, y;\n" in new     # outside any PTX module: left alone
    assert pc.audit_bytes(new)["plain_count"] == 0
    r = pc.audit_bytes(data)
    assert r["modules"] == 2 and r["plain_count"] == 10
    assert r["approx"] == {"lg2.approx.ftz.f32": 2}


def test_tree_scope_is_identical_cuda_only(tmp_path):
    for rel in ("mojolearn/cuda/sm_89/identical/_mojolearn.so",
                "mojolearn/cuda/sm_89/_mojolearn.so",               # FAST: not ours
                "mojolearn/cuda/sm_89/deterministic/_mojolearn.so",  # DETERMINISTIC: not ours
                "mojolearn/hip/gfx942/identical/_mojolearn.so"):     # AMD ships no PTX
        (tmp_path / rel).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / rel).write_bytes(blob(PTX))
    errors, rows = pc.audit_tree(tmp_path)
    assert len(errors) == 1 and "sm_89/identical/_mojolearn.so" in errors[0]
    assert [r["file"] for r in rows] == ["mojolearn/cuda/sm_89/identical/_mojolearn.so"]
    patched = pc.patch_tree(tmp_path)
    assert patched == [{"file": "mojolearn/cuda/sm_89/identical/_mojolearn.so", "modules": 1, "rewritten": 5}]
    assert pc.audit_tree(tmp_path)[0] == []
    assert (tmp_path / "mojolearn/cuda/sm_89/_mojolearn.so").read_bytes() == blob(PTX)


def test_cli_audit_exit_status(tmp_path, capsys):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX))
    sys.argv = ["ptx_contract.py", "audit", str(so)]
    assert pc.main() == 1
    sys.argv = ["ptx_contract.py", "patch", str(so)]
    assert pc.main() == 0
    sys.argv = ["ptx_contract.py", "audit", str(so)]
    assert pc.main() == 0


def test_wheel_audit_refuses_unpinned_identical_ptx(tmp_path):
    pytest.importorskip("lief")
    sys.path.insert(0, str(MATH))
    from stage import build
    spec = importlib.util.spec_from_file_location("math_wheel_audit_ptx", MATH / "wheel.py")
    audit = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(audit)
    build(tmp_path / ("libMojolearnMath.dylib" if sys.platform == "darwin" else "libMojolearnMath.so"))
    so = tmp_path / "mojolearn/cuda/sm_90a/identical/_mojolearn_gbdt.so"
    so.parent.mkdir(parents=True)
    so.write_bytes(b"not an ELF" + b"\0" + PTX + b"\0")
    with pytest.raises(ValueError, match="without a rounding modifier"):
        audit.audit_tree(tmp_path)
    pc.patch_file(so)
    # rounding pinned, but still PTX the driver would JIT: cubin_contract refuses it
    with pytest.raises(ValueError, match="no fatbin embedded"):
        audit.audit_tree(tmp_path)
    import test_cubin_contract as tcc
    so.write_bytes(b"not an ELF" + b"\0" + tcc.fake_fatbin(90, accel=True) + b"\0")
    report = audit.audit_tree(tmp_path)
    assert report["identical_ptx_rounding_pinned"] and report["identical_cuda_machine_code"]
    assert report["identical_ptx"][0]["plain_float_ops"] == 0
    assert report["identical_cuda_fatbins"][0]["arches"] == ["sm_90a"]
