# SPDX-License-Identifier: Apache-2.0
"""The IDENTICAL cubin pass and its audit, on fake PTX and a fake ptxas (no GPU, no CUDA)."""
from pathlib import Path
import stat
import struct
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import cubin_contract as cc  # noqa: E402

PTX89 = (b"//\n// Generated by LLVM NVPTX Back-End\n//\n\n.version 8.1\n.target sm_89\n"
         b".address_size 64\n\n.visible .entry k(\n)\n{\n" + b"\tmul.rn.f32 %r4,%r2, %r3;\n" * 40 + b"\tret;\n}\n")


def fake_cubin(sm, accel=False, abiver=7, size=96):
    """A minimal CUDA ELF header (the fields cubin_arch/cubin_size read)."""
    h = bytearray(size)
    h[0:8] = b"\x7fELF\x02\x01\x01\x33"
    h[8] = abiver
    struct.pack_into("<H", h, 18, 190)
    if abiver >= 8:
        flags = (sm << 8) | (0x8 if accel else 0)
    else:
        flags = sm | (0x800 if accel else 0)
    struct.pack_into("<I", h, 48, flags)
    return bytes(h)


def blob(*mods):
    return b"\x7fELF\x02\x01\x01\x00" + b"\0" * 56 + b"\0".join(mods) + b"\0" + b"trailing\0"


def fake_ptxas(tmp_path, size=96):
    """A ptxas stand-in: writes a fake sm_89 cubin of `size` bytes to -o."""
    p = tmp_path / "ptxas"
    p.write_text(
        "#!/usr/bin/env python3\n"
        "import sys, struct\n"
        "a = sys.argv[1:]\n"
        "if '--version' in a: print('Cuda compilation tools, release 13.0, fake'); sys.exit(0)\n"
        "assert '--fmad=false' in a, a\n"
        "arch = [x for x in a if x.startswith('-arch=')][0][6:]\n"
        f"h = bytearray({size}); h[0:8] = b'\\x7fELF\\x02\\x01\\x01\\x33'; h[8] = 7\n"
        "struct.pack_into('<H', h, 18, 190)\n"
        "sm = int(arch[3:].rstrip('a')); struct.pack_into('<I', h, 48, sm | (0x800 if arch.endswith('a') else 0))\n"
        "open(a[a.index('-o') + 1], 'wb').write(bytes(h))\n")
    p.chmod(p.stat().st_mode | stat.S_IEXEC)
    return str(p)


def test_cubin_arch_both_abi_layouts():
    assert cc.cubin_arch(fake_cubin(89)) == "sm_89"
    assert cc.cubin_arch(fake_cubin(90, accel=True)) == "sm_90a"
    assert cc.cubin_arch(fake_cubin(90, accel=True, abiver=8)) == "sm_90a"
    assert cc.cubin_arch(fake_cubin(89, abiver=8)) == "sm_89"
    # a host ELF (OSABI 0, x86-64) is not a cubin
    assert cc.cubin_arch(b"\x7fELF\x02\x01\x01\x00" + b"\0" * 60) is None


def test_patch_replaces_ptx_in_place_and_audit_passes(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89, PTX89))
    before = so.read_bytes()
    rows = cc.patch_files([so], fake_ptxas(tmp_path), arch="sm_89")
    after = so.read_bytes()
    assert len(after) == len(before)
    assert rows[0]["modules"] == 2 and rows[0]["converted"] == 2 and not rows[0]["too_big"]
    assert after.endswith(b"trailing\0")
    r = cc.audit_bytes(after, arch="sm_89")
    assert r["ptx_modules"] == 0 and r["cubins"] == 2 and r["errors"] == []


def test_audit_refuses_ptx_and_wrong_arch():
    r = cc.audit_bytes(blob(PTX89), arch="sm_89")
    assert r["ptx_modules"] == 1 and any("PTX" in e for e in r["errors"])
    r = cc.audit_bytes(blob(fake_cubin(90, accel=True)), arch="sm_89")
    assert any("architecture" in e for e in r["errors"])
    r = cc.audit_bytes(blob(b"nothing here"), arch="sm_89")
    assert any("no cubin" in e for e in r["errors"])


def test_a_cubin_larger_than_the_ptx_is_left_and_reported(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89))
    rows = cc.patch_files([so], fake_ptxas(tmp_path, size=len(PTX89) + 1))
    assert rows[0]["converted"] == 0 and len(rows[0]["too_big"]) == 1
    assert cc.audit_bytes(so.read_bytes())["ptx_modules"] == 1


def test_patch_refuses_a_module_of_another_arch(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89))
    try:
        cc.patch_files([so], fake_ptxas(tmp_path), arch="sm_90a")
    except ValueError as e:
        assert "sm_89" in str(e)
    else:
        raise AssertionError("a module of another architecture was accepted")
