# SPDX-License-Identifier: Apache-2.0
"""The IDENTICAL fatbin pass and its audit, on fake PTX and fake CUDA tools (no GPU, no CUDA)."""
from pathlib import Path
import stat
import struct
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import cubin_contract as cc  # noqa: E402

BODY = b"\tmul.rn.f32 %r4,%r2, %r3;\n" * 40
PTX89 = (b"//\n// Generated by LLVM NVPTX Back-End\n//\n\n.version 8.1\n.target sm_89\n"
         b".address_size 64\n\n.visible .entry k(\n)\n{\n" + BODY + b"\tret;\n}\n")


def fake_fatbin(sm, accel=False, kind=2, payload=24):
    """The header layout fatbinary 13.0 writes (measured 2026-09-26)."""
    entry = bytearray(64)
    struct.pack_into("<HHIQ", entry, 0, kind, 0x0101, 64, payload)
    struct.pack_into("<I", entry, 28, sm)
    struct.pack_into("<Q", entry, 40, 0x8011 | (cc._FATBIN_ARCH_SPECIFIC if accel else 0))
    body = bytes(entry) + b"\x28\xb5\x2f\xfd" + b"\x11" * (payload - 4)
    return cc._FATBIN_MAGIC + struct.pack("<HHQ", 1, 16, len(body)) + body


def blob(*mods):
    return b"\x7fELF\x02\x01\x01\x00" + b"\0" * 56 + b"\0".join(mods) + b"\0" + b"trailing\0"


def fake_tools(tmp_path, size=None):
    """ptxas and fatbinary stand-ins; the fatbin is `size` bytes (default: a small valid one)."""
    ptxas = tmp_path / "ptxas"
    ptxas.write_text(
        "#!/usr/bin/env python3\nimport sys\na = sys.argv[1:]\n"
        "if '--version' in a: print('Cuda compilation tools, release 13.0, fake'); sys.exit(0)\n"
        "assert '--fmad=false' in a, a\n"
        "open(a[a.index('-o') + 1], 'wb').write(b'CUBIN' + a[0].encode())\n")
    fat = tmp_path / "fatbinary"
    fat.write_text(
        "#!/usr/bin/env python3\nimport sys\nsys.path.insert(0, %r)\n" % str(HERE)
        + "import test_cubin_contract as t\na = sys.argv[1:]\n"
        "if '--version' in a: print('fatbinary 13.0, fake'); sys.exit(0)\n"
        "assert '--compress-all' in a, a\n"
        "spec = [x for x in a if x.startswith('--image3=')][0]\n"
        "sm = spec.split('sm=')[1].split(',')[0]\n"
        "img = t.fake_fatbin(int(sm.rstrip('a')), sm.endswith('a'))\n"
        f"size = {size!r}\n"
        "if size: img = img + b'\\x11' * (size - len(img))\n"
        "open([x for x in a if x.startswith('--create=')][0][9:], 'wb').write(img)\n")
    for p in (ptxas, fat):
        p.chmod(p.stat().st_mode | stat.S_IEXEC)
    return str(ptxas), str(fat)


def test_fatbin_header_arches():
    assert cc.fatbin_images(fake_fatbin(89), 0) == [(2, "sm_89")]
    assert cc.fatbin_images(fake_fatbin(90, accel=True), 0) == [(2, "sm_90a")]
    assert cc.fatbin_images(fake_fatbin(90), 0) == [(2, "sm_90")]
    assert cc.fatbin_images(b"\x7fELF" + b"\0" * 80, 0) is None


def mini_elf(strings, refs):
    """A minimal ELF64: one PT_LOAD over the whole file, a .text of `lea r8,[rip+X]`
    instructions (one per index in `refs`, reaching that string), then the
    NUL-terminated strings. Returns (bytes, text offset)."""
    text_off, n_lea = 0x200, len(refs)
    rod = text_off + 7 * n_lea + 9
    offs, body = [], b""
    for st in strings:
        offs.append(rod + len(body))
        body += st + b"\0"
    total = rod + len(body)
    h = bytearray(total)
    h[0:8] = b"\x7fELF\x02\x01\x01\x00"
    struct.pack_into("<HHIQQQIHHHHHH", h, 16, 3, 62, 1, 0, 64, 0x100, 0, 64, 56, 1, 64, 2, 0)
    struct.pack_into("<IIQQQQQQ", h, 64, 1, 5, 0, 0x1000, 0x1000, total, total, 0x1000)
    # section 1: .text, executable
    struct.pack_into("<IIQQQQIIQQ", h, 0x100 + 64, 0, 1, 0x6, 0x1000 + text_off, text_off, 7 * n_lea, 0, 0, 16, 0)
    for j, which in enumerate(refs):
        i = text_off + 7 * j
        h[i:i + 3] = b"\x4c\x8d\x05"
        struct.pack_into("<i", h, i + 3, (0x1000 + offs[which]) - (0x1000 + i + 7))
    h[rod:] = body
    return bytes(h), text_off


def test_patch_replaces_ptx_in_place_and_audit_passes(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89, PTX89))
    before = so.read_bytes()
    rows = cc.patch_files([so], *fake_tools(tmp_path), arch="sm_89")
    after = so.read_bytes()
    assert len(after) == len(before)
    assert rows[0]["modules"] == 2 and rows[0]["in_place"] == 2 and not rows[0]["unplaced"]
    assert after.endswith(b"trailing\0")
    r = cc.audit_bytes(after, arch="sm_89")
    assert r["ptx_modules"] == 0 and r["fatbins"] == 2 and r["errors"] == []


def test_a_module_too_big_in_place_is_moved_and_its_leas_repointed(tmp_path):
    big = PTX89.replace(BODY, BODY * 4)   # converts in place, leaves padding
    small = PTX89                          # its fatbin (forced large) must move
    data, text_off = mini_elf([big, small], refs=[0, 1, 1])
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(data)
    rows = cc.patch_files([so], *fake_tools(tmp_path, size=len(PTX89) + 64))
    assert rows[0]["in_place"] == 1 and rows[0]["moved"] == 1 and not rows[0]["unplaced"], rows
    after = so.read_bytes()
    assert cc.audit_bytes(after, arch="sm_89")["errors"] == []
    starts = {s for s, _ in cc.fatbins(after)}
    for j in range(3):   # every lea now reaches a fatbin start
        i = text_off + 7 * j
        (disp,) = struct.unpack_from("<i", after, i + 3)
        assert i + 7 + disp in starts
    # both leas of the moved module agree, and not with the in-place one
    d = [text_off + 7 * j + 7 + struct.unpack_from("<i", after, text_off + 7 * j + 3)[0] for j in range(3)]
    assert d[1] == d[2] != d[0]


def test_an_unplaceable_module_stays_ptx_only_if_jit_invariant(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89))
    rows = cc.patch_files([so], *fake_tools(tmp_path, size=len(PTX89) + 1))
    assert rows[0]["moved"] == 0 and len(rows[0]["unplaced"]) == 1
    assert rows[0]["unplaced"][0]["why"] == "no RIP-relative lea reaches it"
    assert rows[0]["unplaced"][0]["jit_invariant"]
    r = cc.audit_bytes(so.read_bytes() + fake_fatbin(89), arch="sm_89")
    assert r["jit_invariant_ptx"] == 1 and r["errors"] == []
    approx = PTX89.replace(b"\tret;", b"\tex2.approx.ftz.f32 %r1, %r2;\n\tret;")
    so.write_bytes(blob(approx))
    rows = cc.patch_files([so], *fake_tools(tmp_path, size=len(approx) + 1))
    assert not rows[0]["unplaced"][0]["jit_invariant"]
    assert cc.audit_bytes(so.read_bytes() + fake_fatbin(89), arch="sm_89")["errors"]


def test_audit_refuses_ptx_wrong_arch_and_ptx_inside_a_fatbin():
    r = cc.audit_bytes(blob(PTX89.replace(BODY, BODY * 10), fake_fatbin(89)), arch="sm_89")
    assert any("JIT" in e for e in r["errors"])
    r = cc.audit_bytes(blob(fake_fatbin(90, accel=True)), arch="sm_89")
    assert any("architecture" in e for e in r["errors"])
    r = cc.audit_bytes(blob(fake_fatbin(89, kind=1)), arch="sm_89")
    assert any("non-ELF" in e for e in r["errors"])
    r = cc.audit_bytes(blob(b"nothing here"), arch="sm_89")
    assert any("no fatbin" in e for e in r["errors"])


def test_patch_refuses_a_module_of_another_arch(tmp_path):
    so = tmp_path / "_mojolearn.so"
    so.write_bytes(blob(PTX89))
    try:
        cc.patch_files([so], *fake_tools(tmp_path), arch="sm_90a")
    except ValueError as e:
        assert "sm_89" in str(e)
    else:
        raise AssertionError("a module of another architecture was accepted")
