# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
"""THE DEPTH AND FEATURE-COUNT SWEEP of the CatBoost differential.

`NEXT_TWO.md` rung 5's second open item. `pixi run oracle` compares the port
against CatBoost at ONE depth (4) and ONE feature count (16), varying only
the border budget. Both of those are structural: depth decides how many
partitions the histogram helper carries and therefore when the subtraction
trick replaces a full pass, and feature count decides how the policy's
features are cut into four-feature blocks and how many blocks the multiplier
spreads over the document axis. Neither has ever been varied against
CatBoost.

Fifteen cells, five depths by three feature counts, generated by

    for d in 1 2 4 6 8; do for f in 8 16 32; do
      ORACLE_DEPTH=$d ORACLE_FEATS=$f \\
      ORACLE_OUT=bench/oracle_d${d}_f${f}.txt \\
      pixi run -e bench python tools/catboost_oracle.py \\
        > bench/oracle_d${d}_f${f}.json
    done; done

Everything else is the committed fixture's: 4096 rows, 12 trees, 15 borders,
learning rate 0.3, L2 3.0, Cosine, and every CatBoost feature this port
refuses pinned off. `bench/oracle_d4_f16.txt` is byte-identical to
`bench/oracle.txt`, which is the check that the environment plumbing changed
nothing at the defaults.

THIS DRIVER DOES NOT RAISE ON A DISAGREEING CELL, and that is deliberate.
`pixi run oracle` is the GATE; this is a MATRIX, and a matrix that stops at
its first red cell reports one number instead of fifteen. Every cell is
printed at full strength whether it agrees or not
([[no-dataset-cherry-picking]]: a cell is never dropped, deferred or retuned
for disagreeing). It exits non-zero at the end if any cell disagreed, so it
is still usable as a check.

WHAT A DISAGREEMENT MEANS HERE, and it is worth reading before the output.
The tree is a greedy argmax over scores, so two faithful implementations can
diverge at a genuine TIE and never reconverge, and one differing split at
depth 0 makes every level below it incomparable. That is why the first
divergence is printed as (tree, depth) rather than only a total: the depth at
which the two first disagree is the number that means something, and a low
match count under a late first divergence is arithmetic rather than a second
finding.
"""

from mojo_only.oracle_check import tree_structure_diff


def main() raises:
    var depths = List[Int]()
    depths.append(1)
    depths.append(2)
    depths.append(4)
    depths.append(6)
    depths.append(8)

    var feats = List[Int]()
    feats.append(8)
    feats.append(16)
    feats.append(32)

    print(
        "THE CATBOOST DIFFERENTIAL OVER DEPTH x FEATURE COUNT, both"
        " searchers."
    )
    print(
        "4096 rows, 12 trees, 15 borders (half-byte policy), Cosine, lr 0.3,"
        " L2 3.0."
    )
    print()
    print(
        "  depth feats | greedy match  first div |"
        " pointwise match  first div | our mse (greedy)   CatBoost mse"
    )

    var disagreeing = 0
    var cells = 0
    for di in range(len(depths)):
        for fi in range(len(feats)):
            var d = depths[di]
            var f = feats[fi]
            var path = (
                String("bench/oracle_d")
                + String(d)
                + "_f"
                + String(f)
                + ".txt"
            )
            var g = tree_structure_diff(path, False, False, False)
            var p = tree_structure_diff(path, True, False, False)
            cells += 2
            if g.matched != g.compared:
                disagreeing += 1
            if p.matched != p.compared:
                disagreeing += 1

            var line = String("  ")
            line += String(d) + "     " + String(f) + "    | "
            line += String(g.matched) + "/" + String(g.compared) + "  "
            if g.first_divergence >= 0:
                line += (
                    "t"
                    + String(g.first_divergence // 100)
                    + "d"
                    + String(g.first_divergence % 100)
                )
            else:
                line += "-"
            line += " | "
            line += String(p.matched) + "/" + String(p.compared) + "  "
            if p.first_divergence >= 0:
                line += (
                    "t"
                    + String(p.first_divergence // 100)
                    + "d"
                    + String(p.first_divergence % 100)
                )
            else:
                line += "-"
            line += " | "
            print(line, g.our_mse, "  ", g.their_mse)
            # THE POINTWISE ARM'S LOSS TOO, on its own line, because the two
            # searchers are bit-identical only while they agree and a cell
            # where they do not is exactly the cell whose two losses have to
            # be readable side by side.
            if p.our_mse != g.our_mse:
                print(
                    "                     pointwise mse", p.our_mse,
                    "differs from greedy", g.our_mse,
                )

    # ------------------------------------------------------------------
    # THE ONE-BYTE ACCUMULATORS AT DEPTH 8, which is the cell the two
    # sweeps above leave empty. The four bit-width fixtures
    # (`pixi run oracle`) are all at depth 4, and the matrix above is all at
    # 15 borders, so the HALF-BYTE kernel is the only one that has ever run
    # at a depth other than 4. Depth is what decides when the histogram
    # helper stops doing full passes and starts recovering a sibling by
    # SUBTRACTION, and the 8-bit accumulator is the one holding Int32 fixed
    # point (DEVIATION 93) -- a subtraction of two quantized histograms is
    # exactly where that representation would show, and nothing had asked
    # it to.
    print()
    print("  the four one-byte accumulators at DEPTH 8, 16 features:")
    var borders = List[Int]()
    borders.append(24)
    borders.append(48)
    borders.append(100)
    borders.append(254)
    var widths = List[Int]()
    widths.append(5)
    widths.append(6)
    widths.append(7)
    widths.append(8)
    for bi in range(len(borders)):
        var path8 = (
            String("bench/oracle_d8_b") + String(borders[bi]) + ".txt"
        )
        var g8 = tree_structure_diff(path8, False, False, False)
        var p8 = tree_structure_diff(path8, True, False, False)
        cells += 2
        if g8.matched != g8.compared:
            disagreeing += 1
        if p8.matched != p8.compared:
            disagreeing += 1
        var l8 = String("  ") + String(widths[bi]) + "bit  " + String(
            borders[bi]
        ) + " borders | "
        l8 += String(g8.matched) + "/" + String(g8.compared) + " greedy, "
        l8 += String(p8.matched) + "/" + String(
            p8.compared
        ) + " pointwise | "
        if g8.first_divergence >= 0 or p8.first_divergence >= 0:
            l8 += (
                "first div greedy "
                + String(g8.first_divergence)
                + " pointwise "
                + String(p8.first_divergence)
            )
        else:
            l8 += "no divergence"
        print(l8, g8.our_mse, "  ", g8.their_mse)

    print()
    print(
        "  cells:", cells, " disagreeing:", disagreeing,
        " (a cell is one fixture on one searcher)",
    )

    # ------------------------------------------------------------------
    # THE SABOTAGE, run at EVERY cell rather than once.
    #
    # [[sabotage-when-required]]: the path is new -- no depth but 4 and no
    # feature count but 16 has ever been compared against CatBoost -- and a
    # green matrix cannot distinguish "every split matches" from "the
    # comparison stopped happening at these parameters". Fifteen cells of
    # 96/96 with nothing checking them is exactly the shape of a check that
    # went quiet.
    #
    # Moving the EXPECTED bin of tree 0 depth 0 up by one must cost exactly
    # one match and put the first divergence at (0, 0), per cell. A
    # comparison that is reached but not POSITIONED -- one that tallies
    # totals, or that compares the tree as a set of splits -- passes the
    # green run above and passes this too, so the sharp expectation is the
    # point.
    print()
    print("  SABOTAGE: expected bin of tree 0 depth 0 moved up by one.")
    var sabotage_bad = 0
    for di in range(len(depths)):
        for fi in range(len(feats)):
            var d = depths[di]
            var f = feats[fi]
            var path = (
                String("bench/oracle_d")
                + String(d)
                + "_f"
                + String(f)
                + ".txt"
            )
            var sg = tree_structure_diff(path, False, False, False, True)
            var want_matched = sg.compared - 1
            if sg.matched != want_matched or sg.first_divergence != 0:
                print(
                    "  FAIL depth", d, "feats", f, ": sabotaged run gave",
                    sg.matched, "of", sg.compared, "with first divergence",
                    sg.first_divergence, "; expected", want_matched,
                    "and 0, so this cell's comparison is not positioned",
                )
                sabotage_bad += 1
    if sabotage_bad != 0:
        raise Error(
            String(sabotage_bad)
            + " cell(s) did not move under the sabotage, so their green"
            " result above is not evidence"
        )
    print(
        "  every cell lost exactly one match at exactly (tree 0, depth 0),"
        " so every cell's comparison is live and positioned"
    )
    if disagreeing != 0:
        raise Error(
            String(disagreeing)
            + " of "
            + String(cells)
            + " sweep cells do not reproduce CatBoost's trees. Read the"
            " matrix above: the FIRST DIVERGENCE column is the finding and"
            " the match count below it is arithmetic"
        )
    print("  every cell reproduces CatBoost's trees split for split")
