# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
"""The PairLogit pairs on the host: generation, validation and the per-row
layout, shared by the device target (`gbdt/targets/kernel/pair_logit.mojo`),
`gbdt/train.mojo::train` and the host oracle (`gbdt/host/gbdt_oracle_pair.mojo`).

GPU-FREE. Nothing here imports `max.gpu` or `max.gpu`, so the GBDT host binding,
which builds with no accelerator target, can import it.

GENERATION is the CatBoost reference's default path, `GenerateBruteForce`
(`private/libs/pairs/util.cpp:14-40`), which `GeneratePairLogitPairs` takes when
`max_pairs` is left at `MAX_AUTOGENERATED_PAIRS_COUNT` (`:113-118`): for each
query, rows in index order, `first < second`, equal grades skipped, the higher
grade the winner, every pair weighted by the group weight, which is the weight
of the query's first row (`data_providers.cpp:841-844` hands the learn weights;
unit without them). No random stream is read on this path. A query whose pair
count exceeds `MAX_PAIR_COUNT_ON_GPU` is refused in the reference's words
(`util.cpp:116-117`, `util.h:13`).

THE ORDER THE DEVICE SEES. The reference files each pair under its winner's
`Competitors` in generation order (`data_providers.cpp:316-331`) and flattens
them query by query, winner row by winner row (`gpu_data/samples_grouping.h:
79-101`). `order_pairs_by_winner` produces that order from any pair list, the
generated one included.
"""

#: `MAX_PAIR_COUNT_ON_GPU` (`private/libs/pairs/util.h:13`)
comptime MAX_PAIR_COUNT_ON_GPU = 1022 * 1023 // 2

#: pair indices ride in an endpoint code shifted left by one
comptime PAIR_LOGIT_MAX_PAIRS = 0x7FFFFFFF


@fieldwise_init
struct PairList(Movable):
    """Pairs as three parallel lists: winner row, loser row, weight."""

    var winners: List[UInt32]
    var losers: List[UInt32]
    var weights: List[Float32]


def generate_pairs(
    group_sizes: List[UInt32],
    targets: List[Float32],
    row_weights: List[Float32],
) raises -> PairList:
    """`GenerateBruteForce` over every query (see the module docstring).
    `row_weights` empty means unit weights."""
    # `GeneratePairs`' own check (`data_providers.cpp:251-255`): training takes
    # it with `skipMinMaxPairsCheck` false
    var constant = True
    for i in range(1, len(targets)):
        if targets[i] != targets[0]:
            constant = False
            break
    if constant:
        raise Error("Target data is constant. Cannot generate pairs.")
    var winners = List[UInt32]()
    var losers = List[UInt32]()
    var weights = List[Float32]()
    var begin = 0
    for q in range(len(group_sizes)):
        var size = Int(group_sizes[q])
        var end = begin + size
        # `pairCount` over the grade counts (`util.cpp:106-112`)
        var pair_count = UInt64(0)
        for i in range(begin, end):
            for j in range(i + 1, end):
                if targets[i] != targets[j]:
                    pair_count += UInt64(1)
        if pair_count > UInt64(MAX_PAIR_COUNT_ON_GPU):
            raise Error(
                "Too many pairs should be generated for group: "
                + String(pair_count)
                + " , use max_pairs option to limit generated pair count"
            )
        var group_weight = Float32(1.0)
        if len(row_weights) > 0:
            group_weight = row_weights[begin]
        for first in range(begin, end):
            for second in range(first + 1, end):
                if targets[first] == targets[second]:
                    continue
                if targets[first] > targets[second]:
                    winners.append(UInt32(first))
                    losers.append(UInt32(second))
                else:
                    winners.append(UInt32(second))
                    losers.append(UInt32(first))
                weights.append(group_weight)
        begin = end
    return PairList(winners^, losers^, weights^)


def order_pairs_by_winner(pairs: PairList, group_sizes: List[UInt32], n_rows: Int) raises -> PairList:
    """The device order: query by query, winner row by winner row, each
    winner's pairs in their given order. Also checks that every pair's rows
    lie in one query, the reference's raw target data check."""
    var n_pairs = len(pairs.winners)
    var query_of = List[Int](length=n_rows, fill=0)
    var at = 0
    for q in range(len(group_sizes)):
        for k in range(Int(group_sizes[q])):
            query_of[at + k] = q
        at += Int(group_sizes[q])
    var counts = List[Int](length=n_rows + 1, fill=0)
    for p in range(n_pairs):
        var a = Int(pairs.winners[p])
        var b = Int(pairs.losers[p])
        if a >= n_rows or b >= n_rows:
            raise Error("pairs: pair " + String(p) + " names a row outside the pool")
        if query_of[a] != query_of[b]:
            raise Error(
                "pairs: pair " + String(p) + " joins rows of two groups; a"
                " pair's winner and loser must belong to the same group"
            )
        counts[a + 1] += 1
    for r in range(n_rows):
        counts[r + 1] += counts[r]
    var cursor = List[Int](length=n_rows, fill=0)
    for r in range(n_rows):
        cursor[r] = counts[r]
    var winners = List[UInt32](length=n_pairs, fill=UInt32(0))
    var losers = List[UInt32](length=n_pairs, fill=UInt32(0))
    var weights = List[Float32](length=n_pairs, fill=Float32(0.0))
    for p in range(n_pairs):
        var a = Int(pairs.winners[p])
        var dst = cursor[a]
        winners[dst] = pairs.winners[p]
        losers[dst] = pairs.losers[p]
        weights[dst] = pairs.weights[p]
        cursor[a] += 1
    return PairList(winners^, losers^, weights^)


@fieldwise_init
struct PairPrep(Movable):
    """Per-row endpoint offsets and codes, the per-row pair weights folded in
    endpoint order, and the total pair weight."""

    var offsets: List[UInt32]
    var codes: List[UInt32]
    var row_weights: List[Float32]
    var total: Float64


def prepare_pairs(
    winners: List[UInt32],
    losers: List[UInt32],
    pair_weights: List[Float32],
    n_rows: Int,
) raises -> PairPrep:
    """Endpoint lists in increasing pair index per row (a winner's code
    `pair << 1`, a loser's `pair << 1 | 1`), the per-row pair weights as
    `MakePairWeightsImpl` accumulates them in that pinned order, and
    `PairsTotalWeight`, refused when not positive in the reference's words
    (`querywise_targets_impl.h:340-342`)."""
    var n_pairs = len(winners)
    if len(losers) != n_pairs or len(pair_weights) != n_pairs:
        raise Error("PairLogit: winners, losers and pair weights disagree in length")
    if n_pairs < 1:
        # no pairs at all: their `PairsTotalWeight` is the dot product of an
        # empty buffer, 0, and `InitPairLogit` raises the weight sentence
        raise Error(
            "Observation weights should be greater or equal zero. Total weight"
            " should be greater, than zero"
        )
    if n_pairs > PAIR_LOGIT_MAX_PAIRS:
        raise Error("PairLogit: more than 2**31 - 1 pairs")
    var counts = List[Int](length=n_rows + 1, fill=0)
    for p in range(n_pairs):
        var a = Int(winners[p])
        var b = Int(losers[p])
        if a >= n_rows or b >= n_rows:
            raise Error("PairLogit: pair " + String(p) + " names a row outside the pool")
        if a == b:
            raise Error("PairLogit: pair " + String(p) + " pairs a row with itself")
        counts[a + 1] += 1
        counts[b + 1] += 1
    var offsets = List[UInt32](length=n_rows + 1, fill=UInt32(0))
    for r in range(n_rows):
        counts[r + 1] += counts[r]
        offsets[r + 1] = UInt32(counts[r + 1])
    var cursor = List[Int](length=n_rows, fill=0)
    for r in range(n_rows):
        cursor[r] = counts[r]
    var codes = List[UInt32](length=2 * n_pairs, fill=UInt32(0))
    for p in range(n_pairs):
        var a = Int(winners[p])
        var b = Int(losers[p])
        codes[cursor[a]] = UInt32(p) << UInt32(1)
        cursor[a] += 1
        codes[cursor[b]] = (UInt32(p) << UInt32(1)) | UInt32(1)
        cursor[b] += 1
    var row_weights = List[Float32](length=n_rows, fill=Float32(0.0))
    for r in range(n_rows):
        var acc = Float32(0.0)
        for k in range(Int(offsets[r]), Int(offsets[r + 1])):
            acc = acc + pair_weights[Int(codes[k] >> UInt32(1))]
        row_weights[r] = acc
    var total = Float64(0.0)
    for p in range(n_pairs):
        total = total + Float64(pair_weights[p])
    if not (total > 0.0):
        raise Error(
            "Observation weights should be greater or equal zero. Total weight"
            " should be greater, than zero"
        )
    return PairPrep(offsets^, codes^, row_weights^, total)
