# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""THE NEIGHBORS EXPANSION LANE'S GPU BINDING (docs/lanes/ALGORITHM_EXPANSION_BRIEFS.md):
every export is xn_<op>(addresses, ints, floats) over x_neighbors/device_ops.mojo."""
from std.os import abort
from std.python import Python, PythonObject
from std.python._cpython import GILReleased
from std.python.bindings import PythonModuleBuilder
from checks.numerics import GLOBAL_NUMERIC_MODE
from x_neighbors.eigh import op_eigh
from checks.vendor import COMPILED_VENDOR
from x_neighbors.device_ops import op_sqdist, op_nan_sqdist, op_l1dist, op_kernel, op_matmul, op_rowsum, op_colsum, op_unary, op_knn_select, op_knn_sq, op_group_mean, op_take_rows, op_take_cols, op_variance, op_ocsvm, op_lof_lrd, op_lof_score, op_kpca_center, op_scale_div, op_svd_flip, op_kpca_alpha_scale, op_nc_std, op_nc_shrink, op_nc_decision, op_softmax, op_log_softmax, op_pcs, op_achi2, op_skew_weights, op_skew_transform, op_absdiff_sum, op_row_normalize, op_lp_clamp, op_ls_clamp, op_ls_laplacian, op_knn_graph, op_knn_impute, op_pagerank_step, op_cc_step, op_louvain, op_svgp, op_svgp_var


def _a(v: PythonObject, k: Int) raises -> Int:
    var x = Int(py=v[k])
    if x == 0:
        raise Error("x_neighbors: null buffer address")
    return x


def _n(v: PythonObject, k: Int) raises -> Int:
    var x = Int(py=v[k])
    if x < 0:
        raise Error("x_neighbors: a negative size was passed")
    return x


def _f(v: PythonObject, k: Int) raises -> Float32:
    return Float32(Float64(py=v[k]))


def eigh_binding(a: PythonObject, i: PythonObject, f: PythonObject) raises -> PythonObject:
    var x = _a(a, 0)
    var w = _a(a, 1)
    var v = _a(a, 2)
    var n = _n(i, 0)
    if n <= 0:
        raise Error("x_neighbors: eigh needs n >= 1")
    var sweeps = 0
    with GILReleased(Python()):
        sweeps = op_eigh(x, n, w, v)
    return PythonObject(sweeps)


def x_neighbors_numeric_mode_binding() raises -> PythonObject:
    return PythonObject(Int(GLOBAL_NUMERIC_MODE))


def sqdist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_sqdist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def nan_sqdist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_nan_sqdist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def l1dist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_l1dist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def kernel_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_kind = _n(i_, 3)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    var v_degree = _n(i_, 4)
    with GILReleased(Python()):
        op_kernel(v_x, v_y, v_res, v_n, v_m, v_d, v_kind, v_gamma, v_coef0, v_degree)
    return PythonObject(None)


def matmul_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_b = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_k = _n(i_, 1)
    var v_m = _n(i_, 2)
    with GILReleased(Python()):
        op_matmul(v_a, v_b, v_res, v_n, v_k, v_m)
    return PythonObject(None)


def rowsum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_rowsum(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def colsum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_colsum(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def unary_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_op = _n(i_, 1)
    var v_a = _f(f_, 0)
    var v_b = _f(f_, 1)
    with GILReleased(Python()):
        op_unary(v_x, v_res, v_count, v_op, v_a, v_b)
    return PythonObject(None)


def knn_select_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dmat = _a(a_, 0)
    var v_dist = _a(a_, 1)
    var v_idx = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    var v_exclude_self = _n(i_, 3)
    with GILReleased(Python()):
        op_knn_select(v_dmat, v_dist, v_idx, v_n, v_m, v_k, v_exclude_self)
    return PythonObject(None)


def knn_sq_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_dist = _a(a_, 2)
    var v_idx = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_exclude_self = _n(i_, 4)
    with GILReleased(Python()):
        op_knn_sq(v_x, v_y, v_dist, v_idx, v_n, v_m, v_d, v_k, v_exclude_self)
    return PythonObject(None)


def group_mean_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_labels = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_g = _n(i_, 2)
    with GILReleased(Python()):
        op_group_mean(v_x, v_labels, v_res, v_n, v_d, v_g)
    return PythonObject(None)


def take_rows_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_rows = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n_out = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_src = _n(i_, 2)
    with GILReleased(Python()):
        op_take_rows(v_src, v_rows, v_res, v_n_out, v_d, v_n_src)
    return PythonObject(None)


def take_cols_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_cols = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_src_c = _n(i_, 1)
    var v_c = _n(i_, 2)
    with GILReleased(Python()):
        op_take_cols(v_src, v_cols, v_res, v_n, v_src_c, v_c)
    return PythonObject(None)


def variance_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_variance(v_x, v_res, v_count)
    return PythonObject(None)


def ocsvm_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_cv = _a(a_, 1)
    var v_alpha = _a(a_, 2)
    var v_info = _a(a_, 3)
    var v_iters = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_eps = _f(f_, 0)
    var v_max_iter = _n(i_, 1)
    with GILReleased(Python()):
        op_ocsvm(v_q, v_cv, v_alpha, v_info, v_iters, v_n, v_eps, v_max_iter)
    return PythonObject(None)


def lof_lrd_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dist = _a(a_, 0)
    var v_idx = _a(a_, 1)
    var v_fit_dist = _a(a_, 2)
    var v_lrd = _a(a_, 3)
    var v_k = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_n_fit = _n(i_, 2)
    with GILReleased(Python()):
        op_lof_lrd(v_dist, v_idx, v_fit_dist, v_lrd, v_k, v_n, v_n_fit)
    return PythonObject(None)


def lof_score_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_idx = _a(a_, 0)
    var v_fit_lrd = _a(a_, 1)
    var v_lrd = _a(a_, 2)
    var v_score = _a(a_, 3)
    var v_k = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_n_fit = _n(i_, 2)
    with GILReleased(Python()):
        op_lof_score(v_idx, v_fit_lrd, v_lrd, v_score, v_k, v_n, v_n_fit)
    return PythonObject(None)


def kpca_center_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_k = _a(a_, 0)
    var v_fit_cols = _a(a_, 1)
    var v_pred_rows = _a(a_, 2)
    var v_fit_all = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_kpca_center(v_k, v_fit_cols, v_pred_rows, v_fit_all, v_res, v_n, v_m)
    return PythonObject(None)


def scale_div_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_s = _f(f_, 0)
    with GILReleased(Python()):
        op_scale_div(v_x, v_res, v_count, v_s)
    return PythonObject(None)


def svd_flip_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_v = _a(a_, 0)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_svd_flip(v_v, v_n, v_c)
    return PythonObject(None)


def kpca_alpha_scale_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_v = _a(a_, 0)
    var v_w = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    var v_divide = _n(i_, 2)
    with GILReleased(Python()):
        op_kpca_alpha_scale(v_v, v_w, v_res, v_n, v_c, v_divide)
    return PythonObject(None)


def nc_std_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_cent = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_std(v_x, v_lab, v_cent, v_std, v_n, v_d, v_n_classes)
    return PythonObject(None)


def nc_shrink_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_nk = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_devs = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    var v_do_shrink = _n(i_, 3)
    var v_med = _f(f_, 0)
    var v_shrink = _f(f_, 1)
    with GILReleased(Python()):
        op_nc_shrink(v_x, v_cent, v_nk, v_std, v_res, v_devs, v_n, v_d, v_n_classes, v_do_shrink, v_med, v_shrink)
    return PythonObject(None)


def nc_decision_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_std = _a(a_, 2)
    var v_prior = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_decision(v_q, v_cent, v_std, v_prior, v_res, v_n, v_d, v_n_classes)
    return PythonObject(None)


def softmax_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_softmax(v_x, v_res, v_n, v_c)
    return PythonObject(None)


def log_softmax_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_log_softmax(v_x, v_res, v_n, v_c)
    return PythonObject(None)


def pcs_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_hidx = _a(a_, 1)
    var v_hbit = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d_in = _n(i_, 1)
    var v_nf = _n(i_, 2)
    var v_nc = _n(i_, 3)
    var v_degree = _n(i_, 4)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    with GILReleased(Python()):
        op_pcs(v_x, v_hidx, v_hbit, v_res, v_n, v_d_in, v_nf, v_nc, v_degree, v_gamma, v_coef0)
    return PythonObject(None)


def achi2_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_steps = _n(i_, 2)
    var v_interval = _f(f_, 0)
    with GILReleased(Python()):
        op_achi2(v_x, v_res, v_n, v_d, v_steps, v_interval)
    return PythonObject(None)


def skew_weights_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_z = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_skew_weights(v_z, v_res, v_count)
    return PythonObject(None)


def skew_transform_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_lx = _a(a_, 0)
    var v_w = _a(a_, 1)
    var v_off = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_nc = _n(i_, 2)
    with GILReleased(Python()):
        op_skew_transform(v_lx, v_w, v_off, v_res, v_n, v_d, v_nc)
    return PythonObject(None)


def absdiff_sum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_b = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_absdiff_sum(v_a, v_b, v_res, v_count)
    return PythonObject(None)


def row_normalize_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_row_normalize(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def lp_clamp_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_ld = _a(a_, 0)
    var v_ystatic = _a(a_, 1)
    var v_unlabeled = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_lp_clamp(v_ld, v_ystatic, v_unlabeled, v_res, v_n, v_c)
    return PythonObject(None)


def ls_clamp_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_ld = _a(a_, 0)
    var v_ystatic = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_count = _n(i_, 0)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_ls_clamp(v_ld, v_ystatic, v_res, v_count, v_alpha)
    return PythonObject(None)


def ls_laplacian_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_ls_laplacian(v_a, v_res, v_n)
    return PythonObject(None)


def knn_graph_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_idx = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    with GILReleased(Python()):
        op_knn_graph(v_idx, v_res, v_n, v_m, v_k)
    return PythonObject(None)


def knn_impute_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_fx = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_weights = _n(i_, 4)
    with GILReleased(Python()):
        op_knn_impute(v_x, v_fx, v_res, v_n, v_m, v_d, v_k, v_weights)
    return PythonObject(None)


def pagerank_step_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_x = _a(a_, 1)
    var v_p = _a(a_, 2)
    var v_dw = _a(a_, 3)
    var v_dangling = _a(a_, 4)
    var v_res = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_pagerank_step(v_q, v_x, v_p, v_dw, v_dangling, v_res, v_n, v_alpha)
    return PythonObject(None)


def cc_step_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_cc_step(v_a, v_lab, v_res, v_n)
    return PythonObject(None)


def louvain_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_labels = _a(a_, 1)
    var v_info = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_max_level = _n(i_, 1)
    var v_resolution = _f(f_, 0)
    var v_threshold = _f(f_, 1)
    with GILReleased(Python()):
        op_louvain(v_a, v_labels, v_info, v_n, v_max_level, v_resolution, v_threshold)
    return PythonObject(None)


def svgp_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_kuu = _a(a_, 0)
    var v_bmat = _a(a_, 1)
    var v_b = _a(a_, 2)
    var v_y = _a(a_, 3)
    var v_alpha = _a(a_, 4)
    var v_cmat = _a(a_, 5)
    var v_qmu = _a(a_, 6)
    var v_qsqrt = _a(a_, 7)
    var v_info = _a(a_, 8)
    var v_m = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_noise = _f(f_, 0)
    var v_jitter = _f(f_, 1)
    var v_kdiag = _f(f_, 2)
    with GILReleased(Python()):
        op_svgp(v_kuu, v_bmat, v_b, v_y, v_alpha, v_cmat, v_qmu, v_qsqrt, v_info, v_m, v_n, v_noise, v_jitter, v_kdiag)
    return PythonObject(None)


def svgp_var_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_ksu = _a(a_, 0)
    var v_cmat = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_kdiag = _f(f_, 0)
    with GILReleased(Python()):
        op_svgp_var(v_ksu, v_cmat, v_res, v_n, v_m, v_kdiag)
    return PythonObject(None)


def _add_ops(mut m: PythonModuleBuilder) raises:
    m.def_function[sqdist_binding]("xn_sqdist")
    m.def_function[nan_sqdist_binding]("xn_nan_sqdist")
    m.def_function[l1dist_binding]("xn_l1dist")
    m.def_function[kernel_binding]("xn_kernel")
    m.def_function[matmul_binding]("xn_matmul")
    m.def_function[rowsum_binding]("xn_rowsum")
    m.def_function[colsum_binding]("xn_colsum")
    m.def_function[unary_binding]("xn_unary")
    m.def_function[knn_select_binding]("xn_knn_select")
    m.def_function[knn_sq_binding]("xn_knn_sq")
    m.def_function[group_mean_binding]("xn_group_mean")
    m.def_function[take_rows_binding]("xn_take_rows")
    m.def_function[take_cols_binding]("xn_take_cols")
    m.def_function[variance_binding]("xn_variance")
    m.def_function[ocsvm_binding]("xn_ocsvm")
    m.def_function[lof_lrd_binding]("xn_lof_lrd")
    m.def_function[lof_score_binding]("xn_lof_score")
    m.def_function[kpca_center_binding]("xn_kpca_center")
    m.def_function[scale_div_binding]("xn_scale_div")
    m.def_function[svd_flip_binding]("xn_svd_flip")
    m.def_function[kpca_alpha_scale_binding]("xn_kpca_alpha_scale")
    m.def_function[nc_std_binding]("xn_nc_std")
    m.def_function[nc_shrink_binding]("xn_nc_shrink")
    m.def_function[nc_decision_binding]("xn_nc_decision")
    m.def_function[softmax_binding]("xn_softmax")
    m.def_function[log_softmax_binding]("xn_log_softmax")
    m.def_function[pcs_binding]("xn_pcs")
    m.def_function[achi2_binding]("xn_achi2")
    m.def_function[skew_weights_binding]("xn_skew_weights")
    m.def_function[skew_transform_binding]("xn_skew_transform")
    m.def_function[absdiff_sum_binding]("xn_absdiff_sum")
    m.def_function[row_normalize_binding]("xn_row_normalize")
    m.def_function[lp_clamp_binding]("xn_lp_clamp")
    m.def_function[ls_clamp_binding]("xn_ls_clamp")
    m.def_function[ls_laplacian_binding]("xn_ls_laplacian")
    m.def_function[knn_graph_binding]("xn_knn_graph")
    m.def_function[knn_impute_binding]("xn_knn_impute")
    m.def_function[pagerank_step_binding]("xn_pagerank_step")
    m.def_function[cc_step_binding]("xn_cc_step")
    m.def_function[louvain_binding]("xn_louvain")
    m.def_function[svgp_binding]("xn_svgp")
    m.def_function[svgp_var_binding]("xn_svgp_var")
    m.def_function[eigh_binding]("xn_eigh")
    m.def_function[x_neighbors_numeric_mode_binding]("x_neighbors_numeric_mode")


def x_neighbors_vendor_binding() raises -> PythonObject:
    return PythonObject(String(COMPILED_VENDOR))


@export
def PyInit__mojolearn_x_neighbors() abi("C") -> PythonObject:
    try:
        var m = PythonModuleBuilder("_mojolearn_x_neighbors")
        _add_ops(m)
        m.def_function[x_neighbors_vendor_binding]("x_neighbors_vendor")
        return m.finalize()
    except e:
        abort(String("failed to create _mojolearn_x_neighbors: ", e))
