# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""CPU binding for `_mojolearn_x_neighbors`: the GPU binding's export names and
address contract over the host drivers x_neighbors/host_ops.mojo. HOST ONLY."""
from std.os import abort
from std.python import Python, PythonObject
from std.python._cpython import GILReleased
from std.python.bindings import PythonModuleBuilder
from checks.numerics import GLOBAL_NUMERIC_MODE
from x_neighbors.eigh import op_eigh
from checks.kernel_matrix import COLUMN_CPU, TARGET_COLUMN, column_name
from x_neighbors.host_ops import X_NEIGHBORS_HOST_SABOTAGE, op_sqdist, op_nan_sqdist, op_l1dist, op_kernel, op_matmul, op_rowsum, op_colsum, op_unary, op_knn_select, op_group_mean, op_take_rows, op_take_cols, op_variance, op_ocsvm, op_lof_lrd, op_lof_score, op_kpca_center, op_scale_div, op_svd_flip, op_kpca_alpha_scale, op_nc_std, op_nc_shrink, op_nc_decision, op_softmax


def _a(v: PythonObject, k: Int) raises -> Int:
    var x = Int(py=v[k])
    if x == 0:
        raise Error("x_neighbors: null buffer address")
    return x


def _n(v: PythonObject, k: Int) raises -> Int:
    var x = Int(py=v[k])
    if x < 0:
        raise Error("x_neighbors: a negative size was passed")
    return x


def _f(v: PythonObject, k: Int) raises -> Float32:
    return Float32(Float64(py=v[k]))


def eigh_binding(a: PythonObject, i: PythonObject, f: PythonObject) raises -> PythonObject:
    var x = _a(a, 0)
    var w = _a(a, 1)
    var v = _a(a, 2)
    var n = _n(i, 0)
    if n <= 0:
        raise Error("x_neighbors: eigh needs n >= 1")
    var sweeps = 0
    with GILReleased(Python()):
        sweeps = op_eigh(x, n, w, v)
    return PythonObject(sweeps)


def x_neighbors_numeric_mode_binding() raises -> PythonObject:
    return PythonObject(Int(GLOBAL_NUMERIC_MODE))


def sqdist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_sqdist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def nan_sqdist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_nan_sqdist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def l1dist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_l1dist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def kernel_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_kind = _n(i_, 3)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    var v_degree = _n(i_, 4)
    with GILReleased(Python()):
        op_kernel(v_x, v_y, v_res, v_n, v_m, v_d, v_kind, v_gamma, v_coef0, v_degree)
    return PythonObject(None)


def matmul_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_b = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_k = _n(i_, 1)
    var v_m = _n(i_, 2)
    with GILReleased(Python()):
        op_matmul(v_a, v_b, v_res, v_n, v_k, v_m)
    return PythonObject(None)


def rowsum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_rowsum(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def colsum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_colsum(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def unary_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_op = _n(i_, 1)
    var v_a = _f(f_, 0)
    var v_b = _f(f_, 1)
    with GILReleased(Python()):
        op_unary(v_x, v_res, v_count, v_op, v_a, v_b)
    return PythonObject(None)


def knn_select_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dmat = _a(a_, 0)
    var v_dist = _a(a_, 1)
    var v_idx = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    var v_exclude_self = _n(i_, 3)
    with GILReleased(Python()):
        op_knn_select(v_dmat, v_dist, v_idx, v_n, v_m, v_k, v_exclude_self)
    return PythonObject(None)


def group_mean_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_labels = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_g = _n(i_, 2)
    with GILReleased(Python()):
        op_group_mean(v_x, v_labels, v_res, v_n, v_d, v_g)
    return PythonObject(None)


def take_rows_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_rows = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n_out = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_src = _n(i_, 2)
    with GILReleased(Python()):
        op_take_rows(v_src, v_rows, v_res, v_n_out, v_d, v_n_src)
    return PythonObject(None)


def take_cols_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_cols = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_src_c = _n(i_, 1)
    var v_c = _n(i_, 2)
    with GILReleased(Python()):
        op_take_cols(v_src, v_cols, v_res, v_n, v_src_c, v_c)
    return PythonObject(None)


def variance_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_variance(v_x, v_res, v_count)
    return PythonObject(None)


def ocsvm_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_alpha = _a(a_, 1)
    var v_info = _a(a_, 2)
    var v_iters = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_eps = _f(f_, 0)
    var v_max_iter = _n(i_, 1)
    with GILReleased(Python()):
        op_ocsvm(v_q, v_alpha, v_info, v_iters, v_n, v_eps, v_max_iter)
    return PythonObject(None)


def lof_lrd_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dist = _a(a_, 0)
    var v_idx = _a(a_, 1)
    var v_fit_dist = _a(a_, 2)
    var v_lrd = _a(a_, 3)
    var v_k = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_n_fit = _n(i_, 2)
    with GILReleased(Python()):
        op_lof_lrd(v_dist, v_idx, v_fit_dist, v_lrd, v_k, v_n, v_n_fit)
    return PythonObject(None)


def lof_score_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_idx = _a(a_, 0)
    var v_fit_lrd = _a(a_, 1)
    var v_lrd = _a(a_, 2)
    var v_score = _a(a_, 3)
    var v_k = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_n_fit = _n(i_, 2)
    with GILReleased(Python()):
        op_lof_score(v_idx, v_fit_lrd, v_lrd, v_score, v_k, v_n, v_n_fit)
    return PythonObject(None)


def kpca_center_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_k = _a(a_, 0)
    var v_fit_cols = _a(a_, 1)
    var v_pred_rows = _a(a_, 2)
    var v_fit_all = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_kpca_center(v_k, v_fit_cols, v_pred_rows, v_fit_all, v_res, v_n, v_m)
    return PythonObject(None)


def scale_div_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_s = _f(f_, 0)
    with GILReleased(Python()):
        op_scale_div(v_x, v_res, v_count, v_s)
    return PythonObject(None)


def svd_flip_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_v = _a(a_, 0)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_svd_flip(v_v, v_n, v_c)
    return PythonObject(None)


def kpca_alpha_scale_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_v = _a(a_, 0)
    var v_w = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    var v_divide = _n(i_, 2)
    with GILReleased(Python()):
        op_kpca_alpha_scale(v_v, v_w, v_res, v_n, v_c, v_divide)
    return PythonObject(None)


def nc_std_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_cent = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_std(v_x, v_lab, v_cent, v_std, v_n, v_d, v_n_classes)
    return PythonObject(None)


def nc_shrink_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_nk = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    var v_do_shrink = _n(i_, 3)
    var v_med = _f(f_, 0)
    var v_shrink = _f(f_, 1)
    with GILReleased(Python()):
        op_nc_shrink(v_x, v_cent, v_nk, v_std, v_res, v_n, v_d, v_n_classes, v_do_shrink, v_med, v_shrink)
    return PythonObject(None)


def nc_decision_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_std = _a(a_, 2)
    var v_prior = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_decision(v_q, v_cent, v_std, v_prior, v_res, v_n, v_d, v_n_classes)
    return PythonObject(None)


def softmax_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_softmax(v_x, v_res, v_n, v_c)
    return PythonObject(None)


def _add_ops(mut m: PythonModuleBuilder) raises:
    m.def_function[sqdist_binding]("xn_sqdist")
    m.def_function[nan_sqdist_binding]("xn_nan_sqdist")
    m.def_function[l1dist_binding]("xn_l1dist")
    m.def_function[kernel_binding]("xn_kernel")
    m.def_function[matmul_binding]("xn_matmul")
    m.def_function[rowsum_binding]("xn_rowsum")
    m.def_function[colsum_binding]("xn_colsum")
    m.def_function[unary_binding]("xn_unary")
    m.def_function[knn_select_binding]("xn_knn_select")
    m.def_function[group_mean_binding]("xn_group_mean")
    m.def_function[take_rows_binding]("xn_take_rows")
    m.def_function[take_cols_binding]("xn_take_cols")
    m.def_function[variance_binding]("xn_variance")
    m.def_function[ocsvm_binding]("xn_ocsvm")
    m.def_function[lof_lrd_binding]("xn_lof_lrd")
    m.def_function[lof_score_binding]("xn_lof_score")
    m.def_function[kpca_center_binding]("xn_kpca_center")
    m.def_function[scale_div_binding]("xn_scale_div")
    m.def_function[svd_flip_binding]("xn_svd_flip")
    m.def_function[kpca_alpha_scale_binding]("xn_kpca_alpha_scale")
    m.def_function[nc_std_binding]("xn_nc_std")
    m.def_function[nc_shrink_binding]("xn_nc_shrink")
    m.def_function[nc_decision_binding]("xn_nc_decision")
    m.def_function[softmax_binding]("xn_softmax")
    m.def_function[eigh_binding]("xn_eigh")
    m.def_function[x_neighbors_numeric_mode_binding]("x_neighbors_numeric_mode")


def x_neighbors_host_numeric_mode_binding() raises -> PythonObject:
    return PythonObject(GLOBAL_NUMERIC_MODE)


def x_neighbors_host_vendor_binding() raises -> PythonObject:
    return PythonObject(String("cpu"))


def x_neighbors_host_column_binding() raises -> PythonObject:
    comptime assert TARGET_COLUMN == COLUMN_CPU, "x_neighbors host: pass -D MOJOLEARN_COLUMN_CPU"
    return PythonObject(column_name(TARGET_COLUMN))


def x_neighbors_host_sabotage_binding() raises -> PythonObject:
    return PythonObject(X_NEIGHBORS_HOST_SABOTAGE)


def x_neighbors_vendor_binding() raises -> PythonObject:
    return PythonObject(String("cpu"))


@export
def PyInit__mojolearn_x_neighbors_host() abi("C") -> PythonObject:
    try:
        var m = PythonModuleBuilder("_mojolearn_x_neighbors_host")
        m.def_function[x_neighbors_host_numeric_mode_binding]("x_neighbors_host_numeric_mode")
        m.def_function[x_neighbors_host_vendor_binding]("x_neighbors_host_vendor")
        m.def_function[x_neighbors_host_column_binding]("x_neighbors_host_column")
        m.def_function[x_neighbors_host_sabotage_binding]("x_neighbors_host_sabotage")
        _add_ops(m)
        m.def_function[x_neighbors_vendor_binding]("x_neighbors_vendor")
        return m.finalize()
    except e:
        abort(String("failed to create _mojolearn_x_neighbors_host: ", e))
