# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
# GENERATED by x_neighbors/gen.py from its OPS table; edit the table, not this file.
"""THE NEIGHBORS EXPANSION LANE'S GPU BINDING:
every export is xn_<op>(addresses, ints, floats) over x_neighbors/device_ops.mojo."""
from std.os import abort
from std.python import Python, PythonObject
from std.python._cpython import GILReleased
from std.python.bindings import PythonModuleBuilder
from std.sys.compile import is_defined
from checks.numerics import GLOBAL_NUMERIC_MODE
from x_neighbors.eigh_device import op_eigh
from checks.vendor import COMPILED_VENDOR
from x_neighbors.device_ops import op_softmax64
from x_neighbors.proba64_nc import NC_PROBA64
from x_neighbors.device_ops import op_sqdist, op_nan_sqdist, op_l1dist, op_kernel, op_matmul, op_rowsum, op_colsum, op_unary, op_knn_select, op_knn_sq, op_group_mean, op_take_rows, op_take_cols, op_variance, op_lof_lrd, op_lof_score, op_kpca_center, op_scale_div, op_svd_flip, op_kpca_alpha_scale, op_nc_std, op_nc_shrink_d, op_nc_shrink, op_nc_decision, op_softmax, op_log_softmax, op_pcs, op_achi2, op_skew_weights, op_skew_transform, op_absdiff_sum, op_row_normalize, op_lp_clamp, op_ls_clamp, op_ls_laplacian, op_knn_graph, op_knn_impute, op_col_degree, op_ls_laplacian_deg, op_row_all_zero, op_pcs_sketch, op_pcs_conv, op_pcs_copy0, op_knn_impute_cells, op_pagerank_step, op_cc_step, op_graph_symmetry, op_svgp_var, op_nc_median, op_row_argmax, op_nc_med_std, op_pos_compact, op_p2m_mask_value, op_p2m_zero_cols, op_p2m_nan_indicator, op_p2m_sign_label, op_p2m_relabel, op_p2m_class_counts, op_p2m_const_cols, op_p2m_lp_labels, op_p2m_fill, op_p2m_iota, op_p2m_negate, op_p2m_transpose, op_p2m_transpose_i, op_p2m_row_sort
from x_neighbors.iter_device import op_nc_stats, op_lp_knn_graph, op_lp_knn_product, op_lp_iterate, op_pr_iterate, op_pr_iterate_sparse, op_pcs_resident, op_knn_sq_tiled, op_knn_impute_tiled, op_cc_iterate, op_cc_iterate_csr, op_nan_cells, op_kpca_transform, op_kernel_matmul, op_svgp_fit_ff, op_svgp_predict, op_lp_iterate_knn
from x_neighbors.ocsvm_dev import op_ocsvm
from x_neighbors.graph_dev import op_louvain
from x_neighbors.kapprox_dev import kpca_resident_binding
from x_neighbors.iter_device import lp_fast_resident_binding
from x_neighbors.nan_cells_device import nc_fit_lean_binding
from x_neighbors.ocsvm_dev import OCSVM_CLS2_RES, ocsvm_resident_binding
from x_neighbors.sort_items import purity_flags_binding
from x_neighbors.kfeat_dev import (
    XN_FAST_SCHI2_LAZYW,
    XN_KFEAT_ANY,
    kfeat_first_negative_binding,
    kfeat_flags_binding,
    kfeat_schi2_draw_binding,
    kfeat_schi2_fit_binding,
    kfeat_schi2_transform_binding,
    kfeat_schi2_weights_binding,
)


def _a(v: PythonObject, k: Int) raises -> Int:
    var x = Int(py=v[k])
    if x == 0:
        raise Error("x_neighbors: null buffer address")
    return x


def _n(v: PythonObject, k: Int) raises -> Int:
    var x = Int(py=v[k])
    if x < 0:
        raise Error("x_neighbors: a negative size was passed")
    return x


def _f(v: PythonObject, k: Int) raises -> Float32:
    return Float32(Float64(py=v[k]))


def eigh_binding(a: PythonObject, i: PythonObject, f: PythonObject) raises -> PythonObject:
    var x = _a(a, 0)
    var w = _a(a, 1)
    var v = _a(a, 2)
    var n = _n(i, 0)
    if n <= 0:
        raise Error("x_neighbors: eigh needs n >= 1")
    var sweeps = 0
    with GILReleased(Python()):
        sweeps = op_eigh(x, n, w, v)
    return PythonObject(sweeps)


def x_neighbors_numeric_mode_binding() raises -> PythonObject:
    return PythonObject(Int(GLOBAL_NUMERIC_MODE))


def x_neighbors_py2mojo_off_binding() raises -> PythonObject:
    """1 when built with -D MOJOLEARN_PY2MOJO_neighbors_OFF: Python runs its
    old data loops instead of the p2m_* ops (lane apple-fast-py2mojo-neighbors)."""
    return PythonObject(1 if is_defined["MOJOLEARN_PY2MOJO_neighbors_OFF"]() else 0)


def sqdist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_sqdist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def nan_sqdist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_nan_sqdist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def l1dist_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    with GILReleased(Python()):
        op_l1dist(v_x, v_y, v_res, v_n, v_m, v_d)
    return PythonObject(None)


def kernel_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_kind = _n(i_, 3)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    var v_degree = _n(i_, 4)
    with GILReleased(Python()):
        op_kernel(v_x, v_y, v_res, v_n, v_m, v_d, v_kind, v_gamma, v_coef0, v_degree)
    return PythonObject(None)


def matmul_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_b = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_k = _n(i_, 1)
    var v_m = _n(i_, 2)
    with GILReleased(Python()):
        op_matmul(v_a, v_b, v_res, v_n, v_k, v_m)
    return PythonObject(None)


def rowsum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_rowsum(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def colsum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_colsum(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def unary_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_op = _n(i_, 1)
    var v_a = _f(f_, 0)
    var v_b = _f(f_, 1)
    with GILReleased(Python()):
        op_unary(v_x, v_res, v_count, v_op, v_a, v_b)
    return PythonObject(None)


def knn_select_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dmat = _a(a_, 0)
    var v_dist = _a(a_, 1)
    var v_idx = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    var v_exclude_self = _n(i_, 3)
    with GILReleased(Python()):
        op_knn_select(v_dmat, v_dist, v_idx, v_n, v_m, v_k, v_exclude_self)
    return PythonObject(None)


def knn_sq_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_dist = _a(a_, 2)
    var v_idx = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_exclude_self = _n(i_, 4)
    with GILReleased(Python()):
        op_knn_sq(v_x, v_y, v_dist, v_idx, v_n, v_m, v_d, v_k, v_exclude_self)
    return PythonObject(None)


def group_mean_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_labels = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_g = _n(i_, 2)
    with GILReleased(Python()):
        op_group_mean(v_x, v_labels, v_res, v_n, v_d, v_g)
    return PythonObject(None)


def take_rows_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_rows = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n_out = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_src = _n(i_, 2)
    with GILReleased(Python()):
        op_take_rows(v_src, v_rows, v_res, v_n_out, v_d, v_n_src)
    return PythonObject(None)


def take_cols_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_cols = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_src_c = _n(i_, 1)
    var v_c = _n(i_, 2)
    with GILReleased(Python()):
        op_take_cols(v_src, v_cols, v_res, v_n, v_src_c, v_c)
    return PythonObject(None)


def variance_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_variance(v_x, v_res, v_count)
    return PythonObject(None)


def lof_lrd_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dist = _a(a_, 0)
    var v_idx = _a(a_, 1)
    var v_fit_dist = _a(a_, 2)
    var v_lrd = _a(a_, 3)
    var v_k = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_n_fit = _n(i_, 2)
    with GILReleased(Python()):
        op_lof_lrd(v_dist, v_idx, v_fit_dist, v_lrd, v_k, v_n, v_n_fit)
    return PythonObject(None)


def lof_score_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_idx = _a(a_, 0)
    var v_fit_lrd = _a(a_, 1)
    var v_lrd = _a(a_, 2)
    var v_score = _a(a_, 3)
    var v_k = _n(i_, 0)
    var v_n = _n(i_, 1)
    var v_n_fit = _n(i_, 2)
    with GILReleased(Python()):
        op_lof_score(v_idx, v_fit_lrd, v_lrd, v_score, v_k, v_n, v_n_fit)
    return PythonObject(None)


def kpca_center_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_k = _a(a_, 0)
    var v_fit_cols = _a(a_, 1)
    var v_pred_rows = _a(a_, 2)
    var v_fit_all = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_kpca_center(v_k, v_fit_cols, v_pred_rows, v_fit_all, v_res, v_n, v_m)
    return PythonObject(None)


def scale_div_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_s = _f(f_, 0)
    with GILReleased(Python()):
        op_scale_div(v_x, v_res, v_count, v_s)
    return PythonObject(None)


def svd_flip_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_v = _a(a_, 0)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_svd_flip(v_v, v_n, v_c)
    return PythonObject(None)


def kpca_alpha_scale_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_v = _a(a_, 0)
    var v_w = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    var v_divide = _n(i_, 2)
    with GILReleased(Python()):
        op_kpca_alpha_scale(v_v, v_w, v_res, v_n, v_c, v_divide)
    return PythonObject(None)


def nc_std_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_cent = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_std(v_x, v_lab, v_cent, v_std, v_n, v_d, v_n_classes)
    return PythonObject(None)


def nc_shrink_d_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_dsc = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_nk = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_devs = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    var v_do_shrink = _n(i_, 3)
    var v_med = _f(f_, 0)
    var v_shrink = _f(f_, 1)
    with GILReleased(Python()):
        op_nc_shrink_d(v_dsc, v_cent, v_nk, v_std, v_res, v_devs, v_n, v_d, v_n_classes, v_do_shrink, v_med, v_shrink)
    return PythonObject(None)


def nc_shrink_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_nk = _a(a_, 2)
    var v_std = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_devs = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    var v_do_shrink = _n(i_, 3)
    var v_med = _f(f_, 0)
    var v_shrink = _f(f_, 1)
    with GILReleased(Python()):
        op_nc_shrink(v_x, v_cent, v_nk, v_std, v_res, v_devs, v_n, v_d, v_n_classes, v_do_shrink, v_med, v_shrink)
    return PythonObject(None)


def nc_decision_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_cent = _a(a_, 1)
    var v_std = _a(a_, 2)
    var v_prior = _a(a_, 3)
    var v_res = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_decision(v_q, v_cent, v_std, v_prior, v_res, v_n, v_d, v_n_classes)
    return PythonObject(None)


def softmax_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_softmax(v_x, v_res, v_n, v_c)
    return PythonObject(None)


def softmax64_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    """Lane apple-fast-q-clf: registered only under NC_PROBA64 (FAST, not
    -D MOJOLEARN_PROBA64_QOLD); NearestCentroid.predict_proba as float64."""
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_softmax64(v_x, v_res, v_n, v_c)
    return PythonObject(None)


def log_softmax_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_log_softmax(v_x, v_res, v_n, v_c)
    return PythonObject(None)


def pcs_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_hidx = _a(a_, 1)
    var v_hbit = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d_in = _n(i_, 1)
    var v_nf = _n(i_, 2)
    var v_nc = _n(i_, 3)
    var v_degree = _n(i_, 4)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    with GILReleased(Python()):
        op_pcs(v_x, v_hidx, v_hbit, v_res, v_n, v_d_in, v_nf, v_nc, v_degree, v_gamma, v_coef0)
    return PythonObject(None)


def achi2_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_steps = _n(i_, 2)
    var v_interval = _f(f_, 0)
    with GILReleased(Python()):
        op_achi2(v_x, v_res, v_n, v_d, v_steps, v_interval)
    return PythonObject(None)


def skew_weights_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_z = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_skew_weights(v_z, v_res, v_count)
    return PythonObject(None)


def skew_transform_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_lx = _a(a_, 0)
    var v_w = _a(a_, 1)
    var v_off = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_nc = _n(i_, 2)
    with GILReleased(Python()):
        op_skew_transform(v_lx, v_w, v_off, v_res, v_n, v_d, v_nc)
    return PythonObject(None)


def absdiff_sum_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_b = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_absdiff_sum(v_a, v_b, v_res, v_count)
    return PythonObject(None)


def row_normalize_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_row_normalize(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def lp_clamp_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_ld = _a(a_, 0)
    var v_ystatic = _a(a_, 1)
    var v_unlabeled = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_lp_clamp(v_ld, v_ystatic, v_unlabeled, v_res, v_n, v_c)
    return PythonObject(None)


def ls_clamp_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_ld = _a(a_, 0)
    var v_ystatic = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_count = _n(i_, 0)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_ls_clamp(v_ld, v_ystatic, v_res, v_count, v_alpha)
    return PythonObject(None)


def ls_laplacian_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_ls_laplacian(v_a, v_res, v_n)
    return PythonObject(None)


def knn_graph_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_idx = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    with GILReleased(Python()):
        op_knn_graph(v_idx, v_res, v_n, v_m, v_k)
    return PythonObject(None)


def knn_impute_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_fx = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_weights = _n(i_, 4)
    with GILReleased(Python()):
        op_knn_impute(v_x, v_fx, v_res, v_n, v_m, v_d, v_k, v_weights)
    return PythonObject(None)


def col_degree_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_col_degree(v_a, v_res, v_n)
    return PythonObject(None)


def ls_laplacian_deg_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_deg = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_ls_laplacian_deg(v_a, v_deg, v_res, v_n)
    return PythonObject(None)


def row_all_zero_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_row_all_zero(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def pcs_sketch_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_hidx = _a(a_, 1)
    var v_hbit = _a(a_, 2)
    var v_sk = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d_in = _n(i_, 1)
    var v_nf = _n(i_, 2)
    var v_nc = _n(i_, 3)
    var v_degree = _n(i_, 4)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    with GILReleased(Python()):
        op_pcs_sketch(v_x, v_hidx, v_hbit, v_sk, v_n, v_d_in, v_nf, v_nc, v_degree, v_gamma, v_coef0)
    return PythonObject(None)


def pcs_conv_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_acc = _a(a_, 0)
    var v_sk = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_nc = _n(i_, 1)
    var v_degree = _n(i_, 2)
    var v_p = _n(i_, 3)
    with GILReleased(Python()):
        op_pcs_conv(v_acc, v_sk, v_res, v_n, v_nc, v_degree, v_p)
    return PythonObject(None)


def pcs_copy0_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_sk = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_nc = _n(i_, 1)
    var v_degree = _n(i_, 2)
    with GILReleased(Python()):
        op_pcs_copy0(v_sk, v_res, v_n, v_nc, v_degree)
    return PythonObject(None)


def knn_impute_cells_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_cells = _a(a_, 0)
    var v_x = _a(a_, 1)
    var v_fx = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_weights = _n(i_, 4)
    var v_nc = _n(i_, 5)
    with GILReleased(Python()):
        op_knn_impute_cells(v_cells, v_x, v_fx, v_res, v_n, v_m, v_d, v_k, v_weights, v_nc)
    return PythonObject(None)


def pagerank_step_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_x = _a(a_, 1)
    var v_p = _a(a_, 2)
    var v_dw = _a(a_, 3)
    var v_dangling = _a(a_, 4)
    var v_res = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_pagerank_step(v_q, v_x, v_p, v_dw, v_dangling, v_res, v_n, v_alpha)
    return PythonObject(None)


def cc_step_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_cc_step(v_a, v_lab, v_res, v_n)
    return PythonObject(None)


def graph_symmetry_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_flags = _a(a_, 1)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_graph_symmetry(v_a, v_flags, v_n)
    return PythonObject(None)


def svgp_var_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_ksu = _a(a_, 0)
    var v_cmat = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_kdiag = _f(f_, 0)
    with GILReleased(Python()):
        op_svgp_var(v_ksu, v_cmat, v_res, v_n, v_m, v_kdiag)
    return PythonObject(None)


def nc_median_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_start = _a(a_, 2)
    var v_cent = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    var v_p = _n(i_, 3)
    var v_n_steps = _n(i_, 4)
    with GILReleased(Python()):
        op_nc_median(v_x, v_lab, v_start, v_cent, v_n, v_d, v_n_classes, v_p, v_n_steps)
    return PythonObject(None)


def row_argmax_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    with GILReleased(Python()):
        op_row_argmax(v_a, v_res, v_n, v_m)
    return PythonObject(None)


def nc_med_std_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_std = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_d = _n(i_, 0)
    var v_p = _n(i_, 1)
    var v_n_steps = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_med_std(v_std, v_res, v_d, v_p, v_n_steps)
    return PythonObject(None)


def pos_compact_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_w = _a(a_, 0)
    var v_rows = _a(a_, 1)
    var v_vals = _a(a_, 2)
    var v_info = _a(a_, 3)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_pos_compact(v_w, v_rows, v_vals, v_info, v_n)
    return PythonObject(None)


def p2m_mask_value_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_want = _f(f_, 0)
    with GILReleased(Python()):
        op_p2m_mask_value(v_x, v_res, v_count, v_want)
    return PythonObject(None)


def p2m_zero_cols_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_flags = _a(a_, 1)
    var v_res = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    with GILReleased(Python()):
        op_p2m_zero_cols(v_x, v_flags, v_res, v_n, v_d)
    return PythonObject(None)


def p2m_nan_indicator_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_cur = _a(a_, 1)
    var v_cols = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_c = _n(i_, 2)
    var v_q = _n(i_, 3)
    with GILReleased(Python()):
        op_p2m_nan_indicator(v_src, v_cur, v_cols, v_res, v_n, v_d, v_c, v_q)
    return PythonObject(None)


def p2m_sign_label_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    var v_mode = _n(i_, 1)
    var v_thr = _f(f_, 0)
    with GILReleased(Python()):
        op_p2m_sign_label(v_x, v_res, v_count, v_mode, v_thr)
    return PythonObject(None)


def p2m_relabel_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_lab = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_info = _a(a_, 2)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_p2m_relabel(v_lab, v_res, v_info, v_n)
    return PythonObject(None)


def p2m_class_counts_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_lab = _a(a_, 0)
    var v_nk = _a(a_, 1)
    var v_info = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_n_classes = _n(i_, 1)
    with GILReleased(Python()):
        op_p2m_class_counts(v_lab, v_nk, v_info, v_n, v_n_classes)
    return PythonObject(None)


def p2m_const_cols_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_flag = _a(a_, 1)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    with GILReleased(Python()):
        op_p2m_const_cols(v_x, v_flag, v_n, v_d)
    return PythonObject(None)


def p2m_lp_labels_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_codes = _a(a_, 0)
    var v_ld = _a(a_, 1)
    var v_ys = _a(a_, 2)
    var v_unl = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    var v_skip = _n(i_, 2)
    var v_a = _f(f_, 0)
    with GILReleased(Python()):
        op_p2m_lp_labels(v_codes, v_ld, v_ys, v_unl, v_n, v_c, v_skip, v_a)
    return PythonObject(None)


def p2m_fill_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_res = _a(a_, 0)
    var v_count = _n(i_, 0)
    var v_value = _f(f_, 0)
    with GILReleased(Python()):
        op_p2m_fill(v_res, v_count, v_value)
    return PythonObject(None)


def p2m_iota_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_res = _a(a_, 0)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_p2m_iota(v_res, v_count)
    return PythonObject(None)


def p2m_negate_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_count = _n(i_, 0)
    with GILReleased(Python()):
        op_p2m_negate(v_x, v_res, v_count)
    return PythonObject(None)


def p2m_transpose_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_r = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_p2m_transpose(v_src, v_res, v_r, v_c)
    return PythonObject(None)


def p2m_transpose_i_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_src = _a(a_, 0)
    var v_res = _a(a_, 1)
    var v_r = _n(i_, 0)
    var v_c = _n(i_, 1)
    with GILReleased(Python()):
        op_p2m_transpose_i(v_src, v_res, v_r, v_c)
    return PythonObject(None)


def p2m_row_sort_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_indptr = _a(a_, 0)
    var v_cols = _a(a_, 1)
    var v_dists = _a(a_, 2)
    var v_out_cols = _a(a_, 3)
    var v_out_d = _a(a_, 4)
    var v_nq = _n(i_, 0)
    var v_nnz = _n(i_, 1)
    var v_p = _n(i_, 2)
    var v_n_steps = _n(i_, 3)
    with GILReleased(Python()):
        op_p2m_row_sort(v_indptr, v_cols, v_dists, v_out_cols, v_out_d, v_nq, v_nnz, v_p, v_n_steps)
    return PythonObject(None)


def nc_stats_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_nk = _a(a_, 2)
    var v_cent = _a(a_, 3)
    var v_std = _a(a_, 4)
    var v_dsc = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_n_classes = _n(i_, 2)
    with GILReleased(Python()):
        op_nc_stats(v_x, v_lab, v_nk, v_cent, v_std, v_dsc, v_n, v_d, v_n_classes)
    return PythonObject(None)


def lp_knn_graph_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_idx = _a(a_, 0)
    var v_cols = _a(a_, 1)
    var v_vals = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    var v_variant = _n(i_, 3)
    with GILReleased(Python()):
        op_lp_knn_graph(v_idx, v_cols, v_vals, v_n, v_m, v_k, v_variant)
    return PythonObject(None)


def lp_knn_product_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_cols = _a(a_, 0)
    var v_vals = _a(a_, 1)
    var v_x = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_k = _n(i_, 2)
    var v_c = _n(i_, 3)
    with GILReleased(Python()):
        op_lp_knn_product(v_cols, v_vals, v_x, v_res, v_n, v_m, v_k, v_c)
    return PythonObject(None)


def lp_iterate_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_g = _a(a_, 0)
    var v_ld = _a(a_, 1)
    var v_ystatic = _a(a_, 2)
    var v_unlabeled = _a(a_, 3)
    var v_info = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_c = _n(i_, 1)
    var v_max_iter = _n(i_, 2)
    var v_variant = _n(i_, 3)
    var v_tol_hi = _n(i_, 4)
    var v_tol_lo = _n(i_, 5)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_lp_iterate(v_g, v_ld, v_ystatic, v_unlabeled, v_info, v_n, v_c, v_max_iter, v_variant, v_tol_hi, v_tol_lo, v_alpha)
    return PythonObject(None)


def pr_iterate_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_x = _a(a_, 1)
    var v_p = _a(a_, 2)
    var v_dw = _a(a_, 3)
    var v_dangling = _a(a_, 4)
    var v_info = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_max_iter = _n(i_, 1)
    var v_thr_hi = _n(i_, 2)
    var v_thr_lo = _n(i_, 3)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_pr_iterate(v_q, v_x, v_p, v_dw, v_dangling, v_info, v_n, v_max_iter, v_thr_hi, v_thr_lo, v_alpha)
    return PythonObject(None)


def pr_iterate_sparse_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_x = _a(a_, 1)
    var v_p = _a(a_, 2)
    var v_dw = _a(a_, 3)
    var v_info = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_max_iter = _n(i_, 1)
    var v_thr_hi = _n(i_, 2)
    var v_thr_lo = _n(i_, 3)
    var v_binary = _n(i_, 4)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_pr_iterate_sparse(v_a, v_x, v_p, v_dw, v_info, v_n, v_max_iter, v_thr_hi, v_thr_lo, v_binary, v_alpha)
    return PythonObject(None)


def pcs_resident_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_hidx = _a(a_, 1)
    var v_hbit = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d_in = _n(i_, 1)
    var v_nf = _n(i_, 2)
    var v_nc = _n(i_, 3)
    var v_degree = _n(i_, 4)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    with GILReleased(Python()):
        op_pcs_resident(v_x, v_hidx, v_hbit, v_res, v_n, v_d_in, v_nf, v_nc, v_degree, v_gamma, v_coef0)
    return PythonObject(None)


def knn_sq_tiled_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_dist = _a(a_, 2)
    var v_idx = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_exclude_self = _n(i_, 4)
    with GILReleased(Python()):
        op_knn_sq_tiled(v_x, v_y, v_dist, v_idx, v_n, v_m, v_d, v_k, v_exclude_self)
    return PythonObject(None)


def knn_impute_tiled_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_cells = _a(a_, 0)
    var v_x = _a(a_, 1)
    var v_fx = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_k = _n(i_, 3)
    var v_weights = _n(i_, 4)
    var v_nc = _n(i_, 5)
    with GILReleased(Python()):
        op_knn_impute_tiled(v_cells, v_x, v_fx, v_res, v_n, v_m, v_d, v_k, v_weights, v_nc)
    return PythonObject(None)


def cc_iterate_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_lab = _a(a_, 1)
    var v_info = _a(a_, 2)
    var v_n = _n(i_, 0)
    with GILReleased(Python()):
        op_cc_iterate(v_a, v_lab, v_info, v_n)
    return PythonObject(None)


def cc_iterate_csr_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_indptr = _a(a_, 0)
    var v_indices = _a(a_, 1)
    var v_lab = _a(a_, 2)
    var v_info = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_nnz = _n(i_, 1)
    with GILReleased(Python()):
        op_cc_iterate_csr(v_indptr, v_indices, v_lab, v_info, v_n, v_nnz)
    return PythonObject(None)


def nan_cells_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_cells = _a(a_, 1)
    var v_colmiss = _a(a_, 2)
    var v_info = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_d = _n(i_, 1)
    var v_only = _n(i_, 2) if len(i_) > 2 else 0
    with GILReleased(Python()):
        op_nan_cells(v_x, v_cells, v_colmiss, v_info, v_n, v_d, v_only)
    return PythonObject(None)


def kpca_transform_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_fitx = _a(a_, 1)
    var v_fit_cols = _a(a_, 2)
    var v_fit_all = _a(a_, 3)
    var v_alphas = _a(a_, 4)
    var v_res = _a(a_, 5)
    var v_nq = _n(i_, 0)
    var v_nf = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_c = _n(i_, 3)
    var v_kind = _n(i_, 4)
    var v_degree = _n(i_, 5)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    var v_s = _f(f_, 2)
    with GILReleased(Python()):
        op_kpca_transform(v_q, v_fitx, v_fit_cols, v_fit_all, v_alphas, v_res, v_nq, v_nf, v_d, v_c, v_kind, v_degree, v_gamma, v_coef0, v_s)
    return PythonObject(None)


def kernel_matmul_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_y = _a(a_, 1)
    var v_w = _a(a_, 2)
    var v_res = _a(a_, 3)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_c = _n(i_, 3)
    var v_kind = _n(i_, 4)
    var v_degree = _n(i_, 5)
    var v_gamma = _f(f_, 0)
    var v_coef0 = _f(f_, 1)
    with GILReleased(Python()):
        op_kernel_matmul(v_q, v_y, v_w, v_res, v_n, v_m, v_d, v_c, v_kind, v_degree, v_gamma, v_coef0)
    return PythonObject(None)


def svgp_fit_ff_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_x = _a(a_, 0)
    var v_z = _a(a_, 1)
    var v_y = _a(a_, 2)
    var v_alpha = _a(a_, 3)
    var v_cmat = _a(a_, 4)
    var v_qmu = _a(a_, 5)
    var v_qsqrt = _a(a_, 6)
    var v_info = _a(a_, 7)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_gamma = _f(f_, 0)
    var v_variance = _f(f_, 1)
    var v_noise = _f(f_, 2)
    var v_jitter = _f(f_, 3)
    var v_kdiag = _f(f_, 4)
    with GILReleased(Python()):
        op_svgp_fit_ff(v_x, v_z, v_y, v_alpha, v_cmat, v_qmu, v_qsqrt, v_info, v_n, v_m, v_d, v_gamma, v_variance, v_noise, v_jitter, v_kdiag)
    return PythonObject(None)


def svgp_predict_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_z = _a(a_, 1)
    var v_alpha = _a(a_, 2)
    var v_cmat = _a(a_, 3)
    var v_mean = _a(a_, 4)
    var v_var_ = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_m = _n(i_, 1)
    var v_d = _n(i_, 2)
    var v_gamma = _f(f_, 0)
    var v_variance = _f(f_, 1)
    var v_kdiag = _f(f_, 2)
    with GILReleased(Python()):
        op_svgp_predict(v_q, v_z, v_alpha, v_cmat, v_mean, v_var_, v_n, v_m, v_d, v_gamma, v_variance, v_kdiag)
    return PythonObject(None)


def lp_iterate_knn_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_cols = _a(a_, 0)
    var v_vals = _a(a_, 1)
    var v_ld = _a(a_, 2)
    var v_ystatic = _a(a_, 3)
    var v_unlabeled = _a(a_, 4)
    var v_info = _a(a_, 5)
    var v_n = _n(i_, 0)
    var v_k = _n(i_, 1)
    var v_c = _n(i_, 2)
    var v_max_iter = _n(i_, 3)
    var v_variant = _n(i_, 4)
    var v_tol_hi = _n(i_, 5)
    var v_tol_lo = _n(i_, 6)
    var v_alpha = _f(f_, 0)
    with GILReleased(Python()):
        op_lp_iterate_knn(v_cols, v_vals, v_ld, v_ystatic, v_unlabeled, v_info, v_n, v_k, v_c, v_max_iter, v_variant, v_tol_hi, v_tol_lo, v_alpha)
    return PythonObject(None)


def ocsvm_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_q = _a(a_, 0)
    var v_cv = _a(a_, 1)
    var v_alpha = _a(a_, 2)
    var v_info = _a(a_, 3)
    var v_iters = _a(a_, 4)
    var v_n = _n(i_, 0)
    var v_eps = _f(f_, 0)
    var v_max_iter = _n(i_, 1)
    with GILReleased(Python()):
        op_ocsvm(v_q, v_cv, v_alpha, v_info, v_iters, v_n, v_eps, v_max_iter)
    return PythonObject(None)


def louvain_binding(a_: PythonObject, i_: PythonObject, f_: PythonObject) raises -> PythonObject:
    var v_a = _a(a_, 0)
    var v_labels = _a(a_, 1)
    var v_info = _a(a_, 2)
    var v_n = _n(i_, 0)
    var v_max_level = _n(i_, 1)
    var v_resolution = _f(f_, 0)
    var v_threshold = _f(f_, 1)
    with GILReleased(Python()):
        op_louvain(v_a, v_labels, v_info, v_n, v_max_level, v_resolution, v_threshold)
    return PythonObject(None)


def _add_ops(mut m: PythonModuleBuilder) raises:
    m.def_function[sqdist_binding]("xn_sqdist")
    m.def_function[nan_sqdist_binding]("xn_nan_sqdist")
    m.def_function[l1dist_binding]("xn_l1dist")
    m.def_function[kernel_binding]("xn_kernel")
    m.def_function[matmul_binding]("xn_matmul")
    m.def_function[rowsum_binding]("xn_rowsum")
    m.def_function[colsum_binding]("xn_colsum")
    m.def_function[unary_binding]("xn_unary")
    m.def_function[knn_select_binding]("xn_knn_select")
    m.def_function[knn_sq_binding]("xn_knn_sq")
    m.def_function[group_mean_binding]("xn_group_mean")
    m.def_function[take_rows_binding]("xn_take_rows")
    m.def_function[take_cols_binding]("xn_take_cols")
    m.def_function[variance_binding]("xn_variance")
    m.def_function[lof_lrd_binding]("xn_lof_lrd")
    m.def_function[lof_score_binding]("xn_lof_score")
    m.def_function[kpca_center_binding]("xn_kpca_center")
    m.def_function[scale_div_binding]("xn_scale_div")
    m.def_function[svd_flip_binding]("xn_svd_flip")
    m.def_function[kpca_alpha_scale_binding]("xn_kpca_alpha_scale")
    m.def_function[nc_std_binding]("xn_nc_std")
    m.def_function[nc_shrink_d_binding]("xn_nc_shrink_d")
    m.def_function[nc_shrink_binding]("xn_nc_shrink")
    m.def_function[nc_decision_binding]("xn_nc_decision")
    m.def_function[softmax_binding]("xn_softmax")
    comptime if NC_PROBA64:
        m.def_function[softmax64_binding]("xn_softmax64")
    m.def_function[log_softmax_binding]("xn_log_softmax")
    m.def_function[pcs_binding]("xn_pcs")
    m.def_function[achi2_binding]("xn_achi2")
    m.def_function[skew_weights_binding]("xn_skew_weights")
    m.def_function[skew_transform_binding]("xn_skew_transform")
    m.def_function[absdiff_sum_binding]("xn_absdiff_sum")
    m.def_function[row_normalize_binding]("xn_row_normalize")
    m.def_function[lp_clamp_binding]("xn_lp_clamp")
    m.def_function[ls_clamp_binding]("xn_ls_clamp")
    m.def_function[ls_laplacian_binding]("xn_ls_laplacian")
    m.def_function[knn_graph_binding]("xn_knn_graph")
    m.def_function[knn_impute_binding]("xn_knn_impute")
    m.def_function[col_degree_binding]("xn_col_degree")
    m.def_function[ls_laplacian_deg_binding]("xn_ls_laplacian_deg")
    m.def_function[row_all_zero_binding]("xn_row_all_zero")
    m.def_function[pcs_sketch_binding]("xn_pcs_sketch")
    m.def_function[pcs_conv_binding]("xn_pcs_conv")
    m.def_function[pcs_copy0_binding]("xn_pcs_copy0")
    m.def_function[knn_impute_cells_binding]("xn_knn_impute_cells")
    m.def_function[pagerank_step_binding]("xn_pagerank_step")
    m.def_function[cc_step_binding]("xn_cc_step")
    m.def_function[graph_symmetry_binding]("xn_graph_symmetry")
    m.def_function[svgp_var_binding]("xn_svgp_var")
    m.def_function[nc_median_binding]("xn_nc_median")
    m.def_function[row_argmax_binding]("xn_row_argmax")
    m.def_function[nc_med_std_binding]("xn_nc_med_std")
    m.def_function[pos_compact_binding]("xn_pos_compact")
    m.def_function[p2m_mask_value_binding]("xn_p2m_mask_value")
    m.def_function[p2m_zero_cols_binding]("xn_p2m_zero_cols")
    m.def_function[p2m_nan_indicator_binding]("xn_p2m_nan_indicator")
    m.def_function[p2m_sign_label_binding]("xn_p2m_sign_label")
    m.def_function[p2m_relabel_binding]("xn_p2m_relabel")
    m.def_function[p2m_class_counts_binding]("xn_p2m_class_counts")
    m.def_function[p2m_const_cols_binding]("xn_p2m_const_cols")
    m.def_function[p2m_lp_labels_binding]("xn_p2m_lp_labels")
    m.def_function[p2m_fill_binding]("xn_p2m_fill")
    m.def_function[p2m_iota_binding]("xn_p2m_iota")
    m.def_function[p2m_negate_binding]("xn_p2m_negate")
    m.def_function[p2m_transpose_binding]("xn_p2m_transpose")
    m.def_function[p2m_transpose_i_binding]("xn_p2m_transpose_i")
    m.def_function[p2m_row_sort_binding]("xn_p2m_row_sort")
    m.def_function[nc_stats_binding]("xn_nc_stats")
    m.def_function[lp_knn_graph_binding]("xn_lp_knn_graph")
    m.def_function[lp_knn_product_binding]("xn_lp_knn_product")
    m.def_function[lp_iterate_binding]("xn_lp_iterate")
    m.def_function[pr_iterate_binding]("xn_pr_iterate")
    m.def_function[pr_iterate_sparse_binding]("xn_pr_iterate_sparse")
    m.def_function[pcs_resident_binding]("xn_pcs_resident")
    m.def_function[knn_sq_tiled_binding]("xn_knn_sq_tiled")
    m.def_function[knn_impute_tiled_binding]("xn_knn_impute_tiled")
    m.def_function[cc_iterate_binding]("xn_cc_iterate")
    m.def_function[cc_iterate_csr_binding]("xn_cc_iterate_csr")
    m.def_function[nan_cells_binding]("xn_nan_cells")
    m.def_function[kpca_transform_binding]("xn_kpca_transform")
    m.def_function[kernel_matmul_binding]("xn_kernel_matmul")
    m.def_function[svgp_fit_ff_binding]("xn_svgp_fit_ff")
    m.def_function[svgp_predict_binding]("xn_svgp_predict")
    m.def_function[lp_iterate_knn_binding]("xn_lp_iterate_knn")
    m.def_function[ocsvm_binding]("xn_ocsvm")
    m.def_function[louvain_binding]("xn_louvain")
    m.def_function[eigh_binding]("xn_eigh")
    m.def_function[x_neighbors_numeric_mode_binding]("x_neighbors_numeric_mode")
    m.def_function[x_neighbors_py2mojo_off_binding]("x_neighbors_py2mojo_off")


def x_neighbors_vendor_binding() raises -> PythonObject:
    return PythonObject(String(COMPILED_VENDOR))


@export
def PyInit__mojolearn_x_neighbors() abi("C") -> PythonObject:
    try:
        var m = PythonModuleBuilder("_mojolearn_x_neighbors")
        _add_ops(m)
        m.def_function[x_neighbors_vendor_binding]("x_neighbors_vendor")
        m.def_function[lp_fast_resident_binding]("x_neighbors_lp_fast_resident")
        m.def_function[nc_fit_lean_binding]("x_neighbors_nc_fit_lean")
        m.def_function[purity_flags_binding]("x_neighbors_purity_flags")
        m.def_function[kpca_resident_binding]("x_neighbors_kpca_resident")
        # lane/apple-fast-gap-cls2: OneClassSVM's Gram kept on the device
        # (x_neighbors/ocsvm_dev.mojo OCSVM_CLS2_RES; FAST + Apple default)
        comptime if OCSVM_CLS2_RES:
            m.def_function[ocsvm_resident_binding]("x_neighbors_ocsvm_resident")
        # lane apple-fast-w2-kfeat: the chi2 samplers' fit entries
        # (x_neighbors/kfeat_dev.mojo; FAST + Apple, opt-in defines)
        comptime if XN_KFEAT_ANY:
            m.def_function[kfeat_flags_binding]("x_neighbors_kfeat_flags")
            m.def_function[kfeat_first_negative_binding]("x_neighbors_kfeat_first_negative")
            m.def_function[kfeat_schi2_fit_binding]("x_neighbors_kfeat_schi2_fit")
        # lane apple-fast-w3-kfeat: SkewedChi2Sampler's lazy weights (opt-in)
        comptime if XN_FAST_SCHI2_LAZYW:
            m.def_function[kfeat_schi2_draw_binding]("x_neighbors_kfeat_schi2_draw")
            m.def_function[kfeat_schi2_weights_binding]("x_neighbors_kfeat_schi2_weights")
            m.def_function[kfeat_schi2_transform_binding]("x_neighbors_kfeat_schi2_transform")
        return m.finalize()
    except e:
        abort(String("failed to create _mojolearn_x_neighbors: ", e))
