#!/usr/bin/env python3
"""Forest host inference gate (the forest host lane, 2026-09-13).

Two halves, one fixture format.

  record   on a GPU box, through the normal package: load a saved forest with
           its own estimator class, predict the fixture rows, write the
           SHA-256 of the predictions to expected.json together with the
           vendor and numeric mode that produced them.
  check    on a CPU box, through mojolearn.HostForest: predict the same rows
           with the host binding and require the same SHA-256.

A fixture directory holds

  model.npz       written by RandomForest*.save or ExtraTrees*.save (a
                  sequential archive; parallel_groves archives are refused)
  fixture.json    {"rows": N, "features": F, "seed": S,
                   "generator": "splitmix64-uniform-f32-v1", "x_sha256": ...}
  expected.json   written by `record`; {"status": "OWED"} until then

X is regenerated from the seed by a pure Python SplitMix64 so no data file
travels; both halves verify the regenerated bytes against `x_sha256` before
predicting, so a mismatch can only be the prediction. The values are
`(bits >> 40) / 2^24` as float32, exactly representable, in [0, 1).

The hashes compared are `predict` and, for classifiers, `predict_proba`, over
the raw bytes of the Array each returns (C order, native dtype); str labels
hash their UTF-8 joined by newlines. The dtype and shape are recorded and
compared as well, so a float64 answer to a float32 question is a mismatch and
not a coincidence of bytes.

Exit 0: every byte equal. 1: any mismatch. 2: the gate could not run, which
includes a fixture whose expected.json is still OWED. --expect-mismatch
inverts the verdict for the sabotage build: exit 0 only if something differs.
"""
import argparse
import hashlib
import json
import os
import platform
import struct
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = 'splitmix64-uniform-f32-v1'
MASK64 = (1 << 64) - 1
ESTIMATORS = ('RandomForestClassifier', 'RandomForestRegressor',
              'ExtraTreesClassifier', 'ExtraTreesRegressor')


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def splitmix64(seed):
    state = seed & MASK64
    while True:
        state = (state + 0x9E3779B97F4A7C15) & MASK64
        z = state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        yield z ^ (z >> 31)


def fixture_bytes(spec):
    """The float32 row-major bytes of the fixture rows, from the seed alone."""
    if spec.get('generator') != GENERATOR:
        raise SystemExit(f"gate: fixture generator {spec.get('generator')!r} is not {GENERATOR!r}")
    rows, features, seed = int(spec['rows']), int(spec['features']), int(spec['seed'])
    if rows < 1 or features < 1:
        raise SystemExit('gate: fixture rows and features must be positive')
    draw = splitmix64(seed)
    values = [float((next(draw) >> 40) / float(1 << 24)) for _ in range(rows * features)]
    return struct.pack(f'<{len(values)}f', *values), rows, features


def load_fixture(directory):
    spec = json.loads((directory / 'fixture.json').read_text())
    raw, rows, features = fixture_bytes(spec)
    got = sha256_bytes(raw)
    want = spec.get('x_sha256')
    if want and got != want:
        raise SystemExit(f'gate: regenerated fixture rows hash {got}, fixture.json records {want}')
    return spec, raw, rows, features


def host_info():
    info = dict(machine=platform.machine(), system=platform.system(),
                release=platform.release(), python=platform.python_version())
    try:
        if platform.system() == 'Darwin':
            info['cpu'] = subprocess.run(['sysctl', '-n', 'machdep.cpu.brand_string'],
                                         capture_output=True, text=True, timeout=10).stdout.strip()
        else:
            wanted = {'model name': 'cpu', 'cpu model': 'cpu', 'vendor_id': 'vendor',
                      'cpu family': 'family', 'model': 'model', 'stepping': 'stepping',
                      'cpu implementer': 'implementer', 'cpu part': 'part'}
            text = Path('/proc/cpuinfo').read_text()
            for line in text.splitlines():
                key, _, value = line.partition(':')
                key = key.strip().lower()
                if key in wanted and wanted[key] not in info:
                    info[wanted[key]] = value.strip()
            flags = [l for l in text.splitlines() if l.startswith(('flags', 'Features'))]
            if flags:
                have = set(flags[0].split(':', 1)[1].split())
                info['isa'] = sorted(have & {'avx2', 'fma', 'avx512f', 'asimd', 'sve', 'sve2'})
    except (OSError, subprocess.SubprocessError):
        pass
    return info


def git_commit():
    env = os.environ.get('MOJOLEARN_GATE_COMMIT')
    if env:
        return env
    try:
        return subprocess.run(['git', '-C', str(ROOT), 'rev-parse', 'HEAD'],
                              capture_output=True, text=True, timeout=10).stdout.strip() or None
    except (OSError, subprocess.SubprocessError):
        return None


def digest_prediction(value):
    """`(sha256, dtype, shape)` of a prediction. An Array hashes its raw
    bytes; a list of str labels hashes the UTF-8 of the labels joined by
    newlines, dtype 'str'."""
    if isinstance(value, list):
        return sha256_bytes('\n'.join(value).encode('utf-8')), 'str', [len(value)]
    return sha256_bytes(value.tobytes()), str(value.dtype), [int(s) for s in value.shape]


def digests_for(model, X, is_classifier):
    out = {}
    started = time.perf_counter()
    out['predict'] = dict(zip(('sha256', 'dtype', 'shape'), digest_prediction(model.predict(X))))
    if is_classifier:
        out['predict_proba'] = dict(zip(('sha256', 'dtype', 'shape'),
                                        digest_prediction(model.predict_proba(X))))
    out['seconds'] = round(time.perf_counter() - started, 6)
    return out


def estimator_of(model_path):
    """The `estimator` member of a saved forest, read with the codec and
    nothing else, so `record` can pick the class without guessing."""
    from mojolearn import _serialize
    arrays = _serialize.read_npz(model_path, (
        'mojolearn-randomforest-1', 'mojolearn-extratrees-1',
        'mojolearn-randomforest-1-parallel-groves-1', 'mojolearn-extratrees-1-parallel-groves-1'))
    fmt = _serialize.scalar_str(arrays, 'format')
    if fmt.endswith('-parallel-groves-1'):
        raise SystemExit(f'gate: {model_path} is a parallel_groves archive; the host engine is sequential')
    name = _serialize.scalar_str(arrays, 'estimator')
    if name not in ESTIMATORS:
        raise SystemExit(f'gate: {model_path} was saved by {name}, not a forest estimator')
    return name


def package_root(args):
    """Where `mojolearn` is imported from. The checkout's python/ by default;
    `--package-root PATH` for another checkout's package (the Mac recording
    imports the GPU build beside this worktree), `--package-root ''` for an
    installed wheel."""
    if args.package_root is None:
        sys.path.insert(0, str(ROOT / 'python'))
    elif args.package_root:
        sys.path.insert(0, os.path.abspath(args.package_root))


def do_record(args):
    """A GPU box, the normal package. Refuses to run on a CPU-only install,
    because a recording made by the host binding would compare the host
    binding with itself."""
    package_root(args)
    import mojolearn
    from mojolearn._buffer import frombytes
    vendor = mojolearn.vendor()
    if vendor == 'cpu' and not args.allow_cpu_recording:
        print('gate: record must run on a GPU box; this install is CPU-only', file=sys.stderr)
        return 2
    directory = args.fixture_dir
    spec, raw, rows, features = load_fixture(directory)
    X = frombytes(raw, '<f4', (rows, features))
    name = estimator_of(directory / 'model.npz')
    cls = getattr(mojolearn, name)
    model = cls.load(str(directory / 'model.npz'))
    if getattr(model, 'inference_engine', 'sequential') != 'sequential':
        print('gate: the loaded model does not select the sequential engine', file=sys.stderr)
        return 2
    mode = model._effective_mode() if hasattr(model, '_effective_mode') else mojolearn.numeric_mode()
    digests = digests_for(model, X, name.endswith('Classifier'))
    report = dict(
        status='RECORDED', estimator=name, vendor=vendor, gpu_arch=mojolearn.gpu_arch(),
        numeric_mode=mode, inference_engine='sequential',
        model_sha256=sha256_bytes((directory / 'model.npz').read_bytes()),
        x_sha256=sha256_bytes(raw), fixture=spec, host=host_info(), commit=git_commit(),
        recorded_at=time.strftime('%Y-%m-%dT%H:%M:%S%z'), predictions=digests,
    )
    target = directory / 'expected.json'
    if target.exists() and not args.overwrite:
        existing = json.loads(target.read_text())
        if existing.get('status') == 'RECORDED':
            print(f'gate: {target} is already recorded; pass --overwrite to replace it', file=sys.stderr)
            return 2
    target.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    for key, value in digests.items():
        if isinstance(value, dict):
            print(f"record {name} {key} {value['dtype']} {value['shape']} sha256 {value['sha256']}")
    print(f'record wrote {target} (vendor {vendor}, mode {mode})')
    return 0


def do_check(args):
    """The CPU box, through HostForest. The package may be a CPU-only install
    or a full GPU install; either way the prediction here is the host
    binding's."""
    package_root(args)
    try:
        import mojolearn
        from mojolearn._buffer import frombytes
        from mojolearn._forest_host import HostForest, binary_path
    except Exception as exc:  # the import itself is part of what is gated
        print(f'gate: import failed: {type(exc).__name__}: {exc}', file=sys.stderr)
        return 2
    results = []
    verdict_ok = True
    for directory in args.fixture_dir:
        expected_path = directory / 'expected.json'
        model_path = directory / 'model.npz'
        if not expected_path.exists() or not model_path.exists():
            print(f'gate: {directory} is missing expected.json or model.npz; the GPU-side '
                  'recording is OWED (tools/forest_host_gate.py record on a GPU box)', file=sys.stderr)
            return 2
        expected = json.loads(expected_path.read_text())
        if expected.get('status') != 'RECORDED' or 'predictions' not in expected:
            print(f'gate: {expected_path} status is {expected.get("status")!r}; the GPU-side '
                  'recording is OWED (tools/forest_host_gate.py record on a GPU box)', file=sys.stderr)
            return 2
        try:
            spec, raw, rows, features = load_fixture(directory)
        except SystemExit as exc:
            print(exc, file=sys.stderr)
            return 2
        if expected.get('x_sha256') != sha256_bytes(raw):
            print(f'gate: {directory} expected.json was recorded for different fixture rows', file=sys.stderr)
            return 2
        model_sha = sha256_bytes(model_path.read_bytes())
        if expected.get('model_sha256') != model_sha:
            print(f'gate: {model_path} hashes {model_sha}, expected.json records '
                  f'{expected.get("model_sha256")}', file=sys.stderr)
            return 2
        X = frombytes(raw, '<f4', (rows, features))
        try:
            model = HostForest.from_file(str(model_path))
            got = digests_for(model, X, model.is_classifier)
        except Exception as exc:
            print(f'gate: {directory} host predict failed: {type(exc).__name__}: {exc}', file=sys.stderr)
            return 2
        if model.estimator != expected.get('estimator'):
            print(f'gate: {directory} model is {model.estimator}, expected.json says '
                  f'{expected.get("estimator")}', file=sys.stderr)
            return 2
        want = expected['predictions']
        rows_out = []
        for key in ('predict', 'predict_proba'):
            if key not in want and key not in got:
                continue
            if (key in want) != (key in got):
                print(f'gate: {directory} {key} present on one side only', file=sys.stderr)
                return 2
            equal = (want[key]['sha256'] == got[key]['sha256'] and want[key]['dtype'] == got[key]['dtype']
                     and list(want[key]['shape']) == list(got[key]['shape']))
            verdict_ok = verdict_ok and equal
            rows_out.append(dict(case=key, want=want[key]['sha256'], got=got[key]['sha256'],
                                 want_dtype=want[key]['dtype'], got_dtype=got[key]['dtype'],
                                 want_shape=want[key]['shape'], got_shape=got[key]['shape'], equal=equal))
            print(f"check {directory.name} {model.estimator} {key} {'EQUAL' if equal else 'DIFFER'} "
                  f"gpu {want[key]['sha256']} host {got[key]['sha256']}")
        results.append(dict(fixture=directory.name, estimator=model.estimator,
                            recorded_vendor=expected.get('vendor'), recorded_gpu_arch=expected.get('gpu_arch'),
                            recorded_numeric_mode=expected.get('numeric_mode'),
                            model_sha256=model_sha, host_model_sha256=model.model_sha256(),
                            rows=rows, features=features, seconds=got['seconds'], cases=rows_out))
    if args.expect_mismatch:
        verdict = 'EXPECTED MISMATCH SEEN' if not verdict_ok else 'SABOTAGE NOT CAUGHT'
        code = 0 if not verdict_ok else 1
    else:
        verdict = 'IDENTICAL' if verdict_ok else 'MISMATCH'
        code = 0 if verdict_ok else 1
    report = dict(verdict=verdict, expect_mismatch=bool(args.expect_mismatch), exit=code,
                  binary=binary_path(), vendor=mojolearn.vendor(), host=host_info(),
                  commit=git_commit(), checked_at=time.strftime('%Y-%m-%dT%H:%M:%S%z'),
                  fixtures=results)
    if args.report:
        if args.report.exists():
            print(f'gate: {args.report} exists; refusing to overwrite a report', file=sys.stderr)
            return 2
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    print(f'gate verdict {verdict} ({len(results)} fixtures, exit {code})')
    return code


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--package-root', default=None,
                        help="directory to import mojolearn from (default: this checkout's python/; "
                             "'' for the installed package)")
    sub = parser.add_subparsers(dest='command', required=True)
    rec = sub.add_parser('record', help='on a GPU box, write expected.json for one fixture directory')
    rec.add_argument('fixture_dir', type=Path)
    rec.add_argument('--overwrite', action='store_true')
    rec.add_argument('--allow-cpu-recording', action='store_true',
                     help='record on a CPU-only install anyway (a self-comparison; never for a certificate)')
    chk = sub.add_parser('check', help='on the CPU box, compare the host predictions with expected.json')
    chk.add_argument('fixture_dir', type=Path, nargs='+')
    chk.add_argument('--report', type=Path, help='new exclusive JSON report')
    chk.add_argument('--expect-mismatch', action='store_true')
    args = parser.parse_args()
    if args.command == 'record':
        return do_record(args)
    return do_check(args)


if __name__ == '__main__':
    sys.exit(main())
