#!/usr/bin/env python3
"""Forest host inference gate (the forest host lane, 2026-09-13; GBDT
fixtures since the GBDT host lane the same day).

Two halves, one fixture format, and a fixture maker.

  make     on a GPU box, through the normal package: fit one small model of
           a named kind on regenerated rows, save it as model.npz, write
           fixture.json for the held-out rows and an OWED expected.json.
  record   on a GPU box, through the normal package: load a saved model with
           its own estimator class, predict the fixture rows, write the
           SHA-256 of the predictions to expected.json together with the
           vendor and numeric mode that produced them.
  check    on a CPU box, through mojolearn.host_model (HostForest or
           HostGBDT by the file's format): predict the same rows with the
           host binding and require the same SHA-256.

A fixture directory holds

  model.npz       written by RandomForest*.save or ExtraTrees*.save (a
                  sequential archive; parallel_groves archives are refused)
                  or by GradientBoosting.save
  fixture.json    {"rows": N, "features": F, "seed": S,
                   "generator": "splitmix64-uniform-f32-v1", "x_sha256": ...}
  expected.json   written by `record`; {"status": "OWED"} until then

X is regenerated from the seed by a pure Python SplitMix64 so no data file
travels; both halves verify the regenerated bytes against `x_sha256` before
predicting, so a mismatch can only be the prediction. The values are
`(bits >> 40) / 2^24` as float32, exactly representable, in [0, 1).

The hashes compared are `predict` and, for classifiers, `predict_proba`, over
the raw bytes of the Array each returns (C order, native dtype); str labels
hash their UTF-8 joined by newlines. A GradientBoosting fixture's `predict`
is the raw float32 score, and `predict_proba` is recorded when the loss is
Logloss or CrossEntropy (the float64 sigmoid columns). The dtype and shape are recorded and
compared as well, so a float64 answer to a float32 question is a mismatch and
not a coincidence of bytes.

Exit 0: every byte equal. 1: any mismatch. 2: the gate could not run, which
includes a fixture whose expected.json is still OWED. --expect-mismatch
inverts the verdict for the sabotage build: exit 0 only if something differs.
"""
import argparse
import hashlib
import json
import os
import platform
import struct
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = 'splitmix64-uniform-f32-v1'
MASK64 = (1 << 64) - 1
#: The classes whose saves are `mojolearn-gbdt-1` archives (`_gbdt_host.GBDT_ESTIMATORS`).
GBDT_ESTIMATORS = ('GradientBoosting', 'OrderedRMSE', 'ExperimentalTwoLevelFeatureFreq')
ESTIMATORS = ('RandomForestClassifier', 'RandomForestRegressor',
              'ExtraTreesClassifier', 'ExtraTreesRegressor') + GBDT_ESTIMATORS
#: `transform` of a fixture whose first two columns are categorical codes
#: (FeatureFreq sources, a one-hot categorical column): column 0 becomes
#: `x2 > 0.5` and column 1 `2 * (x3 > 0.5) + (x4 > 0.5)`, as float32 codes,
#: applied to the regenerated rows in `make`, `record` and `check` alike.
CODED = 'coded-2-4-v1'
FOREST_FORMATS = ('mojolearn-randomforest-1', 'mojolearn-extratrees-1',
                  'mojolearn-randomforest-1-parallel-groves-1', 'mojolearn-extratrees-1-parallel-groves-1')
GBDT_FORMAT = 'mojolearn-gbdt-1'
#: The kinds `make` fits, with the fixture parameters of the 2026-09-13 Apple
#: recordings (forests: 8 trees, depth 6; GBDT: 8 trees, depth 4). The label
#: rules are the brief's: `int((x0 * 7 + x1 * 13) * 3) % k` for classifiers
#: (k = 3 for forests, 2 for the binary Logloss), `x1 * 2 + x2` for regressors.
KINDS = {
    'rf_classifier': dict(estimator='RandomForestClassifier', classes=3),
    'rf_regressor': dict(estimator='RandomForestRegressor', classes=0),
    'et_classifier': dict(estimator='ExtraTreesClassifier', classes=3),
    'et_regressor': dict(estimator='ExtraTreesRegressor', classes=0),
    'gbdt_symmetric': dict(estimator='GradientBoosting', classes=2, loss='Logloss', grow_policy='SymmetricTree'),
    'gbdt_depthwise': dict(estimator='GradientBoosting', classes=2, loss='Logloss', grow_policy='Depthwise'),
    'gbdt_lossguide': dict(estimator='GradientBoosting', classes=2, loss='Logloss', grow_policy='Lossguide'),
    'gbdt_rmse': dict(estimator='GradientBoosting', classes=0, loss='RMSE', grow_policy='SymmetricTree'),
    # lane/inference-gbdt-modes (2026-09-15); no recording yet, OWED
    'gbdt_ordered_rmse': dict(estimator='OrderedRMSE', classes=0, loss='RMSE', grow_policy='SymmetricTree'),
    'gbdt_feature_freq': dict(estimator='ExperimentalTwoLevelFeatureFreq', classes=0, loss='RMSE',
                              grow_policy='SymmetricTree', transform=CODED),
    'gbdt_pointwise_bayesian_eval': dict(estimator='GradientBoosting', classes=2, loss='Logloss',
                                         grow_policy='SymmetricTree', pointwise=True),
    'gbdt_categorical_onehot': dict(estimator='GradientBoosting', classes=2, loss='Logloss',
                                    grow_policy='SymmetricTree', transform=CODED),
}


def proba_wanted(name, loss):
    """Whether `predict_proba` is part of the recording: forest classifiers
    always, a gradient boosting class when its loss has the sigmoid link."""
    if name in GBDT_ESTIMATORS:
        return loss in ('Logloss', 'CrossEntropy')
    return name.endswith('Classifier')


def apply_transform(raw, rows, features, transform):
    """The fixture rows after `transform` (None or CODED), float32 row-major bytes."""
    if not transform:
        return raw
    if transform != CODED:
        raise SystemExit(f'gate: unknown fixture transform {transform!r}')
    if features < 5:
        raise SystemExit(f'gate: transform {CODED} needs at least 5 features')
    xs = list(struct.unpack(f'<{rows * features}f', raw))
    for r in range(rows):
        b = r * features
        c0 = 1.0 if xs[b + 2] > 0.5 else 0.0
        c1 = (2.0 if xs[b + 3] > 0.5 else 0.0) + (1.0 if xs[b + 4] > 0.5 else 0.0)
        xs[b], xs[b + 1] = c0, c1
    return struct.pack(f'<{len(xs)}f', *xs)


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def splitmix64(seed):
    state = seed & MASK64
    while True:
        state = (state + 0x9E3779B97F4A7C15) & MASK64
        z = state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        yield z ^ (z >> 31)


def fixture_bytes(spec):
    """The float32 row-major bytes of the fixture rows, from the seed alone."""
    if spec.get('generator') != GENERATOR:
        raise SystemExit(f"gate: fixture generator {spec.get('generator')!r} is not {GENERATOR!r}")
    rows, features, seed = int(spec['rows']), int(spec['features']), int(spec['seed'])
    if rows < 1 or features < 1:
        raise SystemExit('gate: fixture rows and features must be positive')
    draw = splitmix64(seed)
    values = [float((next(draw) >> 40) / float(1 << 24)) for _ in range(rows * features)]
    return struct.pack(f'<{len(values)}f', *values), rows, features


def load_fixture(directory):
    spec = json.loads((directory / 'fixture.json').read_text())
    raw, rows, features = fixture_bytes(spec)
    got = sha256_bytes(raw)
    want = spec.get('x_sha256')
    if want and got != want:
        raise SystemExit(f'gate: regenerated fixture rows hash {got}, fixture.json records {want}')
    return spec, raw, rows, features


def host_info():
    info = dict(machine=platform.machine(), system=platform.system(),
                release=platform.release(), python=platform.python_version())
    try:
        if platform.system() == 'Darwin':
            info['cpu'] = subprocess.run(['sysctl', '-n', 'machdep.cpu.brand_string'],
                                         capture_output=True, text=True, timeout=10).stdout.strip()
        else:
            wanted = {'model name': 'cpu', 'cpu model': 'cpu', 'vendor_id': 'vendor',
                      'cpu family': 'family', 'model': 'model', 'stepping': 'stepping',
                      'cpu implementer': 'implementer', 'cpu part': 'part'}
            text = Path('/proc/cpuinfo').read_text()
            for line in text.splitlines():
                key, _, value = line.partition(':')
                key = key.strip().lower()
                if key in wanted and wanted[key] not in info:
                    info[wanted[key]] = value.strip()
            flags = [l for l in text.splitlines() if l.startswith(('flags', 'Features'))]
            if flags:
                have = set(flags[0].split(':', 1)[1].split())
                info['isa'] = sorted(have & {'avx2', 'fma', 'avx512f', 'asimd', 'sve', 'sve2'})
    except (OSError, subprocess.SubprocessError):
        pass
    return info


def git_commit():
    env = os.environ.get('MOJOLEARN_GATE_COMMIT')
    if env:
        return env
    try:
        return subprocess.run(['git', '-C', str(ROOT), 'rev-parse', 'HEAD'],
                              capture_output=True, text=True, timeout=10).stdout.strip() or None
    except (OSError, subprocess.SubprocessError):
        return None


def digest_prediction(value):
    """`(sha256, dtype, shape)` of a prediction. An Array hashes its raw
    bytes; a list of str labels hashes the UTF-8 of the labels joined by
    newlines, dtype 'str'."""
    if isinstance(value, list):
        return sha256_bytes('\n'.join(value).encode('utf-8')), 'str', [len(value)]
    return sha256_bytes(value.tobytes()), str(value.dtype), [int(s) for s in value.shape]


def digests_for(model, X, is_classifier):
    out = {}
    started = time.perf_counter()
    out['predict'] = dict(zip(('sha256', 'dtype', 'shape'), digest_prediction(model.predict(X))))
    if is_classifier:
        out['predict_proba'] = dict(zip(('sha256', 'dtype', 'shape'),
                                        digest_prediction(model.predict_proba(X))))
    out['seconds'] = round(time.perf_counter() - started, 6)
    return out


def estimator_of(model_path):
    """`(estimator, loss)` of a saved model, read with the codec and nothing
    else, so `record` can pick the class without guessing. `loss` is None
    for a forest and the archive's `loss` member for GradientBoosting."""
    from mojolearn import _serialize
    arrays = _serialize.read_npz(model_path, FOREST_FORMATS + (GBDT_FORMAT,))
    fmt = _serialize.scalar_str(arrays, 'format')
    if fmt.endswith('-parallel-groves-1'):
        raise SystemExit(f'gate: {model_path} is a parallel_groves archive; the host engine is sequential')
    name = _serialize.scalar_str(arrays, 'estimator')
    if name not in ESTIMATORS or (name in GBDT_ESTIMATORS) != (fmt == GBDT_FORMAT):
        raise SystemExit(f'gate: {model_path} was saved by {name}, not an estimator this gate reads')
    loss = _serialize.scalar_str(arrays, 'loss') if fmt == GBDT_FORMAT else None
    return name, loss


def do_make(args):
    """A GPU box, the normal package: fit one fixture of `--kind`, save it,
    and write fixture.json plus an OWED expected.json. Refuses a CPU-only
    install for the same reason `record` does."""
    package_root(args)
    import mojolearn
    from mojolearn._buffer import frombytes
    from mojolearn._array import Array
    vendor = mojolearn.vendor()
    if vendor == 'cpu':
        print('gate: make must run on a GPU box; this install is CPU-only', file=sys.stderr)
        return 2
    if mojolearn.numeric_mode() != 'identical':
        print(f'gate: make requires MOJOLEARN_NUMERIC_MODE=identical, this process is '
              f'{mojolearn.numeric_mode()}', file=sys.stderr)
        return 2
    kind = KINDS[args.kind]
    directory = args.fixture_dir
    if directory.exists() and any(directory.iterdir()):
        print(f'gate: {directory} exists and is not empty; refusing to overwrite a fixture', file=sys.stderr)
        return 2
    directory.mkdir(parents=True, exist_ok=True)
    rows, features = int(args.rows), int(args.features)
    train_raw, _, _ = fixture_bytes(dict(rows=rows, features=features, seed=int(args.train_seed),
                                         generator=GENERATOR))
    # the labels read the untransformed rows, so a coded kind keeps the
    # label rule of every other kind
    xs = struct.unpack(f'<{rows * features}f', train_raw)
    train_raw = apply_transform(train_raw, rows, features, kind.get('transform'))
    Xt = frombytes(train_raw, '<f4', (rows, features))
    x = lambda r, c: xs[r * features + c]
    if kind['classes']:
        y = Array.from_list([int((x(r, 0) * 7 + x(r, 1) * 13) * 3) % kind['classes'] for r in range(rows)], '<i8')
    else:
        y = Array.from_list([x(r, 1) * 2 + x(r, 2) for r in range(rows)], '<f8')
    cls = getattr(mojolearn, kind['estimator'])
    fit_kw = {}
    if kind['estimator'] == 'OrderedRMSE':
        params = dict(n_estimators=8, max_depth=4)
        # a fixed bijection with no RNG: rows in reverse
        fit_kw['permutation'] = Array.from_list(list(range(rows - 1, -1, -1)), '<i8')
    elif kind['estimator'] == 'ExperimentalTwoLevelFeatureFreq':
        params = dict(sources=[0, 1], random_state=7)
    elif kind['estimator'] == 'GradientBoosting':
        params = dict(n_estimators=8, max_depth=4, random_state=7, loss=kind['loss'],
                      grow_policy=kind['grow_policy'], numeric_mode='identical')
        if kind['grow_policy'] == 'Lossguide':
            params['max_leaves'] = 16
        if kind.get('transform') == CODED:
            params.update(cat_features=[0], one_hot_features=[1], permutation_count=2,
                          ctr_estimation_permutation_id=0)
        if kind.get('pointwise'):
            params.update(score_function='L2', use_pointwise_searcher=True, bootstrap_type='Bayesian',
                          bagging_temperature=0.5, boost_from_average=True)
            fit_kw['sample_weight'] = Array.from_list([0.5 + (r % 11) / 10.0 for r in range(rows)], '<f4')
    else:
        params = dict(n_estimators=8, max_depth=6, random_state=7, numeric_mode='identical',
                      inference_engine='sequential')
    model = cls(**params)
    if 'numeric_mode' not in params and hasattr(model, 'numeric_mode'):
        model.numeric_mode = 'identical'
    model = model.fit(Xt, y, **fit_kw)
    model.save(str(directory / 'model.npz'))
    spec = dict(rows=rows, features=features, seed=int(args.seed), generator=GENERATOR)
    raw, _, _ = fixture_bytes(spec)
    spec['x_sha256'] = sha256_bytes(raw)
    if kind.get('transform'):
        spec['transform'] = kind['transform']
    (directory / 'fixture.json').write_text(json.dumps(spec, indent=2, sort_keys=True) + '\n')
    (directory / 'expected.json').write_text(json.dumps(dict(
        status='OWED', kind=args.kind, estimator=kind['estimator'],
        note='run tools/forest_host_gate.py record on a GPU box'), indent=2, sort_keys=True) + '\n')
    print(f"make wrote {directory} ({args.kind}, {kind['estimator']}, vendor {vendor}, "
          f"model sha256 {sha256_bytes((directory / 'model.npz').read_bytes())})")
    return 0


def package_root(args):
    """Where `mojolearn` is imported from. The checkout's python/ by default;
    `--package-root PATH` for another checkout's package (the Mac recording
    imports the GPU build beside this worktree), `--package-root ''` for an
    installed wheel."""
    if args.package_root is None:
        sys.path.insert(0, str(ROOT / 'python'))
    elif args.package_root:
        sys.path.insert(0, os.path.abspath(args.package_root))


def do_record(args):
    """A GPU box, the normal package. Refuses to run on a CPU-only install,
    because a recording made by the host binding would compare the host
    binding with itself."""
    package_root(args)
    import mojolearn
    from mojolearn._buffer import frombytes
    vendor = mojolearn.vendor()
    if vendor == 'cpu' and not args.allow_cpu_recording:
        print('gate: record must run on a GPU box; this install is CPU-only', file=sys.stderr)
        return 2
    directory = args.fixture_dir
    spec, raw, rows, features = load_fixture(directory)
    X = frombytes(apply_transform(raw, rows, features, spec.get('transform')), '<f4', (rows, features))
    name, loss = estimator_of(directory / 'model.npz')
    cls = getattr(mojolearn, name)
    model = cls.load(str(directory / 'model.npz'))
    if getattr(model, 'inference_engine', 'sequential') != 'sequential':
        print('gate: the loaded model does not select the sequential engine', file=sys.stderr)
        return 2
    if hasattr(model, '_effective_mode'):
        mode = model._effective_mode()
    else:
        # GradientBoosting.load restores the saved tier; None means the
        # process default, which is what its predict would use
        mode = getattr(model, 'numeric_mode', None) or mojolearn.numeric_mode()
    digests = digests_for(model, X, proba_wanted(name, loss))
    report = dict(
        status='RECORDED', estimator=name, loss=loss, vendor=vendor, gpu_arch=mojolearn.gpu_arch(),
        numeric_mode=mode, inference_engine='sequential',
        model_sha256=sha256_bytes((directory / 'model.npz').read_bytes()),
        x_sha256=sha256_bytes(raw), fixture=spec, host=host_info(), commit=git_commit(),
        recorded_at=time.strftime('%Y-%m-%dT%H:%M:%S%z'), predictions=digests,
    )
    target = directory / 'expected.json'
    if target.exists() and not args.overwrite:
        existing = json.loads(target.read_text())
        if existing.get('status') == 'RECORDED':
            print(f'gate: {target} is already recorded; pass --overwrite to replace it', file=sys.stderr)
            return 2
    target.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    for key, value in digests.items():
        if isinstance(value, dict):
            print(f"record {name} {key} {value['dtype']} {value['shape']} sha256 {value['sha256']}")
    print(f'record wrote {target} (vendor {vendor}, mode {mode})')
    return 0


def do_check(args):
    """The CPU box, through HostForest or HostGBDT. The package may be a
    CPU-only install or a full GPU install; either way the prediction here
    is the host binding's."""
    package_root(args)
    try:
        import mojolearn
        from mojolearn._buffer import frombytes
        from mojolearn._forest_host import binary_path, host_model
    except Exception as exc:  # the import itself is part of what is gated
        print(f'gate: import failed: {type(exc).__name__}: {exc}', file=sys.stderr)
        return 2
    results = []
    verdict_ok = True
    for directory in args.fixture_dir:
        expected_path = directory / 'expected.json'
        model_path = directory / 'model.npz'
        if not expected_path.exists() or not model_path.exists():
            print(f'gate: {directory} is missing expected.json or model.npz; the GPU-side '
                  'recording is OWED (tools/forest_host_gate.py record on a GPU box)', file=sys.stderr)
            return 2
        expected = json.loads(expected_path.read_text())
        if expected.get('status') != 'RECORDED' or 'predictions' not in expected:
            print(f'gate: {expected_path} status is {expected.get("status")!r}; the GPU-side '
                  'recording is OWED (tools/forest_host_gate.py record on a GPU box)', file=sys.stderr)
            return 2
        try:
            spec, raw, rows, features = load_fixture(directory)
        except SystemExit as exc:
            print(exc, file=sys.stderr)
            return 2
        if expected.get('x_sha256') != sha256_bytes(raw):
            print(f'gate: {directory} expected.json was recorded for different fixture rows', file=sys.stderr)
            return 2
        model_sha = sha256_bytes(model_path.read_bytes())
        if expected.get('model_sha256') != model_sha:
            print(f'gate: {model_path} hashes {model_sha}, expected.json records '
                  f'{expected.get("model_sha256")}', file=sys.stderr)
            return 2
        try:
            X = frombytes(apply_transform(raw, rows, features, spec.get('transform')), '<f4', (rows, features))
        except SystemExit as exc:
            print(exc, file=sys.stderr)
            return 2
        try:
            model = host_model(str(model_path))
            got = digests_for(model, X, proba_wanted(model.estimator, getattr(model, 'loss', None)))
        except Exception as exc:
            print(f'gate: {directory} host predict failed: {type(exc).__name__}: {exc}', file=sys.stderr)
            return 2
        if model.estimator != expected.get('estimator'):
            print(f'gate: {directory} model is {model.estimator}, expected.json says '
                  f'{expected.get("estimator")}', file=sys.stderr)
            return 2
        if getattr(model, 'loss', None) != expected.get('loss'):
            print(f'gate: {directory} model loss is {getattr(model, "loss", None)}, expected.json says '
                  f'{expected.get("loss")}', file=sys.stderr)
            return 2
        want = expected['predictions']
        rows_out = []
        for key in ('predict', 'predict_proba'):
            if key not in want and key not in got:
                continue
            if (key in want) != (key in got):
                print(f'gate: {directory} {key} present on one side only', file=sys.stderr)
                return 2
            equal = (want[key]['sha256'] == got[key]['sha256'] and want[key]['dtype'] == got[key]['dtype']
                     and list(want[key]['shape']) == list(got[key]['shape']))
            verdict_ok = verdict_ok and equal
            rows_out.append(dict(case=key, want=want[key]['sha256'], got=got[key]['sha256'],
                                 want_dtype=want[key]['dtype'], got_dtype=got[key]['dtype'],
                                 want_shape=want[key]['shape'], got_shape=got[key]['shape'], equal=equal))
            print(f"check {directory.name} {model.estimator} {key} {'EQUAL' if equal else 'DIFFER'} "
                  f"gpu {want[key]['sha256']} host {got[key]['sha256']}")
        results.append(dict(fixture=directory.name, estimator=model.estimator, loss=getattr(model, 'loss', None),
                            recorded_vendor=expected.get('vendor'), recorded_gpu_arch=expected.get('gpu_arch'),
                            recorded_numeric_mode=expected.get('numeric_mode'),
                            model_sha256=model_sha, host_model_sha256=model.model_sha256(),
                            rows=rows, features=features, seconds=got['seconds'], cases=rows_out))
    if args.expect_mismatch:
        verdict = 'EXPECTED MISMATCH SEEN' if not verdict_ok else 'SABOTAGE NOT CAUGHT'
        code = 0 if not verdict_ok else 1
    else:
        verdict = 'IDENTICAL' if verdict_ok else 'MISMATCH'
        code = 0 if verdict_ok else 1
    report = dict(verdict=verdict, expect_mismatch=bool(args.expect_mismatch), exit=code,
                  binary=binary_path(), vendor=mojolearn.vendor(), host=host_info(),
                  commit=git_commit(), checked_at=time.strftime('%Y-%m-%dT%H:%M:%S%z'),
                  fixtures=results)
    if args.report:
        if args.report.exists():
            print(f'gate: {args.report} exists; refusing to overwrite a report', file=sys.stderr)
            return 2
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + '\n')
    print(f'gate verdict {verdict} ({len(results)} fixtures, exit {code})')
    return code


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--package-root', default=None,
                        help="directory to import mojolearn from (default: this checkout's python/; "
                             "'' for the installed package)")
    sub = parser.add_subparsers(dest='command', required=True)
    mk = sub.add_parser('make', help='on a GPU box, fit and save one fixture of --kind into a new directory')
    mk.add_argument('fixture_dir', type=Path)
    mk.add_argument('--kind', required=True, choices=sorted(KINDS))
    mk.add_argument('--rows', type=int, default=200)
    mk.add_argument('--features', type=int, default=8)
    mk.add_argument('--train-seed', type=int, default=1, help='SplitMix64 seed of the training rows')
    mk.add_argument('--seed', type=int, default=7, help='SplitMix64 seed of the held-out fixture rows')
    rec = sub.add_parser('record', help='on a GPU box, write expected.json for one fixture directory')
    rec.add_argument('fixture_dir', type=Path)
    rec.add_argument('--overwrite', action='store_true')
    rec.add_argument('--allow-cpu-recording', action='store_true',
                     help='record on a CPU-only install anyway (a self-comparison; never for a certificate)')
    chk = sub.add_parser('check', help='on the CPU box, compare the host predictions with expected.json')
    # nargs='*' so an empty list reaches the refusal below, which says what
    # is missing, instead of argparse's usage line: in the CPU identity gate
    # the list is the workflow's $RECORDED, empty when an earlier step failed.
    chk.add_argument('fixture_dir', type=Path, nargs='*')
    chk.add_argument('--report', type=Path, help='new exclusive JSON report')
    chk.add_argument('--expect-mismatch', action='store_true')
    args = parser.parse_args()
    if args.command == 'check' and not args.fixture_dir:
        print('forest_host_gate.py check: no fixture directory given, so there is nothing to check; '
              'in the CPU identity gate this is the RECORDED list, which the fixture sorting step '
              'writes and which is empty when that step or an earlier one did not run', file=sys.stderr)
        return 2
    if args.command == 'make':
        return do_make(args)
    if args.command == 'record':
        return do_record(args)
    return do_check(args)


if __name__ == '__main__':
    sys.exit(main())
