#!/bin/sh
# tools/gemm_kernel_census_leg.sh -- DEVIATION 2702: the GEMM kernel REGISTER
# CENSUS. Where do 255
# registers go when 64 accumulators need 64 and 16 accumulators still read 214?
#
# Runs ON THE POD as tools/gemm_remote_leg.sh's MOJOLEARN_GEMM_LEG_EXTRA body
# (the pattern of the kNN census, bench/results/e1g/2026-09-11_011544-nvidia/
# extra_body.sh). A generated driver (never checked in: a fixture that tracks
# the kernel parameter lists) compiles the shipped 128x128 tuned kernel, the
# ksplit group kernel, and kpack / kpack_pad (all-leaves and group) through
#   DeviceContext.compile_function[kern, dump_asm=<Path fn>, _dump_sass=<Path fn>,
#                                  _ptxas_info_verbose=True]()
# and prints the runtime's own NUM_REGS / LOCAL / SHARED / blocks-per-SM. Then
# `ptxas --verbose` on each PTX (spill stores/loads) and `cuobjdump
# --dump-resource-usage` / `--dump-sass` on its cubin. Launches nothing, times
# nothing, fetches no dataset. Everything lands in /root/gemm_leg_out/gemm-census.
# POSIX sh only: RunPod's Ubuntu images link /bin/sh to dash.
set -u
ROOT=${MOJOLEARN_GEMM_STEP_ROOT:-/root/mojolearn}
OUT=${MOJOLEARN_GEMM_STEP_LEG_OUT:-/root/gemm_leg_out/gemm-census}
DUMP="$OUT/dumps"
mkdir -p "$DUMP"
export PATH="$HOME/.pixi/bin:$PATH"
note() { echo "$*" >> "$OUT/census.txt"; }
{
    echo "deviations=2702"
    echo "started=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "root=$ROOT gpu_archs=${MOJOLEARN_GPU_ARCHS:-unset}"
} > "$OUT/census.txt"
cd "$ROOT" || { note "no $ROOT"; exit 9; }
find_tool() {
    _t=$(command -v "$1" 2>/dev/null)
    [ -z "$_t" ] && for d in /usr/local/cuda/bin /usr/local/cuda-*/bin; do [ -x "$d/$1" ] && { _t="$d/$1"; break; }; done
    printf '%s' "$_t"
}
PTXAS=$(find_tool ptxas); CUOBJDUMP=$(find_tool cuobjdump); NVDISASM=$(find_tool nvdisasm)
# The image's ptxas 12.4 refuses Mojo's PTX 8.5 (2026-09-13 leg: "Unsupported
# .version 8.5; current version is '8.4'"). The 2026-09-10 lane's route
# (bench/results/gemm_resources_2026-09-10/README.md): the pip nvcc wheel,
# no deps, into its own directory; its ptxas assembles PTX 8.5.
if [ -z "${MOJOLEARN_CENSUS_NO_PIP_PTXAS:-}" ]; then
    python3 -m pip install --no-deps --target /root/cuda126-tools nvidia-cuda-nvcc-cu12==12.6.85 > "$OUT/pip-ptxas.log" 2>&1
    note "pip_ptxas_exit=$?"
    _p=$(find /root/cuda126-tools -type f -name ptxas 2>/dev/null | head -1)
    [ -n "$_p" ] && { chmod +x "$_p"; PTXAS="$_p"; }
    _d=$(find /root/cuda126-tools -type f -name nvdisasm 2>/dev/null | head -1)
    [ -n "$_d" ] && { chmod +x "$_d"; NVDISASM="$_d"; }
fi
note "ptxas=${PTXAS:-<none>} ($( [ -n "$PTXAS" ] && "$PTXAS" --version 2>/dev/null | grep -o 'V[0-9.]*' | head -1)) cuobjdump=${CUOBJDUMP:-<none>} nvdisasm=${NVDISASM:-<none>}"
HAVE_TOOLKIT=0; [ -n "$PTXAS" ] && [ -n "$CUOBJDUMP" ] && HAVE_TOOLKIT=1
note "have_toolkit=$HAVE_TOOLKIT"

LABELS="shipped ksplit kpack_all kpack_group kpack_pad_all kpack_pad_group"
DRIVER="$OUT/census_driver.mojo"
{
cat <<'MOJO'
# Generated by tools/gemm_kernel_census_leg.sh (DEVIATION 2702). RUNS ON THE
# POD. Compiles the GEMM kernels for this device, dumps PTX and SASS, prints
# the runtime's own resource attributes. Launches nothing.
from std.pathlib import Path
from max.gpu.host import Attribute, DeviceContext
from checks.kernel_matrix import TARGET_COLUMN, lib_smem_pages_for
from gemm.checks.gemm_identical import (
    GEMM_KPACK_CPT, GEMM_KPACK_FS, GEMM_KPACK_KS, GEMM_KPACK_PAD,
    GEMM_KPACK_PAGE_GUARD_BYTES, GEMM_KPACK_RPT,
    GEMM_KSPLIT_CPT, GEMM_KSPLIT_KS, GEMM_KSPLIT_RPT,
    TUNED_CPT, TUNED_FOLD_SLOTS, TUNED_RPT, TUNED_TC, TUNED_TPB, TUNED_VECLEN,
    identical_gemm_kpack_kernel, identical_gemm_ksplit_kernel, identical_gemm_tuned_kernel,
)

comptime TR = TUNED_TPB // TUNED_TC
comptime RPT = TUNED_RPT * 2
comptime CPT = TUNED_CPT * 2
comptime BM = RPT * TR
comptime BN = CPT * TUNED_TC
comptime PAGES_SHIPPED = lib_smem_pages_for[TARGET_COLUMN, (BM + BN) * (16 + TUNED_VECLEN) * 4]()
comptime PAGES_KSPLIT = lib_smem_pages_for[
    TARGET_COLUMN, (GEMM_KSPLIT_RPT * TR + GEMM_KSPLIT_CPT * TUNED_TC) * (GEMM_KSPLIT_KS + TUNED_VECLEN) * 4
]()
comptime KP_BM = GEMM_KPACK_RPT * TR
comptime KP_BN = GEMM_KPACK_CPT * TUNED_TC
comptime PAGES_KPACK = lib_smem_pages_for[
    TARGET_COLUMN, (KP_BM + KP_BN) * GEMM_KPACK_KS * 4 + GEMM_KPACK_PAGE_GUARD_BYTES
]()
comptime PAGES_KPACK_PAD = lib_smem_pages_for[
    TARGET_COLUMN,
    (KP_BM * GEMM_KPACK_KS + TR * GEMM_KPACK_PAD + KP_BN * GEMM_KPACK_KS + TUNED_TC * GEMM_KPACK_PAD) * 4
    + GEMM_KPACK_PAGE_GUARD_BYTES,
]()

MOJO
gen() {
    # gen <label> "<kern expr>". The dump parameters take a Path VALUE in this
    # Mojo (the `fn() -> Path` member the kNN census used is gone from the
    # Variant: "Type does not exist in Variant", 2026-09-13 leg). The fallback
    # below rewrites them to the Bool form (stdout) if this does not build.
    if [ "$HAVE_TOOLKIT" = 1 ]; then
        _dump="dump_asm=Path(\"$DUMP/$1.ptx\"), _dump_sass=Path(\"$DUMP/$1.sass\"), _ptxas_info_verbose=True"
    else
        _dump="dump_asm=Path(\"$DUMP/$1.ptx\")"
    fi
    cat <<MOJO
def stat_$1(ctx: DeviceContext) raises:
    comptime kern = $2
    print("GEMM_CENSUS_BEGIN label=$1")
    var f = ctx.compile_function[kern, $_dump]()
    print(
        "GEMM_CENSUS label=$1",
        " regs=", f.get_attribute(Attribute.NUM_REGS),
        " local=", f.get_attribute(Attribute.LOCAL_SIZE_BYTES),
        " shared=", f.get_attribute(Attribute.SHARED_SIZE_BYTES),
        " max_threads=", f.get_attribute(Attribute.MAX_THREADS_PER_BLOCK),
        " blocks_per_sm_256=", f.occupancy_max_active_blocks_per_multiprocessor(TUNED_TPB, 0),
        sep="",
    )

MOJO
}
gen shipped "identical_gemm_tuned_kernel[RPT, CPT, TUNED_TC, 16, TUNED_FOLD_SLOTS, PAGES_SHIPPED]"
gen ksplit "identical_gemm_ksplit_kernel[GEMM_KSPLIT_RPT, GEMM_KSPLIT_CPT, TUNED_TC, GEMM_KSPLIT_KS, PAGES_KSPLIT, False]"
gen kpack_all "identical_gemm_kpack_kernel[GEMM_KPACK_RPT, GEMM_KPACK_CPT, TUNED_TC, GEMM_KPACK_KS, GEMM_KPACK_FS, PAGES_KPACK, False, False]"
gen kpack_group "identical_gemm_kpack_kernel[GEMM_KPACK_RPT, GEMM_KPACK_CPT, TUNED_TC, GEMM_KPACK_KS, GEMM_KPACK_FS, PAGES_KPACK, True, False]"
gen kpack_pad_all "identical_gemm_kpack_kernel[GEMM_KPACK_RPT, GEMM_KPACK_CPT, TUNED_TC, GEMM_KPACK_KS, GEMM_KPACK_FS, PAGES_KPACK_PAD, False, False, GEMM_KPACK_PAD]"
gen kpack_pad_group "identical_gemm_kpack_kernel[GEMM_KPACK_RPT, GEMM_KPACK_CPT, TUNED_TC, GEMM_KPACK_KS, GEMM_KPACK_FS, PAGES_KPACK_PAD, True, False, GEMM_KPACK_PAD]"
cat <<'MOJO'
def main() raises:
    var ctx = DeviceContext()
MOJO
for l in $LABELS; do
    printf '    try:\n        stat_%s(ctx)\n    except e:\n        print("GEMM_CENSUS_ERROR label=%s error=", e, sep="")\n' "$l" "$l"
done
echo '    print("GEMM_CENSUS_DONE")'
} > "$DRIVER"

if pixi run mojo build -I . -D MOJOLEARN_NUMERIC_IDENTICAL=1 -D MOJOLEARN_GEMM_ARM_TRIAL=1 \
    "$DRIVER" -o "$OUT/census_driver" > "$OUT/build.log" 2>&1; then
    note "build=0"
else
    note "build=$?"
    # Fallback: the Bool dump form, everything to stdout (PTX, and SASS plus
    # ptxas info where the toolkit exists); tools/gemm_census_split.py cuts it.
    if [ "$HAVE_TOOLKIT" = 1 ]; then
        sed -i 's/dump_asm=Path("[^"]*"), _dump_sass=Path("[^"]*"), _ptxas_info_verbose=True/dump_asm=True, _dump_sass=True, _ptxas_info_verbose=True/' "$DRIVER"
    else
        sed -i 's/dump_asm=Path("[^"]*")/dump_asm=True/' "$DRIVER"
    fi
    pixi run mojo build -I . -D MOJOLEARN_NUMERIC_IDENTICAL=1 -D MOJOLEARN_GEMM_ARM_TRIAL=1 \
        "$DRIVER" -o "$OUT/census_driver" > "$OUT/build2.log" 2>&1 && note "build_fallback=0" || { note "build_fallback=$?"; exit 9; }
fi
"$OUT/census_driver" > "$OUT/census.log" 2>&1
note "run=$?"
grep -h '^GEMM_CENSUS' "$OUT/census.log" >> "$OUT/census.txt"

# ---- offline assembly: spills and resource usage per PTX ------------------
if [ "$HAVE_TOOLKIT" = 1 ]; then
    for p in "$DUMP"/*.ptx; do
        [ -f "$p" ] || continue
        stem=${p%.ptx}
        arch=$(grep -m1 -oE '^\.target[[:space:]]+sm_[0-9a-z]+' "$p" | awk '{print $2}')
        "$PTXAS" --verbose --gpu-name "${arch:-sm_90a}" -o "$stem.cubin" "$p" > "$stem.ptxas.log" 2>&1
        note "ptxas $(basename "$stem") exit=$? $(grep -h 'Used\|spill' "$stem.ptxas.log" | tr '\n' ' ' | tr -s ' ')"
        [ -f "$stem.cubin" ] && "$CUOBJDUMP" --dump-resource-usage "$stem.cubin" > "$stem.resources.log" 2>&1
        # The runtime's _dump_sass wrote EMPTY files on 2026-09-13; take the SASS
        # from the cubin, nvdisasm first (the pip one reads its own cubins), then cuobjdump.
        if [ -f "$stem.cubin" ] && [ ! -s "$stem.sass" ]; then
            { [ -n "$NVDISASM" ] && "$NVDISASM" -c "$stem.cubin" > "$stem.sass" 2> "$stem.nvdisasm.err"; } \
                || "$CUOBJDUMP" --dump-sass "$stem.cubin" > "$stem.sass" 2>&1
            note "sass $(basename "$stem") bytes=$(wc -c < "$stem.sass" | tr -d ' ') ffma=$(grep -c FFMA "$stem.sass")"
        fi
    done
fi

# ---- Nsight Compute: the stall breakdown, where the box allows counters ----
# The one instrument that names latency against issue directly. Profiles the
# price binary under the shipped arm, a handful of GEMM launches, sections
# only (no full set), and records the permission refusal if the container
# has none (ERR_NVGPUCTRPERM). Launches kernels; that is its purpose.
NCU=$(find_tool ncu)
[ -z "$NCU" ] && for d in /opt/nvidia/nsight-compute/*/ /usr/local/cuda/nsight-compute-*/; do [ -x "${d}ncu" ] && { NCU="${d}ncu"; break; }; done
note "ncu=${NCU:-<none>}"
if [ -n "$NCU" ]; then
    if pixi run mojo build -I . -D MOJOLEARN_NUMERIC_IDENTICAL=1 -D MOJOLEARN_GEMM_ARM_TRIAL=1 \
        bench/gemm_step_price_main.mojo -o "$OUT/step-price" > "$OUT/build-price.log" 2>&1; then
        env MOJOLEARN_GEMM_ARM=shipped MOJOLEARN_GEMM_ARM_SABOTAGE=0 MOJOLEARN_GEMM_STEP_ROUNDS=1 MOJOLEARN_GEMM_STEP_WARMUPS=0 \
            "$NCU" --target-processes all --launch-count 16 --kernel-name regex:gemm \
            --section SpeedOfLight --section Occupancy --section SchedulerStats --section WarpStateStats \
            --section ComputeWorkloadAnalysis --section MemoryWorkloadAnalysis --section LaunchStats \
            "$OUT/step-price" > "$OUT/ncu.log" 2>&1
        note "ncu_exit=$? $(grep -c 'Section: Warp State' "$OUT/ncu.log") warp-state sections; $(grep -m1 -o 'ERR_NVGPUCTRPERM[^ ]*' "$OUT/ncu.log")"
    else
        note "ncu skipped: price build failed"
    fi
fi
gzip -9 "$DUMP"/*.ptx "$DUMP"/*.sass 2>/dev/null
rm -f "$DUMP"/*.cubin
note "finished=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
