#!/usr/bin/env python3
"""Materialize audited full-workload facts and deployed build receipts, without execution.

Input --workloads is a mapping of matrix workload_id to a saved recipe fact record.
Records carry every field required by six_lane_ab.queue except source_sha,
benchmark_sha256, packages and artifact_provenance. Coverage resolutions must be
retained evidence, not a claim generated by this tool. No dataset/settings/caps
are inferred from an experiment title or from --rows full.

Input --deployments is a list of {configuration, vendor, target_track, packages,
artifacts, optional workload_id}. A workload-specific deployment takes precedence over
a configuration-wide deployment. packages maps A/B to isolated package roots. artifacts maps A/B to
lists of {path, receipt}; path is the deployed shared library and receipt is the
compile receipt. Both arms must name the same target track. Every artifact is
checked against the frozen numerical source closure and exact compiler defines.
Bindings unrelated to the switch can declare prerequisite=true; these still
require matching mode/vendor/source/target, and cannot satisfy the required
candidate binding receipt. Deployment is separate so remote paths are concrete.

Outputs recipes.json (consumed by six_lane_ab queue --recipes) and coverage.json.
Incomplete cells are retained as blocked; success here never means measured or
quality/identity accepted. This command does not import product modules, load
arrays, launch workers, compile, or authorize execution.
"""
from __future__ import annotations
import argparse
import copy
import functools
import json
from pathlib import Path
from six_lane_ab import ROOT, STORE, check_benchmark, digest as file_digest, git, write, runtime_requirements

@functools.lru_cache(maxsize=None)
def _cached_digest(path, size, modified_ns):
    return file_digest(path)


def digest(path):
    path=Path(path).resolve();stat=path.stat()
    return _cached_digest(str(path),stat.st_size,stat.st_mtime_ns)


FACT_FIELDS=('dataset_sha256','dimensions','estimator_settings','timed_boundary',
             'intrinsic_caps','full_dataset_coverage','workload',
             'coverage_resolutions','resource_policy')


def validate_facts(facts, cell):
    absent=[k for k in FACT_FIELDS if k not in facts]
    if absent:raise ValueError('Missing saved recipe fields: '+','.join(absent))
    from six_lane_full_variants import validate_variant
    validate_variant(facts, cell)
    if facts['full_dataset_coverage'] is not True:
        raise ValueError('Incomplete frozen workload')
    work=facts['workload']
    required=('harness','harness_sha256','lane','input_files','actual_shapes',
              'estimator_settings_record','intrinsic_cap_audit','inference',
              'dataset_version','split','seed','output_paths','runtime_vendor','quality_gate_source')
    if any(k not in work for k in required):raise ValueError('Incomplete saved worker workload facts')
    if digest(ROOT/work['harness'])!=work['harness_sha256']:raise ValueError('Saved harness drift')
    if work.get('overrides') or work.get('adapter'):raise ValueError('Alternate runtime recipe is not supported')
    audit=work['intrinsic_cap_audit']
    if not audit.get('reviewed') or audit.get('unresolved'):raise ValueError('Unresolved intrinsic caps')
    if not work['input_files']:raise ValueError('No concrete dataset files')
    for item in work['input_files']:
        if digest(item['path'])!=item['sha256']:raise ValueError('Input hash differs: '+item['path'])
    if work['actual_shapes']!=facts['dimensions'] or work['estimator_settings_record']!=facts['estimator_settings']:
        raise ValueError('Saved dimensions/settings disagree')
    resolutions=facts['coverage_resolutions']
    if set(resolutions)!=set(cell['blockers']):raise ValueError('Every cell coverage gap needs exact retained resolution evidence')
    for reason,evidence in resolutions.items():
        if not evidence.get('conclusion') or digest(evidence['path'])!=evidence['sha256']:
            raise ValueError('Missing or changed gap evidence: '+reason)


def receipt_track(receipt):
    """Read legacy exact argv without relabeling native images as default/PTX."""
    if receipt.get('target_track'):return receipt['target_track']
    argv=receipt['argv'];vendor=receipt['vendor']
    target=argv[argv.index('--target-accelerator')+1] if '--target-accelerator' in argv else None
    if vendor=='nvidia':
        if target and not target.startswith('sm_'):raise ValueError('Unknown NVIDIA target')
        return 'nvidia-native' if target else 'nvidia-default'
    if vendor=='amd':
        if not target or not target.startswith('gfx'):raise ValueError('Missing native AMD target')
        return 'amd-'+target
    return vendor


def validate_deployment(deployment, configuration, vendor):
    provenance={}
    for arm in ('A','B'):
        package=Path(deployment['packages'][arm]).resolve()
        if package==ROOT/'python' or not (package/'mojolearn').is_dir():raise ValueError('Expected isolated package')
        items=deployment['artifacts'][arm]
        if not items:raise ValueError('Missing deployed artifacts')
        provenance[arm]=[];candidate=False
        expected=set(configuration[arm]['defines'])
        if configuration['mode']=='identical':expected.add('MOJOLEARN_NUMERIC_IDENTICAL=1')
        for item in items:
            receipt=json.loads(Path(item['receipt']).read_text());path=Path(item['path']).resolve()
            if not path.is_relative_to(package):raise ValueError('Deployed artifact is outside isolated package')
            if receipt.get('status')!='COMPILED' or receipt.get('vendor')!=vendor or receipt.get('mode')!=configuration['mode']:
                raise ValueError('Artifact has incompatible build status/vendor/mode')
            if receipt_track(receipt)!=deployment['target_track']:raise ValueError('Artifact target track mismatch')
            if not receipt.get('source_files') or any(digest(ROOT/p)!=h for p,h in receipt['source_files'].items()):
                raise ValueError('Artifact numerical source closure differs from freeze')
            if digest(path)!=receipt['artifact_sha256']:raise ValueError('Deployed artifact hash differs')
            if not receipt.get('compiler_sha256') or not receipt.get('compiler'):raise ValueError('Missing compiler provenance')
            if not item.get('prerequisite'):
                if set(receipt['defines'])!=expected:raise ValueError('Artifact defines differ from selected A/B control')
                if not any(x['configuration']==configuration['id'] and x['arm']==arm for x in receipt['configurations']):
                    raise ValueError('Artifact is not attributed to this configuration/arm')
                candidate=True
            provenance[arm].append(dict(path=str(path),sha256=receipt['artifact_sha256'],
                numerical_source_sha=receipt['source_sha'],compiler=receipt['compiler'],
                compiler_sha256=receipt['compiler_sha256'],target=deployment['target_track'],
                defines=receipt['defines'],receipt=str(Path(item['receipt']).resolve()),
                source_closure_sha256=receipt['source_closure_sha256']))
        if not candidate:raise ValueError('Only prerequisites were deployed; candidate binding missing')
    return provenance


def materialize(args):
    check_benchmark()
    source=git('rev-parse','HEAD')
    if git('status','--porcelain','--untracked-files=all'):raise ValueError('Materialization requires a clean freeze')
    output=args.output.resolve()
    if output.is_relative_to(ROOT):raise ValueError('Keep materialized evidence outside the source freeze')
    matrix=json.loads(args.matrix.read_text());facts=json.loads(args.workloads.read_text())
    deployments=json.loads(args.deployments.read_text());index={}
    for deployment in deployments:
        key=(deployment['configuration'],deployment['vendor'],deployment['target_track'],deployment.get('workload_id'))
        if key in index:raise ValueError('Ambiguous duplicate deployment')
        index[key]=deployment
    configurations={c['id']:c for c in matrix['configurations']};recipes={};coverage=[]
    for cell in matrix['cells']:
        if cell['vendor']!=args.vendor or (args.select and cell['configuration'] not in args.select):continue
        entry=dict(key=cell['key'],configuration=cell['configuration'],workload_id=cell['workload_id'],status='BLOCKED')
        try:
            config=configurations[cell['configuration']]
            if cell['status']!='PENDING_COVERAGE' or config['problems']:raise ValueError('Non-executable matrix status: '+cell['status'])
            if runtime_requirements(config,cell['workload_id'],configurations):raise ValueError('No unchanged saved runtime-operation adapter')
            if cell['workload_id'] not in facts:raise ValueError('Missing audited saved full-workload facts')
            deployment=index.get((config['id'],args.vendor,args.target_track,cell['workload_id'])) or index.get((config['id'],args.vendor,args.target_track,None))
            if deployment is None:raise ValueError('Missing deployed A/B full bindings')
            fact=copy.deepcopy(facts[cell['workload_id']]);validate_facts(fact,cell)
            provenance=validate_deployment(deployment,config,args.vendor)
            fact.update(source_sha=source,benchmark_sha256=digest(STORE/'benchmark.json'),
                        packages=deployment['packages'],artifact_provenance=provenance)
            recipes[cell['key']]=fact;entry['status']='MATERIALIZED_NOT_EXECUTED'
        except (ValueError,KeyError,OSError) as exc:entry['reason']=str(exc)
        coverage.append(entry)
    write(output/'recipes.json',recipes)
    summary=dict(source_sha=source,vendor=args.vendor,target_track=args.target_track,
                 selected=len(coverage),materialized=len(recipes),blocked=len(coverage)-len(recipes),
                 execution='NOT RUN',quality='NOT ASSESSED',identity='NOT ASSESSED',cells=coverage)
    write(output/'coverage.json',summary)
    print(json.dumps({k:v for k,v in summary.items() if k!='cells'}))


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--matrix',type=Path,default=STORE/'matrix.json')
    p.add_argument('--workloads',type=Path,required=True);p.add_argument('--deployments',type=Path,required=True)
    p.add_argument('--vendor',choices=('nvidia','amd','apple','host'),required=True)
    p.add_argument('--target-track',required=True);p.add_argument('--select',action='append');p.add_argument('--output',type=Path,required=True)
    materialize(p.parse_args())

if __name__=='__main__':main()
