# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Hendel. Part of mojolearn, https://doi.org/10.5281/zenodo.22068632
"""All seven `feature_border_type`s against CatBoost 1.2.10's own borders.

    pixi run check-border-types

`bench/border_types_oracle.txt` (regenerated by `tools/border_types_oracle.py`
from `Pool.quantize` + `save_quantization_borders`) holds six columns built
to exercise each binarizer -- a 256-level integer grid, a smooth normal, a
log-normal spanning orders of magnitude, seven discrete levels, a signed
quarter grid with zeros, and one dominant value -- and CatBoost's borders at
budgets 1, 7, 15, 32, 63, 128 and 254 for every type: 294 cases, compared
here by float32 BITS. GreedyLogSum runs `best_split`, the default path, and
the other six `select_borders`, the arm the fit's phase B and the host
oracle share.

THE NEGATIVE CONTROL MUST FAIL. Built with
`-D MOJOLEARN_BORDER_TYPES_SABOTAGE=1` (`pixi run check-border-types-sabotage`)
`select_borders` drops its middle border. The same comparison then fails,
exit nonzero, and its per-type table shows WHERE: every non-default case
with a border red, all 42 GreedyLogSum cases still green, because the
sabotage lives on the non-default arm only. A sabotage the gate cannot see
is a gate that proves nothing; a sabotage that also moved GreedyLogSum
would be reaching the wrong branch.
"""
from std.memory import bitcast

from gbdt.grid_creator.binarization import (
    BORDER_TYPES_SABOTAGE,
    BORDER_TYPE_GREEDY_LOG_SUM,
    best_split,
    border_type_from_name,
    select_borders,
)


def _bits_to_f32(tok: String) raises -> Float32:
    return bitcast[DType.float32](UInt32(Int(tok)))


def main() raises:
    var f = open("bench/border_types_oracle.txt", "r")
    var text = f.read()
    f.close()
    var lines = List[String]()
    for line in text.splitlines():
        var s = String(String(line).strip())
        if s.byte_length() > 0:
            lines.append(s^)

    var pos = 0
    var ncol = Int(String(lines[pos].split(" ")[1]))
    pos += 1
    var cols = List[List[Float32]]()
    for _ in range(ncol):
        var n = Int(String(lines[pos].split(" ")[2]))
        pos += 1
        var c = List[Float32]()
        for i in range(n):
            c.append(_bits_to_f32(lines[pos + i]))
        pos += n
        cols.append(c^)

    var ncase = Int(String(lines[pos].split(" ")[1]))
    pos += 1
    var failed_default = 0
    var failed_other = 0
    var other_with_borders = 0
    var names = List[String]()
    var type_cases = List[Int]()
    var type_exact = List[Int]()
    for _ in range(ncase):
        var hh = lines[pos].split(" ")
        var cid = Int(String(hh[1]))
        var tname = String(hh[2])
        var budget = Int(String(hh[3]))
        var nb = Int(String(hh[4]))
        pos += 1
        var exp = List[Float32]()
        for i in range(nb):
            exp.append(_bits_to_f32(lines[pos + i]))
        pos += nb
        var code = border_type_from_name(tname)
        var got: List[Float32]
        if code == BORDER_TYPE_GREEDY_LOG_SUM:
            got = best_split(cols[cid].copy(), budget)
        else:
            got = select_borders(cols[cid].copy(), budget, code)
            if nb > 0:
                other_with_borders += 1
        var same = len(got) == len(exp)
        if same:
            for i in range(len(exp)):
                if bitcast[DType.uint32](got[i]) != bitcast[DType.uint32](exp[i]):
                    same = False
                    break
        var slot = -1
        for k in range(len(names)):
            if names[k] == tname:
                slot = k
        if slot < 0:
            names.append(tname)
            type_cases.append(0)
            type_exact.append(0)
            slot = len(names) - 1
        type_cases[slot] += 1
        if same:
            type_exact[slot] += 1
        else:
            var wrong = 0
            for i in range(min(len(got), len(exp))):
                if got[i] != exp[i]:
                    wrong += 1
            if not BORDER_TYPES_SABOTAGE:
                print("  col", cid, tname, "budget", budget, ": FAIL catboost",
                      len(exp), "borders, ours", len(got), ",", wrong,
                      "of the common prefix differ")
            if code == BORDER_TYPE_GREEDY_LOG_SUM:
                failed_default += 1
            else:
                failed_other += 1
    for k in range(len(names)):
        print("  ", names[k], ":", type_exact[k], "of", type_cases[k],
              "cases match CatBoost by bits")
    if BORDER_TYPES_SABOTAGE:
        print("  SABOTAGE build: non-default failures", failed_other, "of",
              other_with_borders, "with borders; GreedyLogSum failures",
              failed_default)
    if failed_default + failed_other != 0:
        raise Error(
            "border types disagree with CatBoost in "
            + String(failed_default + failed_other) + " of "
            + String(ncase) + " cases"
        )
    print("  all", ncase, "cases match CatBoost exactly")
