#!/bin/sh
# tools/model_leg/run_leg_cpu.sh: THE CPU COLUMN OF THE MODEL LEG, on one
# RunPod CPU pod (no GPU) through tools/runpod_cpu_leg.sh, the host bindings
# built through its cache and the model through the harness's host route.
# The incumbent runs on the same CPU in float32 (torch's CPU wheel).
#
#   sh tools/model_leg/run_leg_cpu.sh                   DRY RUN: creates nothing
#   sh tools/model_leg/run_leg_cpu.sh --rent            creates the pod (billed by the vCPU)
#   sh tools/model_leg/run_leg_cpu.sh --rent --vcpu 16 --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
#
# ENVIRONMENT
#   MOJOLEARN_RUNPOD_KEY_FILE, ~/.mojolearn_r2   as tools/runpod_cpu_leg.sh reads them
#   MOJOLEARN_MODEL_LEG_HOST_FAMILIES  the host families built on the pod (default
#                                      core,linalg,transformer,tokenizer; lane B2 names
#                                      what mojolearn.models needs on a CPU)
#   MOJOLEARN_EVIDENCE_ROOT            default $HOME/mojolearn-evidence; the leg lands in
#                                      $MOJOLEARN_EVIDENCE_ROOT/model-leg/<stamp>-cpu-runpod/
#                                      and the records in its remote/leg_out/model-leg/
#   MOJOLEARN_MODEL_LEG_*              FORMATS, MAX_NEW, RUNS, TRANSFORMERS_PIN: baked in
#
# A GitHub standard runner is the other home for this column
# (.github/workflows/cpu-identity-gate.yml is the pattern); no workflow is
# added here, because the model files and the torch CPU wheel are about 2 GB
# of download per run and the pod caches neither.
set -u
REPO=$(cd "$(dirname "$0")/../.." && pwd) || exit 2
cd "$REPO" || exit 2
MODE=dry; MODEL=${MOJOLEARN_MODEL_LEG_MODEL:-HuggingFaceTB/SmolLM2-360M}; VCPU=${MOJOLEARN_MODEL_LEG_VCPU:-8}
while [ $# -gt 0 ]; do
    case "$1" in
        --rent) MODE=rent ;;
        --dry-run) MODE=dry ;;
        --model) shift; MODEL=${1:-} ;;
        --vcpu) shift; VCPU=${1:-} ;;
        -h|--help) sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument '$1'" >&2; exit 2 ;;
    esac
    shift
done
case "$MODEL" in *[!A-Za-z0-9_./-]*|'') echo "--model '$MODEL': letters, digits and _./- only" >&2; exit 2 ;; esac
case "$VCPU" in ''|*[!0-9]*) echo "--vcpu must be a whole number" >&2; exit 2 ;; esac
FAMILIES=${MOJOLEARN_MODEL_LEG_HOST_FAMILIES:-core,linalg,transformer,tokenizer}
STAMP=$(date -u +%Y-%m-%d_%H%M%S)
EVIDENCE=${MOJOLEARN_EVIDENCE_ROOT:-$HOME/mojolearn-evidence}
OUT=$EVIDENCE/model-leg/$STAMP-cpu-runpod
mkdir -p "$OUT" || exit 2
COMMIT=$(git rev-parse HEAD)
CMD=$OUT/model_leg_cmd.generated.sh
{
    echo "# Generated by tools/model_leg/run_leg_cpu.sh at $STAMP for commit $COMMIT; runs with bash in /root/mojolearn on the pod."
    echo "export MOJOLEARN_MODEL_LEG_ROOT=\"\$PWD\" MOJOLEARN_MODEL_LEG_OUT=\"\$LEG_OUT/model-leg\""
    echo "export MOJOLEARN_MODEL_LEG_SKIP_BUILD=1 MOJOLEARN_MODEL_LEG_MODEL_DIR=/root/model-leg-models/$(printf '%s' "$MODEL" | sed 's|/|__|g')"
    echo "export MOJOLEARN_MODEL_LEG_MODEL='$MODEL' MOJOLEARN_MODEL_LEG_VENV=/root/.venv-model-leg"
    _bad='*[!A-Za-z0-9_.,:/= -]*'
    for v in FORMATS MAX_NEW RUNS TRANSFORMERS_PIN LABEL; do
        eval "_val=\${MOJOLEARN_MODEL_LEG_$v:-}"
        case "$_val" in $_bad) echo "MOJOLEARN_MODEL_LEG_$v carries a character the body refuses" >&2; exit 2 ;; esac
        [ -n "$_val" ] && echo "export MOJOLEARN_MODEL_LEG_$v='$_val'"
    done
    echo 'sh tools/model_leg/leg_body.sh'
} > "$CMD" || exit 2
sh -n "$CMD" || exit 2
echo "leg out:  $OUT"
echo "command:  $CMD"
echo "model:    $MODEL    vcpu: $VCPU    host families: $FAMILIES    commit: $COMMIT"
RENT=""
[ "$MODE" = rent ] && RENT=--rent || echo "DRY RUN: the runner's own dry run follows; nothing is created."
bash tools/runpod_cpu_leg.sh --lane model-leg --worktree "$REPO" --build "$FAMILIES" --envs default \
    --vcpu "$VCPU" --lease 60 --out "$OUT" --cmd-file "$CMD" $RENT
rc=$?
[ "$MODE" = rent ] && echo "records: $OUT/remote/leg_out/model-leg/ (ours.<label>.json, torch.<label>.json, ratio.txt, status.tsv)"
exit $rc
