#!/bin/sh
# tools/model_leg/run_leg_amd.sh: THE AMD COLUMN OF THE MODEL LEG, on a
# DigitalOcean MI325X (gfx942) through tools/do_extra_leg.sh (its guards,
# dead-men, bundle and fetch are that file's; this one only generates the body).
#
#   sh tools/model_leg/run_leg_amd.sh                   DRY RUN: rents nothing
#   sh tools/model_leg/run_leg_amd.sh --rent            RENTS. BILLS. One hour.
#   sh tools/model_leg/run_leg_amd.sh --rent --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
#
# ENVIRONMENT
#   MOJOLEARN_DO_TOKEN_FILE        default ~/.mojolearn_do_token (0600, outside the repo)
#   MOJOLEARN_MODEL_LEG_MINUTES    default 60 (the runner's hard cap)
#   MOJOLEARN_EVIDENCE_ROOT        default $HOME/mojolearn-evidence; the leg lands in
#                                  $MOJOLEARN_EVIDENCE_ROOT/model-leg/<stamp>-amd-mi325x/
#                                  and the records in its remote/model-leg/
#   MOJOLEARN_MODEL_LEG_*          FORMATS, MAX_NEW, RUNS, BUILDS, HOST_BUILDS,
#                                  TRANSFORMERS_PIN, CPU_COLUMN_ALSO: baked into the body
#
# The gates are skipped (--skip-gates): the gemm card is another lane's gate
# and this leg's hour is for the model. The runner exports
# MOJOLEARN_GPU_ARCHS=gfx942 and MOJOLEARN_TARGET_COLUMN=amd to the body.
set -u
REPO=$(cd "$(dirname "$0")/../.." && pwd) || exit 2
cd "$REPO" || exit 2
MODE=dry; MODEL=${MOJOLEARN_MODEL_LEG_MODEL:-HuggingFaceTB/SmolLM2-360M}
while [ $# -gt 0 ]; do
    case "$1" in
        --rent) MODE=rent ;;
        --dry-run) MODE=dry ;;
        --model) shift; MODEL=${1:-} ;;
        -h|--help) sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument '$1'" >&2; exit 2 ;;
    esac
    shift
done
case "$MODEL" in *[!A-Za-z0-9_./-]*|'') echo "--model '$MODEL': letters, digits and _./- only" >&2; exit 2 ;; esac
MINUTES=${MOJOLEARN_MODEL_LEG_MINUTES:-60}
STAMP=$(date -u +%Y-%m-%d_%H%M%S)
EVIDENCE=${MOJOLEARN_EVIDENCE_ROOT:-$HOME/mojolearn-evidence}
OUT=$EVIDENCE/model-leg/$STAMP-amd-mi325x
mkdir -p "$OUT" || exit 2
COMMIT=$(git rev-parse HEAD)
BODY=$OUT/model_leg_body.generated.sh
{
    echo '#!/bin/sh'
    echo "# Generated by tools/model_leg/run_leg_amd.sh at $STAMP for commit $COMMIT. RUNS ON THE DROPLET."
    echo "[ -s /root/mojolearn/commit.txt ] || echo '$COMMIT' > /root/mojolearn/commit.txt"
    echo "export MOJOLEARN_COMMIT='$COMMIT'"
    echo "export MOJOLEARN_MODEL_LEG_MODEL='$MODEL'"
    _bad='*[!A-Za-z0-9_.,:/= -]*'
    for v in FORMATS MAX_NEW RUNS BUILDS HOST_BUILDS TRANSFORMERS_PIN CPU_COLUMN_ALSO LABEL; do
        eval "_val=\${MOJOLEARN_MODEL_LEG_$v:-}"
        case "$_val" in $_bad) echo "MOJOLEARN_MODEL_LEG_$v carries a character the body refuses" >&2; exit 2 ;; esac
        [ -n "$_val" ] && echo "export MOJOLEARN_MODEL_LEG_$v='$_val'"
    done
    echo 'exec sh /root/mojolearn/tools/model_leg/leg_body.sh'
} > "$BODY" || exit 2
sh -n "$BODY" || exit 2
echo "leg out:  $OUT"
echo "body:     $BODY"
echo "model:    $MODEL    minutes: $MINUTES    commit: $COMMIT"
DRY=""
[ "$MODE" = dry ] && { DRY=--dry-run; echo "DRY RUN: the runner's own dry run follows; nothing is rented."; }
MOJOLEARN_GPU_ARCHS=gfx942 MOJOLEARN_GEMM_LEG_EXTRA="$BODY" MOJOLEARN_GEMM_LEG_OUT="$OUT" \
    bash tools/do_extra_leg.sh amd --minutes "$MINUTES" --skip-gates $DRY
rc=$?
[ "$MODE" = rent ] && echo "records: $OUT/remote/model-leg/ (ours.<label>.json, torch.<label>.json, ratio.txt, status.tsv)"
exit $rc
