#!/bin/sh
# tools/model_leg/run_leg_cpu.sh: THE CPU COLUMN OF THE MODEL LEG, on one
# RunPod CPU pod (no GPU) through tools/runpod_cpu_leg.sh, the host bindings
# built through its cache and the model through the harness's host route.
# The incumbent runs on the same CPU in float32 (torch's CPU wheel).
#
#   sh tools/model_leg/run_leg_cpu.sh                   DRY RUN: creates nothing
#   sh tools/model_leg/run_leg_cpu.sh --rent            creates the pod (billed by the vCPU)
#   sh tools/model_leg/run_leg_cpu.sh --rent --vcpu 16 --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
#   sh tools/model_leg/run_leg_cpu.sh --rent --allow-hf-download   against DEVIATION 2704; warns
#
# THE MODEL COMES FROM THE R2 DATASET STORE (DEVIATION 2704).
# tools/runpod_cpu_leg.sh has no tools/stage_from_r2.sh hook of its own, so
# this wrapper does on the Mac exactly what `tools/dataset_store.sh stage`
# does: it mints one presigned GET per key of the group models/<name> and
# writes the store's own self-verifying `box-cmd` fetch for each into the
# generated command file, which the runner ships and runs on the pod before
# the body. The URLs travel inside that file (0600, under the evidence
# directory, never in argv); the R2 secret never leaves this Mac; the pod
# refuses any file whose size or sha256 differs from
# bench/results/dataset_store/manifest.tsv. The files land at
# /root/models/<name>/ and the body refuses an unstaged model.
#
# ENVIRONMENT
#   ~/.mojolearn_r2, MOJOLEARN_RUNPOD_KEY_FILE   as tools/dataset_store.sh and tools/runpod_cpu_leg.sh read them
#   MOJOLEARN_MODEL_LEG_HOST_FAMILIES  the host families built on the pod (default
#                                      core,linalg,transformer,tokenizer; lane B2 names
#                                      what mojolearn.models needs on a CPU)
#   MOJOLEARN_EVIDENCE_ROOT            default $HOME/mojolearn-evidence; the leg lands in
#                                      $MOJOLEARN_EVIDENCE_ROOT/model-leg/<stamp>-cpu-runpod/
#                                      and the records in its remote/leg_out/model-leg/
#   MOJOLEARN_MODEL_LEG_*              FORMATS, MAX_NEW, RUNS, TRANSFORMERS_PIN: baked in
#
# A GitHub standard runner is the other home for this column
# (.github/workflows/cpu-identity-gate.yml is the pattern); no workflow is
# added here, because a hosted runner cannot be handed the store's presigned
# URLs without a secret in the workflow, and the torch CPU wheel is a large
# download per run.
set -u
REPO=$(cd "$(dirname "$0")/../.." && pwd) || exit 2
cd "$REPO" || exit 2
MODE=dry; MODEL=${MOJOLEARN_MODEL_LEG_MODEL:-HuggingFaceTB/SmolLM2-360M}; VCPU=${MOJOLEARN_MODEL_LEG_VCPU:-8}; ALLOW_HF=0
while [ $# -gt 0 ]; do
    case "$1" in
        --rent) MODE=rent ;;
        --dry-run) MODE=dry ;;
        --model) shift; MODEL=${1:-} ;;
        --vcpu) shift; VCPU=${1:-} ;;
        --allow-hf-download) ALLOW_HF=1 ;;
        -h|--help) sed -n '2,38p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument '$1'" >&2; exit 2 ;;
    esac
    shift
done
case "$MODEL" in *[!A-Za-z0-9_./-]*|'') echo "--model '$MODEL': letters, digits and _./- only" >&2; exit 2 ;; esac
case "$VCPU" in ''|*[!0-9]*) echo "--vcpu must be a whole number" >&2; exit 2 ;; esac
NAME=$(basename "$MODEL")
FAMILIES=${MOJOLEARN_MODEL_LEG_HOST_FAMILIES:-core,linalg,transformer,tokenizer}
STAMP=$(date -u +%Y-%m-%d_%H%M%S)
EVIDENCE=${MOJOLEARN_EVIDENCE_ROOT:-$HOME/mojolearn-evidence}
OUT=$EVIDENCE/model-leg/$STAMP-cpu-runpod
mkdir -p "$OUT" || exit 2
COMMIT=$(git rev-parse HEAD)
MANIFEST=bench/results/dataset_store/manifest.tsv
KEYS=$(awk -F'\t' -v p="models/$NAME/" 'index($1, p) == 1 { print $1 }' "$MANIFEST" 2>/dev/null)
if [ "$ALLOW_HF" = 1 ]; then
    echo "WARNING: --allow-hf-download lets the pod fetch $MODEL from Hugging Face when models/$NAME is not" >&2
    echo "WARNING: staged, against DEVIATION 2704 (rented boxes ALWAYS stage from R2); the record will say so" >&2
fi
if [ -z "$KEYS" ] && [ "$ALLOW_HF" != 1 ]; then
    echo "REFUSED: no models/$NAME/* row in $MANIFEST; populate the store first" >&2
    echo "  (bench/model/README.md, The model source) or pass --allow-hf-download against DEVIATION 2704" >&2
    exit 2
fi
CMD=$OUT/model_leg_cmd.generated.sh
umask 077
{
    echo "# Generated by tools/model_leg/run_leg_cpu.sh at $STAMP for commit $COMMIT; runs with bash in /root/mojolearn on the pod."
    echo "# DEVIATION 2704: the model group models/$NAME staged from the R2 dataset store, presigned on the Mac,"
    echo "# each file verified on the pod against bench/results/dataset_store/manifest.tsv (tools/dataset_store.sh box-cmd)."
    if [ -n "$KEYS" ]; then
        for k in $KEYS; do
            if [ "$MODE" = rent ]; then
                _url=$(sh tools/dataset_store.sh presign "$k" 7200) || { echo "presign FAILED for $k (no ~/.mojolearn_r2 or no aws CLI)" >&2; exit 2; }
            else
                _url="DRY-RUN-NO-URL-MINTED"
            fi
            echo "( URL='$_url'"
            sh tools/dataset_store.sh box-cmd "$k" | grep -v '^#' || exit 2
            echo ") || { echo 'R2 STAGING FAILED: $k (DEVIATION 2704)'; exit 1; }"
        done
    fi
    echo "export MOJOLEARN_MODEL_LEG_ROOT=\"\$PWD\" MOJOLEARN_MODEL_LEG_OUT=\"\$LEG_OUT/model-leg\""
    echo "export MOJOLEARN_MODEL_LEG_SKIP_BUILD=1 MOJOLEARN_MODEL_LEG_MODEL_DIR=/root/models/$NAME"
    echo "export MOJOLEARN_MODEL_LEG_MODEL='$MODEL' MOJOLEARN_MODEL_LEG_VENV=/root/.venv-model-leg MOJOLEARN_MODEL_LEG_ALLOW_HF_DOWNLOAD='$ALLOW_HF'"
    _bad='*[!A-Za-z0-9_.,:/= -]*'
    for v in FORMATS MAX_NEW RUNS TRANSFORMERS_PIN LABEL; do
        eval "_val=\${MOJOLEARN_MODEL_LEG_$v:-}"
        case "$_val" in $_bad) echo "MOJOLEARN_MODEL_LEG_$v carries a character the body refuses" >&2; exit 2 ;; esac
        [ -n "$_val" ] && echo "export MOJOLEARN_MODEL_LEG_$v='$_val'"
    done
    echo 'sh tools/model_leg/leg_body.sh'
} > "$CMD" || exit 2
sh -n "$CMD" || exit 2
echo "leg out:  $OUT"
echo "command:  $CMD (0600; carries the presigned URLs on a real run, none on a dry run)"
echo "model:    $MODEL    vcpu: $VCPU    host families: $FAMILIES    commit: $COMMIT"
echo "staging:  $(echo "$KEYS" | grep -c .) key(s) of models/$NAME -> /root/models/$NAME on the pod, verified against $MANIFEST"
RENT=""
[ "$MODE" = rent ] && RENT=--rent || echo "DRY RUN: the runner's own dry run follows; nothing is created."
bash tools/runpod_cpu_leg.sh --lane model-leg --worktree "$REPO" --build "$FAMILIES" --envs default \
    --vcpu "$VCPU" --lease 60 --out "$OUT" --cmd-file "$CMD" $RENT
rc=$?
[ "$MODE" = rent ] && echo "records: $OUT/remote/leg_out/model-leg/ (ours.<label>.json, torch.<label>.json, ratio.txt, status.tsv)"
exit $rc
