#!/bin/sh
# tools/model_leg/run_leg.sh: THE NVIDIA COLUMN OF THE MODEL LEG, on a RunPod
# H100 through tools/gemm_remote_leg.sh (its guards, dead-man, git archive
# transport and fetch are that file's; this one only generates the body).
#
#   sh tools/model_leg/run_leg.sh                       DRY RUN: rents nothing
#   sh tools/model_leg/run_leg.sh --rent                RENTS. BILLS. One hour.
#   sh tools/model_leg/run_leg.sh --rent --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
#   sh tools/model_leg/run_leg.sh --rent --allow-hf-download   against DEVIATION 2704; warns
#
# THE MODEL COMES FROM THE R2 DATASET STORE (DEVIATION 2704): this wrapper
# exports MOJOLEARN_STAGE_KEYS=models/<name> and MOJOLEARN_STAGE_STRICT=1, and
# the runner's own `sh tools/stage_from_r2.sh "$SSH_TARGET"` (right after the
# source is unpacked) puts the group's files at /root/models/<name>/ on the
# pod, each verified against bench/results/dataset_store/manifest.tsv, with no
# credential leaving this Mac. The body refuses an unstaged model.
#
# ENVIRONMENT
#   ~/.mojolearn_r2                the store's credentials, read by tools/dataset_store.sh here
#   MOJOLEARN_RUNPOD_KEY_FILE      default ~/.mojolearn_runpod_key (0600, outside the repo)
#   MOJOLEARN_MODEL_LEG_LOCAL_CARD an EXISTING Apple gemm card for the runner's
#                                  gemm gate (the gemm payload diffs one; generating
#                                  it runs mojo on this Mac, which this lane does not
#                                  do): e.g. bench/results/e1g/<stamp>/local/apple.card
#   MOJOLEARN_MODEL_LEG_GPU        default "NVIDIA H100 80GB HBM3"
#   MOJOLEARN_MODEL_LEG_MINUTES    default 60 (the runner's hard cap)
#   MOJOLEARN_EVIDENCE_ROOT        default $HOME/mojolearn-evidence; the leg lands in
#                                  $MOJOLEARN_EVIDENCE_ROOT/model-leg/<stamp>-nvidia-h100/
#                                  and the records in its remote/model-leg/
#   MOJOLEARN_MODEL_LEG_*          FORMATS, MAX_NEW, RUNS, BUILDS, HOST_BUILDS,
#                                  TRANSFORMERS_PIN, CPU_COLUMN_ALSO: baked into the
#                                  generated body (the RunPod runner passes no env)
#
# The generated body writes commit.txt on the pod (the runner ships a git
# archive with no .git, tools/identity_three_columns_leg.sh explains) and
# execs tools/model_leg/leg_body.sh from the archive.
set -u
REPO=$(cd "$(dirname "$0")/../.." && pwd) || exit 2
cd "$REPO" || exit 2
MODE=dry; MODEL=${MOJOLEARN_MODEL_LEG_MODEL:-HuggingFaceTB/SmolLM2-360M}; ALLOW_HF=0
while [ $# -gt 0 ]; do
    case "$1" in
        --rent) MODE=rent ;;
        --dry-run) MODE=dry ;;
        --model) shift; MODEL=${1:-} ;;
        --allow-hf-download) ALLOW_HF=1 ;;
        -h|--help) sed -n '2,38p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown argument '$1'" >&2; exit 2 ;;
    esac
    shift
done
case "$MODEL" in *[!A-Za-z0-9_./-]*|'') echo "--model '$MODEL': letters, digits and _./- only" >&2; exit 2 ;; esac
NAME=$(basename "$MODEL")
export MOJOLEARN_STAGE_KEYS="models/$NAME" MOJOLEARN_STAGE_STRICT=1
if [ "$ALLOW_HF" = 1 ]; then
    echo "WARNING: --allow-hf-download lets the pod fetch $MODEL from Hugging Face when models/$NAME is not" >&2
    echo "WARNING: staged, against DEVIATION 2704 (rented boxes ALWAYS stage from R2); the record will say so" >&2
fi
if [ "$MODE" = rent ] && ! grep -q "^models/$NAME/" bench/results/dataset_store/manifest.tsv && [ "$ALLOW_HF" != 1 ]; then
    echo "REFUSED: no models/$NAME/* row in bench/results/dataset_store/manifest.tsv; populate the store first" >&2
    echo "  (bench/model/README.md, The model source) or pass --allow-hf-download against DEVIATION 2704" >&2
    exit 2
fi
GPU=${MOJOLEARN_MODEL_LEG_GPU:-NVIDIA H100 80GB HBM3}
MINUTES=${MOJOLEARN_MODEL_LEG_MINUTES:-60}
STAMP=$(date -u +%Y-%m-%d_%H%M%S)
EVIDENCE=${MOJOLEARN_EVIDENCE_ROOT:-$HOME/mojolearn-evidence}
OUT=$EVIDENCE/model-leg/$STAMP-nvidia-h100
mkdir -p "$OUT" || exit 2
COMMIT=$(git rev-parse HEAD)
CARD=${MOJOLEARN_MODEL_LEG_LOCAL_CARD:-${MOJOLEARN_GEMM_LEG_LOCAL_CARD:-}}
if [ "$MODE" = rent ] && [ ! -f "$CARD" ]; then
    echo "MOJOLEARN_MODEL_LEG_LOCAL_CARD must name an existing Apple gemm card (the runner's gemm gate);" >&2
    echo "  ls bench/results/e1g/*/local/apple.card   names the candidates; this lane generates none." >&2
    exit 2
fi
BODY=$OUT/model_leg_body.generated.sh
{
    echo '#!/bin/sh'
    echo "# Generated by tools/model_leg/run_leg.sh at $STAMP for commit $COMMIT. RUNS ON THE POD."
    echo "[ -s /root/mojolearn/commit.txt ] || echo '$COMMIT' > /root/mojolearn/commit.txt"
    echo "export MOJOLEARN_COMMIT='$COMMIT'"
    echo "export MOJOLEARN_MODEL_LEG_MODEL='$MODEL' MOJOLEARN_MODEL_LEG_ALLOW_HF_DOWNLOAD='$ALLOW_HF'"
    _bad='*[!A-Za-z0-9_.,:/= -]*'
    for v in FORMATS MAX_NEW RUNS BUILDS HOST_BUILDS TRANSFORMERS_PIN CPU_COLUMN_ALSO LABEL; do
        eval "_val=\${MOJOLEARN_MODEL_LEG_$v:-}"
        case "$_val" in $_bad) echo "MOJOLEARN_MODEL_LEG_$v carries a character the body refuses" >&2; exit 2 ;; esac
        [ -n "$_val" ] && echo "export MOJOLEARN_MODEL_LEG_$v='$_val'"
    done
    echo 'exec sh /root/mojolearn/tools/model_leg/leg_body.sh'
} > "$BODY" || exit 2
sh -n "$BODY" || exit 2
echo "leg out:  $OUT"
echo "body:     $BODY"
echo "model:    $MODEL    gpu: $GPU    minutes: $MINUTES    commit: $COMMIT"
echo "staging:  MOJOLEARN_STAGE_KEYS=$MOJOLEARN_STAGE_KEYS (strict) -> /root/models/$NAME on the pod, by the runner"
if [ "$MODE" = dry ]; then
    echo "DRY RUN: the runner's own dry run follows; nothing is rented."
    MOJOLEARN_GPU_ARCHS=sm_90a MOJOLEARN_GEMM_LEG_EXTRA="$BODY" MOJOLEARN_GEMM_LEG_OUT="$OUT" \
        sh tools/gemm_remote_leg.sh nvidia --payload gemm --dry-run --minutes "$MINUTES" --gpu "$GPU" \
        ${CARD:+--local-card "$CARD"}
    exit $?
fi
MOJOLEARN_GPU_ARCHS=sm_90a MOJOLEARN_GEMM_LEG_EXTRA="$BODY" MOJOLEARN_GEMM_LEG_OUT="$OUT" \
    sh tools/gemm_remote_leg.sh nvidia --payload gemm --rent --minutes "$MINUTES" --gpu "$GPU" --local-card "$CARD"
rc=$?
echo "records: $OUT/remote/model-leg/ (ours.<label>.json, torch.<label>.json, ratio.txt, status.tsv)"
exit $rc
